-- @TBL_GUI_NAME: Xmdm Conf App
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App
-- @TBL_NAME_AT: XMDM_CONF_APP_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(30 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE) DEFAULT NULL,
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE) DEFAULT NULL,
  CONSTRAINT "PK_XMDM_CONF_APP" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf App 04122025
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App 04122025
-- @TBL_NAME_AT: XMDM_CONF_APP_04122025_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_04122025" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_APP_04122025" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf App 05122025
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App 05122025
-- @TBL_NAME_AT: XMDM_CONF_APP_05122025_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_05122025" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_APP_05122025" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf App 06122025
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App 06122025
-- @TBL_NAME_AT: XMDM_CONF_APP_06122025_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_06122025" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_APP_06122025" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf App 07122025
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App 07122025
-- @TBL_NAME_AT: XMDM_CONF_APP_07122025_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_07122025" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_APP_07122025" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf App 08122025
-- @TBL_GUI_NAME_SHORT: Xmdm Conf App 08122025
-- @TBL_NAME_AT: XMDM_CONF_APP_08122025_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_08122025" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Desc
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: App Help Link
  -- @COL_DISPLAY_ORDER: 4
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre Release Action
  -- @COL_DISPLAY_ORDER: 5
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post Release Action
  -- @COL_DISPLAY_ORDER: 6
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validation Action
  -- @COL_DISPLAY_ORDER: 7
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On Load Action
  -- @COL_DISPLAY_ORDER: 8
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Settings
  -- @COL_DISPLAY_ORDER: 9
  "SETTINGS" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_APP_08122025" PRIMARY KEY ("APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf Column
-- @TBL_GUI_NAME_SHORT: Xmdm Conf Column
-- @TBL_NAME_AT: XMDM_CONF_COLUMN_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM"."XMDM_CONF_COLUMN" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tbl Name
  -- @COL_DISPLAY_ORDER: 2
  "TBL_NAME" VARCHAR2(61 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Col Name
  -- @COL_DISPLAY_ORDER: 3
  "COL_NAME" VARCHAR2(30 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Col Gui Name
  -- @COL_DISPLAY_ORDER: 4
  "COL_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Col Desc
  -- @COL_DISPLAY_ORDER: 5
  "COL_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Col Format
  -- @COL_DISPLAY_ORDER: 6
  "COL_FORMAT" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Col Display Order
  -- @COL_DISPLAY_ORDER: 7
  "COL_DISPLAY_ORDER" NUMBER(3, 0),
  -- @COL_GUI_NAME: Col Pk
  -- @COL_DISPLAY_ORDER: 8
  "COL_PK" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Col Required
  -- @COL_DISPLAY_ORDER: 9
  "COL_REQUIRED" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Col Editable
  -- @COL_DISPLAY_ORDER: 10
  "COL_EDITABLE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Col Datatype
  -- @COL_DISPLAY_ORDER: 11
  "COL_DATATYPE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Lkp Sql Label
  -- @COL_DISPLAY_ORDER: 12
  "LKP_SQL_LABEL" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Lkp Sql Value
  -- @COL_DISPLAY_ORDER: 13
  "LKP_SQL_VALUE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Lkp Sql Stmt1
  -- @COL_DISPLAY_ORDER: 14
  "LKP_SQL_STMT1" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Lkp Sql Stmt2
  -- @COL_DISPLAY_ORDER: 15
  "LKP_SQL_STMT2" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Lkp Sql Param Lst
  -- @COL_DISPLAY_ORDER: 16
  "LKP_SQL_PARAM_LST" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Col Valid Interval Column
  -- @COL_DISPLAY_ORDER: 17
  "COL_VALID_INTERVAL_COLUMN" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Col Multiline
  -- @COL_DISPLAY_ORDER: 18
  "COL_MULTILINE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Col Validator
  -- @COL_DISPLAY_ORDER: 19
  "COL_VALIDATOR" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Col Autoincrement
  -- @COL_DISPLAY_ORDER: 20
  "COL_AUTOINCREMENT" CHAR(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: Col Default Val
  -- @COL_DISPLAY_ORDER: 21
  "COL_DEFAULT_VAL" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_XMDM_CONF_COLUMN" PRIMARY KEY ("APP_NAME", "TBL_NAME", "COL_NAME")
);
COMMENT ON COLUMN "GUI_XMDM"."XMDM_CONF_COLUMN"."COL_VALID_INTERVAL_COLUMN" IS 'Values: T = VALID_TO, F = VALID_FROM. Used for autocomplete of BUSINESS_VALID_FROM, BUSINESS_VALID_TO';
-- @TBL_GUI_NAME: Xmdm Conf Table
-- @TBL_GUI_NAME_SHORT: Xmdm Conf Table
-- @TBL_NAME_AT: XMDM_CONF_TABLE_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM"."XMDM_CONF_TABLE" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tbl Name
  -- @COL_DISPLAY_ORDER: 2
  "TBL_NAME" VARCHAR2(61 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tbl Gui Name
  -- @COL_DISPLAY_ORDER: 3
  "TBL_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Tbl Desc
  -- @COL_DISPLAY_ORDER: 4
  "TBL_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Tbl Display Order
  -- @COL_DISPLAY_ORDER: 5
  "TBL_DISPLAY_ORDER" NUMBER(3, 0),
  -- @COL_GUI_NAME: Tbl Gui Name Short
  -- @COL_DISPLAY_ORDER: 6
  "TBL_GUI_NAME_SHORT" VARCHAR2(31 BYTE),
  -- @COL_GUI_NAME: Tbl Schema
  -- @COL_DISPLAY_ORDER: 7
  "TBL_SCHEMA" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Tbl Name At
  -- @COL_DISPLAY_ORDER: 8
  "TBL_NAME_AT" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Historical Tbl Flag
  -- @COL_DISPLAY_ORDER: 9
  "HISTORICAL_TBL_FLAG" CHAR(1 BYTE),
  CONSTRAINT "PK_XMDM_CONF_TABLE" PRIMARY KEY ("APP_NAME", "TBL_NAME")
);
CREATE INDEX "GUI_XMDM"."IDX_CONF_TABLE_DISPLAY_ORDER" ON "GUI_XMDM"."XMDM_CONF_TABLE"(TBL_DISPLAY_ORDER);
-- @TBL_GUI_NAME: Xmdm Conf User Perm
-- @TBL_GUI_NAME_SHORT: Xmdm Conf User Perm
-- @TBL_NAME_AT: XMDM_CONF_USER_PERM_AT
-- @TBL_DISPLAY_ORDER: 9
CREATE TABLE "GUI_XMDM"."XMDM_CONF_USER_PERM" (
  -- @COL_GUI_NAME: User Name
  -- @COL_DISPLAY_ORDER: 1
  "USER_NAME" VARCHAR2(15 BYTE) NOT NULL,
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Role
  -- @COL_DISPLAY_ORDER: 3
  "ROLE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Department
  -- @COL_DISPLAY_ORDER: 4
  "DEPARTMENT" VARCHAR2(500 BYTE),
  -- @COL_GUI_NAME: Full Name
  -- @COL_DISPLAY_ORDER: 5
  "FULL_NAME" VARCHAR2(500 BYTE),
  CONSTRAINT "PK_XMDM_CONF_USER_PERM" PRIMARY KEY ("USER_NAME", "APP_NAME")
);
-- @TBL_GUI_NAME: Xmdm Conf User Setting
-- @TBL_GUI_NAME_SHORT: Xmdm Conf User Setting
-- @TBL_NAME_AT: XMDM_CONF_USER_SETTING_AT
-- @TBL_DISPLAY_ORDER: 10
CREATE TABLE "GUI_XMDM"."XMDM_CONF_USER_SETTING" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DISPLAY_ORDER: 1
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tbl Name
  -- @COL_DISPLAY_ORDER: 2
  "TBL_NAME" VARCHAR2(61 BYTE) NOT NULL,
  -- @COL_GUI_NAME: User Name
  -- @COL_DISPLAY_ORDER: 3
  "USER_NAME" VARCHAR2(15 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Col Settings
  -- @COL_DISPLAY_ORDER: 4
  "COL_SETTINGS" VARCHAR2(4000 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_XMDM_CONF_USER_SETTING" PRIMARY KEY ("APP_NAME", "TBL_NAME", "USER_NAME")
);