CREATE TABLE "EUREX_LST"."D_DOM_LST_FLOW_TYPE" (
  "FLOW_TYPE_ID" NUMBER,
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE),
  "FLOW_TYPE_NAME" VARCHAR2(100 BYTE),
  "SECURITY_ISIN" VARCHAR2(12 BYTE),
  "FLOW_CLASS" VARCHAR2(10 BYTE),
  "CASH_SEC_IND" VARCHAR2(10 BYTE),
  "ITS" DATE,
  "STL_DATE_NO" NUMBER(2, 0),
  "CI_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "CM_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "CB_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "NA_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "LP_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "SB_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "PS_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "ISSUER_ENTITY_REQ_IND" VARCHAR2(1 BYTE),
  "LEG_TYPE" VARCHAR2(2 BYTE),
  "RISK_SYSTEM" VARCHAR2(64 BYTE),
  "OTC_CURRENCY_IND" VARCHAR2(1 BYTE),
  "ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL,
  "RELATED_FLOW_TYPE_CODE" VARCHAR2(50 BYTE),
  "BASKET_ISO_CRCY_ID" NUMBER,
  "GCP_IND" VARCHAR2(1 BYTE),
  "REL_FLOW_TYPE_EXCLUSIVE_FLAG" VARCHAR2(1 BYTE)
) TABLESPACE EUREX_LST_FACT;
CREATE TABLE "EUREX_LST"."D_OBJ_LST_DOMAIN_VALUES" (
  "PROCESS_ORDER_NO" NUMBER,
  "DOMAIN" VARCHAR2(255 BYTE),
  "DOMAIN_ID" NUMBER(10, 0),
  "DOMAIN_CODE" VARCHAR2(255 BYTE),
  "DOMAIN_NAME" VARCHAR2(4000 BYTE),
  "DOMAIN_DESCR" VARCHAR2(4000 BYTE),
  "DOMAIN_SOURCE" VARCHAR2(4000 BYTE),
  "ACTIVE_FLAG" VARCHAR2(1 BYTE),
  "GUI_ORDER_NO" NUMBER,
  "VALID_FROM" DATE,
  "ITS" DATE,
  "UTS" DATE
) TABLESPACE EUREX_LST_FACT;
CREATE TABLE "EUREX_LST"."D_STA_SCENARIOMASTER" (
  "SCNID" NUMBER(15, 0) NOT NULL,
  "VALID_FROM_BD" TIMESTAMP NOT NULL,
  "VALID_TO_BD" TIMESTAMP NOT NULL,
  "VALID_FROM_PT" TIMESTAMP NOT NULL,
  "VALID_TO_PT" TIMESTAMP NOT NULL,
  "STATE_HASHKEY" VARCHAR2(32 BYTE),
  "PRISMA_TIMESTAMP" TIMESTAMP,
  "PROTO_SCNID" NUMBER(15, 0),
  "STRESSED_SCENARIO_ID" VARCHAR2(256 CHAR),
  "SCENARIO_TEXT" VARCHAR2(100 BYTE),
  "SCENARIO_PURPOSE" VARCHAR2(100 BYTE),
  "SCENARIO_GROUP" VARCHAR2(8 BYTE),
  "DELTA_1" NUMBER,
  "DELTA_2" NUMBER,
  "DELTA_3" NUMBER,
  "DELTA_4" NUMBER,
  "ITS" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  "UTS" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT "PK_D_STA_SCENARIOMASTER" PRIMARY KEY ("SCNID", "VALID_FROM_PT")
) TABLESPACE EUREX_LST_FACT;
CREATE TABLE "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF" (
  "QA_RUN_DEF_ID" NUMBER NOT NULL,
  "QA_RUN_DEF_DESCR" VARCHAR2(200 BYTE),
  "QA_RUN_DEF_CATEGORY" VARCHAR2(200 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE,
  "ITS" DATE NOT NULL,
  "UTS" DATE NOT NULL,
  "QA_RUN_DEF_COMMENT" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_ETL_LST_QUALITY_RUN_DEF" PRIMARY KEY ("QA_RUN_DEF_ID", "VALID_FROM")
) TABLESPACE EUREX_LST_FACT;
COMMENT ON TABLE "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF" IS 'Source: manual. central control table for all quality assurance modules.';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."QA_RUN_DEF_ID" IS 'unique identifier for a quality assurance module';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."QA_RUN_DEF_DESCR" IS 'description on the quality assurance module';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."VALID_FROM" IS 'valid from';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."VALID_TO" IS 'valid to';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."ITS" IS 'insert timestamp';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."UTS" IS 'update timestamp';
COMMENT ON COLUMN "EUREX_LST"."ETL_LST_QUALITY_RUN_DEF"."QA_RUN_DEF_COMMENT" IS 'additional description/comments related to the quality assurance module';