CREATE TABLE "EUREX_DMP_SRC"."D_CCP_CASH_ACCOUNT_CHAIN_OBJ" (
  "CSH_CHAIN_ID" NUMBER(15, 0) NOT NULL,
  "INT_CSH_CHAIN_ID" NUMBER(15, 0) NOT NULL,
  "CSH_ACCT_CHAIN_ID" VARCHAR2(15 BYTE) NOT NULL,
  "CLEARING_MEMBER" VARCHAR2(5 BYTE) NOT NULL,
  "CASH_ACCT_BANK" VARCHAR2(5 BYTE) NOT NULL,
  "CORELATED_BANK" VARCHAR2(5 BYTE) NOT NULL,
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "ITS" DATE,
  "UTS" DATE,
  "DWH_AWARENESS_DATE" DATE
) TABLESPACE EUREX_FACT;
COMMENT ON COLUMN "EUREX_DMP_SRC"."D_CCP_CASH_ACCOUNT_CHAIN_OBJ"."INT_CSH_CHAIN_ID" IS 'From source';