CREATE TABLE "EUREX_DMP"."D_DOM_CAA_DOMAIN_VALUES" (
  "DOMAIN" VARCHAR2(100 BYTE),
  "DOMAIN_VALUE_ID" NUMBER,
  "DOMAIN_VALUE" VARCHAR2(100 BYTE)
) TABLESPACE EUREX_FACT;
CREATE TABLE "EUREX_DMP"."D_DOM_PAY_DOMAIN_VALUES" (
  "DOMAIN" VARCHAR2(100 BYTE),
  "DOMAIN_VALUE_ID" NUMBER,
  "DOMAIN_VALUE" VARCHAR2(100 BYTE)
) TABLESPACE EUREX_FACT;
CREATE TABLE "EUREX_DMP"."D_DOM_PAY_TRANSACTION_GROUP" (
  "TRN_GROUP_NO" NUMBER(15, 0),
  "TRN_GROUP_DESC" VARCHAR2(500 CHAR),
  "RPT_SOURCE" VARCHAR2(25 CHAR),
  "ITS" DATE,
  "DWH_AWARENESS_DATE" DATE,
  "MEASURE_ID" NUMBER(15, 0)
) TABLESPACE EUREX_FACT;
CREATE TABLE "EUREX_DMP"."ETL_GENERIC_PROCESS_PARAM" (
  "PROCESS_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_VALUE" VARCHAR2(200 BYTE),
  "FORMAT" VARCHAR2(4000 BYTE),
  "DESCR" VARCHAR2(4000 BYTE),
  CONSTRAINT "PK_ETL_GENERIC_PROCESS_PARAM" PRIMARY KEY ("PROCESS_NAME", "PARAM_NAME")
) TABLESPACE EUREX_FACT;
CREATE TABLE "EUREX_DMP"."F_DMP_RUN_STATUS" (
  "DMP_RUN_ID" NUMBER(15, 0),
  "CALCULATION_DATE" DATE,
  "DEFAULT_TIMESTAMP" TIMESTAMP,
  "DEFAULT_MEMBER" VARCHAR2(5 BYTE),
  "ACTION_TYPE" VARCHAR2(256 CHAR),
  "IS_AVAILABLE" NUMBER(1, 0),
  "MODIFYING_USER" VARCHAR2(30 BYTE),
  "STATUS" VARCHAR2(256 CHAR),
  "ITS" TIMESTAMP DEFAULT SYSDATE
) TABLESPACE EUREX_FACT;