CREATE TABLE "EUREX_EMIR_SRC"."D_CURRENCY" (
  "ISO_CRCY_ID" NUMBER(*, 0) NOT NULL,
  "COUNTRY_ID" NUMBER(*, 0),
  "ITS" DATE,
  "SHORT_NAME" VARCHAR2(15 BYTE),
  "LONG_NAME" VARCHAR2(60 BYTE),
  "ISO_NUMERIC_CODE" VARCHAR2(3 BYTE),
  "ISO_ALPHA_CODE" VARCHAR2(3 BYTE),
  "PARITY" NUMBER,
  "CURRENCY_ALL_ENTRI" VARCHAR2(1 BYTE),
  "COUNTRY_CODE" VARCHAR2(15 BYTE),
  PRIMARY KEY ("ISO_CRCY_ID")
) TABLESPACE EUREX_EMIR_SRC;
CREATE TABLE "EUREX_EMIR_SRC"."D_MEMBER_OBJ" (
  "MEMBER_ID" NUMBER(15, 0) NOT NULL,
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE),
  "BUSINESS_ID" VARCHAR2(64 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE,
  "ADDR_ID" NUMBER(15, 0),
  "MR_MEMBER_NAME" VARCHAR2(128 BYTE),
  "ITS" DATE NOT NULL,
  "UTS" DATE NOT NULL,
  "DWH_AWARENESS_DATE" DATE NOT NULL,
  CONSTRAINT "XPKD_MEMBER_OBJ" PRIMARY KEY ("MEMBER_ID")
) TABLESPACE EUREX_EMIR_SRC;