CREATE TABLE "EUREX"."D_EX_PRODUCT_OBJ" (
  "PRODUCT_ID" NUMBER(15, 0) NOT NULL,
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE) NOT NULL,
  "BUSINESS_ID" VARCHAR2(15 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE,
  "MR_PRODUCT_NAME" VARCHAR2(30 BYTE),
  "ITS" DATE NOT NULL,
  "UTS" DATE NOT NULL,
  "DWH_AWARENESS_DATE" DATE NOT NULL,
  CONSTRAINT "XPKD_EX_PRODUCT_OBJ" PRIMARY KEY ("PRODUCT_ID")
) TABLESPACE EUREX_FACT;
COMMENT ON TABLE "EUREX"."D_EX_PRODUCT_OBJ" IS 'Table contains the general object Eurex Classic clearing product';
CREATE TABLE "EUREX"."D_EX_PRODUCT_OBJ_HIST" (
  "PRODUCT_ID" NUMBER(15, 0) NOT NULL,
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE) NOT NULL,
  "BUSINESS_ID" VARCHAR2(15 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE,
  "MR_PRODUCT_NAME" VARCHAR2(30 BYTE),
  "ITS" DATE NOT NULL,
  "UTS" DATE NOT NULL,
  "DWH_AWARENESS_DATE" DATE NOT NULL
) TABLESPACE EUREX_FACT PCTFREE 0 COMPRESS FOR OLTP;
COMMENT ON TABLE "EUREX"."D_EX_PRODUCT_OBJ_HIST" IS 'Table contains the general object Eurex Classic clearing product';
CREATE TABLE "EUREX"."ETL_GENERIC_PROCESS_PARAM" (
  "PROCESS_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_VALUE" VARCHAR2(200 BYTE),
  "ITS" DATE,
  PRIMARY KEY ("PROCESS_NAME", "PARAM_NAME")
) TABLESPACE EUREX_FACT PCTFREE 0 COMPRESS FOR OLTP;