CREATE TABLE "EUREX_RLI"."D_DOM_RLI_COMPONENT_DET" (
  "INDICATOR_ID" VARCHAR2(10 BYTE),
  "COMPONENT_NAME" VARCHAR2(50 BYTE),
  "COMPONENT_ID" NUMBER(1, 0),
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "ITS" DATE,
  "UTS" DATE
) TABLESPACE EUREX_FACT;
CREATE TABLE "EUREX_RLI"."D_DOM_RLI_INDICATOR_DET" (
  "INDICATOR_ID" VARCHAR2(10 BYTE),
  "INDICATOR_NAME" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "ITS" DATE,
  "UTS" DATE,
  "REPORT_NAME" VARCHAR2(256 BYTE)
) TABLESPACE EUREX_FACT;