-- @TBL_GUI_NAME: ECAG Transactions
-- @TBL_GUI_NAME_SHORT: ECAG_TRN
-- @TBL_NAME_AT: ECAG_TRN_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_RRS"."ECAG_TRN" (
  -- @COL_GUI_NAME: Transaction Ref Number
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: Number
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[a-zA-Z0-9]*$
  "TRN_REF_NUMBER" VARCHAR2(52 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Trading Venue Transaction ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[a-zA-Z0-9]*$
  "TRADING_VENUE_TRN_ID_CODE" VARCHAR2(52 BYTE),
  -- @COL_GUI_NAME: Buyer ID
  -- @COL_DISPLAY_ORDER: 3
  "BUYER_ID" VARCHAR2(52 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Seller ID
  -- @COL_DISPLAY_ORDER: 4
  "SELLER_ID" VARCHAR2(52 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Trade Time
  -- @COL_DESC: Timestamp e.g. 10.06.2021 16:59:50,123456
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: DD.MM.YYYY HH24:MI:SS,SSSSSS
  "TRADE_TIME" VARCHAR2(52 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Quantity Notation
  -- @COL_DISPLAY_ORDER: 6
  -- @LKP_SQL_STMT1:
  --   SELECT 'UNIT' AS QUANTITY_NOTATION  FROM dual
  --   UNION ALL SELECT 'NOMINAL' FROM dual
  --   UNION ALL SELECT 'MONETARY' FROM dual
  -- @LKP_SQL_LABEL: QUANTITY_NOTATION
  -- @LKP_SQL_VALUE: QUANTITY_NOTATION
  "QUANTITY_NOTATION" VARCHAR2(15 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Quantity
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: #.###############
  "QUANTITY" NUMBER(38, 17) NOT NULL,
  -- @COL_GUI_NAME: Quantity Currency
  -- @COL_DISPLAY_ORDER: 8
  "QUANTITY_CURRENCY" VARCHAR2(3 BYTE),
  -- @COL_GUI_NAME: Price Notation
  -- @COL_DISPLAY_ORDER: 9
  -- @LKP_SQL_STMT1:
  --   SELECT 'MONETARY' AS PRICE_NOTATION  FROM dual
  --   UNION ALL SELECT 'PERCENT' FROM dual
  --   UNION ALL SELECT 'YIELD' FROM dual
  --   UNION ALL SELECT 'BASIS_POINTS' FROM dual
  -- @LKP_SQL_LABEL: PRICE_NOTATION
  -- @LKP_SQL_VALUE: PRICE_NOTATION
  "PRICE_NOTATION" VARCHAR2(52 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Price
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: #.###############
  "PRICE" NUMBER(38, 17) NOT NULL,
  -- @COL_GUI_NAME: Price Currency
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: ISO Code
  "PRICE_CURRENCY" VARCHAR2(3 BYTE),
  -- @COL_GUI_NAME: Net Amount
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: #.###############
  "NET_AMOUNT" NUMBER(38, 5),
  -- @COL_GUI_NAME: Venue
  -- @COL_DISPLAY_ORDER: 13
  "VENUE" VARCHAR2(4 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Instrument ID
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^([A-Za-z]{2})([A-Za-z0-9]{9})([0-9]{1})
  "INSTRUMENT_ID" VARCHAR2(25 BYTE) NOT NULL,
  "ACTIVE_FLAG" NUMBER(1, 0) DEFAULT 1,
  "UTS" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RRS_ECAG_TRN" PRIMARY KEY ("TRN_REF_NUMBER")
) TABLESPACE XMDM_FACT;