-- @TBL_GUI_NAME: Price Trade Monitor Predefined Comments
-- @TBL_GUI_NAME_SHORT: PREDEFINED COMMENTS
-- @TBL_NAME_AT: COMMENT_VALUES_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_F7"."COMMENT_VALUES" (
  -- @COL_GUI_NAME: Field Name
  -- @COL_DESC: Name of the field
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "COL_GUI_NAME" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Display Order
  -- @COL_DESC: Display order of the field
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "DISPLAY_ORDER" NUMBER(2, 0) NOT NULL,
  -- @COL_GUI_NAME: Value
  -- @COL_DESC: Value to display
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_REQUIRED: V
  "VALUE" VARCHAR2(250 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COMMENT_VALUES" PRIMARY KEY ("COL_GUI_NAME", "DISPLAY_ORDER")
) TABLESPACE FACT_DATA;
-- @TBL_GUI_NAME: Eurex Repo Key Figures
-- @TBL_GUI_NAME_SHORT: EUREX_REPO_KEY_FIGURES
-- @TBL_NAME_AT: EUREX_REPO_KEY_FIGURES_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES" (
  -- @COL_GUI_NAME: Key Name
  -- @COL_DESC: Name of Key Figure, which displayed in the report "Daily Key Figures"; use upper-case letters
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "KEY_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Key Value
  -- @COL_DESC: Target Value in billion of the Key Figure for the actual year - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"
  -- @COL_DISPLAY_ORDER: 2
  "KEY_VALUE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Value Last Year
  -- @COL_DESC: Average value of Key Figure of the last year in billion - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"
  -- @COL_DISPLAY_ORDER: 3
  "VALUE_LAST_YEAR" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_EUREX_REPO_KEY_FIGURES" PRIMARY KEY ("KEY_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES"."KEY_NAME" IS 'Name of Key Figure, which displayed in the report "Daily Key Figures"; use upper-case letters';
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES"."KEY_VALUE" IS 'Target Value in billion of the Key Figure for the actual year - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"';
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES"."VALUE_LAST_YEAR" IS 'Average value of Key Figure of the last year in billion - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"';
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES"."VALID_FROM" IS 'start date of validity';
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES"."VALID_TO" IS 'end date of validity';
-- @TBL_GUI_NAME: Member to Billing Group
-- @TBL_GUI_NAME_SHORT: MAP_MEMBER_TO_BILLING_GROUP
-- @TBL_NAME_AT: MAP_MEMBER_TO_BILLING_GROUP_AT
-- @TBL_DISPLAY_ORDER: 2
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP" (
  -- @COL_GUI_NAME: Member ID
  -- @COL_DESC: sap member id of a participant
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Billing Group
  -- @COL_DESC: billing group, e.g. L1, L2
  -- @COL_DISPLAY_ORDER: 2
  "BILLING_GROUP" VARCHAR2(2 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MAP_MEMBER_TO_BILLING_GROUP" PRIMARY KEY ("MEMBER_ID", "VALID_FROM")
) TABLESPACE XMDM_FACT;
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP"."MEMBER_ID" IS 'sap member id of a participant';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP"."BILLING_GROUP" IS 'billing group, e.g. L1, L2';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP"."VALID_FROM" IS 'start date of validity';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP"."VALID_TO" IS 'end date of validity';
-- @TBL_GUI_NAME: Map Participant To Parent
-- @TBL_GUI_NAME_SHORT: MAP_PARTICIPANT_TO_PARENT
-- @TBL_NAME_AT: MAP_PARTICIPANT_TO_PARENT_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT" (
  -- @COL_GUI_NAME: Gp Nr
  -- @COL_DESC: member GP number
  -- @COL_DISPLAY_ORDER: 1
  "GP_NR" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Zhs ID
  -- @COL_DESC: id in source system ZHS
  -- @COL_DISPLAY_ORDER: 2
  "ZHS_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: F7_Id
  -- @COL_DESC: member id for participant in F7 system
  -- @COL_DISPLAY_ORDER: 3
  "F7_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: Sap Member ID
  -- @COL_DESC: SAP member id for participant
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "SAP_MEMBER_ID" VARCHAR2(12 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Parent ID
  -- @COL_DESC: SAP member id for parent participant
  -- @COL_DISPLAY_ORDER: 5
  "PARENT_ID" VARCHAR2(12 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Xemac Clearer ID
  -- @COL_DESC: clearer id in XEMAC
  -- @COL_DISPLAY_ORDER: 6
  "XEMAC_CLEARER_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: Xemac Member ID
  -- @COL_DESC: member id in XEMAC
  -- @COL_DISPLAY_ORDER: 7
  "XEMAC_MEMBER_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: CCP CM ID
  -- @COL_DESC: cm id in CCP
  -- @COL_DISPLAY_ORDER: 8
  "CCP_CM_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: CCP TM ID
  -- @COL_DESC: tm id in CCP
  -- @COL_DISPLAY_ORDER: 9
  "CCP_TM_ID" VARCHAR2(12 BYTE),
  -- @COL_GUI_NAME: Is Corporate
  -- @COL_DESC: indicator whether the member is corporate, e.g. Y or N
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[yY]|^[Nn]
  "IS_CORPORATE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- @COL_GUI_NAME: Is select Finance Member
  -- @COL_DESC: indicator whether the member is a financial member, e.g. Y or N
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[yY]|^[Nn]
  "IS_SELECT_FINANCE_MEMBER" CHAR(1 BYTE),
  CONSTRAINT "PK_MAP_PARTICIPANT_TO_PARENT" PRIMARY KEY ("SAP_MEMBER_ID", "VALID_FROM")
) TABLESPACE XMDM_FACT;
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."GP_NR" IS 'member GP number';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."ZHS_ID" IS 'id in source system ZHS';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."F7_ID" IS 'member id for participant in F7 system';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."SAP_MEMBER_ID" IS 'SAP member id for participant';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."PARENT_ID" IS 'SAP member id for parent participant';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."XEMAC_CLEARER_ID" IS 'clearer id in XEMAC';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."XEMAC_MEMBER_ID" IS 'member id in XEMAC';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."CCP_CM_ID" IS 'cm id in CCP';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."CCP_TM_ID" IS 'tm id in CCP';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."IS_CORPORATE" IS 'indicator whether the member is corporate, e.g. Y or N ';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."VALID_FROM" IS 'start date of validity';
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT"."VALID_TO" IS 'end date of validity';
-- @TBL_GUI_NAME: Price Trade Monitor
-- @TBL_GUI_NAME_SHORT: PRICE_TRADE_MONITOR
-- @TBL_NAME_AT: PRICE_TRADE_MONITOR_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR" (
  -- @COL_GUI_NAME: Trade Date Time
  -- @COL_DESC: BUSINESS_DATE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BUSINESS_DATE" TIMESTAMP NOT NULL,
  -- @COL_GUI_NAME: Trade Id
  -- @COL_DESC: TRADE_ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: #,###
  "TRADE_ID" NUMBER(19, 0) NOT NULL,
  -- @COL_GUI_NAME: Purchase Date
  -- @COL_DESC: PURCHASE_DATE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  "PURCHASE_DATE" DATE,
  -- @COL_GUI_NAME: Repurchase Date
  -- @COL_DESC: REPURCHASE_DATE
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  "REPURCHASE_DATE" DATE,
  -- @COL_GUI_NAME: Basket
  -- @COL_DESC: BASKET
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  "BASKET" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Buyer
  -- @COL_DESC: BUYER
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  "BUYER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Seller
  -- @COL_DESC: SELLER
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_PK: Y
  "SELLER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Contract Term
  -- @COL_DESC: CONTRACT_TERM
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_PK: Y
  "CONTRACT_TERM" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: CURRENCY
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_PK: Y
  "CURRENCY" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Rate
  -- @COL_DESC: RATE
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: #.###
  "RATE" NUMBER(126) NOT NULL,
  -- @COL_GUI_NAME: Mean
  -- @COL_DESC: MEAN
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: #.###
  "MEAN" NUMBER(126),
  -- @COL_GUI_NAME: Standard Deviation
  -- @COL_DESC: STANDARD_DEVIATION
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_FORMAT: 0.###
  "STANDARD_DEVIATION" NUMBER(126),
  -- @COL_GUI_NAME: Lower Bound EWM
  -- @COL_DESC: LOWER_BOUND_EWM
  -- @COL_DISPLAY_ORDER: 15
  -- @COL_FORMAT: #.###
  "LOWER_BOUND" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Upper Bound EWM
  -- @COL_DESC: UPPER_BOUND_EWM
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_FORMAT: #.###
  "UPPER_BOUND" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Estimation
  -- @COL_DESC: ESTIMATION
  -- @COL_DISPLAY_ORDER: 19
  -- @LKP_SQL_STMT1: SELECT VALUE AS ESTIMATION FROM GUI_XMDM_F7.COMMENT_VALUES WHERE COL_GUI_NAME='Estimation' ORDER BY DISPLAY_ORDER
  -- @LKP_SQL_LABEL: ESTIMATION
  -- @LKP_SQL_VALUE: ESTIMATION
  "ESTIMATION" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Description
  -- @COL_DESC: DESCRIPTION
  -- @COL_DISPLAY_ORDER: 20
  -- @LKP_SQL_STMT1: SELECT VALUE AS DESCRIPTION FROM GUI_XMDM_F7.COMMENT_VALUES WHERE COL_GUI_NAME='Description' ORDER BY DISPLAY_ORDER
  -- @LKP_SQL_LABEL: DESCRIPTION
  -- @LKP_SQL_VALUE: DESCRIPTION
  "DESCRIPTION_GUI" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Comment
  -- @COL_DESC: COMMENT
  -- @COL_DISPLAY_ORDER: 21
  -- @COL_MULTILINE: Y
  "COMMENT_GUI" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Result Action
  -- @COL_DESC: RESULT_ACTION
  -- @COL_DISPLAY_ORDER: 22
  -- @LKP_SQL_STMT1: SELECT VALUE AS RESULT_ACTION FROM GUI_XMDM_F7.COMMENT_VALUES WHERE UPPER(COL_GUI_NAME)=UPPER('Result action') ORDER BY DISPLAY_ORDER
  -- @LKP_SQL_LABEL: RESULT_ACTION
  -- @LKP_SQL_VALUE: RESULT_ACTION
  "RESULT_ACTION" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- @COL_GUI_NAME: Market
  -- @COL_DESC: MARKET
  -- @COL_DISPLAY_ORDER: 3
  "MARKET" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Average
  -- @COL_DESC: AVERAGE
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_FORMAT: #.###
  "AVERAGE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Lower Bound AVG
  -- @COL_DESC: LOWER_BOUND_AVG
  -- @COL_DISPLAY_ORDER: 17
  -- @COL_FORMAT: #.###
  "LOWER_BOUND_AVG" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Upper Bound AVG
  -- @COL_DESC: UPPER_BOUND_AVG
  -- @COL_DISPLAY_ORDER: 18
  -- @COL_FORMAT: #.###
  "UPPER_BOUND_AVG" VARCHAR2(50 BYTE)
) TABLESPACE FACT_DATA;
-- @TBL_GUI_NAME: Price Trade Monitor Parameters
-- @TBL_GUI_NAME_SHORT: PRICE_TRADE_MONITOR_PARAMETERS
-- @TBL_NAME_AT: PRICE_TRADE_MONITOR_PARM_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS" (
  -- @COL_GUI_NAME: Market
  -- @COL_DESC: MARKET
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MARKET" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Span
  -- @COL_DESC: SPAN
  -- @COL_DISPLAY_ORDER: 2
  "SPAN" NUMBER(19, 0) NOT NULL,
  -- @COL_GUI_NAME: Observations for STDDEV
  -- @COL_DESC: OBSERVATIONS_FOR_STDDEV
  -- @COL_DISPLAY_ORDER: 3
  "OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL,
  -- @COL_GUI_NAME: Min observations for STDDEV
  -- @COL_DESC: MINOBSERVATIONS_FOR_STDDEV
  -- @COL_DISPLAY_ORDER: 4
  "MIN_OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL,
  -- @COL_GUI_NAME: Number of STDDEV
  -- @COL_DESC: NUMBER_OF_STDDEV
  -- @COL_DISPLAY_ORDER: 5
  "NUMBER_OF_STDDEV" NUMBER(19, 0) NOT NULL,
  -- @COL_GUI_NAME: Fees in BP
  -- @COL_DESC: FEES_IN_BP
  -- @COL_DISPLAY_ORDER: 6
  "FEES_IN_BP" NUMBER(19, 0) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PRICE_TRADE_MONITOR_PARAMETERS" PRIMARY KEY ("MARKET")
) TABLESPACE FACT_DATA;
CREATE TABLE "GUI_XMDM_F7"."VOLATILITY_MONITOR" (
  "SEGMENTMARKET" VARCHAR2(30 BYTE) NOT NULL,
  "CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  "THRESHOLD_VALUES_INTRADAY" NUMBER,
  "THRESHOLD_VALUES_DAY_TO_DAY" NUMBER,
  "MAPPING_IDENTIFIER" VARCHAR2(50 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE FACT_DATA;