-- @TBL_GUI_NAME: Product Scope for SW
-- @TBL_GUI_NAME_SHORT: Product_Scope_for_SW
-- @TBL_NAME_AT: S_EX_SW_MM_PRODUCT_SCOPE_AT
-- @TBL_DISPLAY_ORDER: 14
CREATE TABLE "GUI_XMDM_MMPM"."S_EX_SW_MM_PRODUCT_SCOPE" (
  -- @COL_GUI_NAME: PRODUCT_SET_NO
  -- @COL_DESC: PRODUCT_SET_NO
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_SET_NO" NUMBER(15, 0),
  -- @COL_GUI_NAME: PRODUCT_SET_NAME
  -- @COL_DESC: PRODUCT_SET_NAME
  -- @COL_DISPLAY_ORDER: 2
  "PRODUCT_SET_NAME" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DESC: PRODUCT
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: QR_DAILY_CUT_LIMIT
  -- @COL_DESC: QR_DAILY_CUT_LIMIT
  -- @COL_DISPLAY_ORDER: 4
  "QR_DAILY_CUT_LIMIT" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_DAILY_FLOOR_LIMIT
  -- @COL_DESC: QR_DAILY_FLOOR_LIMIT
  -- @COL_DISPLAY_ORDER: 5
  "QR_DAILY_FLOOR_LIMIT" NUMBER(15, 0),
  -- @COL_GUI_NAME: QUOTATION_START_TIME
  -- @COL_DESC: QUOTATION_START_TIME
  -- @COL_DISPLAY_ORDER: 6
  "QUOTATION_START_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: QUOTATION_END_TIME
  -- @COL_DESC: QUOTATION_END_TIME
  -- @COL_DISPLAY_ORDER: 7
  "QUOTATION_END_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: REQUIRED_COVERAGE
  -- @COL_DESC: REQUIRED_COVERAGE
  -- @COL_DISPLAY_ORDER: 8
  "REQUIRED_COVERAGE" NUMBER,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: PRIMARY_FLAG
  -- @COL_DESC: Primary flag -> Y, N, C. C is combined so Y or N together
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'PRIMARY' AS LABEL, 'Y' AS VALUE FROM DUAL UNION SELECT 'NON PRIMARY' AS LABEL, 'N' AS VALUE FROM DUAL UNION SELECT 'COMBINED' AS LABEL, 'C' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: VALUE
  -- @LKP_SQL_VALUE: VALUE
  "PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT ('Y')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Parameters for Strategies (SW)
-- @TBL_GUI_NAME_SHORT: Parameters_for_Strategies_(SW)
-- @TBL_NAME_AT: S_EX_SW_MM_STRTG_PARAM_AT
-- @TBL_DISPLAY_ORDER: 15
CREATE TABLE "GUI_XMDM_MMPM"."S_EX_SW_MM_STRTG_PARAM" (
  -- @COL_GUI_NAME: PRODUCT_SET_NO
  -- @COL_DESC: PRODUCT_SET_NO
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_SET_NO" NUMBER(15, 0),
  -- @COL_GUI_NAME: STRATEGY_SYMBOL
  -- @COL_DESC: STRATEGY_SYMBOL
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "STRATEGY_SYMBOL" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: EXP_CYCLE_N_FROM
  -- @COL_DESC: EXP_CYCLE_N_FROM
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "EXP_CYCLE_N_FROM" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_N_TO
  -- @COL_DESC: EXP_CYCLE_N_TO
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "EXP_CYCLE_N_TO" NUMBER(3, 0),
  -- @COL_GUI_NAME: STRATEGY_NAME
  -- @COL_DESC: STRATEGY_NAME
  -- @COL_DISPLAY_ORDER: 5
  "STRATEGY_NAME" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: WITH_UNDERLYING_IND
  -- @COL_DESC: WITH_UNDERLYING_IND
  -- @COL_DISPLAY_ORDER: 6
  "WITH_UNDERLYING_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: OUTRIGHT_MAX_SPREAD_MULTPL
  -- @COL_DESC: OUTRIGHT_MAX_SPREAD_MULTPL
  -- @COL_DISPLAY_ORDER: 7
  "OUTRIGHT_MAX_SPREAD_MULTPL" NUMBER,
  -- @COL_GUI_NAME: OUTRIGHT_MIN_Q_SIZE_MULTPL
  -- @COL_DESC: OUTRIGHT_MIN_Q_SIZE_MULTPL
  -- @COL_DISPLAY_ORDER: 8
  "OUTRIGHT_MIN_Q_SIZE_MULTPL" NUMBER,
  -- @COL_GUI_NAME: DAYS_TO_EXP_FADE_OUT
  -- @COL_DESC: DAYS_TO_EXP_FADE_OUT
  -- @COL_DISPLAY_ORDER: 9
  "DAYS_TO_EXP_FADE_OUT" NUMBER(3, 0),
  -- @COL_GUI_NAME: QR_MAX_TRANSACT_TIME_DIFF
  -- @COL_DESC: QR_MAX_TRANSACT_TIME_DIFF
  -- @COL_DISPLAY_ORDER: 10
  "QR_MAX_TRANSACT_TIME_DIFF" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_CLOSE_TIME_DIFF
  -- @COL_DESC: QR_CLOSE_TIME_DIFF
  -- @COL_DISPLAY_ORDER: 11
  "QR_CLOSE_TIME_DIFF" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_HOLD_TIME
  -- @COL_DESC: QR_HOLD_TIME
  -- @COL_DISPLAY_ORDER: 12
  "QR_HOLD_TIME" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_RESPONSE_TIME
  -- @COL_DESC: QR_RESPONSE_TIME
  -- @COL_DISPLAY_ORDER: 13
  "QR_RESPONSE_TIME" NUMBER(15, 0),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Recalculation Schedule
-- @TBL_GUI_NAME_SHORT: Recalculation Schedule
-- @TBL_NAME_AT: S_MMPM_RECALC_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPM_RECALC" (
  -- @COL_GUI_NAME: FACT_DATE
  -- @COL_DESC: Fact Date
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE,
  -- @COL_GUI_NAME: PROGRESS
  -- @COL_DESC: Progress, SCHEDULED is default
  -- @COL_DISPLAY_ORDER: 2
  -- @LKP_SQL_STMT1: SELECT 'SCHEDULED' AS LABEL, 'SCHEDULED' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PROGRESS" VARCHAR2(100 BYTE) DEFAULT 'SCHEDULED',
  -- @COL_GUI_NAME: PROGRESS_AT
  -- @COL_DESC: Progress At
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy hh:mm:ss
  "PROGRESS_AT" DATE DEFAULT SYSDATE,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Verification Schedule
-- @TBL_GUI_NAME_SHORT: Verification Schedule
-- @TBL_NAME_AT: S_MMPM_VERIF_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPM_VERIF" (
  -- @COL_GUI_NAME: FACT_DATE
  -- @COL_DESC: Fact Date
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE,
  -- @COL_GUI_NAME: BUSINESS_UNIT_BUS_ID
  -- @COL_DESC: Business Unit
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "BUSINESS_UNIT_BUS_ID" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: PRODUCT_BUS_ID
  -- @COL_DESC: Product
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUS_ID" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: INSTRUMENT_T7_ID
  -- @COL_DESC: Instrument, 0-ALL
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "INSTRUMENT_T7_ID" NUMBER(20, 0) DEFAULT 0,
  -- @COL_GUI_NAME: PROGRESS
  -- @COL_DESC: Progress, SCHEDULED is default
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT 'SCHEDULED' AS LABEL, 'SCHEDULED' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PROGRESS" VARCHAR2(100 BYTE) DEFAULT 'SCHEDULED',
  -- @COL_GUI_NAME: PROGRESS_AT
  -- @COL_DESC: Progress At
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: dd.MM.yyyy hh:mm:ss
  "PROGRESS_AT" DATE DEFAULT SYSDATE,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: DATA_SOURCE
  -- @COL_DESC: Data source to be verify
  -- @COL_DISPLAY_ORDER: 7
  -- @LKP_SQL_STMT1: SELECT 'T7_EUREX' AS LABEL, 'T7_EUREX' AS VALUE FROM DUAL UNION SELECT 'T7_EUREX_FX' AS LABEL, 'T7_EUREX_FX' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "SOURCE" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: MODE
  -- @COL_DESC: Verification mode
  -- @COL_DISPLAY_ORDER: 8
  -- @LKP_SQL_STMT1: SELECT 'LP' AS LABEL, 'LP' AS VALUE FROM DUAL UNION SELECT 'RMM' AS LABEL, 'RMM' AS VALUE FROM DUAL UNION SELECT 'HFT' AS LABEL, 'HFT' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "SERVICE_MODE" VARCHAR2(20 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Enlight Black List Tab
-- @TBL_GUI_NAME_SHORT: Enlight Black List Tab
-- @TBL_NAME_AT: S_MMPRM_ENLIGHT_BLACK_LIST_AT
-- @TBL_DISPLAY_ORDER: 24
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_ENLIGHT_BLACK_LIST" (
  -- @COL_GUI_NAME: MM_BUSINESS_ID
  -- @COL_DESC: Market maker /Responder/ business id
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_BUSINESS_ID" VARCHAR2(15 BYTE) NOT NULL,
  -- @COL_GUI_NAME: MM_TRADER
  -- @COL_DESC: Market maker /Responder/ trader id
  -- @COL_DISPLAY_ORDER: 2
  "MM_TRADER" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: RM_BUSINESS_ID
  -- @COL_DESC: Requestor business id
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "RM_BUSINESS_ID" VARCHAR2(15 BYTE) NOT NULL,
  -- @COL_GUI_NAME: RM_TRADER
  -- @COL_DESC: Requestor trader id
  -- @COL_DISPLAY_ORDER: 4
  "RM_TRADER" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: Record valid from date
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: Record valid to date
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Exceptional circumstances
-- @TBL_GUI_NAME_SHORT: Exceptional circumstances
-- @TBL_NAME_AT: S_MMPRM_EXCEPT_CIRCUMSTANCS_AT
-- @TBL_DISPLAY_ORDER: 21
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_EXCEPT_CIRCUMSTANCS" (
  -- @COL_GUI_NAME: MEMBER_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MEMBER_BUSINESS_ID" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: FACT_DATE
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE,
  -- @COL_GUI_NAME: START_TIME
  -- @COL_DISPLAY_ORDER: 4
  "START_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: END_TIME
  -- @COL_DISPLAY_ORDER: 5
  "END_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: DESCRIPTION
  -- @COL_DISPLAY_ORDER: 6
  "DESCRIPTION" VARCHAR2(500 BYTE),
  -- @COL_GUI_NAME: RMM_FLAG
  -- @COL_DISPLAY_ORDER: 7
  "RMM_FLAG" VARCHAR2(1 BYTE),
  -- @COL_GUI_NAME: LP_FLAG
  -- @COL_DISPLAY_ORDER: 8
  "LP_FLAG" VARCHAR2(1 BYTE),
  -- @COL_GUI_NAME: REQUIRED_TIME
  -- @COL_DISPLAY_ORDER: 9
  "REQUIRED_TIME" NUMBER(15, 0),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Fulfillment Rules
-- @TBL_GUI_NAME_SHORT: Fulfillment rules
-- @TBL_NAME_AT: S_MMPRM_FULFILLMENT_RULES_AT
-- @TBL_DISPLAY_ORDER: 22
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_FULFILLMENT_RULES" (
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: BASIC_BB
  -- @COL_DISPLAY_ORDER: 3
  "BASIC_BB" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: PACKAGE_BB
  -- @COL_DISPLAY_ORDER: 4
  "PACKAGE_BB" VARCHAR2(4000 BYTE),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: SESSION_TYPE
  -- @COL_DESC: Early/Regular/Early+Regular
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'REGULAR' AS APPLY_SESSION, 'REGULAR' AS VALUE FROM DUAL UNION SELECT 'EARLY' AS APPLY_SESSION, 'EARLY' AS VALUE FROM DUAL UNION SELECT 'REGULAR+EARLY' AS APPLY_SESSION, 'REGULAR+EARLY' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: APPLY_SESSION
  -- @LKP_SQL_VALUE: VALUE
  "SESSION_TYPE" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: STRATEGY_BB
  -- @COL_DESC: STRATEGY_BB rule
  -- @COL_DISPLAY_ORDER: 5
  "STRATEGY_BB" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: SPREAD_BB
  -- @COL_DESC: SPREAD_BB rule
  -- @COL_DISPLAY_ORDER: 6
  "SPREAD_BB" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: SIZE_BB
  -- @COL_DESC: SIZE_BB rule
  -- @COL_DISPLAY_ORDER: 7
  "SIZE_BB" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: EL_BB
  -- @COL_DESC: Enlight rule
  -- @COL_DISPLAY_ORDER: 8
  "EL_BB" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: PRIMARY_FLAG
  -- @COL_DESC: Primary flag -> Y, N, C. C is combined so Y or N together
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'PRIMARY' AS LABEL, 'Y' AS VALUE FROM DUAL UNION SELECT 'NON PRIMARY' AS LABEL, 'N' AS VALUE FROM DUAL UNION SELECT 'COMBINED' AS LABEL, 'C' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: VALUE
  -- @LKP_SQL_VALUE: VALUE
  "PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT ('Y'),
  "ADVANCE_BB_REBATE" VARCHAR2(255 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Parameters for MMPM HFT
-- @TBL_GUI_NAME_SHORT: Parameters for MMPM HFT
-- @TBL_NAME_AT: S_MMPRM_HFT_AT
-- @TBL_DISPLAY_ORDER: 18
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_HFT" (
  -- @COL_GUI_NAME: MMPM Program
  -- @COL_DESC: MMPM Program
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MMPM Package
  -- @COL_DESC: MMPM Package
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Product Business Id
  -- @COL_DESC: Product Business Id
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: Spread Class Code
  -- @COL_DESC: Spread Class Code
  -- @COL_DISPLAY_ORDER: 4
  "SPREAD_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: Size Class Code
  -- @COL_DESC: Size Class Code
  -- @COL_DISPLAY_ORDER: 5
  "SIZE_CLASS_CODE" VARCHAR2(70 BYTE),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: Group Name
  -- @COL_DESC: Group Name
  -- @COL_DISPLAY_ORDER: 6
  "GROUP_NAME" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Liquidity Class
  -- @COL_DESC: Liquidity Class
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0
  "LIQUIDITY_CLASS" NUMBER,
  -- @COL_GUI_NAME: Required Coverage
  -- @COL_DESC: Required Coverage
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.##
  "REQUIRED_COVERAGE" NUMBER,
  -- @COL_GUI_NAME: Quotation Start Time
  -- @COL_DESC: Quotation Start Time
  -- @COL_DISPLAY_ORDER: 9
  "QUOTATION_START_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: Quotation End Time
  -- @COL_DESC: Quotation End Time
  -- @COL_DISPLAY_ORDER: 10
  "QUOTATION_END_TIME" VARCHAR2(8 BYTE),
  -- @COL_GUI_NAME: EXP_CYCLE_N_FROM
  -- @COL_DESC: EXP_CYCLE_N_FROM
  -- @COL_DISPLAY_ORDER: 11
  "EXP_CYCLE_N_FROM" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_N_TO
  -- @COL_DESC: EXP_CYCLE_N_TO
  -- @COL_DISPLAY_ORDER: 12
  "EXP_CYCLE_N_TO" NUMBER(3, 0)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Liquidity class
-- @TBL_GUI_NAME_SHORT: Liquidity class
-- @TBL_NAME_AT: S_MMPRM_LIQUIDITY_CLASS_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_LIQUIDITY_CLASS" (
  -- @COL_GUI_NAME: PRODUCT_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: LIQUIDITY_CLASS
  -- @COL_DISPLAY_ORDER: 4
  "LIQUIDITY_CLASS" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Liquidity Provider
-- @TBL_GUI_NAME_SHORT: Liquidity Provider
-- @TBL_NAME_AT: S_MMPRM_LIQ_PROVIDER_AT
-- @TBL_DISPLAY_ORDER: 20
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_LIQ_PROVIDER" (
  -- @COL_GUI_NAME: MEMBER_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: LP_FLAG
  -- @COL_DISPLAY_ORDER: 4
  "LP_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: RMM_FLAG
  -- @COL_DISPLAY_ORDER: 5
  "RMM_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: ENL_FLAG
  -- @COL_DESC: EnLigh flag
  -- @COL_DISPLAY_ORDER: 6
  "ENL_FLAG" VARCHAR2(1 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Overrule
-- @TBL_GUI_NAME_SHORT: Overrule
-- @TBL_NAME_AT: S_MMPRM_OVERRULE_AT
-- @TBL_DISPLAY_ORDER: 23
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_OVERRULE" (
  -- @COL_GUI_NAME: INTERVAL_FROM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_FORMAT: dd.MM.yyyy
  "INTERVAL_FROM" DATE,
  -- @COL_GUI_NAME: INTERVAL_TO
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  "INTERVAL_TO" DATE,
  -- @COL_GUI_NAME: MEMBER_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_BUSINESS_ID" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: PQ_BB
  -- @COL_DISPLAY_ORDER: 7
  "PQ_BB" NUMBER,
  -- @COL_GUI_NAME: STRATEGY_BB
  -- @COL_DISPLAY_ORDER: 8
  "STRATEGY_BB" NUMBER,
  -- @COL_GUI_NAME: LARGER_SIZE_BB
  -- @COL_DISPLAY_ORDER: 9
  "LARGER_SIZE_BB" NUMBER,
  -- @COL_GUI_NAME: TIGHTER_SPREAD_BB
  -- @COL_DISPLAY_ORDER: 10
  "TIGHTER_SPREAD_BB" NUMBER,
  -- @COL_GUI_NAME: SMC_BB
  -- @COL_DISPLAY_ORDER: 11
  "SMC_BB" NUMBER,
  -- @COL_GUI_NAME: ENLIGHT
  -- @COL_DISPLAY_ORDER: 12
  "ENLIGHT" NUMBER,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 15
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: DESCRIPTION
  -- @COL_DISPLAY_ORDER: 13
  "DESCRIPTION" VARCHAR2(500 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Calendar Spread Matrix
-- @TBL_GUI_NAME_SHORT: Calendar_Spread_Matrix
-- @TBL_NAME_AT: S_MMPRM_PCKG_CAL_SPRD_MTRX_AT
-- @TBL_DISPLAY_ORDER: 13
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_CAL_SPRD_MTRX" (
  -- @COL_GUI_NAME: MMPM Program
  -- @COL_DESC: MMPM Program
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(255 BYTE),
  -- @COL_GUI_NAME: MMPM Package
  -- @COL_DESC: MMPM Package
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Product Business Id
  -- @COL_DESC: Product Business Id
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(255 BYTE),
  -- @COL_GUI_NAME: Leg Expiration
  -- @COL_DESC: Leg 1 Expiration
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "LEG_01_EXP" NUMBER(15, 0),
  "LEG_02_EXP" NUMBER(15, 0),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: Leg primary flag
  -- @COL_DESC: Leg primary flag, Y - primary flag instrument, N - nonprimary instrument, C - combined primary and non-primary instrument
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'PRIMARY' AS LABEL, 'Y' AS VALUE FROM DUAL UNION SELECT 'NON PRIMARY' AS LABEL, 'N' AS VALUE FROM DUAL UNION SELECT 'COMBINED' AS LABEL, 'C' AS VALUE FROM DUAL
  -- @LKP_SQL_LABEL: VALUE
  -- @LKP_SQL_VALUE: VALUE
  "LEG01_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT ('Y'),
  "LEG02_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT null,
  -- @COL_GUI_NAME: Spread group
  -- @COL_DESC: Spread group index
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  "SPREAD_GROUP" NUMBER(15, 0)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Programs, Packages and Components
-- @TBL_GUI_NAME_SHORT: Programs__Packages__Components
-- @TBL_NAME_AT: S_MMPRM_PCKG_COMP_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_COMP" (
  -- @COL_GUI_NAME: MMPM Program
  -- @COL_DESC: MMPM Program
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MMPM Package
  -- @COL_DESC: MMPM Package
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Product Business Id
  -- @COL_DESC: Product Business Id
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: Mandatory Fullfilment
  -- @COL_DESC: Mandatory Fullfilment
  -- @COL_DISPLAY_ORDER: 4
  "MANDATORY_FULFILL_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: ALTERN_MANDATORY_IND
  -- @COL_DESC: ALTERN_MANDATORY_IND
  -- @COL_DISPLAY_ORDER: 5
  "ALTERN_MANDATORY_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: WEEKLY_OPTION_IND
  -- @COL_DESC: WEEKLY_OPTION_IND
  -- @COL_DISPLAY_ORDER: 6
  "WEEKLY_OPTION_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: UNDERLYING_ISIN_OVRD
  -- @COL_DESC: UNDERLYING_ISIN_OVRD
  -- @COL_DISPLAY_ORDER: 7
  "UNDERLYING_ISIN_OVRD" VARCHAR2(12 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: STD_EXP_IN_WEEKLY_QUO_FRM
  -- @COL_DESC: STD_EXP_IN_WEEKLY_QUO_FRM
  -- @COL_DISPLAY_ORDER: 8
  "STD_EXP_INCL_WEEKLY_QUO_FRM" VARCHAR2(1 BYTE),
  -- @COL_GUI_NAME: WEEKLY_QUO_FRM_SIZE
  -- @COL_DESC: WEEKLY_QUO_FRM_SIZE
  -- @COL_DISPLAY_ORDER: 9
  "WEEKLY_QUO_FRM_SIZE" VARCHAR2(1 BYTE),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: Quarterly expir indicator
  -- @COL_DESC: Y or N
  -- @COL_DISPLAY_ORDER: 10
  "QUARTERLY_EXP_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: PRIMARY_FLAG
  -- @COL_DESC: Package primary flag
  -- @COL_DISPLAY_ORDER: 26
  -- @COL_PK: Y
  "PRIMARY_FLAG" CHAR(1 BYTE) DEFAULT 'Y'
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Package Hierarchical Links
-- @TBL_GUI_NAME_SHORT: Package_Hierarchical_Links
-- @TBL_NAME_AT: S_MMPRM_PCKG_HIER_LNK_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_HIER_LNK" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE_PARENT
  -- @COL_DESC: MM_PROG_PACKAGE_PARENT
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MM_PROG_PACKAGE_PARENT" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: SUB_PACKAGE_FULFM_COND
  -- @COL_DESC: SUB_PACKAGE_FULFM_COND
  -- @COL_DISPLAY_ORDER: 4
  "SUB_PACKAGE_FULFM_COND" VARCHAR2(10 BYTE),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Assignment of Members to Programs and Packages
-- @TBL_GUI_NAME_SHORT: Assign_memb_to_prog_and_packag
-- @TBL_NAME_AT: S_MMPRM_PCKG_MBR_ASN_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_MBR_ASN" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: MEMBER_BUSINESS_ID
  -- @COL_DESC: MEMBER_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_BUSINESS_ID" VARCHAR2(15 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: CUSTOMER_ID
  -- @COL_DESC: Customer id name
  -- @COL_DISPLAY_ORDER: 4
  "CUSTOMER_ID" VARCHAR2(50 BYTE) DEFAULT '',
  -- @COL_GUI_NAME: ACCOUNT_TYPE_PATTERN
  -- @COL_DESC: Extended list of accounts used in calculation. For example  A1 / A1,P2 / A*,P3 ....
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_PK: Y
  "ACCOUNT_TYPE_PATTERN" VARCHAR2(30 BYTE),
  "ACCOUNTS_LIST" VARCHAR2(30 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Parameters for Program, Package and Product
-- @TBL_GUI_NAME_SHORT: Param_for_prog__packag__prod
-- @TBL_NAME_AT: S_MMPRM_PCKG_PRD_PARAM_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_PRD_PARAM" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT MM_PROGRAM FROM GUI_XMDM_MMPM_WIF.S_MMPRM_PCKG_COMP
ORDER BY MM_PROGRAM
  -- @LKP_SQL_LABEL: MM_PROGRAM
  -- @LKP_SQL_VALUE: MM_PROGRAM
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT MM_PROG_PACKAGE FROM GUI_XMDM_MMPM_WIF.S_MMPRM_PCKG_COMP WHERE MM_PROGRAM = ? ORDER BY MM_PROG_PACKAGE
  -- @LKP_SQL_LABEL: MM_PROG_PACKAGE
  -- @LKP_SQL_VALUE: MM_PROG_PACKAGE
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: PRODUCT_BUSINESS_ID
  -- @COL_DESC: PRODUCT_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DIM.BUSINESS_ID AS LABEL, DIM.BUSINESS_ID AS VALUE
FROM EUREX.D_EX_PRODUCT_OBJ DIM
WHERE
SOURCE_SYSTEM = 'EUREX'
AND SYSDATE BETWEEN VALID_FROM AND VALID_TO
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_QUOT_TYPE
  -- @COL_DESC: MM_QUOT_TYPE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'Permanent Quotation' AS LABEL, 'PQ' AS VALUE FROM DUAL UNION
SELECT 'Quotation on Request' AS LABEL, 'QR' AS VALUE FROM DUAL
ORDER BY LABEL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "MM_QUOT_TYPE" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: APPLY_DAYS_TO_EXP_SPREAD
  -- @COL_DESC: APPLY_DAYS_TO_EXP_SPREAD
  -- @COL_DISPLAY_ORDER: 5
  "APPLY_DAYS_TO_EXP_SPREAD" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_SELECTION_RULE
  -- @COL_DESC: EXP_SELECTION_RULE
  -- @COL_DISPLAY_ORDER: 6
  "EXP_SELECTION_RULE" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: SCOPE_EXP_CYCLE_NO_FROM
  -- @COL_DESC: SCOPE_EXP_CYCLE_NO_FROM
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0
  "SCOPE_EXP_CYCLE_NO_FROM" NUMBER(3, 0),
  -- @COL_GUI_NAME: SCOPE_EXP_CYCLE_NO_TO
  -- @COL_DESC: SCOPE_EXP_CYCLE_NO_TO
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0
  "SCOPE_EXP_CYCLE_NO_TO" NUMBER(3, 0),
  -- @COL_GUI_NAME: REQUIRED_COVERAGE
  -- @COL_DESC: REQUIRED_COVERAGE
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "REQUIRED_COVERAGE" NUMBER,
  -- @COL_GUI_NAME: TOLERATED_VIOLATION_DAYS
  -- @COL_DESC: TOLERATED_VIOLATION_DAYS
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0
  "TOLERATED_VIOLATION_DAYS" NUMBER(3, 0),
  -- @COL_GUI_NAME: REQUIRED_MTHLY_VOLUME
  -- @COL_DESC: REQUIRED_MTHLY_VOLUME
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: ###,###,##0
  "REQUIRED_MTHLY_VOLUME" NUMBER,
  -- @COL_GUI_NAME: TIME_VALUE_FACTOR
  -- @COL_DESC: TIME_VALUE_FACTOR
  -- @COL_DISPLAY_ORDER: 12
  "TIME_VALUE_FACTOR" NUMBER,
  -- @COL_GUI_NAME: AQ_NBR_OF_RELV_AUCT
  -- @COL_DESC: AQ_NBR_OF_RELV_AUCT
  -- @COL_DISPLAY_ORDER: 13
  "AQ_NBR_OF_RELV_AUCT" NUMBER(15, 0),
  -- @COL_GUI_NAME: AQ_REQUIRED_AUCT_COVERAGE
  -- @COL_DESC: AQ_REQUIRED_AUCT_COVERAGE
  -- @COL_DISPLAY_ORDER: 14
  "AQ_REQUIRED_AUCT_COVERAGE" NUMBER,
  -- @COL_GUI_NAME: REQUIRED_AVG_SPREAD
  -- @COL_DESC: REQUIRED_AVG_SPREAD
  -- @COL_DISPLAY_ORDER: 15
  "REQUIRED_AVG_SPREAD" NUMBER,
  -- @COL_GUI_NAME: SETTLEMENT_PRICE_FACTOR
  -- @COL_DESC: SETTLEMENT_PRICE_FACTOR
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_FORMAT: 0
  "SETTLEMENT_PRICE_FACTOR" NUMBER,
  -- @COL_GUI_NAME: QR_DAILY_CUT_LIMIT
  -- @COL_DESC: QR_DAILY_CUT_LIMIT
  -- @COL_DISPLAY_ORDER: 17
  "QR_DAILY_CUT_LIMIT" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_MONTHLY_FLOOR_LIMIT
  -- @COL_DESC: QR_MONTHLY_FLOOR_LIMIT
  -- @COL_DISPLAY_ORDER: 18
  "QR_MONTHLY_FLOOR_LIMIT" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_MAX_TRANSACT_TIME_DIFF
  -- @COL_DESC: QR_MAX_TRANSACT_TIME_DIFF
  -- @COL_DISPLAY_ORDER: 19
  "QR_MAX_TRANSACT_TIME_DIFF" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_CLOSE_TIME_DIFF
  -- @COL_DESC: QR_CLOSE_TIME_DIFF
  -- @COL_DISPLAY_ORDER: 20
  "QR_CLOSE_TIME_DIFF" NUMBER(15, 0),
  -- @COL_GUI_NAME: MAX_UNL_INSIDE_MKT_SPREAD
  -- @COL_DESC: MAX_UNL_INSIDE_MKT_SPREAD
  -- @COL_DISPLAY_ORDER: 21
  "MAX_UNL_INSIDE_MKT_SPREAD" NUMBER,
  -- @COL_GUI_NAME: MIN_UNL_INSIDE_MKT_SIZE
  -- @COL_DESC: MIN_UNL_INSIDE_MKT_SIZE
  -- @COL_DISPLAY_ORDER: 22
  "MIN_UNL_INSIDE_MKT_SIZE" NUMBER(15, 0),
  -- @COL_GUI_NAME: SPREAD_UNIT
  -- @COL_DESC: SPREAD_UNIT
  -- @COL_DISPLAY_ORDER: 23
  "SPREAD_UNIT" VARCHAR2(10 CHAR),
  -- @COL_GUI_NAME: QUOTE_SIZE_QLTY_TRGT_FCT
  -- @COL_DESC: QUOTE_SIZE_QLTY_TRGT_FCT
  -- @COL_DISPLAY_ORDER: 24
  "QUOTE_SIZE_QLTY_TRGT_FCT" NUMBER,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: MIN_LP_RFQ_PER_MONTH
  -- @COL_DESC: Minumum valid RFQ per month
  -- @COL_DISPLAY_ORDER: 25
  "MIN_LP_RFQ_PER_MONTH" NUMBER(15, 0),
  -- @COL_GUI_NAME: ZERO_PRV_SETTLEMENT_PRICE_FLAG
  -- @COL_DESC: Validate instrument with previous 0.0 settlement price, Y/N flag, in case not fill yes flag used
  -- @COL_DISPLAY_ORDER: 26
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(Y|N)
  "ZERO_PRV_SETTL_PRICE_FLAG" VARCHAR2(1 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Interval Measurement for Program, Package and Product
-- @TBL_GUI_NAME_SHORT: Int_measr_for_prog__pack__prod
-- @TBL_NAME_AT: S_MMPRM_PCKG_PRD_Q_INTV_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_PRD_Q_INTV" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: PRODUCT_BUSINESS_ID
  -- @COL_DESC: PRODUCT_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_QUOT_TYPE
  -- @COL_DESC: MM_QUOT_TYPE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "MM_QUOT_TYPE" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: QUOTATION_INTV_NO
  -- @COL_DESC: QUOTATION_INTV_NO
  -- @COL_DISPLAY_ORDER: 5
  "QUOTATION_INTV_NO" NUMBER(3, 0),
  -- @COL_GUI_NAME: SPW_CODE
  -- @COL_DESC: SPW_CODE
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SPW.SPW_CODE
  "SPW_CODE" VARCHAR2(25 CHAR),
  -- @COL_GUI_NAME: SPREAD_CLASS_CODE
  -- @COL_DESC: SPREAD_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SPREAD_CLASS.SPREAD_CLASS_CODE
  "SPREAD_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: SIZE_CLASS_CODE
  -- @COL_DESC: SIZE_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SIZE_CLASS.SIZE_CLASS_CODE
  "SIZE_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: QUOTATION_START_TIME
  -- @COL_DESC: QUOTATION_START_TIME
  -- @COL_DISPLAY_ORDER: 10
  "QUOTATION_START_TIME" VARCHAR2(8 CHAR),
  -- @COL_GUI_NAME: QUOTATION_END_TIME
  -- @COL_DESC: QUOTATION_END_TIME
  -- @COL_DISPLAY_ORDER: 11
  "QUOTATION_END_TIME" VARCHAR2(8 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: PRODUCT_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_PRODUCT_CLASS.PRODUCT_CLASS_CODE
  "PRODUCT_CLASS_CODE" VARCHAR2(50 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Rollover Cycle for Program, Package and Product
-- @TBL_GUI_NAME_SHORT: Roll_cyc_for_prog__packag_prod
-- @TBL_NAME_AT: S_MMPRM_PCKG_PRD_ROLL_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PCKG_PRD_ROLL" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: PRODUCT_BUSINESS_ID
  -- @COL_DESC: PRODUCT_BUSINESS_ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_QUOT_TYPE
  -- @COL_DESC: MM_QUOT_TYPE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "MM_QUOT_TYPE" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_SCOPE
  -- @COL_DESC: EXP_CYCLE_NO_SCOPE
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0
  "EXP_CYCLE_NO_SCOPE" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_FADE
  -- @COL_DESC: EXP_CYCLE_NO_FADE
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "EXP_CYCLE_NO_FADE" NUMBER(3, 0),
  -- @COL_GUI_NAME: FADE_IN_OUT_IND
  -- @COL_DESC: FADE_IN_OUT_IND
  -- @COL_DISPLAY_ORDER: 7
  "FADE_IN_OUT_IND" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: FADE_IN_OPTIONAL_IND
  -- @COL_DESC: FADE_IN_OPTIONAL_IND
  -- @COL_DISPLAY_ORDER: 8
  "FADE_IN_OPTIONAL_IND" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: FADE_KEYDATE
  -- @COL_DESC: FADE_KEYDATE
  -- @COL_DISPLAY_ORDER: 9
  "FADE_KEYDATE" VARCHAR2(100 CHAR),
  -- @COL_GUI_NAME: DAYS_TO_FADE_KEYDATE
  -- @COL_DESC: DAYS_TO_FADE_KEYDATE
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0
  "DAYS_TO_FADE_KEYDATE" NUMBER(15, 0),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Product class
-- @TBL_GUI_NAME_SHORT: Product_class
-- @TBL_NAME_AT: S_MMPRM_PRODUCT_CLASS_AT
-- @TBL_DISPLAY_ORDER: 16
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PRODUCT_CLASS" (
  -- @COL_GUI_NAME: PRODUCT_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_CLASS_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: FACTOR_BB_SPREAD
  -- @COL_DISPLAY_ORDER: 4
  "FACTOR_BB_SPREAD" NUMBER(6, 3),
  -- @COL_GUI_NAME: FACTOR_BB_SIZE
  -- @COL_DISPLAY_ORDER: 5
  "FACTOR_BB_SIZE" NUMBER(6, 3),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: FACTOR_MAX_RFQ_RESPONSE_TIME
  -- @COL_DESC: Factor for maximum RFQ response time
  -- @COL_DISPLAY_ORDER: 6
  "FACTOR_MAX_RFQ_RESPONSE_TIME" NUMBER(6, 3),
  -- @COL_GUI_NAME: FACTOR_MIN_RFQ_HOLD_TIME
  -- @COL_DESC: Factor for minimum holding time
  -- @COL_DISPLAY_ORDER: 7
  "FACTOR_MIN_RFQ_HOLD_TIME" NUMBER(6, 3)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Product Specific Setup
-- @TBL_GUI_NAME_SHORT: Product_Specific_Setup
-- @TBL_NAME_AT: S_MMPRM_PRODUCT_SETUP_AT
-- @TBL_DISPLAY_ORDER: 25
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PRODUCT_SETUP" (
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: From which day record is active
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: To which day record is active
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DESC: Name of product
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: SETTLEMENT_PRICE
  -- @COL_DESC: Load settlement price flag
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[YN]
  -- @LKP_SQL_STMT1: SELECT 'Y' AS VALUE, 'Y' AS LABEL FROM DUAL UNION ALL SELECT 'N' AS VALUE, 'N' AS LABEL FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "SETTLEMENT_PRICE" CHAR(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: ALLOW_2_SIDE_LIMIT_ORDERS
  -- @COL_DESC: Allow 2 side limit order flag
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[YN]
  -- @LKP_SQL_STMT1: SELECT 'Y' AS VALUE, 'Y' AS LABEL FROM DUAL UNION ALL SELECT 'N' AS VALUE, 'N' AS LABEL FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "ALLOW_2_SIDE_LIMIT_ORDERS" CHAR(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: UNDERLYING_INSTRUMENT_SHIFT
  -- @COL_DESC: Shift of underlying front month instrument in months
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0
  "UNDERLYING_INSTRUMENT_SHIFT" NUMBER(3, 0),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Programs and Packages
-- @TBL_GUI_NAME_SHORT: Programs_and_Packages
-- @TBL_NAME_AT: S_MMPRM_PROG_PACKAGE_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_PROG_PACKAGE" (
  -- @COL_GUI_NAME: MM_PROGRAM
  -- @COL_DESC: MM_PROGRAM
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT MM_PROGRAM FROM GUI_XMDM_MMPM_WIF.S_MMPRM_PROG_PACKAGE
  -- @LKP_SQL_LABEL: MM_PROGRAM
  -- @LKP_SQL_VALUE: MM_PROGRAM
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MM_PROG_PACKAGE
  -- @COL_DESC: MM_PROG_PACKAGE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: NBR_OF_ALLOWED_VIOL_PROD
  -- @COL_DESC: NBR_OF_ALLOWED_VIOL_PROD
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "NBR_OF_ALLOWED_VIOL_PROD" NUMBER(15, 0),
  -- @COL_GUI_NAME: PERCT_OF_ALLOWED_VIOL_PROD
  -- @COL_DESC: PERCT_OF_ALLOWED_VIOL_PROD
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "PERCT_OF_ALLOWED_VIOL_PROD" NUMBER,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Parameters for MMPM Regulatory MM
-- @TBL_GUI_NAME_SHORT: Parameters for MMPM RMM
-- @TBL_NAME_AT: S_MMPRM_RMM_AT
-- @TBL_DISPLAY_ORDER: 19
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_RMM" (
  -- @COL_GUI_NAME: MMPM Program
  -- @COL_DESC: MMPM Program
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MM_PROGRAM" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MMPM Package
  -- @COL_DESC: MMPM Package
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MM_PROG_PACKAGE" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Product Business Id
  -- @COL_DESC: Product Business Id
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: Spread Class Code
  -- @COL_DESC: Spread Class Code
  -- @COL_DISPLAY_ORDER: 4
  "SPREAD_CLASS_CODE" VARCHAR2(70 BYTE),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: Group Name
  -- @COL_DESC: Group Name
  -- @COL_DISPLAY_ORDER: 5
  "GROUP_NAME" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Liquidity Class
  -- @COL_DESC: Liquidity Class
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0
  "LIQUIDITY_CLASS" NUMBER
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: SAP Fulfilment Filter
-- @TBL_GUI_NAME_SHORT: SAP_Ful_Filter
-- @TBL_NAME_AT: S_MMPRM_SAP_FULF_FILTER_AT
-- @TBL_DISPLAY_ORDER: 17
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SAP_FULF_FILTER" (
  -- @COL_GUI_NAME: PRODUCT
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Size Class
-- @TBL_GUI_NAME_SHORT: Size_Class
-- @TBL_NAME_AT: S_MMPRM_SIZE_CLASS_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SIZE_CLASS" (
  -- @COL_GUI_NAME: SIZE_CLASS_CODE
  -- @COL_DESC: SIZE_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SIZE_CLASS_DT.SIZE_CLASS_CODE
  "SIZE_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: SIZE_CLASS_NAME
  -- @COL_DESC: SIZE_CLASS_NAME
  -- @COL_DISPLAY_ORDER: 2
  "SIZE_CLASS_NAME" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: SIZE_CLASS_DESCR
  -- @COL_DESC: SIZE_CLASS_DESCR
  -- @COL_DISPLAY_ORDER: 3
  "SIZE_CLASS_DESCR" VARCHAR2(2000 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Details for Size Class
-- @TBL_GUI_NAME_SHORT: Details_for_Size_Class
-- @TBL_NAME_AT: S_MMPRM_SIZE_CLASS_DT_AT
-- @TBL_DISPLAY_ORDER: 9
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SIZE_CLASS_DT" (
  -- @COL_GUI_NAME: SIZE_CLASS_CODE
  -- @COL_DESC: SIZE_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SIZE_CLASS.SIZE_CLASS_CODE
  -- @LKP_SQL_STMT1: SELECT DISTINCT SIZE_CLASS_CODE FROM GUI_XMDM_MMPM_WIF.S_MMPRM_SIZE_CLASS ORDER BY SIZE_CLASS_CODE
  -- @LKP_SQL_LABEL: SIZE_CLASS_CODE
  -- @LKP_SQL_VALUE: SIZE_CLASS_CODE
  "SIZE_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: DAYS_TO_EXPIRATION
  -- @COL_DESC: DAYS_TO_EXPIRATION
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "DAYS_TO_EXPIRATION" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_FROM
  -- @COL_DESC: EXP_CYCLE_NO_FROM
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "EXP_CYCLE_NO_FROM" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_TO
  -- @COL_DESC: EXP_CYCLE_NO_TO
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "EXP_CYCLE_NO_TO" NUMBER(3, 0),
  -- @COL_GUI_NAME: MIN_QUOTE_SIZE
  -- @COL_DESC: MIN_QUOTE_SIZE
  -- @COL_DISPLAY_ORDER: 5
  "MIN_QUOTE_SIZE" NUMBER(15, 0),
  -- @COL_GUI_NAME: MIN_QUOTE_SIZE_TOTAL
  -- @COL_DESC: MIN_QUOTE_SIZE_TOTAL
  -- @COL_DISPLAY_ORDER: 6
  "MIN_QUOTE_SIZE_TOTAL" NUMBER(15, 0),
  -- @COL_GUI_NAME: MIN_QUOTE_SIZE_FAST
  -- @COL_DESC: MIN_QUOTE_SIZE_FAST
  -- @COL_DISPLAY_ORDER: 7
  "MIN_QUOTE_SIZE_FAST" NUMBER(15, 0),
  -- @COL_GUI_NAME: MIN_QUOTE_SIZE_TOTAL_FAST
  -- @COL_DESC: MIN_QUOTE_SIZE_TOTAL_FAST
  -- @COL_DISPLAY_ORDER: 8
  "MIN_QUOTE_SIZE_TOTAL_FAST" NUMBER(15, 0),
  -- @COL_GUI_NAME: RED_MIN_QUOTE_SIZE
  -- @COL_DESC: RED_MIN_QUOTE_SIZE
  -- @COL_DISPLAY_ORDER: 9
  "RED_MIN_QUOTE_SIZE" NUMBER(15, 0),
  -- @COL_GUI_NAME: RED_MIN_QUOTE_SIZE_TOTAL
  -- @COL_DESC: RED_MIN_QUOTE_SIZE_TOTAL
  -- @COL_DISPLAY_ORDER: 10
  "RED_MIN_QUOTE_SIZE_TOTAL" NUMBER(15, 0),
  -- @COL_GUI_NAME: RED_MIN_QUOTE_SIZE_FAST
  -- @COL_DESC: RED_MIN_QUOTE_SIZE_FAST
  -- @COL_DISPLAY_ORDER: 11
  "RED_MIN_QUOTE_SIZE_FAST" NUMBER(15, 0),
  -- @COL_GUI_NAME: RED_MIN_QUOTE_SIZE_TOTAL_FAST
  -- @COL_DESC: RED_MIN_QUOTE_SIZE_TOTAL_FAST
  -- @COL_DISPLAY_ORDER: 12
  "RED_MIN_QUOTE_SIZE_TOTAL_FAST" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_HOLD_TIME
  -- @COL_DESC: QR_HOLD_TIME
  -- @COL_DISPLAY_ORDER: 13
  "QR_HOLD_TIME" NUMBER(15, 0),
  -- @COL_GUI_NAME: QR_RESPONSE_TIME
  -- @COL_DESC: QR_RESPONSE_TIME
  -- @COL_DISPLAY_ORDER: 14
  "QR_RESPONSE_TIME" NUMBER(15, 0),
  -- @COL_GUI_NAME: MAX_SPREAD_FAST_INCREMENT
  -- @COL_DESC: MAX_SPREAD_FAST_INCREMENT
  -- @COL_DISPLAY_ORDER: 15
  "MAX_SPREAD_FAST_INCREMENT" NUMBER,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: CONTRACT_FREQUENCY
  -- @COL_DESC: Contract frequency of instrument to validate D: Daily, W: Weekly, M: Monthly, E: End-of-month, A: All/Default
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[ADEMW]
  -- @LKP_SQL_STMT1: SELECT 'D' AS VALUE, 'D' AS LABEL FROM DUAL UNION ALL SELECT 'W' AS VALUE, 'W' AS LABEL FROM DUAL UNION ALL SELECT 'M' AS VALUE, 'M' AS LABEL FROM DUAL UNION ALL SELECT 'E' AS VALUE, 'E' AS LABEL FROM DUAL UNION ALL SELECT 'A' AS VALUE, 'A' AS LABEL FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "CONTRACT_FREQUENCY" VARCHAR2(1 BYTE) DEFAULT 'A'
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Spread Class
-- @TBL_GUI_NAME_SHORT: Spread_Class
-- @TBL_NAME_AT: S_MMPRM_SPREAD_CLASS_AT
-- @TBL_DISPLAY_ORDER: 10
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SPREAD_CLASS" (
  -- @COL_GUI_NAME: SPREAD_CLASS_CODE
  -- @COL_DESC: SPREAD_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SPREAD_CLASS_DT.SPREAD_CLASS_CODE
  "SPREAD_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: SPREAD_CLASS_NAME
  -- @COL_DESC: SPREAD_CLASS_NAME
  -- @COL_DISPLAY_ORDER: 2
  "SPREAD_CLASS_NAME" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: SPREAD_CLASS_DESCR
  -- @COL_DESC: SPREAD_CLASS_DESCR
  -- @COL_DISPLAY_ORDER: 3
  "SPREAD_CLASS_DESCR" VARCHAR2(2000 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY')
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Details for Spread Class
-- @TBL_GUI_NAME_SHORT: Details_for_Spread_Class
-- @TBL_NAME_AT: S_MMPRM_SPREAD_CLASS_DT_AT
-- @TBL_DISPLAY_ORDER: 11
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SPREAD_CLASS_DT" (
  -- @COL_GUI_NAME: SPREAD_CLASS_CODE
  -- @COL_DESC: SPREAD_CLASS_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.DbAuditTrailColumnValidator:MMPM.S_MMPRM_SPREAD_CLASS.SPREAD_CLASS_CODE
  -- @LKP_SQL_STMT1: SELECT DISTINCT SPREAD_CLASS_CODE FROM GUI_XMDM_MMPM_WIF.S_MMPRM_SPREAD_CLASS ORDER BY SPREAD_CLASS_CODE
  -- @LKP_SQL_LABEL: SPREAD_CLASS_CODE
  -- @LKP_SQL_VALUE: SPREAD_CLASS_CODE
  "SPREAD_CLASS_CODE" VARCHAR2(70 BYTE),
  -- @COL_GUI_NAME: DAYS_TO_EXPIRATION
  -- @COL_DESC: DAYS_TO_EXPIRATION
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "DAYS_TO_EXPIRATION" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_FROM
  -- @COL_DESC: EXP_CYCLE_NO_FROM
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "EXP_CYCLE_NO_FROM" NUMBER(3, 0),
  -- @COL_GUI_NAME: EXP_CYCLE_NO_TO
  -- @COL_DESC: EXP_CYCLE_NO_TO
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "EXP_CYCLE_NO_TO" NUMBER(3, 0),
  -- @COL_GUI_NAME: BID_PRICE_INTERVAL_NO
  -- @COL_DESC: BID_PRICE_INTERVAL_NO
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "BID_PRICE_INTERVAL_NO" NUMBER(3, 0),
  -- @COL_GUI_NAME: BID_PRICE_UPPER_BOUNDARY
  -- @COL_DESC: BID_PRICE_UPPER_BOUNDARY
  -- @COL_DISPLAY_ORDER: 6
  "BID_PRICE_UPPER_BOUNDARY" NUMBER,
  -- @COL_GUI_NAME: MAX_SPREAD
  -- @COL_DESC: MAX_SPREAD
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: #,##0.####
  "MAX_SPREAD" NUMBER,
  -- @COL_GUI_NAME: MAX_SPREAD_RED
  -- @COL_DESC: MAX_SPREAD_RED
  -- @COL_DISPLAY_ORDER: 8
  "MAX_SPREAD_RED" NUMBER,
  -- @COL_GUI_NAME: SPREAD_UNIT
  -- @COL_DESC: SPREAD_UNIT
  -- @COL_DISPLAY_ORDER: 9
  "SPREAD_UNIT" VARCHAR2(4 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  -- @COL_GUI_NAME: CONTRACT_FREQUENCY
  -- @COL_DESC: Contract frequency of instrument to validate D: Daily, W: Weekly, M: Monthly, E: End-of-month, A: All/Default
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[ADEMW]
  -- @LKP_SQL_STMT1: SELECT 'D' AS VALUE, 'D' AS LABEL FROM DUAL UNION ALL SELECT 'W' AS VALUE, 'W' AS LABEL FROM DUAL UNION ALL SELECT 'M' AS VALUE, 'M' AS LABEL FROM DUAL UNION ALL SELECT 'E' AS VALUE, 'E' AS LABEL FROM DUAL UNION ALL SELECT 'A' AS VALUE, 'A' AS LABEL FROM DUAL
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "CONTRACT_FREQUENCY" VARCHAR2(1 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Strike Price Window
-- @TBL_GUI_NAME_SHORT: Strike_Price_Window
-- @TBL_NAME_AT: S_MMPRM_SPW_AT
-- @TBL_DISPLAY_ORDER: 12
CREATE TABLE "GUI_XMDM_MMPM"."S_MMPRM_SPW" (
  -- @COL_GUI_NAME: SPW_CODE
  -- @COL_DESC: SPW_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SPW_CODE" VARCHAR2(25 CHAR),
  -- @COL_GUI_NAME: SPW_NAME
  -- @COL_DESC: SPW_NAME
  -- @COL_DISPLAY_ORDER: 2
  "SPW_NAME" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: SPW_DESCR
  -- @COL_DESC: SPW_DESCR
  -- @COL_DISPLAY_ORDER: 3
  "SPW_DESCR" VARCHAR2(2000 CHAR),
  -- @COL_GUI_NAME: SIZE_OF_STRIKE_WIN
  -- @COL_DESC: SIZE_OF_STRIKE_WIN
  -- @COL_DISPLAY_ORDER: 4
  "SIZE_OF_STRIKE_WIN" NUMBER(3, 0),
  -- @COL_GUI_NAME: NBR_OF_REQ_STRIKES
  -- @COL_DESC: NBR_OF_REQ_STRIKES
  -- @COL_DISPLAY_ORDER: 5
  "NBR_OF_REQ_STRIKES" NUMBER(3, 0),
  -- @COL_GUI_NAME: NBR_OF_REQ_STRIKES_ITM
  -- @COL_DESC: NBR_OF_REQ_STRIKES_ITM
  -- @COL_DISPLAY_ORDER: 6
  "NBR_OF_REQ_STRIKES_ITM" NUMBER(3, 0),
  -- @COL_GUI_NAME: NBR_OF_REQ_STRIKES_OTM
  -- @COL_DESC: NBR_OF_REQ_STRIKES_OTM
  -- @COL_DISPLAY_ORDER: 7
  "NBR_OF_REQ_STRIKES_OTM" NUMBER(3, 0),
  -- @COL_GUI_NAME: VERSION_FILTER
  -- @COL_DESC: VERSION_FILTER
  -- @COL_DISPLAY_ORDER: 9
  "VERSION_FILTER" VARCHAR2(6 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: NBR_OF_REQ_STRIKES_ATM
  -- @COL_DESC: NBR_OF_REQ_STRIKES_ATM
  -- @COL_DISPLAY_ORDER: 8
  "NBR_OF_REQ_STRIKES_ATM" NUMBER(1, 0) DEFAULT 1,
  -- @COL_GUI_NAME: BUSINESS_VALID_FROM
  -- @COL_DESC: BUSINESS_VALID_FROM
  -- @COL_DISPLAY_ORDER: -1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: BUSINESS_VALID_TO
  -- @COL_DESC: BUSINESS_VALID_TO
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "PUT_DELTA_FLOOR" NUMBER(*, 0),
  "PUT_DELTA_CEIL" NUMBER(*, 0),
  "CALL_DELTA_FLOOR" NUMBER(*, 0),
  "CALL_DELTA_CEIL" NUMBER(*, 0)
) TABLESPACE XMDM_FACT;