-- @TBL_GUI_NAME: Parameters
-- @TBL_GUI_NAME_SHORT: PMRMM_PARAMETER
-- @TBL_NAME_AT: PMRMM_PARAMETER_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMRMM"."PMRMM_PARAMETER" (
  -- @COL_GUI_NAME: Group Number
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "GROUP_NO" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Group Name
  -- @COL_DISPLAY_ORDER: 2
  "GROUP_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: MM Spread Factor
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0
  "MM_SPREAD_FACTOR" NUMBER(126),
  -- @COL_GUI_NAME: Stress Spread Factor
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.0
  "STRESS_SPREAD_FACTOR" NUMBER(126),
  -- @COL_GUI_NAME: ATWS Rating Limit A
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.0
  "ATWS_RATING_LIMIT_A" NUMBER(126),
  -- @COL_GUI_NAME: Min Quotation Rate
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.0
  "MIN_QUOTATION_RATE" NUMBER(126),
  -- @COL_GUI_NAME: Min Quotation Rate Bill
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.0
  "MIN_QUOTATION_RATE_BILL" NUMBER(126),
  -- @COL_GUI_NAME: Min Quotation Rate Stress
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.0
  "MIN_QUOTATION_RATE_STRESS" NUMBER(126),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PMRMM_PARAMETER" PRIMARY KEY ("GROUP_NO")
) TABLESPACE XMDM_FACT;