-- @TBL_GUI_NAME: Committed Credit Lines
-- @TBL_GUI_NAME_SHORT: COMMITTED_CREDIT_LINES
-- @TBL_NAME_AT: COMMITTED_CREDIT_LINES_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_RLI"."COMMITTED_CREDIT_LINES" (
  -- @COL_GUI_NAME: Business Partner
  -- @COL_DESC: Business Partner Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BUSINESS_PARTNER" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: Currency
  -- @COL_DISPLAY_ORDER: 2
  "CURRENCY" VARCHAR2(10 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Credit Line
  -- @COL_DESC: Credit Line available from Business Partner
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: ###,###,##0
  "CREDIT_LINE" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_COMMITTED_CREDIT_LINES" PRIMARY KEY ("BUSINESS_PARTNER", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Fix Indicator Value
-- @TBL_GUI_NAME_SHORT: FIX_RLI_VALUE
-- @TBL_NAME_AT: FIX_RLI_VALUE_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_RLI"."FIX_RLI_VALUE" (
  -- @COL_GUI_NAME: FactDate
  -- @COL_DESC: FactDate
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  -- @COL_GUI_NAME: RLI Id
  -- @COL_DESC: RLI Id
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT INDICATOR_ID FROM EUREX_RLI.D_DOM_RLI_COMPONENT_DET ORDER BY INDICATOR_ID
  -- @LKP_SQL_LABEL: INDICATOR_ID
  -- @LKP_SQL_VALUE: INDICATOR_ID
  "RLI_ID" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Component Name
  -- @COL_DESC: Component Name whose value being changed
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DISTINCT COMPONENT_NAME FROM EUREX_RLI.D_DOM_RLI_COMPONENT_DET ORDER BY COMPONENT_NAME
  -- @LKP_SQL_LABEL: COMPONENT_NAME
  -- @LKP_SQL_VALUE: COMPONENT_NAME
  "COMPONENT_NAME" VARCHAR2(100 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Component Value
  -- @COL_DESC: Component Value
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: ###,###,##0.##
  "COMPONENT_VALUE" NUMBER,
  -- @COL_GUI_NAME: Action Type
  -- @COL_DESC: I for Insert , U for Update , D for Delete . For D , all the sub-components will be deleted with just one entry.
  -- @COL_DISPLAY_ORDER: 5
  "ACTION_TYPE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Entry Date
  -- @COL_DESC: Current Date
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: yyyy-MM-dd
  -- @LKP_SQL_STMT1: SELECT TRUNC(SYSDATE) AS ENTRY_INSERT_DATE FROM DUAL
  -- @LKP_SQL_LABEL: ENTRY_INSERT_DATE
  -- @LKP_SQL_VALUE: ENTRY_INSERT_DATE
  "ENTRY_INSERT_DATE" DATE,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_FIX_RLI_VALUE" PRIMARY KEY ("FACT_DATE", "RLI_ID", "COMPONENT_NAME")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Own Liquidity
-- @TBL_GUI_NAME_SHORT: OWN LIQUIDITY
-- @TBL_NAME_AT: KLI_4_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_RLI"."KLI_4" (
  -- @COL_GUI_NAME: Own Funds
  -- @COL_DESC: Own Funds
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "OWN_FUNDS" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Intragroup Funding
  -- @COL_DESC: Intragroup Funding
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "INTRAGROUP_FUNDING" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Operational Liquidity
  -- @COL_DESC: Operational Liquidity
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "OPERATIONAL_LIQUIDITY" NUMBER NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_KLI_4" PRIMARY KEY ("OWN_FUNDS", "INTRAGROUP_FUNDING", "OPERATIONAL_LIQUIDITY")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Liquidity coverage ratio
-- @TBL_GUI_NAME_SHORT: LIQUIDITY_COVERAGE_RATIO
-- @TBL_NAME_AT: LCR_C76_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_RLI"."LCR_C76" (
  -- @COL_GUI_NAME: RepDate
  -- @COL_DESC: RepDate
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: MM/dd/yyyy
  "REPDATE" DATE NOT NULL,
  -- @COL_GUI_NAME: CCode
  -- @COL_DESC: CCode
  -- @COL_DISPLAY_ORDER: 2
  "CCODE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: ID
  -- @COL_DESC: ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "ID" VARCHAR2(50 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(200 BYTE),
  -- @COL_GUI_NAME: Amount
  -- @COL_DESC: Amount
  -- @COL_DISPLAY_ORDER: 5
  "AMOUNT" NUMBER,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_LCR_C76" PRIMARY KEY ("REPDATE", "ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Limits
-- @TBL_GUI_NAME_SHORT: LIMITS
-- @TBL_NAME_AT: LIMITS_AT
-- @TBL_DISPLAY_ORDER: 4
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_RLI"."LIMITS" (
  -- @COL_GUI_NAME: Liquidity Indicator
  -- @COL_DESC: Liquidity Indicator Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT INDICATOR_NAME FROM EUREX_RLI.D_DOM_RLI_INDICATOR_DET
  -- @LKP_SQL_LABEL: INDICATOR_NAME
  -- @LKP_SQL_VALUE: INDICATOR_NAME
  "LIQUIDITY_INDICATOR" VARCHAR2(255 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Amber Limit
  -- @COL_DESC: Amber Limit Value
  -- @COL_DISPLAY_ORDER: 2
  "AMBER_LIMIT" NUMBER,
  -- @COL_GUI_NAME: Red Limit
  -- @COL_DESC: Red Limit Value
  -- @COL_DISPLAY_ORDER: 3
  "RED_LIMIT" NUMBER,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_LIMITS" PRIMARY KEY ("LIQUIDITY_INDICATOR", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Minimum Reserve Calendar
-- @TBL_GUI_NAME_SHORT: MIN_RESERVE_CALENDAR
-- @TBL_NAME_AT: MIN_RESERVE_CALENDAR_AT
-- @TBL_DISPLAY_ORDER: 3
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_RLI"."MIN_RESERVE_CALENDAR" (
  -- @COL_GUI_NAME: Report Month
  -- @COL_DESC: Report Month
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: MMM-YY
  "REPORT_MONTH" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Amount
  -- @COL_DESC: Amount
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: ###,###,##0.##
  "AMOUNT" NUMBER,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_MIN_RESERVE_CALENDAR" PRIMARY KEY ("REPORT_MONTH", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Recurring Payments
-- @TBL_GUI_NAME_SHORT: RECURRING_PAYMENTS
-- @TBL_NAME_AT: RECURRING_PAYMENTS_AT
-- @TBL_DISPLAY_ORDER: 2
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_RLI"."RECURRING_PAYMENTS" (
  -- @COL_GUI_NAME: Location
  -- @COL_DESC: Location
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LOCATION" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Account
  -- @COL_DESC: Account
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "ACCOUNT" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Facility
  -- @COL_DESC: Facility
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "FACILITY" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: Currency
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "CURRENCY" VARCHAR2(10 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Amount
  -- @COL_DESC: Amount
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: ###,###,##0
  "AMOUNT" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_RECURRING_PAYMENTS" PRIMARY KEY ("LOCATION", "ACCOUNT", "FACILITY", "CURRENCY", "VALID_FROM")
) TABLESPACE XMDM_FACT;