-- @TBL_GUI_NAME: CD090 Clearing Member
-- @TBL_GUI_NAME_SHORT: D_ST_BPM_MEMBER
-- @TBL_NAME_AT: D_ST_BPM_MEMBER_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_CST"."D_ST_BPM_MEMBER" (
  -- @COL_GUI_NAME: Clearing Member
  -- @COL_DESC: Clearing Member Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CLEARING_MEMBER" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_BPM_MEMBER" PRIMARY KEY ("CLEARING_MEMBER", "VALID_FROM")
) TABLESPACE XMDM_FACT;