-- @TBL_GUI_NAME: MMPM tests
-- @TBL_GUI_NAME_SHORT: MMPM_TESTS
-- @TBL_NAME_AT: S_TEST_MMPM_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_STX_TESTS"."S_TEST_MMPM" (
  -- @COL_GUI_NAME: MODULE_NAME
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MODULE_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: DATA_SOURCE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "DATA_SOURCE" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: BUSINESS_DATE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_DATE" DATE NOT NULL,
  -- @COL_GUI_NAME: TEST_GROUP
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "TEST_GROUP" VARCHAR2(30 CHAR) NOT NULL,
  -- @COL_GUI_NAME: TEST_NAME
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "TEST_NAME" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: ACTIVE
  -- @COL_DISPLAY_ORDER: 5
  "ACTIVE" CHAR(1 BYTE) DEFAULT 'Y',
  -- @COL_GUI_NAME: INPUT
  -- @COL_DISPLAY_ORDER: 6
  "INPUT" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: EXPECTED
  -- @COL_DISPLAY_ORDER: 7
  "EXPECTED" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: PARAMETERS
  -- @COL_DISPLAY_ORDER: 8
  "PARAMETERS" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: DESCRIPTION
  -- @COL_DISPLAY_ORDER: 9
  "DESCRIPTION" VARCHAR2(255 CHAR),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;