-- @TBL_GUI_NAME: OTR Parameters
-- @TBL_GUI_NAME_SHORT: OTR_PARAMS
-- @TBL_NAME_AT: S_OTR_PARAMS_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_PARAMS" (
  -- @COL_GUI_NAME: Exchange code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: select 'XFRA' as LABEL, 'XFRA' as VALUE from dual 
UNION ALL select 'XETR' as LABEL, 'XETR' as VALUE from dual
UNION ALL select 'XEUB' as LABEL, 'XEUB' as VALUE from dual 
UNION ALL select 'XMAL' as LABEL, 'XMAL' as VALUE from dual 
UNION ALL select 'XDUB' as LABEL, 'XDUB' as VALUE from dual
UNION ALL select 'XBUL' as LABEL, 'XBUL' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) NOT NULL,
  -- @COL_GUI_NAME: OTR instrument class name
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "OTR_INSTR_CLASS_NAME" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Volume foor
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0
  "VOLUME_FLOOR" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Volume max RM ratio
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0
  "VOLUME_MAX_RM_RATIO" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Volume max MM ratio
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0
  "VOLUME_MAX_MM_RATIO" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Number foor
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0
  "NUMBER_FLOOR" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Number max RM ratio
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0
  "NUMBER_MAX_RM_RATIO" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Number max MM ratio
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0
  "NUMBER_MAX_MM_RATIO" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY') NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: OTR Reasons
-- @TBL_GUI_NAME_SHORT: OTR_REASONS
-- @TBL_NAME_AT: S_OTR_REASONS_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_REASONS" (
  -- @COL_GUI_NAME: Log Reason
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "LOG_REASON" NUMBER(10, 0),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Segment Mapping
-- @TBL_GUI_NAME_SHORT: OTR_SEGM_MAP
-- @TBL_NAME_AT: S_OTR_SEGM_PARAMS_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_SEGM_PARAMS" (
  -- @COL_GUI_NAME: Exchange code
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: select 'XETR' as LABEL, 'XETR' as VALUE from dual UNION ALL select 'XFRA' as LABEL, 'XFRA' as VALUE from dual UNION ALL select 'XEUB' as LABEL, 'XEUB' as VALUE from dual UNION ALL select 'XMAL' as LABEL, 'XMAL' as VALUE from dual UNION ALL select 'XBUL' as LABEL, 'XBUL' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Segment Name
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "SEGMENT_NAME" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: OTR instrument class name
  -- @COL_DISPLAY_ORDER: 6
  "OTR_INSTR_CLASS_NAME" VARCHAR2(200 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 7
  "DESCRIPTION" VARCHAR2(500 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY') NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;