CREATE TABLE "GUI_XMDM_CLOUDERA"."S_CLOUDERA_CONFIG" (
  "SECTION" VARCHAR2(30 CHAR),
  "PARAM_NAME" VARCHAR2(100 CHAR),
  "PARAM_VALUE" VARCHAR2(255 CHAR),
  "PARAM_DESCRIPTION" VARCHAR2(255 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  "DATA_SOURCE" VARCHAR2(250 BYTE),
  "MODULE" VARCHAR2(250 BYTE)
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_CLOUDERA"."S_CLOUDERA_STATISTICS" (
  "DATA_SOURCE" VARCHAR2(64 BYTE) NOT NULL,
  "MODULE" VARCHAR2(64 BYTE) NOT NULL,
  "MEASURE" VARCHAR2(64 BYTE) NOT NULL,
  "VALUE_DATE" DATE NOT NULL,
  "VALUE" NUMBER(10, 0),
  "RUN_TIMESTAMP" TIMESTAMP,
  "DURATION" INTERVAL DAY(0) TO SECOND(3)
) TABLESPACE XMDM_FACT;