-- @TBL_GUI_NAME: Parameters
-- @TBL_GUI_NAME_SHORT: PMDS_PARAMETER
-- @TBL_NAME_AT: PMDS_PARAMETER_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMDS"."PMDS_PARAMETER" (
  -- @COL_GUI_NAME: Group Number
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "GROUP_NO" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Group Name
  -- @COL_DISPLAY_ORDER: 2
  "GROUP_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Min Particip Rate All AU
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0
  "MIN_PARTICIP_RATE_ALL_AU" NUMBER(126),
  -- @COL_GUI_NAME: Min Particip Rate OA
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.0
  "MIN_PARTICIP_RATE_OA" NUMBER(126),
  -- @COL_GUI_NAME: Min Particip Rate VOLA
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.0
  "MIN_PARTICIP_RATE_VOLA" NUMBER(126),
  -- @COL_GUI_NAME: Max Quote Response Time AU
  -- @COL_DISPLAY_ORDER: 6
  "MAX_QUOTE_RESPONSE_TIME_AU" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: Particip Only At PD AU
  -- @COL_DISPLAY_ORDER: 7
  "PARTICIP_ONLY_AT_PD_AU" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Max Bonus Quotation Rate CT
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.0
  "MAX_BONUS_QUOTATION_RATE_CT" NUMBER(126),
  -- @COL_GUI_NAME: Min Quotation Rate CT
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.0
  "MIN_QUOTATION_RATE_CT" NUMBER(126),
  -- @COL_GUI_NAME: Spread Factor Stress MKT
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0.0
  "SPREAD_FACTOR_STRESS_MKT" NUMBER(126),
  -- @COL_GUI_NAME: Bill Min Particip Rate All AU
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: 0.0
  "BILL_MIN_PARTICIP_RATE_ALL_AU" NUMBER(126),
  -- @COL_GUI_NAME: Bill Min Particip Rate OA
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: 0.0
  "BILL_MIN_PARTICIP_RATE_OA" NUMBER(126),
  -- @COL_GUI_NAME: Bill Min Particip Rate VOLA
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_FORMAT: 0.0
  "BILL_MIN_PARTICIP_RATE_VOLA" NUMBER(126),
  -- @COL_GUI_NAME: Bill Min Quotation Rate CT
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_FORMAT: 0.0
  "BILL_MIN_QUOTATION_RATE_CT" NUMBER(126),
  -- @COL_GUI_NAME: Limit A Bonus Quotation Rate
  -- @COL_DISPLAY_ORDER: 15
  -- @COL_FORMAT: 0.0
  "LIMIT_A_BONUS_QUOTATION_RATE" NUMBER(126),
  -- @COL_GUI_NAME: Limit B Bonus Quotation Rate
  -- @COL_DISPLAY_ORDER: 16
  -- @COL_FORMAT: 0.0
  "LIMIT_B_BONUS_QUOTATION_RATE" NUMBER(126),
  -- @COL_GUI_NAME: Limit C Bonus Quotation Rate
  -- @COL_DISPLAY_ORDER: 17
  -- @COL_FORMAT: 0.0
  "LIMIT_C_BONUS_QUOTATION_RATE" NUMBER(126),
  -- @COL_GUI_NAME: Limit A ATW Relative Spread
  -- @COL_DISPLAY_ORDER: 18
  -- @COL_FORMAT: 0.0
  "LIMIT_A_ATW_RELATIVE_SPREAD" NUMBER(126),
  -- @COL_GUI_NAME: Limit B ATW Relative Spread
  -- @COL_DISPLAY_ORDER: 19
  -- @COL_FORMAT: 0.0
  "LIMIT_B_ATW_RELATIVE_SPREAD" NUMBER(126),
  -- @COL_GUI_NAME: Limit C ATW Relative Spread
  -- @COL_DISPLAY_ORDER: 20
  -- @COL_FORMAT: 0.0
  "LIMIT_C_ATW_RELATIVE_SPREAD" NUMBER(126),
  -- @COL_GUI_NAME: Rating Time Bonus
  -- @COL_DISPLAY_ORDER: 21
  "RATING_TIME_BONUS" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: Min Qtrly Fulfillment Ratio
  -- @COL_DISPLAY_ORDER: 22
  -- @COL_FORMAT: 0.0
  "MIN_QTRLY_FULFILLMENT_RATIO" NUMBER(126),
  -- @COL_GUI_NAME: Liq 1 Min Passive Trade Share
  -- @COL_DISPLAY_ORDER: 23
  -- @COL_FORMAT: 0.0
  "LIQ_1_MIN_PASSIVE_TRADE_SHARE" NUMBER(126),
  -- @COL_GUI_NAME: Liq 2 Min Passive Trade Share
  -- @COL_DISPLAY_ORDER: 24
  -- @COL_FORMAT: 0.0
  "LIQ_2_MIN_PASSIVE_TRADE_SHARE" NUMBER(126),
  -- @COL_GUI_NAME: Liq 3 Min Passive Trade Share
  -- @COL_DISPLAY_ORDER: 25
  -- @COL_FORMAT: 0.0
  "LIQ_3_MIN_PASSIVE_TRADE_SHARE" NUMBER(126),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PMDS_PARAMETER" PRIMARY KEY ("GROUP_NO")
) TABLESPACE XMDM_FACT;