-- @TBL_GUI_NAME: OTR Limits Count
-- @TBL_GUI_NAME_SHORT: OTR_LIMITS_COUNT
-- @TBL_NAME_AT: S_OTR_LIMITS_COUNT_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_F7_HFT"."S_OTR_LIMITS_COUNT" (
  -- @COL_GUI_NAME: Service placement
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "SERVICE_PLACEMENT" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Limit per month
  -- @COL_DISPLAY_ORDER: 5
  "OTR_LIMIT_PER_MONTH" NUMBER(10, 0) NOT NULL,
  -- @COL_GUI_NAME: Min quotes per participant
  -- @COL_DISPLAY_ORDER: 6
  "MIN_QUOTES_PER_PARTICIPANT" NUMBER(10, 0) NOT NULL,
  -- @COL_GUI_NAME: Transaction limit per day
  -- @COL_DISPLAY_ORDER: 7
  "TRANSACTION_LIMIT_PER_DAY" NUMBER(10, 0) NOT NULL,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY') NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: OTR Limits Volume
-- @TBL_GUI_NAME_SHORT: OTR_LIMITS_VOLUME
-- @TBL_NAME_AT: S_OTR_LIMITS_VOLUME_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_F7_HFT"."S_OTR_LIMITS_VOLUME" (
  -- @COL_GUI_NAME: Service placement
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "SERVICE_PLACEMENT" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Limit per month
  -- @COL_DISPLAY_ORDER: 5
  "OTR_LIMIT_PER_MONTH" NUMBER(26, 0) NOT NULL,
  -- @COL_GUI_NAME: Min volume per participant
  -- @COL_DISPLAY_ORDER: 6
  "MIN_VOLUME_PER_PARTICIPANT" NUMBER(26, 0) NOT NULL,
  -- @COL_GUI_NAME: Transaction limit per day
  -- @COL_DISPLAY_ORDER: 7
  "TRANSACTION_LIMIT_PER_DAY" NUMBER(26, 0) NOT NULL,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY') NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: Avgerage Volumne
  -- @COL_DISPLAY_ORDER: 8
  "AVERAGE_VOLUME" NUMBER(18, 5) NOT NULL
) TABLESPACE XMDM_FACT;