-- @TBL_GUI_NAME: SCS Spanish Tax Companies
-- @TBL_GUI_NAME_SHORT: SPANISH_TAX
-- @TBL_NAME_AT: D_STA_SCS_SPANISH_TAX_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_SCS"."D_STA_SCS_SPANISH_TAX" (
  -- @COL_GUI_NAME: Financial year
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "FINANCIAL_YEAR" VARCHAR2(4 BYTE) NOT NULL,
  -- @COL_GUI_NAME: ISIN
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "ISIN" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCS_SPANISH_TAX" PRIMARY KEY ("FINANCIAL_YEAR", "ISIN", "VALID_TO")
) TABLESPACE XMDM_FACT;