-- @TBL_GUI_NAME: Applications
-- @TBL_GUI_NAME_SHORT: Applications
-- @TBL_NAME_AT: XMDM_CONF_APP_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DESC: App Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "APP_NAME" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: App Gui Name
  -- @COL_DESC: App Gui Name
  -- @COL_DISPLAY_ORDER: 2
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: App Description
  -- @COL_DESC: App Description
  -- @COL_DISPLAY_ORDER: 3
  "APP_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Help link
  -- @COL_DESC: Help link
  -- @COL_DISPLAY_ORDER: 9
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Pre-release action
  -- @COL_DESC: Java class which is called before release is processed
  -- @COL_DISPLAY_ORDER: 4
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Post-release action
  -- @COL_DESC: Java class which is called after release is processed
  -- @COL_DISPLAY_ORDER: 5
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Validator action
  -- @COL_DESC: Java class which is called after pressing validation button
  -- @COL_DISPLAY_ORDER: 6
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: On load action
  -- @COL_DESC: Java class which is called on loading application
  -- @COL_DISPLAY_ORDER: 7
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE) DEFAULT NULL,
  -- @COL_GUI_NAME: Custom Settings
  -- @COL_DESC: Json format for customize setting
  -- @COL_DISPLAY_ORDER: 8
  "SETTINGS" VARCHAR2(4000 BYTE) DEFAULT NULL
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_04122025" (
  "APP_NAME" VARCHAR2(20 BYTE),
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  "APP_DESC" VARCHAR2(250 BYTE),
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  "SETTINGS" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_05122025" (
  "APP_NAME" VARCHAR2(20 BYTE),
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  "APP_DESC" VARCHAR2(250 BYTE),
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  "SETTINGS" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_06122025" (
  "APP_NAME" VARCHAR2(20 BYTE),
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  "APP_DESC" VARCHAR2(250 BYTE),
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  "SETTINGS" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_07122025" (
  "APP_NAME" VARCHAR2(20 BYTE),
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  "APP_DESC" VARCHAR2(250 BYTE),
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  "SETTINGS" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_08122025" (
  "APP_NAME" VARCHAR2(20 BYTE),
  "APP_GUI_NAME" VARCHAR2(150 BYTE),
  "APP_DESC" VARCHAR2(250 BYTE),
  "APP_HELP_LINK" VARCHAR2(1000 BYTE),
  "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE),
  "VALIDATION_ACTION" VARCHAR2(4000 BYTE),
  "ON_LOAD_ACTION" VARCHAR2(1000 BYTE),
  "SETTINGS" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Columns
-- @TBL_GUI_NAME_SHORT: Columns
-- @TBL_NAME_AT: XMDM_CONF_COLUMN_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM"."XMDM_CONF_COLUMN" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DESC: App Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "APP_NAME" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Table Name
  -- @COL_DESC: Table Name
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "TBL_NAME" VARCHAR2(61 BYTE),
  -- @COL_GUI_NAME: Column Name
  -- @COL_DESC: Column Name
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "COL_NAME" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Column Gui Name
  -- @COL_DESC: Column Gui Name
  -- @COL_DISPLAY_ORDER: 4
  "COL_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Column Description
  -- @COL_DESC: Column Description
  -- @COL_DISPLAY_ORDER: 5
  "COL_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Column Format
  -- @COL_DESC: Column Format
  -- @COL_DISPLAY_ORDER: 6
  "COL_FORMAT" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Column Display Order
  -- @COL_DESC: Column Display Order
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0
  "COL_DISPLAY_ORDER" NUMBER(3, 0),
  -- @COL_GUI_NAME: Column PK
  -- @COL_DESC: Column PK
  -- @COL_DISPLAY_ORDER: 8
  "COL_PK" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Column Required
  -- @COL_DESC: Column Required
  -- @COL_DISPLAY_ORDER: 9
  "COL_REQUIRED" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Column Editable
  -- @COL_DESC: Column Editable
  -- @COL_DISPLAY_ORDER: 10
  "COL_EDITABLE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Column Datatype
  -- @COL_DESC: Column Datatype
  -- @COL_DISPLAY_ORDER: 11
  "COL_DATATYPE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Column Sql Label
  -- @COL_DESC: Column Sql Label
  -- @COL_DISPLAY_ORDER: 12
  "LKP_SQL_LABEL" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Column Sql Value
  -- @COL_DESC: Column Sql Value
  -- @COL_DISPLAY_ORDER: 13
  "LKP_SQL_VALUE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Column Sql Statement Part1
  -- @COL_DESC: Column Sql Statement Part1
  -- @COL_DISPLAY_ORDER: 14
  "LKP_SQL_STMT1" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Column Sql Statement Part2
  -- @COL_DESC: Column Sql Statement Part2
  -- @COL_DISPLAY_ORDER: 15
  "LKP_SQL_STMT2" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Column Sql Parameters
  -- @COL_DESC: Column Sql Parameters
  -- @COL_DISPLAY_ORDER: 16
  "LKP_SQL_PARAM_LST" VARCHAR2(4000 BYTE),
  "COL_VALID_INTERVAL_COLUMN" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Is Multiline
  -- @COL_DESC: Is Multiline
  -- @COL_DISPLAY_ORDER: 10
  "COL_MULTILINE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Column validator
  -- @COL_DESC: Validator is run only if application has also valid validator
  -- @COL_DISPLAY_ORDER: 9
  "COL_VALIDATOR" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Autoincrement
  -- @COL_DESC: Autoincrement column - Y or N
  -- @COL_DISPLAY_ORDER: 12
  "COL_AUTOINCREMENT" CHAR(1 BYTE) DEFAULT 'N',
  -- @COL_GUI_NAME: Default value
  -- @COL_DESC: Default value all reference to method <class.method>
  -- @COL_DISPLAY_ORDER: 12
  "COL_DEFAULT_VAL" VARCHAR2(4000 BYTE)
) TABLESPACE XMDM_FACT;
COMMENT ON COLUMN "GUI_XMDM"."XMDM_CONF_COLUMN"."COL_VALID_INTERVAL_COLUMN" IS 'Values: T = VALID_TO, F = VALID_FROM. Used for autocomplete of BUSINESS_VALID_FROM, BUSINESS_VALID_TO';
-- @TBL_GUI_NAME: Tables
-- @TBL_GUI_NAME_SHORT: Tables
-- @TBL_NAME_AT: XMDM_CONF_TABLE_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM"."XMDM_CONF_TABLE" (
  -- @COL_GUI_NAME: App Name
  -- @COL_DESC: App Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "APP_NAME" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Table Name
  -- @COL_DESC: Table Name
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "TBL_NAME" VARCHAR2(61 BYTE),
  -- @COL_GUI_NAME: Table Gui Name
  -- @COL_DESC: Table Gui Name
  -- @COL_DISPLAY_ORDER: 5
  "TBL_GUI_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Table Description
  -- @COL_DESC: Table Description
  -- @COL_DISPLAY_ORDER: 6
  "TBL_DESC" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Display Order
  -- @COL_DESC: Display Order
  -- @COL_DISPLAY_ORDER: 7
  "TBL_DISPLAY_ORDER" NUMBER(3, 0),
  -- @COL_GUI_NAME: Table Gui Name Short
  -- @COL_DESC: Maximum 32 character because of excel limitation
  -- @COL_DISPLAY_ORDER: 7
  "TBL_GUI_NAME_SHORT" VARCHAR2(31 BYTE),
  -- @COL_GUI_NAME: Schema
  -- @COL_DESC: Database schema in case that application has different schema than GUI_XMDM
  -- @COL_DISPLAY_ORDER: 2
  "TBL_SCHEMA" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Audittrail table
  -- @COL_DESC: Audittrail table name
  -- @COL_DISPLAY_ORDER: 4
  "TBL_NAME_AT" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Historical tables flag
  -- @COL_DESC: Copy history into HS tables
  -- @COL_DISPLAY_ORDER: 10
  "HISTORICAL_TBL_FLAG" CHAR(1 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Users
-- @TBL_GUI_NAME_SHORT: Users
-- @TBL_NAME_AT: XMDM_CONF_USER_PERM_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM"."XMDM_CONF_USER_PERM" (
  -- @COL_GUI_NAME: User Name
  -- @COL_DESC: User Name
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "USER_NAME" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: App Name
  -- @COL_DESC: App Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "APP_NAME" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Role
  -- @COL_DESC: user role
  -- @COL_DISPLAY_ORDER: 2
  "ROLE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Department
  -- @COL_DESC: Department
  -- @COL_DISPLAY_ORDER: 5
  "DEPARTMENT" VARCHAR2(500 BYTE),
  -- @COL_GUI_NAME: Full name
  -- @COL_DESC: Full name
  -- @COL_DISPLAY_ORDER: 4
  "FULL_NAME" VARCHAR2(500 BYTE),
  CONSTRAINT "UNIUQ_USER_APP" UNIQUE ("USER_NAME", "APP_NAME")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: User settings
-- @TBL_GUI_NAME_SHORT: User settings
-- @TBL_NAME_AT: XMDM_CONF_USER_SETTING_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM"."XMDM_CONF_USER_SETTING" (
  -- @COL_GUI_NAME: App name
  -- @COL_DESC: Application name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "APP_NAME" VARCHAR2(20 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Table name
  -- @COL_DESC: Table name
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "TBL_NAME" VARCHAR2(61 BYTE) NOT NULL,
  -- @COL_GUI_NAME: User name
  -- @COL_DESC: User Name
  -- @COL_DISPLAY_ORDER: 3
  "USER_NAME" VARCHAR2(15 BYTE),
  -- @COL_GUI_NAME: Table settings
  -- @COL_DESC: Json formatted table settings
  -- @COL_DISPLAY_ORDER: 4
  "COL_SETTINGS" VARCHAR2(4000 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UNIQ_TABLE_SET" UNIQUE ("APP_NAME", "TBL_NAME", "USER_NAME")
) TABLESPACE XMDM_FACT;
