-- @TBL_GUI_NAME: Ariva Mapping
-- @TBL_GUI_NAME_SHORT: TX_ARIVA_MAPPING
-- @TBL_NAME_AT: TX_ARIVA_MAPPING_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMBFZ"."TX_ARIVA_MAPPING" (
  -- @COL_GUI_NAME: Ariva Sub CLass ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "A_ARIVA_SUB_CLASS_ID" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Product Subtype
  -- @COL_DISPLAY_ORDER: 2
  "A_PRODUCT_SUBTYPE" CHAR(3 BYTE),
  -- @COL_GUI_NAME: Product Subtype Desc
  -- @COL_DISPLAY_ORDER: 3
  "A_PRODUCT_SUBTYPE_DESC" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: War Segment
  -- @COL_DISPLAY_ORDER: 4
  "A_WAR_SEGMENT" CHAR(2 BYTE),
  -- @COL_GUI_NAME: War Segment name
  -- @COL_DISPLAY_ORDER: 5
  "A_WAR_SEGMENT_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Investment Leverage IND
  -- @COL_DISPLAY_ORDER: 6
  "A_INVESTMENT_LEVERAGE_IND" CHAR(1 BYTE),
  -- @COL_GUI_NAME: KO Possible
  -- @COL_DISPLAY_ORDER: 7
  "A_KO_POSSIBLE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TX_ARIVA_MAPPING" PRIMARY KEY ("A_ARIVA_SUB_CLASS_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: STM Parameter
-- @TBL_GUI_NAME_SHORT: TX_STM_PARAMETER
-- @TBL_NAME_AT: TX_STM_PARAMETER_AT
-- @TBL_DISPLAY_ORDER: 2
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMBFZ"."TX_STM_PARAMETER" (
  -- @COL_GUI_NAME: Prod Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "A_PROD_GROUP" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Start Time DEV
  -- @COL_DISPLAY_ORDER: 2
  "A_START_TIME_DEV" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: End Time DEV
  -- @COL_DISPLAY_ORDER: 3
  "A_END_TIME_DEV" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: Min Price
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.0
  "A_MIN_PRICE" NUMBER(126),
  -- @COL_GUI_NAME: Min Quote Size X
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.0
  "A_MIN_QUOTE_SIZE_X" NUMBER(126),
  -- @COL_GUI_NAME: Min Quote Volume
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.0
  "A_MIN_QUOTE_VOLUME_X" NUMBER(126),
  -- @COL_GUI_NAME: Scb Exe Time
  -- @COL_DISPLAY_ORDER: 7
  "A_SCB_EXE_TIME" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: Max Small Order Size X
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.0
  "A_MAX_SMALL_ORDER_SIZE_X" NUMBER(126),
  -- @COL_GUI_NAME: Max Small Order Volume X
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.0
  "A_MAX_SMALL_ORDER_VOLUME_X" NUMBER(126),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TX_STM_PARAMETER" PRIMARY KEY ("A_PROD_GROUP")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: STM Execution Performance Parameter
-- @TBL_GUI_NAME_SHORT: TX_STM_PAR_EXE_PERF
-- @TBL_NAME_AT: TX_STM_PAR_EXE_PERF_AT
-- @TBL_DISPLAY_ORDER: 3
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMBFZ"."TX_STM_PAR_EXE_PERF" (
  -- @COL_GUI_NAME: PM Type
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "A_PM_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  -- @COL_GUI_NAME: PM Type Level
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "A_PM_TYPE_LEVEL" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: PM Execution Time
  -- @COL_DISPLAY_ORDER: 3
  "A_PM_EXE_TIME" VARCHAR2(14 BYTE),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TX_STM_PAR_EXE_PERF" PRIMARY KEY ("A_PM_TYPE", "A_PM_TYPE_LEVEL")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: STM Grouping Categories to an Product Group
-- @TBL_GUI_NAME_SHORT: TX_STM_SEGMENT_GROUP
-- @TBL_NAME_AT: TX_STM_SEGMENT_GROUP_AT
-- @TBL_DISPLAY_ORDER: 4
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMBFZ"."TX_STM_SEGMENT_GROUP" (
  -- @COL_GUI_NAME: War Segment
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "A_WAR_SEGMENT" CHAR(2 BYTE) NOT NULL,
  -- @COL_GUI_NAME: War Segment name
  -- @COL_DISPLAY_ORDER: 2
  "A_WAR_SEGMENT_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Prod Group
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: #
  "A_PROD_GROUP" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Prod Group name
  -- @COL_DISPLAY_ORDER: 4
  "A_PROD_GROUP_NAME" CHAR(50 BYTE),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TX_STM_SEGMENT_GROUP" PRIMARY KEY ("A_WAR_SEGMENT")
) TABLESPACE XMDM_FACT;