-- @TBL_GUI_NAME: Parameters
-- @TBL_GUI_NAME_SHORT: PMETF_PARAMETER
-- @TBL_NAME_AT: PMETF_PARAMETER_AT
-- @TBL_DISPLAY_ORDER: 1
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMETF"."PMETF_PARAMETER" (
  -- @COL_GUI_NAME: Parameter Set Id
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PARAMETER_SET_ID" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Isin
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "ISIN" VARCHAR2(12 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRICE_CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Issuer
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "ISSUER" VARCHAR2(5 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Issuer Name
  -- @COL_DISPLAY_ORDER: 5
  "ISSUER_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Spread Format
  -- @COL_DISPLAY_ORDER: 6
  "SPREAD_FORMAT" VARCHAR2(1 BYTE),
  -- @COL_GUI_NAME: Max Quote Spread
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.0
  "MAX_QUOTE_SPREAD" NUMBER(126),
  -- @COL_GUI_NAME: Min Quote Size
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.0
  "MIN_QUOTE_SIZE" NUMBER(126),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PMETF_PARAMETER" PRIMARY KEY ("PARAMETER_SET_ID", "ISIN", "PRICE_CURRENCY", "ISSUER")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Report Owners
-- @TBL_GUI_NAME_SHORT: PMETF_REPORT_OWNER
-- @TBL_NAME_AT: PMETF_REPORT_OWNER_AT
-- @TBL_DISPLAY_ORDER: 2
-- @HISTORICAL_TBL_FLAG: Y
CREATE TABLE "GUI_XMDM_PMETF"."PMETF_REPORT_OWNER" (
  -- @COL_GUI_NAME: Member Id
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Issuer
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "ISSUER" VARCHAR2(5 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PMETF_REPORT_OWNER" PRIMARY KEY ("MEMBER_ID", "ISSUER")
) TABLESPACE XMDM_FACT;