-- @TBL_GUI_NAME: ESU Common Parameters
-- @TBL_GUI_NAME_SHORT: ESU
-- @TBL_NAME_AT: S_ESU_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Grace Factor
  -- @COL_DISPLAY_ORDER: 2
  "GRACE_FACTOR" NUMBER,
  -- @COL_GUI_NAME: OBSOLETE: Volume Factor
  -- @COL_DESC: to be removed with the T7 13.1 release
  -- @COL_DISPLAY_ORDER: 5
  "VOLUME_FACTOR" NUMBER,
  -- @COL_GUI_NAME: SMC Factor
  -- @COL_DISPLAY_ORDER: 6
  "SMC_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Non MM Floor
  -- @COL_DISPLAY_ORDER: 7
  "NON_MM_FLOOR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: Limit Type
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_PK: Y
  "LIMIT_TYPE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Volume Factor Passive
  -- @COL_DISPLAY_ORDER: 3
  "VOLUME_FACTOR_PASSIVE" NUMBER,
  -- @COL_GUI_NAME: Volume Factor Aggressive
  -- @COL_DISPLAY_ORDER: 4
  "VOLUME_FACTOR_AGGRESSIVE" NUMBER
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: ESU Fee
-- @TBL_GUI_NAME_SHORT: ESU_FEE
-- @TBL_NAME_AT: S_ESU_FEE_AT
-- @TBL_DISPLAY_ORDER: 10
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_FEE" (
  -- @COL_GUI_NAME: Limit Type
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LIMIT_TYPE" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Systematic Threshold (Accidential Violations Allowed)
  -- @COL_DISPLAY_ORDER: 2
  "SYSTEMATIC_THRESHLD" NUMBER,
  -- @COL_GUI_NAME: Interval < 50
  -- @COL_DISPLAY_ORDER: 3
  "TXN_LT_50_PCT_EUR" NUMBER,
  -- @COL_GUI_NAME: Interval 50-100
  -- @COL_DISPLAY_ORDER: 4
  "TXN_GT_50_LT_100_PCT_EUR" NUMBER,
  -- @COL_GUI_NAME: Interval >100
  -- @COL_DISPLAY_ORDER: 5
  "TXN_GT_100_PCT_EUR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: ESU Spread Quality
-- @TBL_GUI_NAME_SHORT: ESU_INTV_SQ
-- @TBL_NAME_AT: S_ESU_INTV_SQ_AT
-- @TBL_DISPLAY_ORDER: 9
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_INTV_SQ" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "INTERVAL_NO" NUMBER,
  -- @COL_GUI_NAME: Spread Quality
  -- @COL_DISPLAY_ORDER: 3
  "SPREAD_QUALITY" NUMBER,
  -- @COL_GUI_NAME: MM Base
  -- @COL_DISPLAY_ORDER: 4
  "MM_BASE" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  -- @COL_GUI_NAME: Limit Type
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_PK: Y
  "LIMIT_TYPE" VARCHAR2(100 CHAR) DEFAULT 'A'
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: ESU VI Quality
-- @TBL_GUI_NAME_SHORT: ESU_VI
-- @TBL_NAME_AT: S_ESU_VI_INTV_AT
-- @TBL_DISPLAY_ORDER: 15
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_VI_INTV" (
  -- @COL_GUI_NAME: Limit type
  -- @COL_DESC: Expected values: A,N,S
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LIMIT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Product type
  -- @COL_DESC: allowed values:FBND,FCUR,FINT,FINX,FIPS,FSTK,FVOL,OCUR,OFBD,OFIT,OFIX,OINX,OSTK
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(FBND|FCUR|FINT|FINX|FIPS|FSTK|FVOL|OCUR|OFBD|OFIT|OFIX|OINX|OSTK)
  -- @LKP_SQL_STMT1: select 'FBND' as LABEL, 'FBND' as VALUE from dual UNION ALL select 'FCUR' as LABEL, 'FCUR' as VALUE from dual UNION ALL select 'FINT' as LABEL, 'FINT' as VALUE from dual UNION ALL select 'FINX' as LABEL, 'FINX' as VALUE from dual UNION ALL select 'FIPS' as LABEL, 'FIPS' as VALUE from dual UNION ALL select 'FSTK' as LABEL, 'FSTK' as VALUE from dual UNION ALL select 'FVOL' as LABEL, 'FVOL' as VALUE from dual UNION ALL select 'OCUR' as LABEL, 'OCUR' as VALUE from dual UNION ALL select 'OFBD' as LABEL, 'OFBD' as VALUE from dual UNION ALL select 'OFIT' as LABEL, 'OFIT' as VALUE from dual UNION ALL select 'OFIX' as LABEL, 'OFIX' as VALUE from dual UNION ALL select 'OINX' as LABEL, 'OINX' as VALUE from dual UNION ALL select 'OSTK' as LABEL, 'OSTK' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Volatility
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: ########.########
  "VI" NUMBER(16, 8),
  -- @COL_GUI_NAME: Volatility factor
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: ########.########
  "VI_FACTOR" NUMBER(16, 8),
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_ESU_VI_INTV" PRIMARY KEY ("LIMIT_TYPE", "PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Limit Usage Notif
-- @TBL_GUI_NAME_SHORT: LIMIT_USAGE_NOTIF
-- @TBL_NAME_AT: S_HFT_LIMIT_USAGE_NOTIF_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_LIMIT_USAGE_NOTIF" (
  -- @COL_GUI_NAME: Attribute name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT 'VOLUME_LIMIT_USAGE' AS LABEL, 'VOLUME_LIMIT_USAGE' AS VALUE FROM dual UNION ALL SELECT 'TRANS_LIMIT_USAGE' AS LABEL, 'TRANS_LIMIT_USAGE' AS VALUE FROM dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "ATTR_NAME" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Attribute value
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: #.###
  "ATTR_VALUE" NUMBER(19, 2),
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Member Relationship
-- @TBL_GUI_NAME_SHORT: MEMBER_AGGREGATION
-- @TBL_NAME_AT: S_HFT_MEMBER_RELATIONSHIP_AT
-- @TBL_DISPLAY_ORDER: 11
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_MEMBER_RELATIONSHIP" (
  -- @COL_GUI_NAME: Member ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MEMBER_ID" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Reporting Member ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "REPORTING_MEMBER_ID" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_MEMBER_RELATIONSHIP" PRIMARY KEY ("MEMBER_ID", "REPORTING_MEMBER_ID", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Transaction Based OTR
-- @TBL_GUI_NAME_SHORT: TRANS_OTR
-- @TBL_NAME_AT: S_HFT_TRANS_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Grace Factor
  -- @COL_DISPLAY_ORDER: 2
  "GRACE_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Minimum Denominator
  -- @COL_DISPLAY_ORDER: 3
  "MINIMUM_DENOMINATOR" NUMBER,
  -- @COL_GUI_NAME: Base Limit
  -- @COL_DISPLAY_ORDER: 4
  "BASE_LIMIT" NUMBER,
  -- @COL_GUI_NAME: SMC Factor
  -- @COL_DISPLAY_ORDER: 5
  "SMC_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Transaction Based OTR for Product
-- @TBL_GUI_NAME_SHORT: TRANS_OTR_PROD
-- @TBL_NAME_AT: S_HFT_TRANS_PROD_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_PROD" (
  -- @COL_GUI_NAME: Product ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Threshold
  -- @COL_DISPLAY_ORDER: 2
  "THRESHOLD" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Transaction Based OTR Spread Quality
-- @TBL_GUI_NAME_SHORT: TRANS_OTR_SQ
-- @TBL_NAME_AT: S_HFT_TRANS_SQ_INTV_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_SQ_INTV" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "INTERVAL_NO" NUMBER,
  -- @COL_GUI_NAME: Spread Quality
  -- @COL_DISPLAY_ORDER: 3
  "SPREAD_QUALITY" NUMBER,
  -- @COL_GUI_NAME: MM Factor
  -- @COL_DISPLAY_ORDER: 4
  "MM_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Transaction Based OTR VI Quality
-- @TBL_GUI_NAME_SHORT: TRANS_OTR_VI
-- @TBL_NAME_AT: S_HFT_TRANS_VI_INTV_AT
-- @TBL_DISPLAY_ORDER: 14
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_VI_INTV" (
  -- @COL_GUI_NAME: Product type
  -- @COL_DESC: allowed values:FBND,FCUR,FINT,FINX,FIPS,FSTK,FVOL,OCUR,OFBD,OFIT,OFIX,OINX,OSTK
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(FBND|FCUR|FINT|FINX|FIPS|FSTK|FVOL|OCUR|OFBD|OFIT|OFIX|OINX|OSTK)
  -- @LKP_SQL_STMT1: select 'FBND' as LABEL, 'FBND' as VALUE from dual UNION ALL select 'FCUR' as LABEL, 'FCUR' as VALUE from dual UNION ALL select 'FINT' as LABEL, 'FINT' as VALUE from dual UNION ALL select 'FINX' as LABEL, 'FINX' as VALUE from dual UNION ALL select 'FIPS' as LABEL, 'FIPS' as VALUE from dual UNION ALL select 'FSTK' as LABEL, 'FSTK' as VALUE from dual UNION ALL select 'FVOL' as LABEL, 'FVOL' as VALUE from dual UNION ALL select 'OCUR' as LABEL, 'OCUR' as VALUE from dual UNION ALL select 'OFBD' as LABEL, 'OFBD' as VALUE from dual UNION ALL select 'OFIT' as LABEL, 'OFIT' as VALUE from dual UNION ALL select 'OFIX' as LABEL, 'OFIX' as VALUE from dual UNION ALL select 'OINX' as LABEL, 'OINX' as VALUE from dual UNION ALL select 'OSTK' as LABEL, 'OSTK' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Volatility
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: ########.########
  "VI" NUMBER(16, 8),
  -- @COL_GUI_NAME: Volatility factor
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: ########.########
  "VI_FACTOR" NUMBER(16, 8),
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_TRANS_VI_INTV" PRIMARY KEY ("PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volatility indicator
-- @TBL_GUI_NAME_SHORT: VOLATILITY_INDICATOR
-- @TBL_NAME_AT: S_HFT_VOLATILITY_INDICATOR_AT
-- @TBL_DISPLAY_ORDER: 12
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR" (
  -- @COL_GUI_NAME: Product type
  -- @COL_DESC: allowed values:FBND,FCUR,FINT,FINX,FIPS,FSTK,FVOL,OCUR,OFBD,OFIT,OFIX,OINX,OSTK
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(FBND|FCUR|FINT|FINX|FIPS|FSTK|FVOL|OCUR|OFBD|OFIT|OFIX|OINX|OSTK)
  -- @LKP_SQL_STMT1: select 'FBND' as LABEL, 'FBND'  as VALUE from dual UNION ALL select 'FCUR' as LABEL, 'FCUR' as VALUE from dual UNION ALL select 'FINT' as LABEL, 'FINT' as VALUE from dual UNION ALL select 'FINX' as LABEL, 'FINX' as VALUE from dual UNION ALL select 'FIPS' as LABEL, 'FIPS' as VALUE from dual UNION ALL select 'FSTK' as LABEL, 'FSTK' as VALUE from dual UNION ALL select 'FVOL' as LABEL, 'FVOL' as VALUE from dual UNION ALL select 'OCUR' as LABEL, 'OCUR' as VALUE from dual UNION ALL select 'OFBD' as LABEL, 'OFBD' as VALUE from dual UNION ALL select 'OFIT' as LABEL, 'OFIT' as VALUE from dual UNION ALL select 'OFIX' as LABEL, 'OFIX' as VALUE from dual UNION ALL select 'OINX' as LABEL, 'OINX' as VALUE from dual UNION ALL select 'OSTK' as LABEL, 'OSTK' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Reference product
  -- @COL_DESC: values example:FGBL,FESX
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[A-Z0-9]{4,6}$
  "REFERENCE_PRODUCT" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Rollover window
  -- @COL_DESC: front month switch days.
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: #
  "ROLLOVER_WINDOW" NUMBER,
  -- @COL_GUI_NAME: Averaging window
  -- @COL_DESC: number of days used for average of RVraw. Minimum value is: 2
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: #
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^(2|[3-9]|[1-9][0-9]+)$
  "AVERAGING_WINDOW" NUMBER,
  -- @COL_GUI_NAME: Primary flag
  -- @COL_DESC: primary products will be used for reporting as reference. Allowed values are: Y or N
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(Y|N)
  "PRIMARY_FLAG" CHAR(1 BYTE) DEFAULT ('Y'),
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_VOLATILITY_INDICATOR" PRIMARY KEY ("PRODUCT_TYPE", "REFERENCE_PRODUCT", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volume Based OTR
-- @TBL_GUI_NAME_SHORT: VOLUME_OTR
-- @TBL_NAME_AT: S_HFT_VOLUME_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Grace Factor
  -- @COL_DISPLAY_ORDER: 2
  "GRACE_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Minimum Denominator
  -- @COL_DISPLAY_ORDER: 3
  "MINIMUM_DENOMINATOR" NUMBER,
  -- @COL_GUI_NAME: Base Limit
  -- @COL_DISPLAY_ORDER: 4
  "BASE_LIMIT" NUMBER,
  -- @COL_GUI_NAME: SMC Factor
  -- @COL_DISPLAY_ORDER: 5
  "SMC_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volume Based OTR for Product
-- @TBL_GUI_NAME_SHORT: VOLUME_OTR_PROD
-- @TBL_NAME_AT: S_HFT_VOLUME_PROD_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_PROD" (
  -- @COL_GUI_NAME: Product ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Threshold
  -- @COL_DISPLAY_ORDER: 2
  "THRESHOLD" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volume Based OTR Spread Quality
-- @TBL_GUI_NAME_SHORT: VOLUME_OTR_SQ
-- @TBL_NAME_AT: S_HFT_VOLUME_SQ_INTV_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_SQ_INTV" (
  -- @COL_GUI_NAME: Product Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "INTERVAL_NO" NUMBER,
  -- @COL_GUI_NAME: Spread Quality
  -- @COL_DISPLAY_ORDER: 3
  "SPREAD_QUALITY" NUMBER,
  -- @COL_GUI_NAME: MM Factor
  -- @COL_DISPLAY_ORDER: 4
  "MM_FACTOR" NUMBER,
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volume Based OTR VI Quality
-- @TBL_GUI_NAME_SHORT: VOLUME_OTR_VI
-- @TBL_NAME_AT: S_HFT_VOLUME_VI_INTV_AT
-- @TBL_DISPLAY_ORDER: 13
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_VI_INTV" (
  -- @COL_GUI_NAME: Product type
  -- @COL_DESC: allowed values:FBND,FCUR,FINT,FINX,FIPS,FSTK,FVOL,OCUR,OFBD,OFIT,OFIX,OINX,OSTK
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(FBND|FCUR|FINT|FINX|FIPS|FSTK|FVOL|OCUR|OFBD|OFIT|OFIX|OINX|OSTK)
  -- @LKP_SQL_STMT1: select 'FBND' as LABEL, 'FBND'  as VALUE from dual UNION ALL select 'FCUR' as LABEL, 'FCUR' as VALUE from dual UNION ALL select 'FINT' as LABEL, 'FINT' as VALUE from dual UNION ALL select 'FINX' as LABEL, 'FINX' as VALUE from dual UNION ALL select 'FIPS' as LABEL, 'FIPS' as VALUE from dual UNION ALL select 'FSTK' as LABEL, 'FSTK' as VALUE from dual UNION ALL select 'FVOL' as LABEL, 'FVOL' as VALUE from dual UNION ALL select 'OCUR' as LABEL, 'OCUR' as VALUE from dual UNION ALL select 'OFBD' as LABEL, 'OFBD' as VALUE from dual UNION ALL select 'OFIT' as LABEL, 'OFIT' as VALUE from dual UNION ALL select 'OFIX' as LABEL, 'OFIX' as VALUE from dual UNION ALL select 'OINX' as LABEL, 'OINX' as VALUE from dual UNION ALL select 'OSTK' as LABEL, 'OSTK' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Interval Number
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  -- @COL_GUI_NAME: Volatility
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: ########.########
  "VI" NUMBER(16, 8),
  -- @COL_GUI_NAME: Volatility factor
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: ########.########
  "VI_FACTOR" NUMBER(16, 8),
  -- @COL_GUI_NAME: Business valid from
  -- @COL_DESC: start date of validity
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- @COL_GUI_NAME: Business valid to
  -- @COL_DESC: end date of validity
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_VOLUME_VI_INTV" PRIMARY KEY ("PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
) TABLESPACE XMDM_FACT;