-- @TBL_GUI_NAME: Account Mapping C7FXS_ETD
-- @TBL_GUI_NAME_SHORT: ACCOUNT_MAPPING_C7FXS_ETD
-- @TBL_NAME_AT: ACCOUNT_MAPPING_C7FXS_ETD_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_C7FXS_ETD" (
  -- @COL_GUI_NAME: Tbcr Sender
  -- @COL_DESC: Sender in TBCR
  -- @COL_DISPLAY_ORDER: 3
  "TBCR_SENDER" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Comments
  -- @COL_DESC: Comment (Optional)
  -- @COL_DISPLAY_ORDER: 5
  "COMMENTS" VARCHAR2(500 CHAR),
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: Currency
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Tbcr Account
  -- @COL_DESC: Account in TBCR
  -- @COL_DISPLAY_ORDER: 4
  "TBCR_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Source System
  -- @COL_DESC: Source System
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SOURCE_SYSTEM" VARCHAR2(9 CHAR) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_ACCOUNT_MAPPING_C7FXS_ETD" PRIMARY KEY ("CURRENCY", "SOURCE_SYSTEM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Account Mapping Scs
-- @TBL_GUI_NAME_SHORT: ACCOUNT_MAPPING_SCS
-- @TBL_NAME_AT: ACCOUNT_MAPPING_SCS_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SCS" (
  -- @COL_GUI_NAME: Settlement Account Number
  -- @COL_DESC: Account Number from Source System
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "SETTLEMENT_ACCOUNT_NUMBER" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tbcr Sender
  -- @COL_DESC: Sender in TBCR
  -- @COL_DISPLAY_ORDER: 6
  "TBCR_SENDER" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Logic
  -- @COL_DESC: Mapping Logic
  -- @COL_DISPLAY_ORDER: 5
  "LOGIC" VARCHAR2(200 CHAR),
  -- @COL_GUI_NAME: Comments
  -- @COL_DESC: Comment (Optional)
  -- @COL_DISPLAY_ORDER: 8
  "COMMENTS" VARCHAR2(500 CHAR),
  -- @COL_GUI_NAME: Settlement Account Location
  -- @COL_DESC: Settlement Account Location
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "SETTLEMENT_ACCOUNT_LOCATION" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: Currency
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "CURRENCY" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Tbcr Account
  -- @COL_DESC: Account in TBCR
  -- @COL_DISPLAY_ORDER: 7
  "TBCR_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Source System
  -- @COL_DESC: Source System
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SOURCE_SYSTEM" VARCHAR2(30 CHAR) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_ACCOUNT_MAPPING_SCS" PRIMARY KEY ("SETTLEMENT_ACCOUNT_NUMBER", "SETTLEMENT_ACCOUNT_LOCATION", "CURRENCY", "SOURCE_SYSTEM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Account Mapping Swift
-- @TBL_GUI_NAME_SHORT: ACCOUNT_MAPPING_SWIFT
-- @TBL_NAME_AT: ACCOUNT_MAPPING_SWIFT_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SWIFT" (
  -- @COL_GUI_NAME: Include For Balances
  -- @COL_DESC: Include in Balance calculation (Y or N)
  -- @COL_DISPLAY_ORDER: 9
  "INCLUDE_FOR_BALANCES" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: Receiver
  -- @COL_DESC: Receiver
  -- @COL_DISPLAY_ORDER: 3
  "RECEIVER" VARCHAR2(20 CHAR),
  -- @COL_GUI_NAME: Tbcr Sender
  -- @COL_DESC: Sender in TBCR
  -- @COL_DISPLAY_ORDER: 6
  "TBCR_SENDER" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency
  -- @COL_DESC: Currency
  -- @COL_DISPLAY_ORDER: 5
  "CURRENCY" VARCHAR2(3 CHAR),
  -- @COL_GUI_NAME: Mapping Required
  -- @COL_DESC: Is the mapping required (Y or N)
  -- @COL_DISPLAY_ORDER: 8
  "MAPPING_REQUIRED" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: Comments
  -- @COL_DESC: Comment (Optional)
  -- @COL_DISPLAY_ORDER: 11
  "COMMENTS" VARCHAR2(500 CHAR),
  -- @COL_GUI_NAME: Sender
  -- @COL_DESC: Sender
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "SENDER" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Include For Transactions
  -- @COL_DESC: Include in transactions (Y or N)
  -- @COL_DISPLAY_ORDER: 10
  "INCLUDE_FOR_TRANSACTIONS" VARCHAR2(1 CHAR),
  -- @COL_GUI_NAME: External Account Number
  -- @COL_DESC: External Account Number
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "EXTERNAL_ACCOUNT_NUMBER" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Tbcr Account
  -- @COL_DESC: Account in TBCR
  -- @COL_DISPLAY_ORDER: 7
  "TBCR_ACCOUNT" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Source System
  -- @COL_DESC: Source System
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: select 'MT940' as LABEL, 'MT940' as VALUE from dual UNION ALL select 'MT950' as LABEL, 'MT950' as VALUE from dual UNION ALL select 'camt.053' as LABEL, 'camt.053' as VALUE from dual UNION ALL select 'pacs.009' as LABEL, 'pacs.009' as VALUE from dual
  -- @LKP_SQL_LABEL: LABEL
  -- @LKP_SQL_VALUE: VALUE
  "SOURCE_SYSTEM" VARCHAR2(20 CHAR) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_ACCOUNT_MAPPING_SWIFT" PRIMARY KEY ("SENDER", "EXTERNAL_ACCOUNT_NUMBER", "SOURCE_SYSTEM")
) TABLESPACE XMDM_FACT;