-- @TBL_GUI_NAME: Agg slice
-- @TBL_GUI_NAME_SHORT: AGG_SLICE
-- @TBL_NAME_AT: S_HYPMI_AGG_SLICE_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_EUREX_HYPMI"."S_HYPMI_AGG_SLICE" (
  -- @COL_GUI_NAME: Slice ID
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "SLICE_ID" NUMBER(4, 0) NOT NULL,
  -- @COL_GUI_NAME: Aggregation level
  -- @COL_DISPLAY_ORDER: 2
  "AGGREGATION_LEVEL" VARCHAR2(30 CHAR),
  -- @COL_GUI_NAME: Slice begin
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "SLICE_BEGIN" NUMBER(9, 0) NOT NULL,
  -- @COL_GUI_NAME: Slice end
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "SLICE_END" NUMBER(9, 0) NOT NULL,
  -- @COL_GUI_NAME: Slice name
  -- @COL_DISPLAY_ORDER: 5
  "SLICE_NAME" VARCHAR2(30 CHAR),
  -- @COL_GUI_NAME: Slice weight
  -- @COL_DISPLAY_ORDER: 6
  "SLICE_WEIGHT" NUMBER(6, 3),
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Order book calc scope
-- @TBL_GUI_NAME_SHORT: OBOOK_CALC_SCOPE
-- @TBL_NAME_AT: S_HYPMI_OBOOK_CALC_SCOPE_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_EUREX_HYPMI"."S_HYPMI_OBOOK_CALC_SCOPE" (
  -- @COL_GUI_NAME: Calculation begin time
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:([01]?[0-9]|2[0-3])[0-5][0-9][0-5][0-9]
  "CALC_BEGIN" VARCHAR2(6 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Calculation end time
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:([01]?[0-9]|2[0-3])[0-5][0-9][0-5][0-9]
  "CALC_END" VARCHAR2(6 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Calculation increase
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "CALC_INCR" NUMBER(9, 4) NOT NULL,
  -- @COL_GUI_NAME: Calculation increase unit
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:(MI|HO)
  "CALC_INCR_UNIT" VARCHAR2(15 BYTE) NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_EUREX_HYPMI"."S_HYPMI_PRODUCT_CLASS_ASN" (
  "PRODUCT_CLASS_CODE" VARCHAR2(15 BYTE),
  "PRODUCT_CODE" VARCHAR2(15 BYTE),
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE),
  "PRODUCT_SUB_CLASS_CODE" CHAR(12 BYTE)
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Volume Class
-- @TBL_GUI_NAME_SHORT: VOLUME_CLASS
-- @TBL_NAME_AT: S_HYPMI_VOLUME_CLASS_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_EUREX_HYPMI"."S_HYPMI_VOLUME_CLASS" (
  -- @COL_GUI_NAME: Product type
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT_TYPE" VARCHAR2(30 CHAR) DEFAULT 'N/A',
  -- @COL_GUI_NAME: Product class
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "PRODUCT_CLASS" VARCHAR2(30 CHAR) DEFAULT 'N/A',
  -- @COL_GUI_NAME: Product business ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PRODUCT_BUSINESS_ID" VARCHAR2(30 CHAR) DEFAULT 'N/A',
  -- @COL_GUI_NAME: Volume class
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "VOLUME_CLASS" NUMBER(*, 0) NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
) TABLESPACE XMDM_FACT;