-- @TBL_GUI_NAME: Member Input FX
-- @TBL_GUI_NAME_SHORT: OTC_INPUT_FX
-- @TBL_NAME_AT: S_MATLAB_OTC_INPUT_FX_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_INPUT_FX" (
  -- @COL_GUI_NAME: CCY
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_PK: Y
  "CCY" VARCHAR2(6 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Notional (in mn EUR)
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "NOTIONAL" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Barclays
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0.00
  "BARCLAYS" NUMBER,
  -- @COL_GUI_NAME: Credit Suisse
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.00
  "CREDIT_SUISSE" NUMBER,
  -- @COL_GUI_NAME: Deutsche Bank
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.00
  "DEUTSCHE_BANK" NUMBER,
  -- @COL_GUI_NAME: Morgan Stanley
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.00
  "MORGAN_STANLEY" NUMBER,
  -- @COL_GUI_NAME: RBS
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.00
  "RBS" NUMBER,
  -- @COL_GUI_NAME: JP Morgan
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.00
  "JP_MORGAN" NUMBER,
  -- @COL_GUI_NAME: HSBC
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.00
  "HSBC" NUMBER,
  -- @COL_GUI_NAME: Banca IMI
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "BANCA_IMI" NUMBER,
  -- @COL_GUI_NAME: SocGen
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0.00
  "SOCGEN" NUMBER
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Member Input XCCY
-- @TBL_GUI_NAME_SHORT: OTC_INPUT_XCCY
-- @TBL_NAME_AT: S_MATLAB_OTC_INPUT_XCCY_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_INPUT_XCCY" (
  -- @COL_GUI_NAME: CCY
  -- @COL_DISPLAY_ORDER: 0
  -- @COL_PK: Y
  "CCY" VARCHAR2(6 BYTE) NOT NULL,
  -- @COL_GUI_NAME: MATURITY
  -- @COL_DESC: MATURITY
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "MATURITY" NUMBER NOT NULL,
  -- @COL_GUI_NAME: XCCY DV01
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "XCCY_DV01" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Barclays
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.00
  "BARCLAYS" NUMBER,
  -- @COL_GUI_NAME: Credit Suisse
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.00
  "CREDIT_SUISSE" NUMBER,
  -- @COL_GUI_NAME: Deutsche Bank
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.00
  "DEUTSCHE_BANK" NUMBER,
  -- @COL_GUI_NAME: Morgan Stanley
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.00
  "MORGAN_STANLEY" NUMBER,
  -- @COL_GUI_NAME: RBS
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.00
  "RBS" NUMBER,
  -- @COL_GUI_NAME: JP Morgan
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.00
  "JP_MORGAN" NUMBER,
  -- @COL_GUI_NAME: HSBC
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "HSBC" NUMBER,
  -- @COL_GUI_NAME: BAML
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "BAML" NUMBER,
  -- @COL_GUI_NAME: Banca IMI
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "BANCA_IMI" NUMBER,
  -- @COL_GUI_NAME: Danske
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "DANSKE" NUMBER,
  -- @COL_GUI_NAME: SocGen
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_FORMAT: 0.00
  "SOCGEN" NUMBER,
  -- @COL_GUI_NAME: Nordea
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_FORMAT: 0.00
  "NORDEA" NUMBER
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Curve Whitelist
-- @TBL_GUI_NAME_SHORT: CURVE_WHITELIST
-- @TBL_NAME_AT: S_MATLAB_OTC_IRS_CUR_WHILIS_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_CUR_WHITELIST" (
  -- @COL_GUI_NAME: Curve
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CURVE" VARCHAR2(25 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Active
  -- @COL_DISPLAY_ORDER: 2
  "ACTIVE" CHAR(1 CHAR) DEFAULT 'N'
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Market Capacities (Minor Currencies vs CHF)
-- @TBL_GUI_NAME_SHORT: Mrkt Capacity-Minor CCY vs CHF
-- @TBL_NAME_AT: S_MATLAB_OTC_IRS_MINOR_CUR_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_MINOR_CUR" (
  -- @COL_GUI_NAME: CURRENCY
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CCY" VARCHAR2(25 CHAR),
  -- @COL_GUI_NAME: 2Y
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0.00
  "COL_2Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 5Y
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.00
  "COL_5Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 10Y
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.00
  "COL_10Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 15Y
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.00
  "COL_15Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 20Y
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.00
  "COL_20Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 30Y
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.00
  "COL_30Y" NUMBER(15, 4),
  -- @COL_GUI_NAME: 50Y
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.00
  "COL_50Y" NUMBER(15, 4),
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: OTC IRS
-- @TBL_GUI_NAME_SHORT: OTC IRS
-- @TBL_NAME_AT: S_MATLAB_OTC_IRS_RISK_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_RISK" (
  -- @COL_GUI_NAME: PROCESS NAME
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PROCESS_NAME" VARCHAR2(25 CHAR),
  -- @COL_GUI_NAME: PARAM CLASS
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "PARAM_CLASS" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: PARAM NAME
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "PARAM_NAME" VARCHAR2(255 CHAR),
  "ITS" DATE,
  -- @COL_GUI_NAME: PARAM VALUE
  -- @COL_DISPLAY_ORDER: 4
  "PARAM_VALUE" VARCHAR2(255 CHAR)
) TABLESPACE XMDM_FACT;