-- @TBL_GUI_NAME: Price per TradeVR
-- @TBL_GUI_NAME_SHORT: Price per TradeVR
-- @TBL_NAME_AT: PRICE_TRADEVR_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_EPS_REBATES_RF"."PRICE_TRADEVR" (
  -- @COL_GUI_NAME: Trade VR
  -- @COL_DESC: Trade VR
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TRADEVR" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Pricing Group
  -- @COL_DESC: Pricing Group
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "PRICING_GROUP" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Node
  -- @COL_DESC: Node
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "NODE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Product ID
  -- @COL_DESC: Product ID
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "PRODUCT_ID" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Product Name
  -- @COL_DESC: Product Name
  -- @COL_DISPLAY_ORDER: 5
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Band
  -- @COL_DESC: Band
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "BAND" NUMBER(*, 0),
  -- @COL_GUI_NAME: Threshold
  -- @COL_DESC: Threshold
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: #
  "THRESHOLD" NUMBER(*, 0),
  -- @COL_GUI_NAME: Price
  -- @COL_DESC: Price
  -- @COL_DISPLAY_ORDER: 8
  "PRICE" NUMBER,
  -- @COL_GUI_NAME: Rebate
  -- @COL_DESC: Rebate
  -- @COL_DISPLAY_ORDER: 9
  "REBATE" NUMBER,
  -- @COL_GUI_NAME: Max Fee
  -- @COL_DESC: Max Fee
  -- @COL_DISPLAY_ORDER: 10
  "MAX_FEE" NUMBER(*, 0),
  -- @COL_GUI_NAME: Price List Text
  -- @COL_DESC: Price List Text
  -- @COL_DISPLAY_ORDER: 11
  "PLIST_TEXT" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: TradeVR List to Scenario Assign
-- @TBL_GUI_NAME_SHORT: TradeVR List to Scenario Assign
-- @TBL_NAME_AT: TRADEVRLST_SCENARIO_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_EPS_REBATES_RF"."TRADEVRLST_SCENARIO_ASSIGNM" (
  -- @COL_GUI_NAME: Scenario Name
  -- @COL_DESC: Scenario Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Service
  -- @COL_DESC: Service
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "SERVICE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Route
  -- @COL_DESC: Route
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "ROUTE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Start Date
  -- @COL_DESC: Start Date
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "START_DATE" DATE,
  -- @COL_GUI_NAME: End Date
  -- @COL_DESC: End Date
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  "END_DATE" DATE,
  -- @COL_GUI_NAME: Priority
  -- @COL_DESC: Priority
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "PRIORITY" NUMBER(*, 0),
  -- @COL_GUI_NAME: TSR List
  -- @COL_DESC: TSR List
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  "TSRLIST" VARCHAR2(150 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: TradeVR Lists
-- @TBL_GUI_NAME_SHORT: TradeVR Lists
-- @TBL_NAME_AT: TRADEVR_LISTS_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_EPS_REBATES_RF"."TRADEVR_LISTS" (
  -- @COL_GUI_NAME: TSR List
  -- @COL_DESC: TSR List
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TSRLIST" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Remarks
  -- @COL_DESC: Remarks
  -- @COL_DISPLAY_ORDER: 2
  "REMARKS" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Tradevr to Price List Assignm
-- @TBL_GUI_NAME_SHORT: Tradevr to Price List Assignm
-- @TBL_NAME_AT: TRADEVR_PRICELIST_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_EPS_REBATES_RF"."TRADEVR_PRICELIST_ASSIGNM" (
  -- @COL_GUI_NAME: TSR List
  -- @COL_DESC: TSR List
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TSRLIST" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Trade VR
  -- @COL_DESC: Trade VR
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "TRADEVR" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Node
  -- @COL_DESC: Node
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "NODE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Priority
  -- @COL_DESC: Priority
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "PRIORITY" NUMBER(*, 0),
  -- @COL_GUI_NAME: Account Type
  -- @COL_DESC: Account Type
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "ACCOUNTTYPE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Disclosed
  -- @COL_DESC: Disclosed
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  "DISCLOSED" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Execution Type
  -- @COL_DESC: Execution Type
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  "EXECTYPE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Price Changed
  -- @COL_DESC: Price Changed
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_PK: Y
  "PRICE_CHANGED" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: M_AS_P
  -- @COL_DESC: M_AS_P
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: #
  "M_AS_P" NUMBER(*, 0),
  -- @COL_GUI_NAME: Rebate EBI
  -- @COL_DESC: Rebate EBI
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: #
  "REBATE_EBI" NUMBER(*, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: TradeVR to Template Assignm
-- @TBL_GUI_NAME_SHORT: TradeVR to Template Assignm
-- @TBL_NAME_AT: TRADEVR_TEMPLATE_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_EPS_REBATES_RF"."TRADEVR_TEMPLATE_ASSIGNM" (
  -- @COL_GUI_NAME: Trade VR
  -- @COL_DESC: Trade VR
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TRADEVR" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Remarks
  -- @COL_DESC: Remarks
  -- @COL_DISPLAY_ORDER: 2
  "REMARKS" VARCHAR2(250 BYTE),
  -- @COL_GUI_NAME: Template
  -- @COL_DESC: Template
  -- @COL_DISPLAY_ORDER: 3
  "TEMPLATE" VARCHAR2(100 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;