-- @TBL_GUI_NAME: Parameters
-- @TBL_GUI_NAME_SHORT: PMRLP_PARAMETER
-- @TBL_NAME_AT: PMRLP_PARAMETER_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_PMRLP"."PMRLP_PARAMETER" (
  -- @COL_GUI_NAME: Isin
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "ISIN" VARCHAR2(12 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PMRLP_PARAMETER" PRIMARY KEY ("ISIN")
) TABLESPACE XMDM_FACT;