-- @TBL_GUI_NAME: Basket
-- @TBL_GUI_NAME_SHORT: Basket
-- @TBL_NAME_AT: D_STG_BASKET_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_BASKET" (
  -- @COL_GUI_NAME: BASKET_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BASKET_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: BASKET_NAME
  -- @COL_DISPLAY_ORDER: 2
  "BASKET_NAME" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: EXPLICITLY_DEF_IND
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "EXPLICITLY_DEF_IND" NUMBER(1, 0),
  -- @COL_GUI_NAME: DERIVED_FROM_IDX_ISIN
  -- @COL_DISPLAY_ORDER: 4
  "DERIVED_FROM_IDX_ISIN" VARCHAR2(12 CHAR),
  -- @COL_GUI_NAME: RECOMPOSITION_RULE
  -- @COL_DISPLAY_ORDER: 5
  "RECOMPOSITION_RULE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: ORDER_VALUE_THRESHOLD
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.000
  "ORDER_VALUE_THRESHOLD" NUMBER(15, 0),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Basket Benchmark Tier
-- @TBL_GUI_NAME_SHORT: Basket Benchmark Tier
-- @TBL_NAME_AT: D_STG_BASKET_BENCHM_TIER_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_BASKET_BENCHM_TIER" (
  -- @COL_GUI_NAME: BASKET_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BASKET_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: TIER
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "TIER" NUMBER(15, 0),
  -- @COL_GUI_NAME: BBO_PERF_THRESHOLD
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: 0.0000
  "BBO_PERF_THRESHOLD" NUMBER(15, 4),
  -- @COL_GUI_NAME: PASS_VALUE_SHARE_THRESHOLD
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: 0.0000
  "PASS_VALUE_SHARE_THRESHOLD" NUMBER(15, 4),
  -- @COL_GUI_NAME: PASS_VALUE_RATIO_THRESHOLD
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @COL_FORMAT: 0.0000
  "PASS_VALUE_RATIO_THRESHOLD" NUMBER(15, 4),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Basket Composition
-- @TBL_GUI_NAME_SHORT: Basket Composition
-- @TBL_NAME_AT: D_STG_BASKET_COMPOSITION_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_BASKET_COMPOSITION" (
  -- @COL_GUI_NAME: BASKET_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BASKET_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: COMP_INSTR_ISIN
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "COMP_INSTR_ISIN" VARCHAR2(12 CHAR),
  -- @COL_GUI_NAME: EXPLICITLY_DEF_IND
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "EXPLICITLY_DEF_IND" NUMBER(1, 0),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Liquidity Provider
-- @TBL_GUI_NAME_SHORT: Liquidity Provider
-- @TBL_NAME_AT: D_STG_LIQUIDITY_PROVIDER_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_LIQUIDITY_PROVIDER" (
  -- @COL_GUI_NAME: LP_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LP_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: LP_NAME
  -- @COL_DISPLAY_ORDER: 2
  "LP_NAME" VARCHAR2(255 CHAR),
  -- @COL_GUI_NAME: CLUSTER_TYPE
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "CLUSTER_TYPE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: ALGO_TRADING_OPT
  -- @COL_DISPLAY_ORDER: 3
  "ALGO_TRADING_OPT" VARCHAR2(10 BYTE),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Liquidity Provider Composition
-- @TBL_GUI_NAME_SHORT: Liquidity Provider Composition
-- @TBL_NAME_AT: D_STG_LIQ_PROVIDER_COMP_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_LIQ_PROVIDER_COMP" (
  -- @COL_GUI_NAME: LP_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LP_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: BP_NO
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "BP_NO" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: MEMBER_CODE
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_CODE" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: TRADER_CODE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "TRADER_CODE" VARCHAR2(15 CHAR),
  -- @COL_GUI_NAME: ACCOUNT_TYPE_PATTERN
  -- @COL_DISPLAY_ORDER: 5
  "ACCOUNT_TYPE_PATTERN" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Assignment of Liquiditiy Provider to Basket
-- @TBL_GUI_NAME_SHORT: Assig liquid provider to baske
-- @TBL_NAME_AT: D_STG_LIQ_PROV_BASKET_ASN_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_LPPM"."D_STG_LIQ_PROV_BASKET_ASN" (
  -- @COL_GUI_NAME: LP_CODE
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "LP_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: BASKET_CODE
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "BASKET_CODE" VARCHAR2(50 CHAR),
  -- @COL_GUI_NAME: VALIDITY_START_DATE
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALIDITY_START_DATE" DATE,
  -- @COL_GUI_NAME: VALIDITY_END_DATE
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: yyyy-MM-dd
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALIDITY_END_DATE" DATE,
  "ITS" DATE,
  -- @COL_GUI_NAME: REPORT_MEMBER
  -- @COL_DISPLAY_ORDER: 5
  "REPORT_MEMBER" CHAR(1 BYTE) DEFAULT 'Y'
) TABLESPACE XMDM_FACT;