-- @TBL_GUI_NAME: OTC IRD CLIENT STRUCTURE
-- @TBL_GUI_NAME_SHORT: F_OTC_IRD_CLIENT_STRUCTURE
-- @TBL_NAME_AT: F_OTC_IRD_CLIENT_STRUCTURE_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE" (
  -- @COL_GUI_NAME: Book Final
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "BOOK_FINAL" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: BP ID
  -- @COL_DISPLAY_ORDER: 2
  "BP_ID" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Acc
  -- @COL_DISPLAY_ORDER: 3
  "ACC" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Type
  -- @COL_DISPLAY_ORDER: 4
  "TYPE" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Account Name
  -- @COL_DISPLAY_ORDER: 5
  "ACCOUNT_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Account Group Name
  -- @COL_DISPLAY_ORDER: 6
  "ACCOUNT_GROUP_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Account LEI
  -- @COL_DISPLAY_ORDER: 7
  "ACCOUNT_LEI" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Earliest account LEI admission date
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: dd.MM.yyyy
  "EARLIEST_ACC_LEI_ADMISS_DATE" DATE,
  -- @COL_GUI_NAME: Account termination date
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: dd.MM.yyyy
  "ACC_TERMINATION_DATE" DATE,
  -- @COL_GUI_NAME: Lei termination date
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: dd.MM.yyyy
  "LEI_TERMINATION_DATE" DATE,
  -- @COL_GUI_NAME: Acc Type
  -- @COL_DISPLAY_ORDER: 11
  "ACC_TYPE" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Client Categorization
  -- @COL_DISPLAY_ORDER: 12
  "CLIENT_CATEGORIZATION" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Market Function
  -- @COL_DISPLAY_ORDER: 13
  "MARKET_FUNCTION" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: LSOC Flag
  -- @COL_DISPLAY_ORDER: 14
  "LSOC_FLAG" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Country
  -- @COL_DISPLAY_ORDER: 15
  "COUNTRY" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Code
  -- @COL_DISPLAY_ORDER: 16
  "CODE" VARCHAR2(2 BYTE),
  -- @COL_GUI_NAME: Region
  -- @COL_DISPLAY_ORDER: 17
  "REGION" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Packages 2023
  -- @COL_DISPLAY_ORDER: 18
  "PACKAGES_2023" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Packages 2024
  -- @COL_DISPLAY_ORDER: 19
  "PACKAGES_2024" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Last Package start date
  -- @COL_DISPLAY_ORDER: 20
  -- @COL_FORMAT: dd.MM.yyyy
  "LAST_PACKAGE_START_DATE" DATE,
  -- @COL_GUI_NAME: Last Package end date
  -- @COL_DISPLAY_ORDER: 21
  -- @COL_FORMAT: dd.MM.yyyy
  "LAST_PACKAGE_END_DATE" DATE,
  -- @COL_GUI_NAME: Previous Package start date
  -- @COL_DISPLAY_ORDER: 22
  -- @COL_FORMAT: dd.MM.yyyy
  "PREVIOUS_PACKAGE_START_DATE" DATE,
  -- @COL_GUI_NAME: Previous Package end date
  -- @COL_DISPLAY_ORDER: 23
  -- @COL_FORMAT: dd.MM.yyyy
  "PREVIOUS_PACKAGE_END_DATE" DATE,
  -- @COL_GUI_NAME: Owner Member ID
  -- @COL_DISPLAY_ORDER: 24
  "OWNER_MEMBER_ID" VARCHAR2(5 BYTE),
  -- @COL_GUI_NAME: Owner Name
  -- @COL_DISPLAY_ORDER: 25
  "OWNER_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Owner Group Name
  -- @COL_DISPLAY_ORDER: 26
  "OWNER_GROUP_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: Owner LEI
  -- @COL_DISPLAY_ORDER: 27
  "OWNER_LEI" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Earliest Owner LEI admission date
  -- @COL_DISPLAY_ORDER: 28
  -- @COL_FORMAT: dd.MM.yyyy
  "EARLIEST_OWN_LEI_ADMISS_DATE" DATE,
  -- @COL_GUI_NAME: Owner Admission Type
  -- @COL_DISPLAY_ORDER: 29
  "OWNER_ADMISSION_TYPE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Owner Country
  -- @COL_DISPLAY_ORDER: 30
  "OWNER_COUNTRY" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Owner Code
  -- @COL_DISPLAY_ORDER: 31
  "OWNER_CODE" VARCHAR2(2 BYTE),
  -- @COL_GUI_NAME: Owner Region
  -- @COL_DISPLAY_ORDER: 32
  "OWNER_REGION" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: Authorized Fund Manager
  -- @COL_DISPLAY_ORDER: 33
  "AUTHORIZED_FUND_MANAGER" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: AM Member ID
  -- @COL_DISPLAY_ORDER: 34
  "AM_MEMBER_ID" VARCHAR2(5 BYTE),
  -- @COL_GUI_NAME: AM LEI
  -- @COL_DISPLAY_ORDER: 35
  "AM_LEI" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: AM Country
  -- @COL_DISPLAY_ORDER: 36
  "AM_COUNTRY" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: AM Code
  -- @COL_DISPLAY_ORDER: 37
  "AM_CODE" VARCHAR2(2 BYTE),
  -- @COL_GUI_NAME: AM Region
  -- @COL_DISPLAY_ORDER: 38
  "AM_REGION" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: CM Member ID
  -- @COL_DISPLAY_ORDER: 39
  "CM_MEMBER_ID" VARCHAR2(5 BYTE),
  -- @COL_GUI_NAME: CM Name
  -- @COL_DISPLAY_ORDER: 40
  "CM_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: CM Group Name
  -- @COL_DISPLAY_ORDER: 41
  "CM_GROUP_NAME" VARCHAR2(150 BYTE),
  -- @COL_GUI_NAME: CM LEI
  -- @COL_DISPLAY_ORDER: 42
  "CM_LEI" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: CM Type
  -- @COL_DISPLAY_ORDER: 43
  "CM_TYPE" VARCHAR2(20 BYTE),
  -- @COL_GUI_NAME: CM Country
  -- @COL_DISPLAY_ORDER: 44
  "CM_COUNTRY" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: CM Code
  -- @COL_DISPLAY_ORDER: 45
  "CM_CODE" VARCHAR2(2 BYTE),
  -- @COL_GUI_NAME: CM Region
  -- @COL_DISPLAY_ORDER: 46
  "CM_REGION" VARCHAR2(20 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_OTC_IRD_CLIENT_STRUCTURE" PRIMARY KEY ("BOOK_FINAL")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: CC210 Input Filter
-- @TBL_GUI_NAME_SHORT: CC210_Input_Filter
-- @TBL_NAME_AT: S_OTC_CC210_INPUT_FILTER_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_OTC"."S_OTC_CC210_INPUT_FILTER" (
  -- @COL_GUI_NAME: Filter Code
  -- @COL_DESC: Technical Filter Code (no whitespaces)
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "FILTER_CODE" VARCHAR2(30 BYTE),
  -- @COL_GUI_NAME: Filter Value
  -- @COL_DESC: The filter value is used for filtering the data by maturity offset
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[0-9]+$
  "FILTER_VALUE" NUMBER,
  -- @COL_GUI_NAME: Filter enabled
  -- @COL_DESC: Enable this filter oder disable
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "ENABLED" NUMBER(1, 0),
  "ITS" TIMESTAMP
) TABLESPACE XMDM_FACT;