-- @TBL_GUI_NAME: STAT_PRODUCTS
-- @TBL_GUI_NAME_SHORT: EsMiRa
-- @TBL_NAME_AT: STAT_PRODUCTS_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_ESMIRA"."STAT_PRODUCTS" (
  -- @COL_GUI_NAME: Product
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PRODUCT" VARCHAR2(20 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Rule Key
  -- @COL_DISPLAY_ORDER: 2
  "RULE_KEY" VARCHAR2(20 CHAR),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STAT_PRODUCTS" PRIMARY KEY ("PRODUCT")
) TABLESPACE XMDM_FACT;