CREATE TABLE "GUI_XMDM_LST"."AGGREGATION_LEVELS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "ENTITY" VARCHAR2(50 BYTE) NOT NULL,
  "AGG_GROUP" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_AGGREGATION_LEVELS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Backup Arrangement
-- @TBL_GUI_NAME_SHORT: BACKUP_ARRANGEMENT
-- @TBL_NAME_AT: BACKUP_ARRANGEMENT_AT
-- @TBL_DISPLAY_ORDER: 28
CREATE TABLE "GUI_XMDM_LST"."BACKUP_ARRANGEMENT" (
  -- @COL_GUI_NAME: Member Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE  FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MEMBER_ROLE'  AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MEMBER_ROLE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Backup arrangement in days
  -- @COL_DISPLAY_ORDER: 2
  "BACKUP_ARRANGEMENT_IN_DAYS" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_BACKUP_ARRANGEMENT" PRIMARY KEY ("MEMBER_ROLE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."BASKET_CAPACITIES" (
  "CATEGORY_I" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY_II" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_BASKET" VARCHAR2(50 BYTE) NOT NULL,
  "CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  "CAP_IN_BN_SINGLE_CURR" NUMBER(7, 3) NOT NULL,
  "CAP_IN_BN_AGG" NUMBER(7, 3) NOT NULL,
  "HAIRCUT" NUMBER(3, 0),
  "CROSS_CURR_HAIRCUT" NUMBER(3, 2),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_BASKET_CAPACITIES" PRIMARY KEY ("CATEGORY_I", "CATEGORY_II", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY_FAILURE" VARCHAR2(50 BYTE),
  "CASH_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_COMPANY_CAP" VARCHAR2(50 BYTE) NOT NULL,
  "SEC_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE),
  "SEC_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE),
  "OTC_CURRENCY_PREFUNDING" VARCHAR2(50 BYTE),
  "OWN_FUNDS" VARCHAR2(50 BYTE) NOT NULL,
  "CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "COLLATERALISED_CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "OTC_CURRENCY_SWAPLINES" VARCHAR2(50 BYTE),
  "CCP_PREFINANCING_ACTIVITIES" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99_9" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COMPONENT_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET_CONFIG" (
  "FLOW_TYPE_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_SECURITIES_INDICATOR" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_GROUP" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "ESMA_FLOW_TYPE" VARCHAR2(50 BYTE),
  "ALLOWED_USAGE" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COMPONENT_SET_CONFIG" PRIMARY KEY ("FLOW_TYPE_CODE", "FLOW_TYPE_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Counterparty Def Assign
-- @TBL_GUI_NAME_SHORT: COUNTERPARTY_DEF_ASSIGN
-- @TBL_NAME_AT: COUNTERPARTY_DEF_ASSIGN_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_DEF_ASSIGN" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT SCENARIO_CODE FROM GUI_XMDM_LST.SCENARIO_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CODE
  -- @LKP_SQL_VALUE: SCENARIO_CODE
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Clearing Member
  -- @COL_DISPLAY_ORDER: 2
  "CLEARING_MEMBER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Clearing Institute
  -- @COL_DISPLAY_ORDER: 3
  "CLEARING_INSTITUTE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Liquidity Provider
  -- @COL_DISPLAY_ORDER: 4
  "LIQUIDITY_PROVIDER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Nostro Agent
  -- @COL_DISPLAY_ORDER: 5
  "NOSTRO_AGENT" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Settlement Bank
  -- @COL_DISPLAY_ORDER: 6
  "SETTLEMENT_BANK" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Custodian Bank
  -- @COL_DISPLAY_ORDER: 7
  "CUSTODIAN_BANK" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Payment systems/Securities Settlement Systems
  -- @COL_DISPLAY_ORDER: 8
  "PAYMENT_SYSTEMS_AND_SSS" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_DEF_ASSIGN" PRIMARY KEY ("SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_EX_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY__EX_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_EX_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Counterparty Role Assign
-- @TBL_GUI_NAME_SHORT: COUNTERPARTY_ROLE_ASSIGN
-- @TBL_NAME_AT: COUNTERPARTY_ROLE_ASSIGN_AT
-- @TBL_DISPLAY_ORDER: 9
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_ROLE_ASSIGN" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT SCENARIO_CODE FROM GUI_XMDM_LST.SCENARIO_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CODE
  -- @LKP_SQL_VALUE: SCENARIO_CODE
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Clearing Member
  -- @COL_DISPLAY_ORDER: 2
  "CLEARING_MEMBER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Clearing Institute
  -- @COL_DISPLAY_ORDER: 3
  "CLEARING_INSTITUTE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Liquidity Provider
  -- @COL_DISPLAY_ORDER: 4
  "LIQUIDITY_PROVIDER" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Nostro Agent
  -- @COL_DISPLAY_ORDER: 5
  "NOSTRO_AGENT" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Settlement Bank
  -- @COL_DISPLAY_ORDER: 6
  "SETTLEMENT_BANK" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Custodian Bank
  -- @COL_DISPLAY_ORDER: 7
  "CUSTODIAN_BANK" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Payment systems/Securities Settlement Systems
  -- @COL_DISPLAY_ORDER: 8
  "PAYMENT_SYSTEMS_AND_SSS" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Issuer
  -- @COL_DISPLAY_ORDER: 9
  "ISSUER" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_ROLE_ASSIGN" PRIMARY KEY ("SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CLEARING_MEMBER" VARCHAR2(50 BYTE),
  "CLEARING_INSTITUTE" VARCHAR2(50 BYTE),
  "LIQUIDITY_PROVIDER" VARCHAR2(50 BYTE),
  "NOSTRO_AGENT" VARCHAR2(50 BYTE),
  "SETTLEMENT_BANK" VARCHAR2(50 BYTE),
  "CUSTODIAN_BANK" VARCHAR2(50 BYTE),
  "PAYMENT_SEC_SET_SYSTEMS" VARCHAR2(50 BYTE),
  "ISSUER" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Counterparty Excl. Set Assign
-- @TBL_GUI_NAME_SHORT: CP_EXCL_SET_ASN
-- @TBL_NAME_AT: CP_EXCL_SET_ASN_AT
-- @TBL_DISPLAY_ORDER: 18
CREATE TABLE "GUI_XMDM_LST"."CP_EXCL_SET_ASN" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT SCENARIO_CODE FROM GUI_XMDM_LST.SCENARIO_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CODE
  -- @LKP_SQL_VALUE: SCENARIO_CODE
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Counterparty Exclusion Set Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT COUNTERPARTY_EXCL_SET_CODE FROM GUI_XMDM_LST.CP_EXCL_SET_MSTR
  -- @LKP_SQL_LABEL: COUNTERPARTY_EXCL_SET_CODE
  -- @LKP_SQL_VALUE: COUNTERPARTY_EXCL_SET_CODE
  "COUNTERPARTY_EXCL_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CP_EXCL_SET_ASN" PRIMARY KEY ("SCENARIO_CODE", "COUNTERPARTY_EXCL_SET_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Counterparty Excl. Set Config
-- @TBL_GUI_NAME_SHORT: CP_EXCL_SET_CFG
-- @TBL_NAME_AT: CP_EXCL_SET_CFG_AT
-- @TBL_DISPLAY_ORDER: 17
CREATE TABLE "GUI_XMDM_LST"."CP_EXCL_SET_CFG" (
  -- @COL_GUI_NAME: Counterparty  Exclusion Set Code
  -- @COL_DESC: Unique Counterparty Exclusion Set Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT COUNTERPARTY_EXCL_SET_CODE FROM GUI_XMDM_LST.CP_EXCL_SET_MSTR
  -- @LKP_SQL_LABEL: COUNTERPARTY_EXCL_SET_CODE
  -- @LKP_SQL_VALUE: COUNTERPARTY_EXCL_SET_CODE
  "COUNTERPARTY_EXCL_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Aggregation Level Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'AGGREGATION_LEVEL' AND DOMAIN_CODE != 'ENTITY_GROUP' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "AGGREGATION_LEVEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Excluded Counterparty
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1:
  --   SELECT EM.ENTITY_MEMBER_CODE AS CP_CODE FROM CMS.F_CMS_ENTITY_MEMBER EM WHERE SYSDATE BETWEEN VALID_FROM AND VALID_TO UNION ALL SELECT GM.GROUP_MEMBER_CODE  AS CP_CODE FROM 
  --   CMS.F_CMS_GROUP_MEMBER GM WHERE sysdate between valid_from and valid_to ORDER BY 1 ASC
  -- @LKP_SQL_LABEL: CP_CODE
  -- @LKP_SQL_VALUE: CP_CODE
  "EXCLUDED_COUNTERPARTY" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CP_EXCL_SET_CFG" PRIMARY KEY ("COUNTERPARTY_EXCL_SET_CODE", "AGGREGATION_LEVEL_CODE", "EXCLUDED_COUNTERPARTY")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Counterparty Excl. Set Master
-- @TBL_GUI_NAME_SHORT: CP_EXCL_SET_MSTR
-- @TBL_NAME_AT: CP_EXCL_SET_MSTR_AT
-- @TBL_DISPLAY_ORDER: 16
CREATE TABLE "GUI_XMDM_LST"."CP_EXCL_SET_MSTR" (
  -- @COL_GUI_NAME: Counterparty Exclusion Set Code
  -- @COL_DESC: Unique Counterparty Exclusion Set Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "COUNTERPARTY_EXCL_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Counterparty  Exclusion Set Name
  -- @COL_DISPLAY_ORDER: 2
  "COUNTERPARTY_EXCL_SET_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Exclusion Purpose
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'EXCLUSION_PURPOSE' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "EXCLUSION_PURPOSE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 4
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CP_EXCL_SET_MSTR" PRIMARY KEY ("COUNTERPARTY_EXCL_SET_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."CST_GLOBAL_SCENARIOS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_GLOBAL_SCENARIOS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: CST MP Scale Factor
-- @TBL_GUI_NAME_SHORT: CST_MP_SCAL_FACTOR
-- @TBL_NAME_AT: CST_MP_SCAL_FACTOR_AT
-- @TBL_DISPLAY_ORDER: 37
CREATE TABLE "GUI_XMDM_LST"."CST_MP_SCAL_FACTOR" (
  -- @COL_GUI_NAME: CST Scenario Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT STRESSED_SCENARIO_ID FROM EUREX_LST.D_STA_SCENARIOMASTER WHERE SYSDATE BETWEEN VALID_FROM_BD AND VALID_TO_BD ORDER BY STRESSED_SCENARIO_ID
  -- @LKP_SQL_LABEL: STRESSED_SCENARIO_ID
  -- @LKP_SQL_VALUE: STRESSED_SCENARIO_ID
  "CST_SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: MP Scale Factor
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: #.##
  "MP_SCALING_FACTOR" NUMBER,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_MP_SCAL_FACTOR" PRIMARY KEY ("CST_SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Global CST Scenario Group Config
-- @TBL_GUI_NAME_SHORT: CST_SCEN_GROUP_CFG
-- @TBL_NAME_AT: CST_SCEN_GROUP_CFG_AT
-- @TBL_DISPLAY_ORDER: 15
CREATE TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_CFG" (
  -- @COL_GUI_NAME: CST Global Scenario Group Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT CST_GBL_SCENARIO_GROUP_CODE FROM GUI_XMDM_LST.CST_SCEN_GROUP_MSTR
  -- @LKP_SQL_LABEL: CST_GBL_SCENARIO_GROUP_CODE
  -- @LKP_SQL_VALUE: CST_GBL_SCENARIO_GROUP_CODE
  "CST_GBL_SCENARIO_GROUP_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: CST Gobal Scenario Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT STRESSED_SCENARIO_ID FROM EUREX_LST.D_STA_SCENARIOMASTER WHERE SYSDATE BETWEEN VALID_FROM_BD AND VALID_TO_BD ORDER BY STRESSED_SCENARIO_ID
  -- @LKP_SQL_LABEL: STRESSED_SCENARIO_ID
  -- @LKP_SQL_VALUE: STRESSED_SCENARIO_ID
  "CST_GOBAL_SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_SCEN_GROUP_CFG" PRIMARY KEY ("CST_GBL_SCENARIO_GROUP_CODE", "CST_GOBAL_SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Global CST Scenario Group Master
-- @TBL_GUI_NAME_SHORT: CST_SCEN_GROUP_MSTR
-- @TBL_NAME_AT: CST_SCEN_GROUP_MSTR_AT
-- @TBL_DISPLAY_ORDER: 14
CREATE TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_MSTR" (
  -- @COL_GUI_NAME: CST Global Scenario Group Code
  -- @COL_DESC: Unique CST Global Scenario Group Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CST_GBL_SCENARIO_GROUP_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: CST Global Scenario Group Name
  -- @COL_DISPLAY_ORDER: 2
  "CST_GBL_SCENARIO_GROUP_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_SCEN_GROUP_MSTR" PRIMARY KEY ("CST_GBL_SCENARIO_GROUP_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."CTRPARTY_EXCL_SETS_CONFIG" (
  "CTRPARTY_EXCLUSION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "MEMBERS" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CTRPARTY_EXCL_SETS_CONFIG" PRIMARY KEY ("CTRPARTY_EXCLUSION_SET", "MEMBERS", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Currency Priority
-- @TBL_GUI_NAME_SHORT: CURRENCY_PRIORITY
-- @TBL_NAME_AT: CURRENCY_PRIORITY_AT
-- @TBL_DISPLAY_ORDER: 31
CREATE TABLE "GUI_XMDM_LST"."CURRENCY_PRIORITY" (
  -- @COL_GUI_NAME: Currency Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_CODE FROM GUI_XMDM_LST.CURRENCY_PRIORITY ORDER BY CURRENCY_CODE
  -- @LKP_SQL_LABEL: CURRENCY_CODE
  -- @LKP_SQL_VALUE: CURRENCY_CODE
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Priority
  -- @COL_DESC: Priority the currency has in the scenario calculation, only processing priority no further business logic is based on this priorisation
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0000
  "PRIORITY" NUMBER(4, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CURRENCY_PRIORITY" PRIMARY KEY ("CURRENCY_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Currency Sets Config
-- @TBL_GUI_NAME_SHORT: CURRENCY_SET_CFG
-- @TBL_NAME_AT: CURRENCY_SET_CFG_AT
-- @TBL_DISPLAY_ORDER: 30
CREATE TABLE "GUI_XMDM_LST"."CURRENCY_SET_CFG" (
  -- @COL_GUI_NAME: Currency Set Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT CURRENCY_SET_CODE FROM GUI_XMDM_LST.CURRENCY_SET_MSTR
  -- @LKP_SQL_LABEL: CURRENCY_SET_CODE
  -- @LKP_SQL_VALUE: CURRENCY_SET_CODE
  "CURRENCY_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_CODE FROM GUI_XMDM_LST.CURRENCY_PRIORITY ORDER BY CURRENCY_CODE
  -- @LKP_SQL_LABEL: CURRENCY_CODE
  -- @LKP_SQL_VALUE: CURRENCY_CODE
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CURRENCY_SET_CFG" PRIMARY KEY ("CURRENCY_SET_CODE", "CURRENCY_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Currency Set Master
-- @TBL_GUI_NAME_SHORT: CURRENCY_SET_MSTR
-- @TBL_NAME_AT: CURRENCY_SET_MSTR_AT
-- @TBL_DISPLAY_ORDER: 29
CREATE TABLE "GUI_XMDM_LST"."CURRENCY_SET_MSTR" (
  -- @COL_GUI_NAME: Currency Set Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CURRENCY_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency Set Name
  -- @COL_DISPLAY_ORDER: 2
  "CURRENCY_SET_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CURRENCY_SET_MSTR" PRIMARY KEY ("CURRENCY_SET_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Data Quality Aborts
-- @TBL_GUI_NAME_SHORT: DQA_ABORTS
-- @TBL_NAME_AT: DQA_ABORTS_AT
-- @TBL_DISPLAY_ORDER: 39
CREATE TABLE "GUI_XMDM_LST"."DQA_ABORTS" (
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Fact date for failed DQ
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: yyyy-MM-dd
  "FACT_DATE" DATE NOT NULL,
  -- @COL_GUI_NAME: Instruction
  -- @COL_DESC: Instruction on what to do next
  -- @COL_DISPLAY_ORDER: 2
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'DQA_INSTRUCTIONS'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "INSTRUCTION" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Analysis Result
  -- @COL_DESC: Reason for what to be done next
  -- @COL_DISPLAY_ORDER: 3
  "ANALYSIS_RESULT" VARCHAR2(1000 BYTE),
  CONSTRAINT "PK_LST_DQA_ABORTS" PRIMARY KEY ("FACT_DATE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Config
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_CFG
-- @TBL_NAME_AT: FLOW_TYPE_CFG_AT
-- @TBL_DISPLAY_ORDER: 12
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_CFG" (
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE WHERE ACTIVE_FLAG = 'Y' ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Component Code
  -- @COL_DISPLAY_ORDER: 2
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_COMPONENT' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_COMPONENT_CODE" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Flow Type Group Code
  -- @COL_DESC: Flow Type Group is used as grouping of cash flows types to groups and input to the scenario calculation module
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'FLOW_TYPE_GROUP' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "FLOW_TYPE_GROUP_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Component Code
  -- @COL_DESC: Flow Type Component is used as grouping of cash flows types to define the cash flows that should be considered in the LST scenarios. Which flow type components have to be considered in a scenario is configured in tab "Flow Type Component Assign"
  -- @COL_DISPLAY_ORDER: 4
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_COMPONENT_CODE FROM GUI_XMDM_LST.FLOW_TYPE_COMP_MSTR
  -- @LKP_SQL_LABEL: FLOW_TYPE_COMPONENT_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_COMPONENT_CODE
  "FLOW_TYPE_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Reporting Component Code - Receive
  -- @COL_DESC: Reporting Component Code is used for  reporting purposes only. The Reporting Component depends on the direction of the position. Direction = CCP view.
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT REPORTING_COMPONENT_CODE FROM GUI_XMDM_LST.REPORTING_COMP_MSTR
  -- @LKP_SQL_LABEL: REPORTING_COMPONENT_CODE
  -- @LKP_SQL_VALUE: REPORTING_COMPONENT_CODE
  "REPORT_COMPONENT_CODE_RECEIVE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Reporting Component Code - Deliver
  -- @COL_DESC: Reporting Component Code is used for  reporting purposes only. The Reporting Component depends on the direction of the position. Direction = CCP view.
  -- @COL_DISPLAY_ORDER: 6
  -- @LKP_SQL_STMT1: SELECT REPORTING_COMPONENT_CODE FROM GUI_XMDM_LST.REPORTING_COMP_MSTR
  -- @LKP_SQL_LABEL: REPORTING_COMPONENT_CODE
  -- @LKP_SQL_VALUE: REPORTING_COMPONENT_CODE
  "REPORT_COMPONENT_CODE_DELIVER" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: ESMA Flow Type
  -- @COL_DESC: Cash Flow grouping like needed in ESMA stress testing exercises
  -- @COL_DISPLAY_ORDER: 7
  "ESMA_FLOW_TYPE" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Allowed Usage  Code
  -- @COL_DESC: Allowed usage is input to the selection of relevant positions (sources)
  -- @COL_DISPLAY_ORDER: 8
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'ALLOWED_USAGE' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "ALLOWED_USAGE_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_CFG" PRIMARY KEY ("FLOW_TYPE_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Component Assign
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_COMP
-- @TBL_NAME_AT: FLOW_TYPE_COMP_AT
-- @TBL_DISPLAY_ORDER: 13
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT SCENARIO_CODE FROM GUI_XMDM_LST.SCENARIO_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CODE
  -- @LKP_SQL_VALUE: SCENARIO_CODE
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Component Assign.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_COMPONENT_CODE FROM GUI_XMDM_LST.FLOW_TYPE_COMP_MSTR
  -- @LKP_SQL_LABEL: FLOW_TYPE_COMPONENT_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_COMPONENT_CODE
  "FLOW_TYPE_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_COMP" PRIMARY KEY ("SCENARIO_CODE", "FLOW_TYPE_COMPONENT_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Component Master
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_COMP_MSTR
-- @TBL_NAME_AT: FLOW_TYPE_COMP_MSTR_AT
-- @TBL_DISPLAY_ORDER: 10
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP_MSTR" (
  -- @COL_GUI_NAME: Flow Type Component Code
  -- @COL_DESC: Unique Flow Type Component Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "FLOW_TYPE_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Component Name
  -- @COL_DESC: Flow Type Component  Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "FLOW_TYPE_COMPONENT_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_COMP_MSTR" PRIMARY KEY ("FLOW_TYPE_COMPONENT_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Group Config
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_GROUP_CFG
-- @TBL_NAME_AT: FLOW_TYPE_GROUP_CFG_AT
-- @TBL_DISPLAY_ORDER: 36
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_CFG" (
  -- @COL_GUI_NAME: Flow Type Reporting Group Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT FLOW_TYPE_REP_GROUP_CODE FROM GUI_XMDM_LST.FLOW_TYPE_REP_GROUP_MASTER
  -- @LKP_SQL_LABEL: FLOW_TYPE_REP_GROUP_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_REP_GROUP_CODE
  "FLOW_TYPE_REP_GROUP_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Group Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT FLOW_TYPE_GROUP_CODE FROM GUI_XMDM_LST.FLOW_TYPE_GROUP_MASTER
  -- @LKP_SQL_LABEL: FLOW_TYPE_GROUP_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_GROUP_CODE
  "FLOW_TYPE_GROUP_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE WHERE ACTIVE_FLAG = 'Y' ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_GROUP_CFG" PRIMARY KEY ("FLOW_TYPE_REP_GROUP_CODE", "FLOW_TYPE_GROUP_CODE", "FLOW_TYPE_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Group Master
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_GROUP_MASTER
-- @TBL_NAME_AT: FLOW_TYPE_GROUP_MASTER_AT
-- @TBL_DISPLAY_ORDER: 35
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_MASTER" (
  -- @COL_GUI_NAME: Flow Type Group Code
  -- @COL_DESC: Unique Flow Type Group Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "FLOW_TYPE_GROUP_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Group Name
  -- @COL_DESC: Flow Type Group Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "FLOW_TYPE_GROUP_NAME" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Group Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_LOW_TYPE_GROUP_MASTER" PRIMARY KEY ("FLOW_TYPE_GROUP_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Rep. Group Master
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_REP_GROUP_MASTER
-- @TBL_NAME_AT: FLOW_TYPE_REP_GROUP_MASTER_AT
-- @TBL_DISPLAY_ORDER: 34
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_REP_GROUP_MASTER" (
  -- @COL_GUI_NAME: Flow Type Reporting Group Code
  -- @COL_DESC: Unique Flow Type Reporting Group Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "FLOW_TYPE_REP_GROUP_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Reporting Group Name
  -- @COL_DESC: Flow Type Reporting Group Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "FLOW_TYPE_REP_GROUP_NAME" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Reporting Group Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_REP_GROUP_MASTER" PRIMARY KEY ("FLOW_TYPE_REP_GROUP_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Flow Type Scale Factors
-- @TBL_GUI_NAME_SHORT: FLOW_TYPE_SCALE_FACT
-- @TBL_NAME_AT: FLOW_TYPE_SCALE_FACT_AT
-- @TBL_DISPLAY_ORDER: 32
CREATE TABLE "GUI_XMDM_LST"."FLOW_TYPE_SCALE_FACT" (
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE  WHERE ACTIVE_FLAG = 'Y' ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Holding Period
  -- @COL_DESC: NOTE: Holding period only for information. This field is not used in any backend process
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0
  "HOLDING_PERIOD" NUMBER(2, 0) NOT NULL,
  -- @COL_GUI_NAME: Weight_T0
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T0" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T1
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T1" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T2
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T2" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T3
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T3" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T4
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T4" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T5
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T5" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T6
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T6" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T7
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T7" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Weight_T>7
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: 0.0000
  "WEIGHT_T_GRT_7" NUMBER(5, 4) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_FLOW_TYPE_SCALE_FACT" PRIMARY KEY ("FLOW_TYPE_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."GLOBAL_CST_SCENARIO_CONFIG" (
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_PURPOSE" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_COUNT" NUMBER(4, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_GLOBAL_CST_SCENARIO_CONFIG" PRIMARY KEY ("CST_GLOBAL_SCENARIO_GROUPING", "SCENARIO_PURPOSE", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."LST_MASTER_DATA" (
  "LST_MASTER_DATA_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "CALCULATION_PRIORITY" NUMBER,
  "CALCULATION_FREQUENCY" VARCHAR2(50 BYTE) NOT NULL,
  "ACTIVE_FLAG" CHAR(1 BYTE) NOT NULL,
  "NO_OF_FAILED_COUNTERPARTS" NUMBER(4, 0) NOT NULL,
  "COUNTERPARTY_GROUP" VARCHAR2(50 BYTE),
  "TIME_HORIZON" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_LST_MASTER_DATA" PRIMARY KEY ("LST_MASTER_DATA_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOBILIZATION_SETS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS_CONFIG" (
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILISATION_LAG" NUMBER(4, 0) NOT NULL,
  "CALCULATION_LOGIC" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOBILIZATION_SETS_CONFIG" PRIMARY KEY ("MOBILIZATION_SET", "COMPONENT", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Channel Config (legacy)
-- @TBL_GUI_NAME_SHORT: MOB_CHANNEL_CFG
-- @TBL_NAME_AT: MOB_CHANNEL_CFG_AT
-- @TBL_DISPLAY_ORDER: 41
CREATE TABLE "GUI_XMDM_LST"."MOB_CHANNEL_CFG" (
  -- @COL_GUI_NAME: Mobilization Channel Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_CHANNEL' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_CHANNEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Basket Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_BASKET' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_BASKET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Currency Code
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_CODE FROM GUI_XMDM_LST.CURRENCY_PRIORITY ORDER BY CURRENCY_CODE
  -- @LKP_SQL_LABEL: CURRENCY_CODE
  -- @LKP_SQL_VALUE: CURRENCY_CODE
  "MOBILIZATION_CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency View Code
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CURRENCY_VIEW' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CURRENCY_VIEW_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Capacity in bn - T0
  -- @COL_DESC: Please fill even if no capacity is available (0 instead of NULL)
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.000
  "CAPACITY_IN_BN_T0" NUMBER(7, 3),
  -- @COL_GUI_NAME: Capacity in bn - T1
  -- @COL_DESC: Please fill even if no capacity is available (0 instead of NULL)
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.000
  "CAPACITY_IN_BN_T1" NUMBER(7, 3),
  -- @COL_GUI_NAME: Capacity in bn - T1
  -- @COL_DESC: Please fill even if no capacity is available (0 instead of NULL)
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.000
  "CAPACITY_IN_BN_T_GRT_1" NUMBER(7, 3),
  -- @COL_GUI_NAME: Haircut
  -- @COL_DESC: 0=0% and 1=100%
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.00
  "HAIRCUT" NUMBER(3, 2),
  -- @COL_GUI_NAME: Cross-Currency Haircut
  -- @COL_DESC: 0=0% and 1=100%
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00
  "CROSS_CURRENCY_HAIRCUT" NUMBER(3, 2) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_CHANNEL_CFG" PRIMARY KEY ("MOBILIZATION_CHANNEL_CODE", "MOBILIZATION_BASKET_CODE", "MOBILIZATION_CURRENCY_CODE", "CURRENCY_VIEW_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Channel to Flow Type Assign
-- @TBL_GUI_NAME_SHORT: MOB_CHANNEL_FLOW_TYPE_ASN
-- @TBL_NAME_AT: MOB_CHANNEL_FLOW_TYPE_ASN_AT
-- @TBL_DISPLAY_ORDER: 22
CREATE TABLE "GUI_XMDM_LST"."MOB_CHANNEL_FLOW_TYPE_ASN" (
  -- @COL_GUI_NAME: Mobilization Channel Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOB_CHANNEL_CODE FROM GUI_XMDM_LST.MOB_CHANNEL_MSTR
  -- @LKP_SQL_LABEL: MOB_CHANNEL_CODE
  -- @LKP_SQL_VALUE: MOB_CHANNEL_CODE
  "MOB_CHANNEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_CHANNEL_FLOW_TYPE_ASN" PRIMARY KEY ("MOB_CHANNEL_CODE", "FLOW_TYPE_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Channel Master
-- @TBL_GUI_NAME_SHORT: MOB_CHANNEL_MSTR
-- @TBL_NAME_AT: MOB_CHANNEL_MSTR_AT
-- @TBL_DISPLAY_ORDER: 21
CREATE TABLE "GUI_XMDM_LST"."MOB_CHANNEL_MSTR" (
  -- @COL_GUI_NAME: Mobilization Channel Code
  -- @COL_DESC: Unique mobilization channel  code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MOB_CHANNEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Channel Name
  -- @COL_DESC: Mobilization Channel Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "MOB_CHANNEL_NAME" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Instrument Quality Code
  -- @COL_DESC: Instrument quality that is mobilizable via the mobilization channel, possible qualities are maintained in backend table D_OBJ_LST_DOMAIN_VALUES
  -- @COL_DISPLAY_ORDER: 4
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'INSTRUMENT_QUALITY'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "INSTRUMENT_QLTY_CODE" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Mobilization Haircut Method Code
  -- @COL_DESC: Mobilization Haircut method to be applied for this  mobilization channel, possible qualities are maintained in backend table D_OBJ_LST_DOMAIN_VALUES
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOB_HAIRCUT_METHOD'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOB_HAIRCUT_METHOD_CODE" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Mobilization Channel Type Code
  -- @COL_DESC: Grouping of mobilization channels into different types for reporting purposes only. Mobilization channels type code as defined in tab "Mobilization Channel Type Master"
  -- @COL_DISPLAY_ORDER: 6
  -- @LKP_SQL_STMT1: SELECT MOB_CHANNEL_TYPE_CODE FROM GUI_XMDM_LST.MOB_CHANNEL_TYPE_MSTR
  -- @LKP_SQL_LABEL: MOB_CHANNEL_TYPE_CODE
  -- @LKP_SQL_VALUE: MOB_CHANNEL_TYPE_CODE
  "MOB_CHANNEL_TYPE_CODE" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_LST_MOB_CHANNEL_MSTR" PRIMARY KEY ("MOB_CHANNEL_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Channel Type Master
-- @TBL_GUI_NAME_SHORT: MOB_CHANNEL_TYPE_MSTR
-- @TBL_NAME_AT: MOB_CHANNEL_TYPE_MSTR_AT
-- @TBL_DISPLAY_ORDER: 20
CREATE TABLE "GUI_XMDM_LST"."MOB_CHANNEL_TYPE_MSTR" (
  -- @COL_GUI_NAME: Mobilization Channel Type Code
  -- @COL_DESC: Unique mobilization channel type code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MOB_CHANNEL_TYPE_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Channel Type Name
  -- @COL_DESC: Mobilization Channel Type Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "MOB_CHANNEL_TYPE_NAME" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_CHANNEL_TYPE_MSTR" PRIMARY KEY ("MOB_CHANNEL_TYPE_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Factor Set Config
-- @TBL_GUI_NAME_SHORT: MOB_FACTOR_SET_CONF
-- @TBL_NAME_AT: MOB_FACTOR_SET_CONF_AT
-- @TBL_DISPLAY_ORDER: 26
CREATE TABLE "GUI_XMDM_LST"."MOB_FACTOR_SET_CONF" (
  -- @COL_GUI_NAME: Mobilization Factor Set Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_FACTOR_SET_CODE FROM GUI_XMDM_LST.MOB_FACTOR_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_FACTOR_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_FACTOR_SET_CODE
  "MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE WHERE LEG_TYPE IN  ('CS', 'S')
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilisation Factor
  -- @COL_DESC: 0=0% and 1=100%
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.00
  "MOBILISATION_FACTOR" NUMBER(3, 2) NOT NULL,
  -- @COL_GUI_NAME: Currency Code
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_CODE FROM GUI_XMDM_LST.CURRENCY_PRIORITY ORDER BY CURRENCY_CODE
  -- @LKP_SQL_LABEL: CURRENCY_CODE
  -- @LKP_SQL_VALUE: CURRENCY_CODE
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_FACTOR_SET_CONF" PRIMARY KEY ("MOBILIZATION_FACTOR_SET_CODE", "FLOW_TYPE_CODE", "CURRENCY_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Factor Set Master
-- @TBL_GUI_NAME_SHORT: MOB_FACTOR_SET_MSTR
-- @TBL_NAME_AT: MOB_FACTOR_SET_MSTR_AT
-- @TBL_DISPLAY_ORDER: 25
CREATE TABLE "GUI_XMDM_LST"."MOB_FACTOR_SET_MSTR" (
  -- @COL_GUI_NAME: Mobilization Factor Set Code
  -- @COL_DESC: Unique Mobilization Factor Set Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Factor Set Name
  -- @COL_DESC: Name as to be shown in reports.
  -- @COL_DISPLAY_ORDER: 2
  "MOBILIZATION_FACTOR_SET_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_FACTOR_SET_MSTR" PRIMARY KEY ("MOBILIZATION_FACTOR_SET_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Jurisdictions
-- @TBL_GUI_NAME_SHORT: MOB_JURISDICTIONS
-- @TBL_NAME_AT: MOB_JURISDICTIONS_AT
-- @TBL_DISPLAY_ORDER: 27
CREATE TABLE "GUI_XMDM_LST"."MOB_JURISDICTIONS" (
  -- @COL_GUI_NAME: CMS Region Code
  -- @COL_DESC: CMS Region Code as maintained in Cesar GUI.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CMS_REGION_CODE" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 2
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_JURISDICTIONS" PRIMARY KEY ("CMS_REGION_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Sets Config (legacy)
-- @TBL_GUI_NAME_SHORT: MOB_SET_CFG
-- @TBL_NAME_AT: MOB_SET_CFG_AT
-- @TBL_DISPLAY_ORDER: 40
CREATE TABLE "GUI_XMDM_LST"."MOB_SET_CFG" (
  -- @COL_GUI_NAME: Mobilization Set Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_SET_CODE FROM GUI_XMDM_LST.MOB_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_SET_CODE
  "MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Component Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_COMPONENT' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Lag
  -- @COL_DISPLAY_ORDER: 3
  "MOBILIZATION_LAG" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Calculation Logic Code
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_CALCULATION_LOGIC' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_CALC_LOGIC_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Channel Code
  -- @COL_DESC: IF calculation logic 'MOBILIZATION_FACTORS' is selected, categories may not be filled. The mobilzatipn channels are configures in tab ""Mobilization Channel Config.""."
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_CHANNEL' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_CHANNEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Factor Set Code
  -- @COL_DESC: IF calculation logic BASKET_CAPACITIES 'is selected, categories may not be filled. The Mobilization Factor Set are configures in ""Mobilization Factor Set Config.""."
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_FACTOR_SET_CODE From GUI_XMDM_LST.MOB_FACTOR_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_FACTOR_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_FACTOR_SET_CODE
  "MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_SET_CFG" PRIMARY KEY ("MOBILIZATION_SET_CODE", "MOBILIZATION_COMPONENT_CODE", "MOBILIZATION_CALC_LOGIC_CODE", "MOBILIZATION_CHANNEL_CODE", "MOBILIZATION_FACTOR_SET_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Set Config - Channels
-- @TBL_GUI_NAME_SHORT: MOB_SET_CFG_CHANNEL
-- @TBL_NAME_AT: MOB_SET_CFG_CHANNEL_AT
-- @TBL_DISPLAY_ORDER: 23
CREATE TABLE "GUI_XMDM_LST"."MOB_SET_CFG_CHANNEL" (
  -- @COL_GUI_NAME: Mobilization Set Code
  -- @COL_DESC: Mobilization set code as defined in tab "Mobilization Set Master"
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_SET_CODE FROM GUI_XMDM_LST.MOB_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_SET_CODE
  "MOB_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Channel Code
  -- @COL_DESC: Mobilization channel code as defined in tab "Mobilization Channel Master"
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOB_CHANNEL_CODE FROM GUI_XMDM_LST.MOB_CHANNEL_MSTR
  -- @LKP_SQL_LABEL: MOB_CHANNEL_CODE
  -- @LKP_SQL_VALUE: MOB_CHANNEL_CODE
  "MOB_CHANNEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Currency
  -- @COL_DESC: Currency into which the securities can be mobilized in the respective mobilization channel
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_CODE FROM GUI_XMDM_LST.CURRENCY_PRIORITY ORDER BY CURRENCY_CODE
  -- @LKP_SQL_LABEL: CURRENCY_CODE
  -- @LKP_SQL_VALUE: CURRENCY_CODE
  "MOB_CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Amount
  -- @COL_DESC: Maximum amount that can be mobilized via the channel in the respective currency. For "unlimited" amounts please enter 999999999999999.
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "MOB_AMOUNT" NUMBER,
  -- @COL_GUI_NAME: EURagg view Relevant Indicator
  -- @COL_DESC: Indicator X to be set if this channel in the respective currency should be considered in the calculation of EURagg view scenarios and empty if not.
  -- @COL_DISPLAY_ORDER: 5
  "EURAGG_RI" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Mobilization Start Date No
  -- @COL_DESC: Earliest Settlement Date No(as integer) to indicate from which day in the forecast horizon the channel in resp. currency is available for mob. activities, e.g. 0 if it is available already on the first day after the stress event(member default).
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0
  "MOB_START_DATE_NO" NUMBER,
  -- @COL_GUI_NAME: Waterfall Order No
  -- @COL_DESC: Order in which the different mobilization channels should be assessed / utilized.
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0
  "WATERFALL_ORDER_NO" NUMBER,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_SET_CFG_CHANNEL" PRIMARY KEY ("MOB_SET_CODE", "MOB_CHANNEL_CODE", "MOB_CURRENCY")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Set Config - Components
-- @TBL_GUI_NAME_SHORT: MOB_SET_CFG_COMPONENTS
-- @TBL_NAME_AT: MOB_SET_CFG_COMPONENTS_AT
-- @TBL_DISPLAY_ORDER: 24
CREATE TABLE "GUI_XMDM_LST"."MOB_SET_CFG_COMPONENTS" (
  -- @COL_GUI_NAME: Mobilization Set Code
  -- @COL_DESC: Mobilization set code as defined in tab "Mobilization Set Master"
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_SET_CODE FROM GUI_XMDM_LST.MOB_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_SET_CODE
  "MOB_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Component Code
  -- @COL_DESC: Mobilization component, possible Mobilization component are maintained in backend table D_OBJ_LST_DOMAIN_VALUES. These components represent the different sources of mobilizable securities, e.g. deal securities, Investment collateral, etc.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_COMPONENT'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOB_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Lag
  -- @COL_DESC: Integer (e.g. 0,1,2,..). This Mobilization Lag is used in cases some securities as assumed to be not available for refinance activities immediately, but delayed.
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "MOB_LAG" NUMBER,
  -- @COL_GUI_NAME: Mobilization Priority
  -- @COL_DESC: Ranking that indicates the order in which the Mobilization Components should be processes. In case no clear mobilization order is needed within a mobilization set code, all values to be set to 1.
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "MOB_PRIORITY" NUMBER,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOB_SET_CFG_COMPONENTS" PRIMARY KEY ("MOB_SET_CODE", "MOB_COMPONENT_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Mobilization Set Master
-- @TBL_GUI_NAME_SHORT: MOB_SET_MSTR
-- @TBL_NAME_AT: MOB_SET_MSTR_AT
-- @TBL_DISPLAY_ORDER: 19
CREATE TABLE "GUI_XMDM_LST"."MOB_SET_MSTR" (
  -- @COL_GUI_NAME: Mobilization Set Code
  -- @COL_DESC: Unique Mobilization Set Code. Please avoid any "blanks" or special characters in the code. \nA mobilization set is assigned to a scenario in tab "Set and Rule Assign".
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Set Name
  -- @COL_DISPLAY_ORDER: 2
  "MOBILIZATION_SET_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- @COL_GUI_NAME: Mobilization Calculation Logic Code
  -- @COL_DISPLAY_ORDER: 4
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'MOBILIZATION_CALCULATION_LOGIC' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "MOBILIZATION_CALC_LOGIC_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL,
  -- @COL_GUI_NAME: Mobilization Factor Set Code
  -- @COL_DESC: IF calculation logic BASKET_CAPACITIES is selected, categories may not be filled. The Mobilization Factor Set are configures in "Mobilization Factor Set Config".
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_FACTOR_SET_CODE From GUI_XMDM_LST.MOB_FACTOR_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_FACTOR_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_FACTOR_SET_CODE
  "MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL,
  CONSTRAINT "PK_MOB_SET_MSTR" PRIMARY KEY ("MOBILIZATION_SET_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Other LST Components
-- @TBL_GUI_NAME_SHORT: OTHER_LST_COMPONENTS
-- @TBL_NAME_AT: OTHER_LST_COMPONENTS_AT
-- @TBL_DISPLAY_ORDER: 33
CREATE TABLE "GUI_XMDM_LST"."OTHER_LST_COMPONENTS" (
  -- @COL_GUI_NAME: Flow Type Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE  WHERE ACTIVE_FLAG = 'Y' ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency View Code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CURRENCY_VIEW' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CURRENCY_VIEW_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Param Value Type Code
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'PARAMETER_VALUE_TYPE' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "PARAM_VALUE_TYPE_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Param Value Unit Code
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'PARAM_VALUE_UNIT' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "PARAM_VALUE_UNIT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency Code
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT ISO_ALPHA_CODE FROM DWH.D_CURRENCY ORDER BY ISO_ALPHA_CODE
  -- @LKP_SQL_LABEL: ISO_ALPHA_CODE
  -- @LKP_SQL_VALUE: ISO_ALPHA_CODE
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Value_T0
  -- @COL_DESC: Allowed Values 0-1, 0= 0%, 1= 100%.
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: #.####
  "VALUE_T0" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Value_T1
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: #.####
  "VALUE_T1" NUMBER,
  -- @COL_GUI_NAME: Value_T2
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: #.####
  "VALUE_T2" NUMBER,
  -- @COL_GUI_NAME: Value_T3
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: #.####
  "VALUE_T3" NUMBER,
  -- @COL_GUI_NAME: Value_T4
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: #.####
  "VALUE_T4" NUMBER,
  -- @COL_GUI_NAME: Value_T5
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: #.####
  "VALUE_T5" NUMBER,
  -- @COL_GUI_NAME: Value_T6
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: #.####
  "VALUE_T6" NUMBER,
  -- @COL_GUI_NAME: Value_T7
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_FORMAT: #.####
  "VALUE_T7" NUMBER,
  -- @COL_GUI_NAME: Value_T>7
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_FORMAT: #.####
  "VALUE_T_GRT_7" NUMBER(11, 2),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_OTHER_LST_COMPONENTS" PRIMARY KEY ("FLOW_TYPE_CODE", "CURRENCY_VIEW_CODE", "PARAM_VALUE_TYPE_CODE", "PARAM_VALUE_UNIT_CODE", "CURRENCY_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: QA check Definition
-- @TBL_GUI_NAME_SHORT: QUALITY_CHECK_DEF
-- @TBL_NAME_AT: QUALITY_CHECK_DEF_AT
-- @TBL_DISPLAY_ORDER: 38
CREATE TABLE "GUI_XMDM_LST"."QUALITY_CHECK_DEF" (
  -- @COL_GUI_NAME: Check Id
  -- @COL_DESC: Unique Id of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "CHECK_ID" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Check Code
  -- @COL_DESC: Name of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 2
  "CHECK_CODE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Check Type
  -- @COL_DESC: Type of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'DQA_CHECK_TYPE'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CHECK_TYPE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Check Table
  -- @COL_DESC: Table used for Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 4
  "CHECK_TABLE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Result Value Descr
  -- @COL_DESC: Detail of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 5
  "RESULT_VALUE_DESCR" VARCHAR2(1000 BYTE),
  -- @COL_GUI_NAME: Check Period
  -- @COL_DESC: Period of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 6
  "CHECK_PERIOD" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Check Description
  -- @COL_DESC: Description of Quality Assurance Check
  -- @COL_DISPLAY_ORDER: 7
  "CHECK_DESCRIPTION" VARCHAR2(4000 BYTE),
  -- @COL_GUI_NAME: Info Limit Abs
  -- @COL_DESC: Absolute Info Limit
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: #.##
  "INFO_LIMIT_ABS" NUMBER,
  -- @COL_GUI_NAME: Info Limit Rel
  -- @COL_DESC: Relative Info Limit
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: #.##
  "INFO_LIMIT_REL" NUMBER,
  -- @COL_GUI_NAME: Warning Limit Abs
  -- @COL_DESC: Warning Limit Absolute
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: #.##
  "WARNING_LIMIT_ABS" NUMBER,
  -- @COL_GUI_NAME: Warning Limit Rel
  -- @COL_DESC: Warning Limit Relative
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: #.##
  "WARNING_LIMIT_REL" NUMBER,
  -- @COL_GUI_NAME: Abort Limit Abs
  -- @COL_DESC: Abort Limit Absolute
  -- @COL_DISPLAY_ORDER: 12
  -- @COL_FORMAT: #.##
  "ABORT_LIMIT_ABS" NUMBER,
  -- @COL_GUI_NAME: Abort Limit Rel
  -- @COL_DESC: Abort Limit Relative
  -- @COL_DISPLAY_ORDER: 13
  -- @COL_FORMAT: #.##
  "ABORT_LIMIT_REL" NUMBER,
  -- @COL_GUI_NAME: QA Run Def Id
  -- @COL_DESC: Quality Assurance Run Id
  -- @COL_DISPLAY_ORDER: 14
  -- @COL_FORMAT: #
  -- @LKP_SQL_STMT1: SELECT QA_RUN_DEF_ID FROM EUREX_LST.ETL_LST_QUALITY_RUN_DEF
  -- @LKP_SQL_LABEL: QA_RUN_DEF_ID
  -- @LKP_SQL_VALUE: QA_RUN_DEF_ID
  "QA_RUN_DEF_ID" NUMBER,
  -- @COL_GUI_NAME: Source Database
  -- @COL_DESC: Source Database
  -- @COL_DISPLAY_ORDER: 15
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'DQA_SOURCE_DATABASE'
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "SOURCE_DATABASE" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Active FLag
  -- @COL_DESC: Flag to activate / deactivate the calculation of a scenario without deletion of the scenario
  -- @COL_DISPLAY_ORDER: 16
  "ACTIVE_FLAG" CHAR(1 BYTE),
  CONSTRAINT "PK_LST_QA_DEF" PRIMARY KEY ("CHECK_ID")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."REFINANCING_FACTORS" (
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "REFINANCING_FACTOR" NUMBER(3, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_REFINANCING_FACTORS" PRIMARY KEY ("FLOW_TYPE", "REFINANCING_FACTOR", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Reporting Component Master
-- @TBL_GUI_NAME_SHORT: REPORTING_COMP_MSTR
-- @TBL_NAME_AT: REPORTING_COMP_MSTR_AT
-- @TBL_DISPLAY_ORDER: 11
CREATE TABLE "GUI_XMDM_LST"."REPORTING_COMP_MSTR" (
  -- @COL_GUI_NAME: Flow Type Component Code
  -- @COL_DESC: Unique Flow Type Component Code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "REPORTING_COMPONENT_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type Component Name
  -- @COL_DESC: Flow Type Component  Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "REPORTING_COMPONENT_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- @COL_GUI_NAME: Reporting Order No
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: #
  "REPORTING_ORDER_NO" NUMBER,
  CONSTRAINT "PK_REPORTING_COMP_MSTR" PRIMARY KEY ("REPORTING_COMPONENT_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_CLASS" (
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS_DESC" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCENARIO_CLASS" PRIMARY KEY ("LST_SCENARIO_CLASS", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Scenario Class Master
-- @TBL_GUI_NAME_SHORT: SCENARIO_CLASS_MASTER
-- @TBL_NAME_AT: SCENARIO_CLASS_MASTER_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_CLASS_MASTER" (
  -- @COL_GUI_NAME: Scenario Class
  -- @COL_DESC: NOTE: please don't use any special characters and separators (e.g. "," or ";")
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Class Description
  -- @COL_DISPLAY_ORDER: 2
  "SCENARIO_CLASS_DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCENARIO_CLASS_MASTER" PRIMARY KEY ("SCENARIO_CLASS")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Scenario Group Master
-- @TBL_GUI_NAME_SHORT: SCENARIO_GROUP_MASTER
-- @TBL_NAME_AT: SCENARIO_GROUP_MASTER_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_GROUP_MASTER" (
  -- @COL_GUI_NAME: Scenario Group Code
  -- @COL_DESC: NOTE: please don't use any special characters and separators (e.g. "," or ";")
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_GROUP_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Group Name
  -- @COL_DESC: Scenario Group Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "SCENARIO_GROUP_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Scenario Group Code Description
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCENARIO_GROUP_MASTER" PRIMARY KEY ("SCENARIO_GROUP_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: LST Scenario Master
-- @TBL_GUI_NAME_SHORT: SCENARIO_MASTER
-- @TBL_NAME_AT: SCENARIO_MASTER_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_MASTER" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DESC: Unique liquidity stress testing scenario code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Name
  -- @COL_DESC: Scenario Name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "SCENARIO_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Class
  -- @COL_DESC: Scenario Class as defined in tab "Scenario Classes"
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DISTINCT SCENARIO_CLASS FROM GUI_XMDM_LST.SCENARIO_CLASS_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CLASS
  -- @LKP_SQL_VALUE: SCENARIO_CLASS
  "SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Type
  -- @COL_DESC: Scenario Type as defined in tab "Scenario Type"
  -- @COL_DISPLAY_ORDER: 4
  -- @LKP_SQL_STMT1: SELECT DISTINCT SCENARIO_TYPE FROM GUI_XMDM_LST.SCENARIO_TYPE_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_TYPE
  -- @LKP_SQL_VALUE: SCENARIO_TYPE
  "SCENARIO_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Calculation Priority
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CALCULATION_PRIORITY' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CALCULATION_PRIORITY" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Calculation Frequency
  -- @COL_DISPLAY_ORDER: 7
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CALCULATION_FREQUENCY' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CALCULATION_FREQUENCY" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Active FLag
  -- @COL_DESC: Flag to activate / deactivate the calculation of a scenario without deletion of the scenario
  -- @COL_DISPLAY_ORDER: 8
  "ACTIVE_FLAG" CHAR(1 BYTE) NOT NULL,
  -- @COL_GUI_NAME: No. of "failed" counterparts
  -- @COL_DESC: NOTE: As of now  the backend process can only calculate  the "failure" of 0, 1 or 2 counterparts.
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0
  "NO_OF_FAILED_COUNTERPARTS" NUMBER(4, 0) NOT NULL,
  -- @COL_GUI_NAME: Counterparty Group
  -- @COL_DESC:
  --   NOTE: This is only a descriptive field and changes to this field don't change the backend calculation.
  --   To change the backend calculation the counterparty configuration data in tabs "Counterparty Set" and "Counterparty Role" have to be changed.
  -- @COL_DISPLAY_ORDER: 10
  "COUNTERPARTY_GROUP" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Time Horizon
  -- @COL_DESC: Future cash flows dates to be considered in the scenario. 0 = next clearing day
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: 0
  "TIME_HORIZON" NUMBER(4, 0) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- @COL_GUI_NAME: Scenario Group
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT DISTINCT SCENARIO_GROUP_CODE FROM GUI_XMDM_LST.SCENARIO_GROUP_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_GROUP_CODE
  -- @LKP_SQL_VALUE: SCENARIO_GROUP_CODE
  "SCENARIO_GROUP_CODE" VARCHAR2(50 BYTE),
  CONSTRAINT "PK_LST_SCENARIO_MASTER" PRIMARY KEY ("SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Scenario Type Master
-- @TBL_GUI_NAME_SHORT: SCENARIO_TYPE_MASTER
-- @TBL_NAME_AT: SCENARIO_TYPE_MASTER_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_TYPE_MASTER" (
  -- @COL_GUI_NAME: Scenario Type
  -- @COL_DESC: NOTE: please don't use any special characters and separators (e.g. "," or ";")
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Scenario Type Description
  -- @COL_DISPLAY_ORDER: 2
  "SCENARIO_TYPE_DESCRIPTION" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCENARIO_TYPE_MASTER" PRIMARY KEY ("SCENARIO_TYPE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Set and Rule Assign
-- @TBL_GUI_NAME_SHORT: SET_RULE_ASN
-- @TBL_NAME_AT: SET_RULE_ASN_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_LST"."SET_RULE_ASN" (
  -- @COL_GUI_NAME: Scenario Code
  -- @COL_DESC: Unique liquidity stress testing scenario code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT SCENARIO_CODE FROM GUI_XMDM_LST.SCENARIO_MASTER
  -- @LKP_SQL_LABEL: SCENARIO_CODE
  -- @LKP_SQL_VALUE: SCENARIO_CODE
  "SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Time Factor Set Code
  -- @COL_DISPLAY_ORDER: 2
  -- @LKP_SQL_STMT1: SELECT DISTINCT TIME_FACTOR_SET_CODE FROM GUI_XMDM_LST.TIME_FACTOR_SET_MASTER
  -- @LKP_SQL_LABEL: TIME_FACTOR_SET_CODE
  -- @LKP_SQL_VALUE: TIME_FACTOR_SET_CODE
  "TIME_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Aggregation Level Code
  -- @COL_DISPLAY_ORDER: 3
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE  FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'AGGREGATION_LEVEL' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "AGGREGATION_LEVEL_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: CST Global Scenario Group Code
  -- @COL_DESC: CST Scenario grouping as defined in tab "Global CST Scenario Config"
  -- @COL_DISPLAY_ORDER: 4
  -- @LKP_SQL_STMT1: SELECT CST_GBL_SCENARIO_GROUP_CODE FROM GUI_XMDM_LST.CST_SCEN_GROUP_MSTR
  -- @LKP_SQL_LABEL: CST_GBL_SCENARIO_GROUP_CODE
  -- @LKP_SQL_VALUE: CST_GBL_SCENARIO_GROUP_CODE
  "CST_GBL_SCENARIO_GROUP_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Mobilization Set Code
  -- @COL_DISPLAY_ORDER: 5
  -- @LKP_SQL_STMT1: SELECT MOBILIZATION_SET_CODE FROM GUI_XMDM_LST.MOB_SET_MSTR
  -- @LKP_SQL_LABEL: MOBILIZATION_SET_CODE
  -- @LKP_SQL_VALUE: MOBILIZATION_SET_CODE
  "MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE),
  -- @COL_GUI_NAME: Currency Conversion Rule Code
  -- @COL_DISPLAY_ORDER: 6
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CURRENCY_CONVERSION_RULE' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CURRENCY_CONVERSION_RULE_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency Set Code
  -- @COL_DISPLAY_ORDER: 7
  -- @LKP_SQL_STMT1: SELECT DISTINCT CURRENCY_SET_CODE FROM GUI_XMDM_LST.CURRENCY_SET_MSTR
  -- @LKP_SQL_LABEL: CURRENCY_SET_CODE
  -- @LKP_SQL_VALUE: CURRENCY_SET_CODE
  "CURRENCY_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Currency View Code
  -- @COL_DISPLAY_ORDER: 8
  -- @LKP_SQL_STMT1: SELECT DOMAIN_CODE FROM EUREX_LST.D_OBJ_LST_DOMAIN_VALUES WHERE DOMAIN = 'CURRENCY_VIEW' AND ACTIVE_FLAG = 'Y' ORDER BY GUI_ORDER_NO, DOMAIN_CODE
  -- @LKP_SQL_LABEL: DOMAIN_CODE
  -- @LKP_SQL_VALUE: DOMAIN_CODE
  "CURRENCY_VIEW_CODE" VARCHAR2(256 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_LST_SET_RULE_ASN" PRIMARY KEY ("SCENARIO_CODE")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "SET_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SETS" PRIMARY KEY ("TIME_FACTOR_SET", "VALID_FROM")
) TABLESPACE XMDM_FACT;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS_CONFIG" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "FROM_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TO_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR" NUMBER(8, 5),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SETS_CONFIG" PRIMARY KEY ("TIME_FACTOR_SET", "FLOW_TYPE", "VALID_FROM")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Time Factor Set Config
-- @TBL_GUI_NAME_SHORT: TIME_FACTOR_SET_CONFIG
-- @TBL_NAME_AT: TIME_FACTOR_SET_CONFIG_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SET_CONFIG" (
  -- @COL_GUI_NAME: Time Factor Set Code
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT TIME_FACTOR_SET_CODE FROM GUI_XMDM_LST.TIME_FACTOR_SET_MASTER
  -- @LKP_SQL_LABEL: TIME_FACTOR_SET_CODE
  -- @LKP_SQL_VALUE: TIME_FACTOR_SET_CODE
  "TIME_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Flow Type code
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @LKP_SQL_STMT1: SELECT DISTINCT FLOW_TYPE_CODE FROM EUREX_LST.D_DOM_LST_FLOW_TYPE WHERE ACTIVE_FLAG = 'Y' ORDER BY FLOW_TYPE_CODE
  -- @LKP_SQL_LABEL: FLOW_TYPE_CODE
  -- @LKP_SQL_VALUE: FLOW_TYPE_CODE
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 0
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.00000
  "STL_DATE_0" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 1
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.00000
  "STL_DATE_1" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 2
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0.00000
  "STL_DATE_2" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 3
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: 0.00000
  "STL_DATE_3" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 4
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: 0.00000
  "STL_DATE_4" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 5
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: 0.00000
  "STL_DATE_5" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 6
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: 0.00000
  "STL_DATE_6" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE 7
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: 0.00000
  "STL_DATE_7" NUMBER(8, 5) NOT NULL,
  -- @COL_GUI_NAME: STL_DATE > 7
  -- @COL_DESC: Possible values: 0 - 100 with up to 5 decimals
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: 0.00000
  "STL_DATE_GRT_7" NUMBER(8, 5) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SET_CONFIG" PRIMARY KEY ("TIME_FACTOR_SET_CODE", "FLOW_TYPE_CODE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Time Factor Set Master
-- @TBL_GUI_NAME_SHORT: TIME_FACTOR_SET_MASTER
-- @TBL_NAME_AT: TIME_FACTOR_SET_MASTER_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SET_MASTER" (
  -- @COL_GUI_NAME: Time Factor Set Code
  -- @COL_DESC: Unique time factor set code. Please avoid any "blanks" or special characters in the code.
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TIME_FACTOR_SET_CODE" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Time Factor Set Name
  -- @COL_DESC: Time factor set name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 2
  "TIME_FACTOR_SET_NAME" VARCHAR2(256 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Description
  -- @COL_DESC: Time factor set name (as to be shown in reports)
  -- @COL_DISPLAY_ORDER: 3
  "DESCRIPTION" VARCHAR2(256 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SET_MASTER" PRIMARY KEY ("TIME_FACTOR_SET_CODE")
) TABLESPACE XMDM_FACT;