-- @TBL_GUI_NAME: Member Groups
-- @TBL_GUI_NAME_SHORT: Member Groups
-- @TBL_NAME_AT: MEMBER_GROUPS_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."MEMBER_GROUPS" (
  -- @COL_GUI_NAME: Member Group
  -- @COL_DESC: Member Group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "MEMBER_GROUP" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Member
  -- @COL_DESC: Member
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MEMBER" VARCHAR2(100 BYTE),
  -- @COL_GUI_NAME: Member ID
  -- @COL_DESC: Member ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_ID" VARCHAR2(5 BYTE),
  -- @COL_GUI_NAME: Valid From
  -- @COL_DESC: Valid From
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "VALID_FROM" DATE,
  -- @COL_GUI_NAME: Valid To
  -- @COL_DESC: Valid To
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  "VALID_TO" DATE,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: TakeUp Member Lists
-- @TBL_GUI_NAME_SHORT: TakeUp Member Lists
-- @TBL_NAME_AT: TAKEUP_MEMBER_LISTS_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."TAKEUP_MEMBER_LISTS" (
  -- @COL_GUI_NAME: TakeUp List
  -- @COL_DESC: TakeUp List
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "TKLIST" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Member ID TakeUp
  -- @COL_DESC: Member ID TakeUp
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "MEMBER_ID_TAKEUP" VARCHAR2(5 BYTE),
  -- @COL_GUI_NAME: Member ID Traded
  -- @COL_DESC: Member ID Traded
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "MEMBER_ID_TRADED" VARCHAR2(5 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: TakeUp Member Lists to Scenario
-- @TBL_GUI_NAME_SHORT: TakeUp Member Lists to Scenario
-- @TBL_NAME_AT: TKUP_MEMBERLST_SCN_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."TKUP_MEMBERLST_SCN_ASSIGNM" (
  -- @COL_GUI_NAME: Scenario Name
  -- @COL_DESC: Scenario Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Start Date
  -- @COL_DESC: Start Date
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "START_DATE" DATE,
  -- @COL_GUI_NAME: End Date
  -- @COL_DESC: End Date
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: dd.MM.yyyy
  "END_DATE" DATE,
  -- @COL_GUI_NAME: TakeUp List
  -- @COL_DESC: TakeUp List
  -- @COL_DISPLAY_ORDER: 4
  "TKLIST" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Remarks
  -- @COL_DESC: Remarks
  -- @COL_DISPLAY_ORDER: 5
  "REMARKS" VARCHAR2(150 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: VR Definitions
-- @TBL_GUI_NAME_SHORT: VR Definitions
-- @TBL_NAME_AT: VR_DEFINITIONS_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEFINITIONS" (
  -- @COL_GUI_NAME: VR Definition
  -- @COL_DESC: VR Definition
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "VRDEF" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Template
  -- @COL_DESC: Template
  -- @COL_DISPLAY_ORDER: 2
  "TEMPLATE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Violations
  -- @COL_DESC: Violations
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: #
  "VIOLATIONS" NUMBER(*, 0),
  -- @COL_GUI_NAME: Comments
  -- @COL_DESC: Comments
  -- @COL_DISPLAY_ORDER: 4
  "COMMENTS" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: Assignment VRDEF to Price List
-- @TBL_GUI_NAME_SHORT: Assignment VRDEF to Price List
-- @TBL_NAME_AT: VR_DEF_PRICE_LIST_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEF_PRICE_LIST_ASSIGNM" (
  -- @COL_GUI_NAME: VR List
  -- @COL_DESC: VR List
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "VRLIST" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Join ID
  -- @COL_DESC: Join ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: #
  "JOIN_ID" NUMBER(*, 0),
  -- @COL_GUI_NAME: Service
  -- @COL_DESC: Service
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "SERVICE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Route
  -- @COL_DESC: Route
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  "ROUTE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Package ID
  -- @COL_DESC: Package ID
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "PACKAGE_ID" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Account Type
  -- @COL_DESC: Account Type
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  "ACCOUNTTYPE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Execution Type
  -- @COL_DESC: Execution Type
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  "EXECTYPE" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: M + P
  -- @COL_DESC: M + P
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: #
  "M_PLUS_P" NUMBER(*, 0),
  -- @COL_GUI_NAME: Blended
  -- @COL_DESC: Blended
  -- @COL_DISPLAY_ORDER: 9
  -- @COL_FORMAT: #
  "BLENDED" NUMBER(*, 0),
  -- @COL_GUI_NAME: Overall Threshold
  -- @COL_DESC: Overall Threshold
  -- @COL_DISPLAY_ORDER: 10
  -- @COL_FORMAT: #
  "OVERALL_THRESHOLD" NUMBER(*, 0),
  -- @COL_GUI_NAME: No Member Circle
  -- @COL_DESC: No Member Circle
  -- @COL_DISPLAY_ORDER: 11
  -- @COL_FORMAT: #
  "NO_MEMBER_CIRCLE" NUMBER(*, 0),
  -- @COL_GUI_NAME: Member Group
  -- @COL_DESC: Member Group
  -- @COL_DISPLAY_ORDER: 12
  "MEMBER_GROUP" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: VR Definition
  -- @COL_DESC: VR Definition
  -- @COL_DISPLAY_ORDER: 13
  "VRDEF" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: VR Lists
-- @TBL_GUI_NAME_SHORT: VR Lists
-- @TBL_NAME_AT: VR_LISTS_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."VR_LISTS" (
  -- @COL_GUI_NAME: VR List
  -- @COL_DESC: VR List
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "VRLIST" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Remarks
  -- @COL_DESC: Remarks
  -- @COL_DISPLAY_ORDER: 2
  "REMARKS" VARCHAR2(150 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: VR List to Scenario Assign
-- @TBL_GUI_NAME_SHORT: VR List to Scenario Assign
-- @TBL_NAME_AT: VR_LIST_SCN_ASSIGNM_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."VR_LIST_SCN_ASSIGNM" (
  -- @COL_GUI_NAME: Scenario Name
  -- @COL_DESC: Scenario Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "SCENARIO_NAME" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Priority
  -- @COL_DESC: Priority
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: #
  "PRIORITY" NUMBER(*, 0),
  -- @COL_GUI_NAME: Start Date
  -- @COL_DESC: Start Date
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "START_DATE" DATE,
  -- @COL_GUI_NAME: End Date
  -- @COL_DESC: End Date
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "END_DATE" DATE,
  -- @COL_GUI_NAME: Exclude IPS
  -- @COL_DESC: Exclude IPS
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: #
  "EXCLUDE_IPS" NUMBER(*, 0),
  -- @COL_GUI_NAME: VR list
  -- @COL_DESC: VR list
  -- @COL_DISPLAY_ORDER: 6
  "VRLIST" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: VR Rebates
-- @TBL_GUI_NAME_SHORT: VR Rebates
-- @TBL_NAME_AT: VR_REBATES_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_EPS_REBATES_V"."VR_REBATES" (
  -- @COL_GUI_NAME: VR Definition
  -- @COL_DESC: VR Definition
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "VRDEF" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Pricing Group
  -- @COL_DESC: Pricing Group
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "PRICING_GROUP" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Band
  -- @COL_DESC: Band
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  "BAND" VARCHAR2(50 BYTE),
  -- @COL_GUI_NAME: Threshold
  -- @COL_DESC: Threshold
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: #
  "THRESHOLD" NUMBER(*, 0),
  -- @COL_GUI_NAME: Rebate
  -- @COL_DESC: Rebate
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: #
  "REBATE" NUMBER(*, 0),
  -- @COL_GUI_NAME: Package Rebate
  -- @COL_DESC: Package Rebate
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_FORMAT: #
  "PACKAGE_REBATE" NUMBER(*, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;