-- @TBL_GUI_NAME: NDF_CURRENCY
-- @TBL_GUI_NAME_SHORT: NDF_CURRENCY
-- @TBL_NAME_AT: NDF_CURRENCY_AT
-- @TBL_DISPLAY_ORDER: 6
CREATE TABLE "GUI_XMDM_NDF"."NDF_CURRENCY" (
  -- @COL_GUI_NAME: Currency name
  -- @COL_DESC: Currency name
  -- @COL_PK: Y
  "CURRENCY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: NDF_REPORT_APPROVAL
-- @TBL_GUI_NAME_SHORT: NDF_REPORT_APPROVAL
-- @TBL_NAME_AT: NDF_REPORT_APPROVAL_AT
-- @TBL_DISPLAY_ORDER: 7
CREATE TABLE "GUI_XMDM_NDF"."NDF_REPORT_APPROVAL" (
  -- @COL_GUI_NAME: Out of bounds variations
  -- @COL_DESC: Out of bounds variations
  -- @COL_DISPLAY_ORDER: 1
  "OUT_OF_BOUNDS_VARIATIONS" VARCHAR2(4000 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Fact Date
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_NDF_REPORT_APPROVAL" PRIMARY KEY ("FACT_DATE")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: PEGGING_INDICATOR
-- @TBL_GUI_NAME_SHORT: PEGGING_INDICATOR
-- @TBL_NAME_AT: PEGGING_INDICATOR_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "GUI_XMDM_NDF"."PEGGING_INDICATOR" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier if the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Pegging Value
  -- @COL_DESC: Pegging value per currency.
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "PEGGING_VALUE" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Date to be set by operations unit when they amend the value
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PEGGING_INDICATOR" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: POLITICAL_STABILITY_INDEX
-- @TBL_GUI_NAME_SHORT: POLITICAL_STABILITY_INDEX
-- @TBL_NAME_AT: POLITICAL_STABILITY_INDEX_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "GUI_XMDM_NDF"."POLITICAL_STABILITY_INDEX" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier if the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: PSI Value
  -- @COL_DESC: Political Stability Index Values. Each value is between -2.5 (Worst) and +2.5 (Best).
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "PSI_VALUE" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Publishing date of the correspondiong report to map values to a date.
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_POLITICAL_STABILITY_INDEX" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: PRICE_SOURCE_DISRUPTION_INDICATOR
-- @TBL_GUI_NAME_SHORT: PRICE_SOURCE_DISRUPTION_IND
-- @TBL_NAME_AT: PRICE_SOURCE_DISRUPTION_IND_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "GUI_XMDM_NDF"."PRICE_SOURCE_DISRUPTION_IND" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier if the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: PSD Value
  -- @COL_DESC: PSD value per currency
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_VALIDATOR: de.deutsche_boerse.statistix.xmdm.validators.RegexColumnValidator:^[yY]|^[Nn]
  "PSD_VALUE" CHAR(1 BYTE),
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Date to be set by operations unit when they amend the value
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PRICE_SOURCE_DISRUPTION_IND" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: SOVEREIGN_HEALTH_INDEX
-- @TBL_GUI_NAME_SHORT: SOVEREIGN_HEALTH_INDEX
-- @TBL_NAME_AT: SOVEREIGN_HEALTH_INDEX_AT
-- @TBL_DISPLAY_ORDER: 4
CREATE TABLE "GUI_XMDM_NDF"."SOVEREIGN_HEALTH_INDEX" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier if the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: SHI Value
  -- @COL_DESC: SHI value per currency
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "SHI_VALUE" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Date to be set by operations unit when they amend the value
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SOVEREIGN_HEALTH_INDEX" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: STRESS_SCENARIO
-- @TBL_GUI_NAME_SHORT: STRESS_SCENARIO
-- @TBL_NAME_AT: STRESS_SCENARIO_AT
-- @TBL_DISPLAY_ORDER: 8
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SCENARIO" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country.
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier of the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Stress Value Up
  -- @COL_DESC: Stress Value Up.
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "STRESS_VALUE_UP" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Stress Value Down
  -- @COL_DESC: Stress Value Down.
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0.0000
  "STRESS_VALUE_DOWN" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Publishing date of the corresponding report to map values to a date.
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STRESS_SCENARIO" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;
-- @TBL_GUI_NAME: STRESS_SHIFT_MUTIPLIER_NDF
-- @TBL_GUI_NAME_SHORT: STRESS_SHIFT_MUTIPLIER_NDF
-- @TBL_NAME_AT: STRESS_SHIFT_MUTIPLIER_NDF_AT
-- @TBL_DISPLAY_ORDER: 5
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SHIFT_MUTIPLIER_NDF" (
  -- @COL_GUI_NAME: Country Name
  -- @COL_DESC: Long name of the country
  -- @COL_DISPLAY_ORDER: 1
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Currency ID
  -- @COL_DESC: Currency identifier if the country.
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  -- @COL_GUI_NAME: Stress Shift Multiplier
  -- @COL_DESC: SHI value per currency
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0.0000
  "STRESS_SHIFT_MULTIPLIER" NUMBER(5, 4) NOT NULL,
  -- @COL_GUI_NAME: Fact Date
  -- @COL_DESC: Date to be set by operations unit when they amend the value.
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: dd.MM.yyyy
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STRESS_SHIFT_MUTIPLIER_NDF" PRIMARY KEY ("CURRENCY_ID")
) TABLESPACE XMDM_FACT;