CREATE TABLE "MDSYS"."NTV2_XML_DATA" (
  "NTV2_FILE_ID" NUMBER NOT NULL,
  "SEQUENCE_NUMBER" NUMBER NOT NULL,
  "XML" XMLTYPE NOT NULL,
  CONSTRAINT "NTV2_XML_DATA_PK" PRIMARY KEY ("NTV2_FILE_ID", "SEQUENCE_NUMBER")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."OGIS_GEOMETRY_COLUMNS" (
  "F_TABLE_SCHEMA" VARCHAR2(260 BYTE),
  "F_TABLE_NAME" VARCHAR2(260 BYTE),
  "F_GEOMETRY_COLUMN" VARCHAR2(260 BYTE),
  "G_TABLE_SCHEMA" VARCHAR2(260 BYTE),
  "G_TABLE_NAME" VARCHAR2(260 BYTE),
  "STORAGE_TYPE" NUMBER,
  "GEOMETRY_TYPE" NUMBER,
  "COORD_DIMENSION" NUMBER,
  "MAX_PPR" NUMBER,
  "SRID" NUMBER,
  CONSTRAINT "FK_SRID" FOREIGN KEY ("SRID") REFERENCES "OGIS_SPATIAL_REFERENCE_SYSTEMS"("SRID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."OGIS_SPATIAL_REFERENCE_SYSTEMS" (
  "SRID" NUMBER NOT NULL,
  "AUTH_NAME" VARCHAR2(128 BYTE),
  "AUTH_SRID" NUMBER,
  "SRTEXT" VARCHAR2(1000 BYTE),
  "SRNUM" NUMBER,
  CONSTRAINT "PK_SRID" PRIMARY KEY ("SRID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_AXES" (
  "COORD_SYS_ID" NUMBER(10, 0) NOT NULL,
  "COORD_AXIS_NAME_ID" NUMBER(10, 0),
  "COORD_AXIS_ORIENTATION" VARCHAR2(24 BYTE),
  "COORD_AXIS_ABBREVIATION" VARCHAR2(24 BYTE),
  "UOM_ID" NUMBER(10, 0),
  "ORDER" NUMBER(5, 0) NOT NULL,
  CONSTRAINT "COORD_AXIS_PRIM" PRIMARY KEY ("COORD_SYS_ID", "ORDER"),
  CONSTRAINT "COORD_AXIS_FOREIGN_AXIS" FOREIGN KEY ("COORD_AXIS_NAME_ID") REFERENCES "SDO_COORD_AXIS_NAMES"("COORD_AXIS_NAME_ID"),
  CONSTRAINT "COORD_AXIS_FOREIGN_CS" FOREIGN KEY ("COORD_SYS_ID") REFERENCES "SDO_COORD_SYS"("COORD_SYS_ID"),
  CONSTRAINT "COORD_AXIS_FOREIGN_UOM" FOREIGN KEY ("UOM_ID") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_AXIS_NAMES" (
  "COORD_AXIS_NAME_ID" NUMBER(10, 0) NOT NULL,
  "COORD_AXIS_NAME" VARCHAR2(80 BYTE) NOT NULL,
  CONSTRAINT "COORD_AXIS_NAME_PRIM" PRIMARY KEY ("COORD_AXIS_NAME_ID"),
  CONSTRAINT "SYS_C004606" UNIQUE ("COORD_AXIS_NAME")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OPS" (
  "COORD_OP_ID" NUMBER(10, 0) NOT NULL,
  "COORD_OP_NAME" VARCHAR2(80 BYTE),
  "COORD_OP_TYPE" VARCHAR2(24 BYTE),
  "SOURCE_SRID" NUMBER(10, 0),
  "TARGET_SRID" NUMBER(10, 0),
  "COORD_TFM_VERSION" VARCHAR2(24 BYTE),
  "COORD_OP_VARIANT" NUMBER(5, 0),
  "COORD_OP_METHOD_ID" NUMBER(10, 0),
  "UOM_ID_SOURCE_OFFSETS" NUMBER(10, 0),
  "UOM_ID_TARGET_OFFSETS" NUMBER(10, 0),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "SHOW_OPERATION" NUMBER(3, 0) NOT NULL,
  "IS_LEGACY" VARCHAR2(5 BYTE) NOT NULL,
  "LEGACY_CODE" NUMBER(10, 0),
  "REVERSE_OP" NUMBER(1, 0),
  "IS_IMPLEMENTED_FORWARD" NUMBER(1, 0),
  "IS_IMPLEMENTED_REVERSE" NUMBER(1, 0),
  CONSTRAINT "COORD_OP_PRIM" PRIMARY KEY ("COORD_OP_ID"),
  CONSTRAINT "COORD_OPERATION_FOREIGN_LEGACY" FOREIGN KEY ("LEGACY_CODE") REFERENCES "SDO_COORD_OPS"("COORD_OP_ID"),
  CONSTRAINT "COORD_OPERATION_FOREIGN_METHOD" FOREIGN KEY ("COORD_OP_METHOD_ID") REFERENCES "SDO_COORD_OP_METHODS"("COORD_OP_METHOD_ID"),
  CONSTRAINT "COORD_OPERATION_FOREIGN_SOURCE" FOREIGN KEY ("SOURCE_SRID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_OPERATION_FOREIGN_TARGET" FOREIGN KEY ("TARGET_SRID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_OP_NAME_UNIQUE" UNIQUE ("COORD_OP_NAME"),
  CONSTRAINT "COORD_OP_ID_MUST_BE_POS" CHECK (COORD_OP_ID > 10),
  CONSTRAINT "COORD_OP_VARIANT_MUST_BE_POS" CHECK (COORD_OP_VARIANT > 0),
  CONSTRAINT "COORD_OP_NAME_NO_LEGACY_NAME" CHECK (
          COORD_OP_NAME NOT IN (
            'Geographic (Lat/Long)',
            'Universal Transverse Mercator',
            'State Plane Coordinates',
            'Albers Conical Equal Area',
            'Lambert Conformal Conic',
            'Mercator',
            'Polar Stereographic',
            'Polyconic',
            'Equidistant Conic',
            'Transverse Mercator',
            'Stereographic',
            'Lambert Azimuthal Equal Area',
            'Azimuthal Equidistant',
            'Gnomonic',
            'Orthographic',
            'General Vertical Near-Side Perspective',
            'Sinusoidal',
            'Equirectangular',
            'Miller Cylindrical',
            'Van der Grinten',
            'Hotine Oblique Mercator',
            'Robinson',
            'Space Oblique Mercator',
            'Alaska Conformal',
            'Interrupted Goode Homolosine',
            'Mollweide',
            'Interrupted Mollweide',
            'Hammer',
            'Wagner IV',
            'Wagner VII',
            'Oblated Equal Area',
            'Non-earth',
            'Transverse Mercator Danish System 45 Bornholm',
            'Transverse Mercator Danish System 34 Jylland-Fyn',
            'Transverse Mercator Sjaelland',
            'Transverse Mercator Finnish KKJ',
            'Eckert IV',
            'Eckert VI',
            'Gall',
            'Lambert Conformal Conic (Belgium 1972)',
            'New Zealand Map Grid',
            'Cylindrical Equal Area',
            'Swiss Oblique Mercator',
            'Bonne',
            'Cassini'))
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OP_METHODS" (
  "COORD_OP_METHOD_ID" NUMBER(10, 0) NOT NULL,
  "COORD_OP_METHOD_NAME" VARCHAR2(50 BYTE),
  "LEGACY_NAME" VARCHAR2(50 BYTE) DEFAULT NULL,
  "REVERSE_OP" NUMBER(1, 0) NOT NULL,
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "IS_IMPLEMENTED_FORWARD" NUMBER(1, 0) NOT NULL,
  "IS_IMPLEMENTED_REVERSE" NUMBER(1, 0) NOT NULL,
  CONSTRAINT "COORD_OP_METHOD_PRIM" PRIMARY KEY ("COORD_OP_METHOD_ID"),
  CONSTRAINT "COORD_OP_METHOD_ID_MUST_BE_POS" CHECK (COORD_OP_METHOD_ID > 0),
  CONSTRAINT "REVERSE_OP_1_OR_0" CHECK (REVERSE_OP IN (0, 1)),
  CONSTRAINT "IS_IMPL_FW_1_OR_0" CHECK (IS_IMPLEMENTED_FORWARD IN (0, 1)),
  CONSTRAINT "IS_IMPL_RV_1_OR_0" CHECK (IS_IMPLEMENTED_REVERSE IN (0, 1))
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OP_PARAMS" (
  "PARAMETER_ID" NUMBER(10, 0) NOT NULL,
  "PARAMETER_NAME" VARCHAR2(80 BYTE),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "UNIT_OF_MEAS_TYPE" VARCHAR2(50 BYTE),
  CONSTRAINT "COORD_OP_PARA_PRIM" PRIMARY KEY ("PARAMETER_ID"),
  CONSTRAINT "PARAMETER_ID_MUST_BE_POS" CHECK (PARAMETER_ID > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OP_PARAM_USE" (
  "COORD_OP_METHOD_ID" NUMBER(10, 0) NOT NULL,
  "PARAMETER_ID" NUMBER(10, 0),
  "LEGACY_PARAM_NAME" VARCHAR2(80 BYTE) DEFAULT NULL,
  "SORT_ORDER" NUMBER(5, 0) NOT NULL,
  "PARAM_SIGN_REVERSAL" VARCHAR2(3 BYTE),
  CONSTRAINT "COORD_OP_PARA_USE_PRIM" PRIMARY KEY ("COORD_OP_METHOD_ID", "SORT_ORDER"),
  CONSTRAINT "COORD_OP_PARA_USE_FOREIGN_METH" FOREIGN KEY ("COORD_OP_METHOD_ID") REFERENCES "SDO_COORD_OP_METHODS"("COORD_OP_METHOD_ID"),
  CONSTRAINT "COORD_OP_PARA_USE_FOREIGN_PARA" FOREIGN KEY ("PARAMETER_ID") REFERENCES "SDO_COORD_OP_PARAMS"("PARAMETER_ID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OP_PARAM_VALS" (
  "COORD_OP_ID" NUMBER(10, 0) NOT NULL,
  "COORD_OP_METHOD_ID" NUMBER(10, 0),
  "PARAMETER_ID" NUMBER(10, 0) NOT NULL,
  "PARAMETER_VALUE" NUMBER(49),
  "PARAM_VALUE_FILE_REF" VARCHAR2(254 BYTE),
  "PARAM_VALUE_FILE" CLOB DEFAULT NULL,
  "PARAM_VALUE_XML" XMLTYPE GENERATED ALWAYS AS (NULL),
  "UOM_ID" NUMBER(10, 0),
  CONSTRAINT "COORD_OP_PARA_VAL_PRIM" PRIMARY KEY ("COORD_OP_ID", "PARAMETER_ID"),
  CONSTRAINT "COORD_OP_PARA_VAL_FOREIGN_METH" FOREIGN KEY ("COORD_OP_METHOD_ID") REFERENCES "SDO_COORD_OP_METHODS"("COORD_OP_METHOD_ID"),
  CONSTRAINT "COORD_OP_PARA_VAL_FOREIGN_OP" FOREIGN KEY ("COORD_OP_ID") REFERENCES "SDO_COORD_OPS"("COORD_OP_ID"),
  CONSTRAINT "COORD_OP_PARA_VAL_FOREIGN_PARA" FOREIGN KEY ("PARAMETER_ID") REFERENCES "SDO_COORD_OP_PARAMS"("PARAMETER_ID"),
  CONSTRAINT "COORD_OP_PARA_VAL_FOREIGN_UOM" FOREIGN KEY ("UOM_ID") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_OP_PATHS" (
  "CONCAT_OPERATION_ID" NUMBER(10, 0) NOT NULL,
  "SINGLE_OPERATION_ID" NUMBER(10, 0),
  "SINGLE_OP_SOURCE_ID" NUMBER(10, 0),
  "SINGLE_OP_TARGET_ID" NUMBER(10, 0),
  "OP_PATH_STEP" NUMBER(5, 0),
  CONSTRAINT "COORD_OP_PATH_FOREIGN_SOURCE" FOREIGN KEY ("SINGLE_OP_SOURCE_ID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_OP_PATH_FOREIGN_TARGET" FOREIGN KEY ("SINGLE_OP_TARGET_ID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "CONCAT_OP_ID_MUST_BE_POS" CHECK (CONCAT_OPERATION_ID > 10),
  CONSTRAINT "OP_PATH_STEP_MUST_BE_POS" CHECK (OP_PATH_STEP > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_REF_SYS" (
  "SRID" NUMBER(10, 0) NOT NULL,
  "COORD_REF_SYS_NAME" VARCHAR2(80 BYTE) NOT NULL,
  "COORD_REF_SYS_KIND" VARCHAR2(24 BYTE) NOT NULL,
  "COORD_SYS_ID" NUMBER(10, 0),
  "DATUM_ID" NUMBER(10, 0),
  "GEOG_CRS_DATUM_ID" NUMBER(10, 0),
  "SOURCE_GEOG_SRID" NUMBER(10, 0),
  "PROJECTION_CONV_ID" NUMBER(10, 0),
  "CMPD_HORIZ_SRID" NUMBER(10, 0),
  "CMPD_VERT_SRID" NUMBER(10, 0),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "IS_LEGACY" VARCHAR2(5 BYTE) NOT NULL,
  "LEGACY_CODE" NUMBER(10, 0),
  "LEGACY_WKTEXT" VARCHAR2(2046 BYTE),
  "LEGACY_CS_BOUNDS" VARCHAR2(1 BYTE),
  "IS_VALID" VARCHAR2(5 BYTE) DEFAULT 'TRUE',
  "SUPPORTS_SDO_GEOMETRY" VARCHAR2(5 BYTE) DEFAULT 'TRUE',
  CONSTRAINT "COORD_REF_SYSTEM_PRIM" PRIMARY KEY ("SRID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_CS" FOREIGN KEY ("COORD_SYS_ID") REFERENCES "SDO_COORD_SYS"("COORD_SYS_ID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_DATUM" FOREIGN KEY ("DATUM_ID") REFERENCES "SDO_DATUMS"("DATUM_ID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_GEOG" FOREIGN KEY ("SOURCE_GEOG_SRID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_HORIZ" FOREIGN KEY ("CMPD_HORIZ_SRID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_LEGACY" FOREIGN KEY ("LEGACY_CODE") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_PROJ" FOREIGN KEY ("PROJECTION_CONV_ID") REFERENCES "SDO_COORD_OPS"("COORD_OP_ID"),
  CONSTRAINT "COORD_REF_SYS_FOREIGN_VERT" FOREIGN KEY ("CMPD_VERT_SRID") REFERENCES "SDO_COORD_REF_SYS"("SRID"),
  CONSTRAINT "SRID_MUST_BE_POS" CHECK (SRID > 0),
  CONSTRAINT "CRS_CHECK_ENGINEERING" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'ENGINEERING') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (NOT  DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_GEOCENTRIC" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'GEOCENTRIC') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (NOT  DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_GEOGRAPHIC2D" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'GEOGRAPHIC2D') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (NOT  DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_GEOGRAPHIC3D" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'GEOGRAPHIC3D') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (NOT  DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_PROJECTED" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'PROJECTED') OR
          (
            (NOT  SOURCE_GEOG_SRID    IS NULL) AND
            (NOT  PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (     DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_VERTICAL" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'VERTICAL') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (     CMPD_HORIZ_SRID     IS NULL) AND
            (     CMPD_VERT_SRID      IS NULL) AND
            (NOT  COORD_SYS_ID        IS NULL) AND
            (NOT  DATUM_ID            IS NULL) AND
            (NOT  GEOG_CRS_DATUM_ID   IS NULL)
          )
        ),
  CONSTRAINT "CRS_CHECK_COMPOUND" CHECK (
          (IS_VALID = 'FALSE') OR
          (IS_LEGACY = 'TRUE') OR
          (coord_ref_sys_kind <> 'COMPOUND') OR
          (
            (     SOURCE_GEOG_SRID    IS NULL) AND
            (     PROJECTION_CONV_ID  IS NULL) AND
            (NOT  CMPD_HORIZ_SRID     IS NULL) AND
            (NOT  CMPD_VERT_SRID      IS NULL) AND
            (     COORD_SYS_ID        IS NULL) AND
            (     DATUM_ID            IS NULL)
          )
        )
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_COORD_SYS" (
  "COORD_SYS_ID" NUMBER(10, 0) NOT NULL,
  "COORD_SYS_NAME" VARCHAR2(254 BYTE) NOT NULL,
  "COORD_SYS_TYPE" VARCHAR2(24 BYTE),
  "DIMENSION" NUMBER(5, 0),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(50 BYTE),
  CONSTRAINT "COORDINATE_SYSTEM_PRIM" PRIMARY KEY ("COORD_SYS_ID"),
  CONSTRAINT "SYS_C004604" UNIQUE ("COORD_SYS_NAME"),
  CONSTRAINT "COORD_SYS_ID_MUST_BE_POS" CHECK (COORD_SYS_ID > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_CRS_GEOGRAPHIC_PLUS_HEIGHT" (
  "SRID" NUMBER(10, 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_CS_CONTEXT_INFORMATION" (
  "FROM_SRID" NUMBER,
  "TO_SRID" NUMBER,
  "CONTEXT" RAW(4)
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_CS_SRS" (
  "CS_NAME" VARCHAR2(80 BYTE),
  "SRID" NUMBER(*, 0) NOT NULL,
  "AUTH_SRID" NUMBER(*, 0),
  "AUTH_NAME" VARCHAR2(256 BYTE),
  "WKTEXT" VARCHAR2(2046 BYTE),
  "CS_BOUNDS" VARCHAR2(1 BYTE),
  "WKTEXT3D" VARCHAR2(4000 BYTE),
  PRIMARY KEY ("SRID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_DATUMS" (
  "DATUM_ID" NUMBER(10, 0) NOT NULL,
  "DATUM_NAME" VARCHAR2(80 BYTE) NOT NULL,
  "DATUM_TYPE" VARCHAR2(24 BYTE),
  "ELLIPSOID_ID" NUMBER(10, 0),
  "PRIME_MERIDIAN_ID" NUMBER(10, 0),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "SHIFT_X" NUMBER,
  "SHIFT_Y" NUMBER,
  "SHIFT_Z" NUMBER,
  "ROTATE_X" NUMBER,
  "ROTATE_Y" NUMBER,
  "ROTATE_Z" NUMBER,
  "SCALE_ADJUST" NUMBER,
  "IS_LEGACY" VARCHAR2(5 BYTE) NOT NULL,
  "LEGACY_CODE" NUMBER(10, 0),
  CONSTRAINT "DATUM_PRIM" PRIMARY KEY ("DATUM_ID"),
  CONSTRAINT "DATUM_FOREIGN_ELLIPSOID" FOREIGN KEY ("ELLIPSOID_ID") REFERENCES "SDO_ELLIPSOIDS"("ELLIPSOID_ID"),
  CONSTRAINT "DATUM_FOREIGN_LEGACY" FOREIGN KEY ("LEGACY_CODE") REFERENCES "SDO_DATUMS"("DATUM_ID"),
  CONSTRAINT "DATUM_FOREIGN_MERIDIAN" FOREIGN KEY ("PRIME_MERIDIAN_ID") REFERENCES "SDO_PRIME_MERIDIANS"("PRIME_MERIDIAN_ID"),
  CONSTRAINT "DATUM_ID_MUST_BE_POS" CHECK (DATUM_ID > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_DATUMS_OLD_SNAPSHOT" (
  "NAME" VARCHAR2(260 BYTE),
  "SHIFT_X" NUMBER,
  "SHIFT_Y" NUMBER,
  "SHIFT_Z" NUMBER,
  "ROTATE_X" NUMBER,
  "ROTATE_Y" NUMBER,
  "ROTATE_Z" NUMBER,
  "SCALE_ADJUST" NUMBER
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_DIST_METADATA_TABLE" (
  "SDO_INDEX_OWNER" VARCHAR2(130 BYTE) NOT NULL,
  "SDO_INDEX_NAME" VARCHAR2(130 BYTE) NOT NULL,
  "SDO_PARTITION_NAME" VARCHAR2(130 BYTE) NOT NULL,
  "TXNID" VARCHAR2(128 BYTE) NOT NULL,
  "SDO_TSNAME" VARCHAR2(130 BYTE),
  "SDO_TABLE_NAME" VARCHAR2(130 BYTE),
  "IS_GEODETIC" NUMBER,
  "DML_CHAR" NUMBER,
  "UNITFACTOR" NUMBER,
  "TOLERANCE" NUMBER,
  "LAYER_GTYPE" NUMBER,
  "LAYER_SRID" NUMBER,
  "INDX_DIMS" NUMBER,
  "DATA_DIMS" NUMBER,
  "INS_BB_START1" NUMBER,
  "INS_BB_END1" NUMBER,
  "INS_BB_START2" NUMBER,
  "INS_BB_END2" NUMBER,
  "INS_BB_START3" NUMBER,
  "INS_BB_END3" NUMBER,
  "INS_BB_START4" NUMBER,
  "INS_BB_END4" NUMBER,
  "DEL_BB_START1" NUMBER,
  "DEL_BB_END1" NUMBER,
  "DEL_BB_START2" NUMBER,
  "DEL_BB_END2" NUMBER,
  "DEL_BB_START3" NUMBER,
  "DEL_BB_END3" NUMBER,
  "DEL_BB_START4" NUMBER,
  "DEL_BB_END4" NUMBER,
  "INS_NO" NUMBER,
  "DEL_NO" NUMBER
) TABLESPACE SYSAUX INITRANS 255;
CREATE TABLE "MDSYS"."SDO_ELLIPSOIDS" (
  "ELLIPSOID_ID" NUMBER NOT NULL,
  "ELLIPSOID_NAME" VARCHAR2(80 BYTE) NOT NULL,
  "SEMI_MAJOR_AXIS" NUMBER,
  "UOM_ID" NUMBER,
  "INV_FLATTENING" NUMBER,
  "SEMI_MINOR_AXIS" NUMBER,
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "IS_LEGACY" VARCHAR2(5 BYTE) NOT NULL,
  "LEGACY_CODE" NUMBER,
  CONSTRAINT "ELLIPSOID_PRIM" PRIMARY KEY ("ELLIPSOID_ID"),
  CONSTRAINT "ELLIPSOID_FOREIGN_UOM" FOREIGN KEY ("UOM_ID") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID"),
  CONSTRAINT "ELLIPSOID_ID_MUST_BE_POS" CHECK (ELLIPSOID_ID > 0),
  CONSTRAINT "SEMI_MAJOR_AXIS_MUST_BE_POS" CHECK (SEMI_MAJOR_AXIS > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_ELLIPSOIDS_OLD_SNAPSHOT" (
  "NAME" VARCHAR2(260 BYTE),
  "SEMI_MAJOR_AXIS" NUMBER,
  "INVERSE_FLATTENING" NUMBER
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_FEATURE_USAGE" (
  "FEATURE_NAME" VARCHAR2(24 BYTE) NOT NULL,
  "USED" VARCHAR2(1 BYTE),
  "IS_SPATIAL" VARCHAR2(1 BYTE),
  PRIMARY KEY ("FEATURE_NAME")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_INDEX_HISTOGRAM_TABLE" (
  "SDO_INDEX_OBJNO" NUMBER,
  "BKT_ID" NUMBER,
  "NUM_MBRS" NUMBER,
  "START1" NUMBER,
  "END1" NUMBER,
  "AVGMBRLEN1" NUMBER,
  "START2" NUMBER,
  "END2" NUMBER,
  "AVGMBRLEN2" NUMBER,
  "START3" NUMBER,
  "END3" NUMBER,
  "AVGMBRLEN3" NUMBER
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_PREFERRED_OPS_SYSTEM" (
  "SOURCE_SRID" NUMBER(10, 0) NOT NULL,
  "COORD_OP_ID" NUMBER(10, 0) NOT NULL,
  "TARGET_SRID" NUMBER(10, 0) NOT NULL,
  CONSTRAINT "PREFERRED_OPS_SYS_PRIM" PRIMARY KEY ("SOURCE_SRID", "TARGET_SRID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_PREFERRED_OPS_USER" (
  "USE_CASE" VARCHAR2(32 BYTE) NOT NULL,
  "SOURCE_SRID" NUMBER(10, 0) NOT NULL,
  "COORD_OP_ID" NUMBER(10, 0) NOT NULL,
  "TARGET_SRID" NUMBER(10, 0) NOT NULL,
  CONSTRAINT "PREFERRED_OPS_USE_PRIM" PRIMARY KEY ("USE_CASE", "SOURCE_SRID", "TARGET_SRID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_PRIME_MERIDIANS" (
  "PRIME_MERIDIAN_ID" NUMBER(10, 0) NOT NULL,
  "PRIME_MERIDIAN_NAME" VARCHAR2(80 BYTE) NOT NULL,
  "GREENWICH_LONGITUDE" NUMBER(49),
  "UOM_ID" NUMBER(10, 0),
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(254 BYTE),
  CONSTRAINT "PRIME_MERIDIAN_PRIM" PRIMARY KEY ("PRIME_MERIDIAN_ID"),
  CONSTRAINT "PRIME_MERIDIAN_FOREIGN_UOM" FOREIGN KEY ("UOM_ID") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID"),
  CONSTRAINT "SYS_C004591" UNIQUE ("PRIME_MERIDIAN_NAME"),
  CONSTRAINT "PRIME_MERIDIAN_ID_MUST_BE_POS" CHECK (PRIME_MERIDIAN_ID > 0)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_PROJECTIONS_OLD_SNAPSHOT" (
  "NAME" VARCHAR2(64 BYTE)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_SRIDS_BY_URN" (
  "SRID" NUMBER NOT NULL,
  "URN" VARCHAR2(1000 BYTE) NOT NULL,
  PRIMARY KEY ("SRID"),
  CONSTRAINT "SYS_C002319471" UNIQUE ("URN")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_SRIDS_BY_URN_PATTERN" (
  "URN_PREFIX" VARCHAR2(1000 BYTE),
  "URN_POSTFIX" VARCHAR2(1000 BYTE)
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_ST_TOLERANCE" (
  "TOLERANCE" NUMBER
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TOPO_DATA$" (
  "TOPOLOGY" VARCHAR2(20 BYTE),
  "TG_LAYER_ID" NUMBER,
  "TG_ID" NUMBER,
  "TOPO_ID" NUMBER,
  "TOPO_TYPE" NUMBER
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TOPO_RELATION_DATA" (
  "TG_LAYER_ID" NUMBER,
  "TG_ID" NUMBER,
  "TOPO_ID" NUMBER,
  "TOPO_TYPE" NUMBER,
  "TOPO_ATTRIBUTE" VARCHAR2(100 BYTE)
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TOPO_TRANSACT_DATA" (
  "TOPO_SEQUENCE" NUMBER,
  "TOPOLOGY_ID" VARCHAR2(20 BYTE),
  "TOPO_ID" NUMBER,
  "TOPO_TYPE" NUMBER,
  "TOPO_OP" VARCHAR2(3 BYTE),
  "PARENT_ID" NUMBER
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TTS_METADATA_TABLE" (
  "SDO_INDEX_OWNER" VARCHAR2(130 BYTE),
  "SDO_INDEX_TYPE" VARCHAR2(32 BYTE),
  "SDO_LEVEL" NUMBER,
  "SDO_NUMTILES" NUMBER,
  "SDO_MAXLEVEL" NUMBER,
  "SDO_COMMIT_INTERVAL" NUMBER,
  "SDO_INDEX_TABLE" VARCHAR2(130 BYTE),
  "SDO_INDEX_NAME" VARCHAR2(130 BYTE),
  "SDO_INDEX_PRIMARY" NUMBER,
  "SDO_TSNAME" VARCHAR2(130 BYTE),
  "SDO_COLUMN_NAME" VARCHAR2(2048 BYTE),
  "SDO_RTREE_HEIGHT" NUMBER,
  "SDO_RTREE_NUM_NODES" NUMBER,
  "SDO_RTREE_DIMENSIONALITY" NUMBER,
  "SDO_RTREE_FANOUT" NUMBER,
  "SDO_RTREE_ROOT" VARCHAR2(32 BYTE),
  "SDO_RTREE_SEQ_NAME" VARCHAR2(130 BYTE),
  "SDO_FIXED_META" RAW(255),
  "SDO_TABLESPACE" VARCHAR2(130 BYTE),
  "SDO_INITIAL_EXTENT" VARCHAR2(32 BYTE),
  "SDO_NEXT_EXTENT" VARCHAR2(32 BYTE),
  "SDO_PCTINCREASE" NUMBER,
  "SDO_MIN_EXTENTS" NUMBER,
  "SDO_MAX_EXTENTS" NUMBER,
  "SDO_INDEX_DIMS" NUMBER,
  "SDO_LAYER_GTYPE" VARCHAR2(32 BYTE),
  "SDO_RTREE_PCTFREE" NUMBER,
  "SDO_INDEX_PARTITION" VARCHAR2(130 BYTE),
  "SDO_PARTITIONED" NUMBER,
  "SDO_RTREE_QUALITY" NUMBER,
  "SDO_INDEX_VERSION" NUMBER,
  "SDO_INDEX_GEODETIC" VARCHAR2(8 BYTE),
  "SDO_INDEX_STATUS" VARCHAR2(32 BYTE),
  "SDO_NL_INDEX_TABLE" VARCHAR2(131 BYTE),
  "SDO_DML_BATCH_SIZE" NUMBER,
  "SDO_RTREE_ENT_XPND" NUMBER,
  "SDO_NUM_ROWS" NUMBER,
  "SDO_NUM_BLKS" NUMBER,
  "SDO_ROOT_MBR" VARCHAR2(1 BYTE),
  "SDO_OPTIMIZED_NODES" NUMBER,
  "SDO_TABLE_NAME" VARCHAR2(130 BYTE),
  "SDO_RTREE_READ_ONLY" NUMBER
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TXN_IDX_EXP_UPD_RGN" (
  "SDO_TXN_IDX_ID" VARCHAR2(32 BYTE) NOT NULL,
  "RID" VARCHAR2(24 BYTE) NOT NULL,
  "START_1" NUMBER,
  "END_1" NUMBER,
  "START_2" NUMBER,
  "END_2" NUMBER,
  "START_3" NUMBER,
  "END_3" NUMBER,
  "START_4" NUMBER,
  "END_4" NUMBER,
  PRIMARY KEY ("SDO_TXN_IDX_ID", "RID")
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TXN_JOURNAL_GTT" (
  "SID" NUMBER NOT NULL,
  "SDO_TXN_IDX_ID" VARCHAR2(130 BYTE) NOT NULL,
  "OPERATION" NUMBER NOT NULL,
  "RID" VARCHAR2(24 BYTE) NOT NULL,
  "INDEXPTNIDEN" NUMBER NOT NULL,
  "TABLEPTNIDEN" NUMBER NOT NULL,
  "START_1" BINARY_DOUBLE,
  "END_1" BINARY_DOUBLE,
  "START_2" BINARY_DOUBLE,
  "END_2" BINARY_DOUBLE,
  "START_3" BINARY_DOUBLE,
  "END_3" BINARY_DOUBLE,
  "START_4" BINARY_DOUBLE,
  "END_4" BINARY_DOUBLE,
  PRIMARY KEY ("SID", "SDO_TXN_IDX_ID", "INDEXPTNIDEN", "OPERATION", "RID")
) PCTUSED 40 NOLOGGING;
CREATE TABLE "MDSYS"."SDO_TXN_JOURNAL_REG" (
  "SID" NUMBER NOT NULL,
  "SDO_TXN_IDX_ID" VARCHAR2(130 BYTE) NOT NULL,
  "OPERATION" NUMBER NOT NULL,
  "RID" VARCHAR2(24 BYTE) NOT NULL,
  "INDEXPTNIDEN" NUMBER NOT NULL,
  "TABLEPTNIDEN" NUMBER NOT NULL,
  "START_1" BINARY_DOUBLE,
  "END_1" BINARY_DOUBLE,
  "START_2" BINARY_DOUBLE,
  "END_2" BINARY_DOUBLE,
  "START_3" BINARY_DOUBLE,
  "END_3" BINARY_DOUBLE,
  "START_4" BINARY_DOUBLE,
  "END_4" BINARY_DOUBLE,
  PRIMARY KEY ("SID", "SDO_TXN_IDX_ID", "INDEXPTNIDEN", "OPERATION", "RID")
);
CREATE TABLE "MDSYS"."SDO_UNITS_OF_MEASURE" (
  "UOM_ID" NUMBER(10, 0) NOT NULL,
  "UNIT_OF_MEAS_NAME" VARCHAR2(2083 BYTE) NOT NULL,
  "SHORT_NAME" VARCHAR2(80 BYTE),
  "LEGACY_UNIT_NAME" VARCHAR2(80 BYTE) DEFAULT NULL,
  "UNIT_OF_MEAS_TYPE" VARCHAR2(50 BYTE),
  "TARGET_UOM_ID" NUMBER(10, 0),
  "FACTOR_B" NUMBER,
  "FACTOR_C" NUMBER,
  "INFORMATION_SOURCE" VARCHAR2(254 BYTE),
  "DATA_SOURCE" VARCHAR2(40 BYTE),
  "IS_LEGACY" VARCHAR2(5 BYTE) NOT NULL,
  "LEGACY_CODE" NUMBER(10, 0),
  CONSTRAINT "UNIT_OF_MEASURE_PRIM" PRIMARY KEY ("UOM_ID"),
  CONSTRAINT "ELLIPSOID_FOREIGN_LEGACY" FOREIGN KEY ("LEGACY_CODE") REFERENCES "SDO_ELLIPSOIDS"("ELLIPSOID_ID"),
  CONSTRAINT "UNIT_OF_MEASURE_FOREIGN_LEGACY" FOREIGN KEY ("LEGACY_CODE") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID"),
  CONSTRAINT "UNIT_OF_MEASURE_FOREIGN_UOM" FOREIGN KEY ("TARGET_UOM_ID") REFERENCES "SDO_UNITS_OF_MEASURE"("UOM_ID"),
  CONSTRAINT "UOM_UNIQUE1" UNIQUE ("UOM_ID", "UNIT_OF_MEAS_TYPE"),
  CONSTRAINT "UOM_UNIQUE_SHORT_NAME" UNIQUE ("SHORT_NAME"),
  CONSTRAINT "UOM_ID_MUST_BE_POS" CHECK (UOM_ID > 0),
  CONSTRAINT "FACTOR_B_MUST_BE_POS" CHECK (FACTOR_B IS NULL OR FACTOR_B > 0),
  CONSTRAINT "FACTOR_C_MUST_BE_POS" CHECK (FACTOR_C IS NULL OR FACTOR_C > 0),
  CONSTRAINT "UOM_TYPE_CONSTR" CHECK (nls_lower(unit_of_meas_type) in ('area', 'angle', 'length', 'scale', 'volume')),
  CONSTRAINT "ONLY_STD_TARGET_UOMS" CHECK (target_uom_id in (9001, 9101, 9201, 10008, 19501))
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SDO_XML_SCHEMAS" (
  "ID" NUMBER NOT NULL,
  "DESCRIPTION" VARCHAR2(300 BYTE),
  "XMLSCHEMA" CLOB,
  PRIMARY KEY ("ID")
) TABLESPACE SYSAUX;
CREATE TABLE "MDSYS"."SRSNAMESPACE_TABLE" (
  "SRSNAMESPACE" VARCHAR2(2000 BYTE) NOT NULL,
  "SRSNAME" VARCHAR2(2000 BYTE) NOT NULL,
  "SDO_SRID" NUMBER,
  PRIMARY KEY ("SRSNAMESPACE", "SRSNAME")
) TABLESPACE SYSAUX;