CREATE TABLE "MMPM_NTA"."ETL_GENERIC_PROCESS_PARAM" (
  "PROCESS_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "PARAM_VALUE" VARCHAR2(200 BYTE),
  PRIMARY KEY ("PROCESS_NAME", "PARAM_NAME")
) TABLESPACE MMPM_DATA;