CREATE TABLE "OUTLN"."OL$" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "SQL_TEXT" LONG,
  "TEXTLEN" NUMBER,
  "SIGNATURE" RAW(16),
  "HASH_VALUE" NUMBER,
  "HASH_VALUE2" NUMBER,
  "CATEGORY" VARCHAR2(128 BYTE),
  "VERSION" VARCHAR2(64 BYTE),
  "CREATOR" VARCHAR2(128 BYTE),
  "TIMESTAMP" DATE,
  "FLAGS" NUMBER,
  "HINTCOUNT" NUMBER,
  "SPARE1" NUMBER,
  "SPARE2" VARCHAR2(1000 BYTE)
) TABLESPACE SYSTEM PCTUSED 40;
CREATE TABLE "OUTLN"."OL$HINTS" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "HINT#" NUMBER,
  "CATEGORY" VARCHAR2(128 BYTE),
  "HINT_TYPE" NUMBER,
  "HINT_TEXT" VARCHAR2(512 BYTE),
  "STAGE#" NUMBER,
  "NODE#" NUMBER,
  "TABLE_NAME" VARCHAR2(128 BYTE),
  "TABLE_TIN" NUMBER,
  "TABLE_POS" NUMBER,
  "REF_ID" NUMBER,
  "USER_TABLE_NAME" VARCHAR2(260 BYTE),
  "COST" NUMBER(126),
  "CARDINALITY" NUMBER(126),
  "BYTES" NUMBER(126),
  "HINT_TEXTOFF" NUMBER,
  "HINT_TEXTLEN" NUMBER,
  "JOIN_PRED" VARCHAR2(2000 BYTE),
  "SPARE1" NUMBER,
  "SPARE2" NUMBER,
  "HINT_STRING" CLOB
) TABLESPACE SYSTEM PCTUSED 40;
CREATE TABLE "OUTLN"."OL$NODES" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "CATEGORY" VARCHAR2(128 BYTE),
  "NODE_ID" NUMBER,
  "PARENT_ID" NUMBER,
  "NODE_TYPE" NUMBER,
  "NODE_TEXTLEN" NUMBER,
  "NODE_TEXTOFF" NUMBER,
  "NODE_NAME" VARCHAR2(64 BYTE)
) TABLESPACE SYSTEM PCTUSED 40;