-- @TBL_GUI_NAME: SP Benchmarks
-- @TBL_GUI_NAME_SHORT: SP_DEF_BENCHMARKS
-- @TBL_NAME_AT: D_STA_SP_DEF_BENCHMARKS_AT
-- @TBL_DISPLAY_ORDER: 2
CREATE TABLE "PRISMA_RFP"."D_STA_SP_DEF_BENCHMARKS" (
  -- @COL_GUI_NAME: Calibration group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CALIBRATION_GROUP" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Benchmark group
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "BENCHMARK_GROUP" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Factor ID
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "FACTOR_ID" NUMBER(15, 0) NOT NULL,
  -- @COL_GUI_NAME: Risk factor type
  -- @COL_DISPLAY_ORDER: 4
  "RISK_FACTOR_TYPE" VARCHAR2(255 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Parameter name
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_PK: Y
  "PARAMETER_NAME" VARCHAR2(255 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Parameter value
  -- @COL_DISPLAY_ORDER: 6
  "PARAMETER_VALUE" VARCHAR2(255 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 8
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "CREATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  "UTS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_D_STA_SP_DEF_BENCHMARKS" PRIMARY KEY ("CALIBRATION_GROUP", "BENCHMARK_GROUP", "FACTOR_ID", "PARAMETER_NAME", "VALID_FROM")
) TABLESPACE PRISMA_FACT;
-- @TBL_GUI_NAME: SP Calibration Groups
-- @TBL_GUI_NAME_SHORT: SP_DEF_CALIB_GRP
-- @TBL_NAME_AT: D_STA_SP_DEF_CALIB_GRP_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "PRISMA_RFP"."D_STA_SP_DEF_CALIB_GRP" (
  -- @COL_GUI_NAME: Calibration group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CALIBRATION_GROUP" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: RMS ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_FORMAT: 0
  "RMS_ID" NUMBER(15, 0),
  -- @COL_GUI_NAME: OTC LG
  -- @COL_DISPLAY_ORDER: 3
  "OTC_LG" VARCHAR2(32 BYTE),
  -- @COL_GUI_NAME: Risk horizon
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_FORMAT: 0
  "RISK_HORIZON" NUMBER(10, 0),
  -- @COL_GUI_NAME: Number stress days
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: 0
  "NUMBER_STRESS_DAYS" NUMBER(10, 0),
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "CREATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  "UTS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_D_STA_SP_DEF_CALIB_GRP" PRIMARY KEY ("CALIBRATION_GROUP", "VALID_FROM")
) TABLESPACE PRISMA_FACT;
-- @TBL_GUI_NAME: SP Weights
-- @TBL_GUI_NAME_SHORT: SP_DEF_WEIGHTS
-- @TBL_NAME_AT: D_STA_SP_DEF_WEIGHTS_AT
-- @TBL_DISPLAY_ORDER: 3
CREATE TABLE "PRISMA_RFP"."D_STA_SP_DEF_WEIGHTS" (
  -- @COL_GUI_NAME: Calibration group
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "CALIBRATION_GROUP" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Benchmark group
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  "BENCHMARK_GROUP" VARCHAR2(32 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Weight
  -- @COL_DISPLAY_ORDER: 3
  -- @COL_FORMAT: 0
  "WEIGHT" NUMBER NOT NULL,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 4
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "CREATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  "UTS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_D_STA_SP_DEF_WEIGHTS" PRIMARY KEY ("CALIBRATION_GROUP", "BENCHMARK_GROUP", "VALID_FROM")
) TABLESPACE PRISMA_FACT;
-- @TBL_GUI_NAME: Tool Configuration
-- @TBL_GUI_NAME_SHORT: TOOL_CONFIGURATION
-- @TBL_NAME_AT: D_STA_TOOL_CONFIGURATION_AT
-- @TBL_DISPLAY_ORDER: 1
CREATE TABLE "PRISMA_RFP"."D_STA_TOOL_CONFIGURATION" (
  -- @COL_GUI_NAME: Parameter Name
  -- @COL_DISPLAY_ORDER: 1
  -- @COL_PK: Y
  "PARAM_NAME" VARCHAR2(80 BYTE) NOT NULL,
  -- @COL_GUI_NAME: Tool ID
  -- @COL_DISPLAY_ORDER: 2
  -- @COL_PK: Y
  -- @COL_FORMAT: 0
  "TOOL_ID" NUMBER(15, 0),
  -- @COL_GUI_NAME: Parameter value number
  -- @COL_DISPLAY_ORDER: 3
  "PARAM_VALUE_NUM" NUMBER,
  -- @COL_GUI_NAME: Parameter value char
  -- @COL_DISPLAY_ORDER: 4
  "PARAM_VALUE_CHAR" VARCHAR2(255 BYTE),
  -- @COL_GUI_NAME: Parameter value date
  -- @COL_DISPLAY_ORDER: 5
  -- @COL_FORMAT: dd.MM.yyyy
  "PARAM_VALUE_DATE" DATE,
  -- @COL_GUI_NAME: Valid from
  -- @COL_DISPLAY_ORDER: 6
  -- @COL_PK: Y
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: F
  "VALID_FROM" DATE NOT NULL,
  -- @COL_GUI_NAME: Valid to
  -- @COL_DISPLAY_ORDER: 7
  -- @COL_FORMAT: dd.MM.yyyy
  -- @COL_VALID_INTERVAL_COLUMN: T
  "VALID_TO" DATE NOT NULL,
  "CREATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'GUI_XMDM' NOT NULL,
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  "UTS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "FK1_D_STA_TOOL_CONFIGURATION" UNIQUE ("PARAM_NAME", "TOOL_ID", "VALID_FROM")
) TABLESPACE PRISMA_FACT;