CREATE TABLE "REFDATA"."REF_EX_PRODUCT_CLASS_ASN" (
  "PRODUCT_CLASS_CODE" VARCHAR2(15 BYTE),
  "PRODUCT_CODE" VARCHAR2(15 BYTE) NOT NULL,
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE),
  "PRODUCT_SUB_CLASS_CODE" CHAR(12 BYTE),
  CONSTRAINT "PK_PRODUCT_CODE" PRIMARY KEY ("PRODUCT_CODE")
) TABLESPACE EUREX_FACT COMPRESS FOR OLTP;