CREATE TABLE "REVENUE_SHARING_P2"."D_CURRENCY" (
  "ISO_CRCY_ID" NUMBER(*, 0) NOT NULL,
  "COUNTRY_ID" NUMBER(*, 0),
  "ITS" DATE,
  "SHORT_NAME" VARCHAR2(15 BYTE),
  "LONG_NAME" VARCHAR2(60 BYTE),
  "ISO_NUMERIC_CODE" VARCHAR2(3 BYTE),
  "ISO_ALPHA_CODE" VARCHAR2(3 BYTE),
  "PARITY" NUMBER,
  "CURRENCY_ALL_ENTRI" VARCHAR2(1 BYTE),
  "COUNTRY_CODE" VARCHAR2(15 BYTE),
  "PARENT_CRCY_ID" NUMBER,
  "PARENT_CRCY_ALPHA_CODE" VARCHAR2(3 BYTE),
  "PARENT_CRCY_DIVISOR" NUMBER
) TABLESPACE REVENUE_SHARING_FACT;
CREATE TABLE "REVENUE_SHARING_P2"."D_MEMBER_OBJ" (
  "MEMBER_ID" NUMBER(15, 0) NOT NULL,
  "SOURCE_SYSTEM" VARCHAR2(30 BYTE),
  "BUSINESS_ID" VARCHAR2(64 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE,
  "ADDR_ID" NUMBER(15, 0),
  "MR_MEMBER_NAME" VARCHAR2(4000 BYTE),
  "ITS" DATE NOT NULL,
  "UTS" DATE NOT NULL,
  "DWH_AWARENESS_DATE" DATE NOT NULL,
  PRIMARY KEY ("MEMBER_ID")
) TABLESPACE REVENUE_SHARING_FACT;