CREATE TABLE "SYSTEM"."HELP" (
  "TOPIC" VARCHAR2(50 BYTE) NOT NULL,
  "SEQ" NUMBER NOT NULL,
  "INFO" VARCHAR2(80 BYTE),
  CONSTRAINT "HELP_TOPIC_SEQ" PRIMARY KEY ("TOPIC", "SEQ")
) TABLESPACE SYSTEM PCTFREE 0 PCTUSED 40;
CREATE TABLE "SYSTEM"."OL$" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "SQL_TEXT" LONG,
  "TEXTLEN" NUMBER,
  "SIGNATURE" RAW(16),
  "HASH_VALUE" NUMBER,
  "HASH_VALUE2" NUMBER,
  "CATEGORY" VARCHAR2(128 BYTE),
  "VERSION" VARCHAR2(64 BYTE),
  "CREATOR" VARCHAR2(128 BYTE),
  "TIMESTAMP" DATE,
  "FLAGS" NUMBER,
  "HINTCOUNT" NUMBER,
  "SPARE1" NUMBER,
  "SPARE2" VARCHAR2(1000 BYTE)
) PCTUSED 40 NOLOGGING;
CREATE TABLE "SYSTEM"."OL$HINTS" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "HINT#" NUMBER,
  "CATEGORY" VARCHAR2(128 BYTE),
  "HINT_TYPE" NUMBER,
  "HINT_TEXT" VARCHAR2(512 BYTE),
  "STAGE#" NUMBER,
  "NODE#" NUMBER,
  "TABLE_NAME" VARCHAR2(128 BYTE),
  "TABLE_TIN" NUMBER,
  "TABLE_POS" NUMBER,
  "REF_ID" NUMBER,
  "USER_TABLE_NAME" VARCHAR2(260 BYTE),
  "COST" NUMBER(126),
  "CARDINALITY" NUMBER(126),
  "BYTES" NUMBER(126),
  "HINT_TEXTOFF" NUMBER,
  "HINT_TEXTLEN" NUMBER,
  "JOIN_PRED" VARCHAR2(2000 BYTE),
  "SPARE1" NUMBER,
  "SPARE2" NUMBER,
  "HINT_STRING" CLOB
) PCTUSED 40 NOLOGGING;
CREATE TABLE "SYSTEM"."OL$NODES" (
  "OL_NAME" VARCHAR2(128 BYTE),
  "CATEGORY" VARCHAR2(128 BYTE),
  "NODE_ID" NUMBER,
  "PARENT_ID" NUMBER,
  "NODE_TYPE" NUMBER,
  "NODE_TEXTLEN" NUMBER,
  "NODE_TEXTOFF" NUMBER,
  "NODE_NAME" VARCHAR2(64 BYTE)
) PCTUSED 40 NOLOGGING;
CREATE TABLE "SYSTEM"."SCHEDULER_JOB_ARGS_TBL" (
  "OWNER" VARCHAR2(128 BYTE),
  "JOB_NAME" VARCHAR2(128 BYTE),
  "ARGUMENT_NAME" VARCHAR2(128 BYTE),
  "ARGUMENT_POSITION" NUMBER,
  "ARGUMENT_TYPE" VARCHAR2(257 BYTE),
  "VALUE" VARCHAR2(4000 BYTE),
  "ANYDATA_VALUE" VARCHAR2(3752 BYTE),
  "OUT_ARGUMENT" VARCHAR2(5 BYTE)
) TABLESPACE SYSTEM PCTUSED 40;
CREATE TABLE "SYSTEM"."SCHEDULER_PROGRAM_ARGS_TBL" (
  "OWNER" VARCHAR2(128 BYTE) NOT NULL,
  "PROGRAM_NAME" VARCHAR2(128 BYTE) NOT NULL,
  "ARGUMENT_NAME" VARCHAR2(128 BYTE),
  "ARGUMENT_POSITION" NUMBER NOT NULL,
  "ARGUMENT_TYPE" VARCHAR2(257 BYTE),
  "METADATA_ATTRIBUTE" VARCHAR2(19 BYTE),
  "DEFAULT_VALUE" VARCHAR2(4000 BYTE),
  "DEFAULT_ANYDATA_VALUE" VARCHAR2(3752 BYTE),
  "OUT_ARGUMENT" VARCHAR2(5 BYTE)
) TABLESPACE SYSTEM PCTUSED 40;