CREATE TABLE "XDB"."APP_ROLE_MEMBERSHIP" (
  "ROLE_GUID" RAW(16),
  "MEMBER_GUID" RAW(16)
) TABLESPACE SYSAUX;
COMMENT ON TABLE "XDB"."APP_ROLE_MEMBERSHIP" IS 'Application role membership';
COMMENT ON COLUMN "XDB"."APP_ROLE_MEMBERSHIP"."ROLE_GUID" IS 'The GUID for the role/workgroup';
COMMENT ON COLUMN "XDB"."APP_ROLE_MEMBERSHIP"."MEMBER_GUID" IS 'The GUID of the role member';
CREATE TABLE "XDB"."APP_USERS_AND_ROLES" (
  "GUID" RAW(16),
  "NAME" VARCHAR2(1024 BYTE),
  "ISROLE" VARCHAR2(3 BYTE),
  CONSTRAINT "SYS_C004004" UNIQUE ("NAME")
) TABLESPACE SYSAUX;
COMMENT ON TABLE "XDB"."APP_USERS_AND_ROLES" IS 'Application users and roles/workspaces';
COMMENT ON COLUMN "XDB"."APP_USERS_AND_ROLES"."GUID" IS 'The GUID for user or role/workgroup';
COMMENT ON COLUMN "XDB"."APP_USERS_AND_ROLES"."NAME" IS 'The name of user or role/workgroup';
COMMENT ON COLUMN "XDB"."APP_USERS_AND_ROLES"."ISROLE" IS 'Whether user or role/workgroup';
CREATE TABLE "XDB"."X$NM78WP8DPUMJIBBE0GWV4I5GKCGL" (
  "NMSPCURI" VARCHAR2(2000 BYTE),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."X$PT78WP8DPUMJIBBE0GWV4I5GKCGL" (
  "PATH" RAW(2000),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."X$QN78WP8DPUMJIBBE0GWV4I5GKCGL" (
  "NMSPCID" RAW(8),
  "LOCALNAME" VARCHAR2(2000 BYTE),
  "FLAGS" RAW(4),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$COLUMN_INFO" (
  "SCHEMA_REF" XMLTYPE,
  "ELNUM" NUMBER(*, 0),
  "COLNUM" NUMBER(*, 0),
  "PROPINFO" RAW(2000)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$DXPTAB" (
  "IDXOBJ#" NUMBER NOT NULL,
  "PATHTABOBJ#" NUMBER NOT NULL,
  "FLAGS" NUMBER,
  "RAWSIZE" NUMBER,
  "PARAMETERS" XMLTYPE,
  "PENDTABOBJ#" NUMBER,
  "SNAPSHOT" RAW(20),
  "TABLESPACE" VARCHAR2(128 BYTE),
  "TABLE_ATTRS" VARCHAR2(4000 BYTE),
  "NBPENDTABOBJ#" NUMBER,
  "NBERRTABOBJ#" NUMBER,
  CONSTRAINT "XDB$DXPTABPK" PRIMARY KEY ("IDXOBJ#")
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$D_LINK" (
  "SOURCE_ID" RAW(16),
  "TARGET_ID" RAW(16),
  "TARGET_PATH" VARCHAR2(4000 BYTE),
  "FLAGS" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$H_INDEX" (
  "OID" RAW(16),
  "ACL_ID" RAW(16),
  "OWNER_ID" RAW(16),
  "FLAGS" RAW(4),
  "CHILDREN" BLOB
) TABLESPACE SYSAUX PCTFREE 99;
CREATE TABLE "XDB"."XDB$IMPORT_NM_INFO" (
  "NMSPCURI" VARCHAR2(2000 BYTE),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$IMPORT_PT_INFO" (
  "PATH" RAW(2000),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$IMPORT_QN_INFO" (
  "NMSPCID" RAW(8),
  "LOCALNAME" VARCHAR2(2000 BYTE),
  "FLAGS" RAW(4),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$IMPORT_TT_INFO" (
  "GUID" RAW(16),
  "NMSPCID" RAW(8),
  "LOCALNAME" VARCHAR2(2000 BYTE),
  "FLAGS" RAW(4),
  "ID" RAW(8)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$MOUNTS" (
  "DOBJ#" NUMBER,
  "DPATH" VARCHAR2(4000 BYTE),
  "SOBJ#" NUMBER,
  "SPATH" VARCHAR2(4000 BYTE),
  "FLAGS" NUMBER
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$NONCEKEY" (
  "NONCEKEY" CHAR(32 BYTE)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$REPOS" (
  "OBJ#" NUMBER NOT NULL,
  "FLAGS" NUMBER,
  "ROOTINFO#" NUMBER,
  "HINDEX#" NUMBER,
  "HLINK#" NUMBER,
  "RESOURCE#" NUMBER,
  "ACL#" NUMBER,
  "CONFIG#" NUMBER,
  "DLINK#" NUMBER,
  "NLOCKS#" NUMBER,
  "STATS#" NUMBER,
  "CHECKOUTS#" NUMBER,
  "RESCONFIG#" NUMBER,
  "WKSPC#" NUMBER,
  "VERSHIST#" NUMBER,
  "PARAMS" XMLTYPE
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$ROOT_INFO" (
  "RESOURCE_ROOT" ROWID,
  "RCLIST" RAW(2000),
  "FTP_PORT" NUMBER(5, 0),
  "FTP_PROTOCOL" VARCHAR2(4000 BYTE),
  "HTTP_PORT" NUMBER(5, 0),
  "HTTP_PROTOCOL" VARCHAR2(4000 BYTE),
  "HTTP_HOST" VARCHAR2(4000 BYTE),
  "HTTP2_PORT" NUMBER(5, 0),
  "HTTP2_PROTOCOL" VARCHAR2(4000 BYTE),
  "HTTP2_HOST" VARCHAR2(4000 BYTE),
  "NFS_PORT" NUMBER(5, 0),
  "NFS_PROTOCOL" VARCHAR2(4000 BYTE),
  "RHTTP_PORT" NUMBER(5, 0),
  "RHTTP_PROTOCOL" VARCHAR2(4000 BYTE),
  "RHTTP_HOST" VARCHAR2(4000 BYTE),
  "RHTTPS_PORT" NUMBER(5, 0),
  "RHTTPS_PROTOCOL" VARCHAR2(4000 BYTE),
  "RHTTPS_HOST" VARCHAR2(4000 BYTE)
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$TTSET" (
  "GUID" RAW(16),
  "TOKSUF" VARCHAR2(26 BYTE),
  "FLAGS" NUMBER,
  "OBJ#" NUMBER,
  CONSTRAINT "SYS_C004003" UNIQUE ("OBJ#")
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$XDB_READY" (
  "DATA" CLOB
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$XIDX_IMP_T" (
  "INDEX_NAME" VARCHAR2(138 BYTE),
  "SCHEMA_NAME" VARCHAR2(138 BYTE),
  "ID" VARCHAR2(40 BYTE),
  "DATA" CLOB,
  "GRPPOS" NUMBER
) PCTUSED 40 NOLOGGING;
CREATE TABLE "XDB"."XDB$XIDX_PARAM_T" (
  "USERID" NUMBER,
  "PARAM_NAME" VARCHAR2(128 BYTE),
  "PARAMSTR" CLOB
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$XTAB" (
  "IDXOBJ#" NUMBER NOT NULL,
  "GROUPNAME" NVARCHAR2(128) NOT NULL,
  "XMLTABOBJ#" NUMBER NOT NULL,
  "PTABOBJ#" NUMBER,
  "XPATH" VARCHAR2(4000 BYTE) NOT NULL,
  "XQUERY" CLOB,
  "FLAGS" NUMBER,
  "PARAMETERS" XMLTYPE,
  "GRPPOS" NUMBER,
  "DEPGRPPOS" NUMBER,
  "SEGATTRS" VARCHAR2(4000 BYTE),
  CONSTRAINT "XDB$XTABPK" PRIMARY KEY ("IDXOBJ#", "GROUPNAME", "XMLTABOBJ#")
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$XTABCOLS" (
  "IDXOBJ#" NUMBER NOT NULL,
  "GROUPNAME" NVARCHAR2(128) NOT NULL,
  "XMLTABOBJ#" NUMBER NOT NULL,
  "COLNAME" NVARCHAR2(2000) NOT NULL,
  "COLTYPE" NVARCHAR2(100) NOT NULL,
  "XPATH" VARCHAR2(4000 BYTE) NOT NULL,
  "FLAGS" NUMBER NOT NULL
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB$XTABNMSP" (
  "IDXOBJ#" NUMBER NOT NULL,
  "GROUPNAME" NVARCHAR2(128) NOT NULL,
  "XMLTABOBJ#" NUMBER NOT NULL,
  "PREFIX" NVARCHAR2(128),
  "NAMESPACE" NVARCHAR2(2000),
  "FLAGS" NUMBER NOT NULL
) TABLESPACE SYSAUX;
CREATE TABLE "XDB"."XDB_INDEX_DDL_CACHE" (
  "ROOT_TABLE_NAME" VARCHAR2(128 BYTE),
  "ROOT_TABLE_OWNER" VARCHAR2(128 BYTE),
  "ROOT_COL_NAME" VARCHAR2(128 BYTE),
  "TABLE_NAME" VARCHAR2(128 BYTE),
  "TABLE_OWNER" VARCHAR2(128 BYTE),
  "IDX_OWNER" VARCHAR2(128 BYTE),
  "IDX_TABLE_NAME" VARCHAR2(128 BYTE),
  "IDX_NAME" VARCHAR2(128 BYTE),
  "IDX_TYPE" VARCHAR2(27 BYTE),
  "CONSTR_NAME" VARCHAR2(128 BYTE),
  "CONSTR_OWNER" VARCHAR2(128 BYTE)
) TABLESPACE SYSAUX;