package sequala.schema

abstract class Statement

/** Marker trait for schema diff operations. Types that can be generated by SchemaDiffer extend this. */
trait SchemaDiffOp

case class CreateTable[DT, CO <: ColumnOptions, TO <: TableOptions](
  table: Table[DT, CO, TO],
  orReplace: Boolean = false,
  ifNotExists: Boolean = false
) extends Statement
    with SchemaDiffOp

case class DropTable[DO <: DropOptions](tableName: String, ifExists: Boolean = false, options: DO)
    extends Statement
    with SchemaDiffOp

// Backward compatibility: provide apply method that uses CommonDropOptions
object DropTable:
  def apply(tableName: String, ifExists: Boolean, cascade: Boolean): DropTable[CommonDropOptions] =
    DropTable[CommonDropOptions](tableName, ifExists, CommonDropOptions(cascade))
  def apply(tableName: String): DropTable[CommonDropOptions] = apply(tableName, false, false)
  def apply(tableName: String, ifExists: Boolean): DropTable[CommonDropOptions] = apply(tableName, ifExists, false)
  def apply(tableName: String, cascade: Boolean, _unused: Unit): DropTable[CommonDropOptions] =
    apply(tableName, false, cascade)

case class AlterTable[DT, CO <: ColumnOptions, TO <: TableOptions, ATA <: AlterTableAction[DT, CO]](
  tableName: String,
  actions: Seq[ATA]
) extends Statement
    with SchemaDiffOp

import sequala.schema.ast.SqlComment

abstract class AlterTableAction[DT, CO <: ColumnOptions](val sourceComment: Seq[SqlComment] = Seq.empty):
  protected def quote(name: String): String = IdentifierQuoting.DoubleQuote.quoteIdentifier(name)

case class AddColumn[DT <: DataType, CO <: ColumnOptions](column: Column[DT, CO], comment: Seq[SqlComment] = Seq.empty)
    extends AlterTableAction[DT, CO](comment)

case class DropColumn[DT, CO <: ColumnOptions](
  columnName: String,
  cascade: Boolean = false,
  comment: Seq[SqlComment] = Seq.empty
) extends AlterTableAction[DT, CO](comment)

case class ModifyColumn[DT <: DataType, CO <: ColumnOptions](
  column: Column[DT, CO],
  comment: Seq[SqlComment] = Seq.empty
) extends AlterTableAction[DT, CO](comment)

case class RenameColumn[DT, CO <: ColumnOptions](oldName: String, newName: String, comment: Seq[SqlComment] = Seq.empty)
    extends AlterTableAction[DT, CO](comment)

case class AddConstraint[DT, CO <: ColumnOptions](constraint: TableConstraint, comment: Seq[SqlComment] = Seq.empty)
    extends AlterTableAction[DT, CO](comment)

case class DropConstraint[DT, CO <: ColumnOptions](
  constraintName: String,
  cascade: Boolean = false,
  comment: Seq[SqlComment] = Seq.empty
) extends AlterTableAction[DT, CO](comment)

sealed trait TableConstraint:
  protected def quote(name: String): String = IdentifierQuoting.DoubleQuote.quoteIdentifier(name)

case class PrimaryKeyConstraint(pk: PrimaryKey) extends TableConstraint

case class ForeignKeyConstraint(fk: ForeignKey) extends TableConstraint

case class UniqueConstraint(unique: Unique) extends TableConstraint

case class CheckConstraint(check: Check) extends TableConstraint

case class CreateIndex[IO <: IndexOptions](
  name: String,
  tableName: String,
  columns: Seq[IndexColumn],
  unique: Boolean = false,
  ifNotExists: Boolean = false,
  options: IO
) extends Statement
    with SchemaDiffOp

object CreateIndex:
  def apply(
    name: String,
    tableName: String,
    columns: Seq[IndexColumn],
    unique: Boolean,
    ifNotExists: Boolean,
    where: Option[String]
  ): CreateIndex[CommonIndexOptions] =
    CreateIndex(name, tableName, columns, unique, ifNotExists, CommonIndexOptions(where))
  def apply(
    name: String,
    tableName: String,
    columns: Seq[IndexColumn],
    unique: Boolean
  ): CreateIndex[CommonIndexOptions] =
    CreateIndex(name, tableName, columns, unique, false, CommonIndexOptions.empty)
  def apply(name: String, tableName: String, columns: Seq[IndexColumn]): CreateIndex[CommonIndexOptions] =
    CreateIndex(name, tableName, columns, false, false, CommonIndexOptions.empty)

case class DropIndex(name: String, ifExists: Boolean = false, cascade: Boolean = false)
    extends Statement
    with SchemaDiffOp

case class SetTableComment(tableName: String, comment: Option[String]) extends Statement with SchemaDiffOp

case class SetColumnComment(tableName: String, columnName: String, comment: Option[String])
    extends Statement
    with SchemaDiffOp

// DML and other SQL statements
// These use schema-level AST types mirroring the parser AST structure

import sequala.schema.ast.*

case class Select(body: SelectBody, withClause: Seq[WithClause] = Seq()) extends Statement

case class Update(table: ast.Name, set: Seq[(ast.Name, Expression)], where: Option[Expression]) extends Statement

case class Delete(table: ast.Name, where: Option[Expression]) extends Statement

case class Insert(table: ast.Name, columns: Option[Seq[ast.Name]], values: InsertValues, orReplace: Boolean = false)
    extends Statement

// MERGE statement for upsert operations (Oracle, SQL Server, etc.)
case class Merge(
  intoTable: ast.Name,
  intoAlias: Option[String],
  usingSource: MergeSource,
  onCondition: Expression,
  whenMatched: Option[MergeWhenMatched],
  whenNotMatched: Option[MergeWhenNotMatched]
) extends Statement

sealed trait MergeSource
case class MergeSourceTable(table: ast.Name, alias: Option[String]) extends MergeSource
case class MergeSourceSelect(query: SelectBody, alias: String) extends MergeSource

case class MergeWhenMatched(set: Seq[(ast.Name, Expression)], where: Option[Expression] = None)

case class MergeWhenNotMatched(columns: Seq[ast.Name], values: Seq[Expression])

case class CreateTableAs(name: ast.Name, orReplace: Boolean = false, query: SelectBody) extends Statement

case class CreateView[VO <: CreateViewOptions](
  name: ast.Name,
  orReplace: Boolean = false,
  query: SelectBody,
  options: VO
) extends Statement

object CreateView:
  def apply(
    name: ast.Name,
    orReplace: Boolean,
    query: SelectBody,
    materialized: Boolean,
    temporary: Boolean
  ): CreateView[CommonCreateViewOptions] =
    CreateView(name, orReplace, query, CommonCreateViewOptions(materialized, temporary))
  def apply(name: ast.Name, orReplace: Boolean, query: SelectBody): CreateView[CommonCreateViewOptions] =
    CreateView(name, orReplace, query, CommonCreateViewOptions.empty)

case class AlterView(name: ast.Name, action: AlterViewAction) extends Statement

case class DropView[DVO <: DropViewOptions](name: ast.Name, ifExists: Boolean = false, options: DVO) extends Statement

object DropView:
  def apply(name: ast.Name, ifExists: Boolean): DropView[CommonDropViewOptions] =
    DropView(name, ifExists, CommonDropViewOptions.empty)
  def apply(name: ast.Name): DropView[CommonDropViewOptions] =
    DropView(name, false, CommonDropViewOptions.empty)

case class Explain[EO <: ExplainOptions](query: SelectBody, options: EO) extends Statement

object Explain:
  def apply(query: SelectBody): Explain[CommonExplainOptions] = Explain(query, CommonExplainOptions.empty)

/** Empty statement (whitespace/comments only). Used for comment-only statements or empty statements with just
  * terminators.
  */
case class EmptyStatement() extends Statement

/** Unparseable statement (parse error recovery). Captures statements that failed to parse, allowing the parser to
  * continue.
  */
case class Unparseable(content: String) extends Statement

/** Trait for COMMENT ON TABLE statements. Dialect-specific comment statements should extend this. */
trait TableCommentStatement extends Statement:
  def tableName: String
  def comment: String

/** Trait for COMMENT ON COLUMN statements. Dialect-specific comment statements should extend this. */
trait ColumnCommentStatement extends Statement:
  def tableName: String
  def columnName: String
  def comment: String
