ALTER TABLE "GUI_XMDM_F7"."COMMENT_VALUES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_COMMENT_VALUES PRIMARY KEY (COL_GUI_NAME, DISPLAY_ORDER);
ALTER TABLE "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_EUREX_REPO_KEY_FIGURES PRIMARY KEY (KEY_NAME, VALID_FROM);
ALTER TABLE "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MAP_MEMBER_TO_BILLING_GROUP PRIMARY KEY (MEMBER_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT" ADD ("IS_SELECT_FINANCE_MEMBER" CHAR(1 BYTE)) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MAP_PARTICIPANT_TO_PARENT PRIMARY KEY (SAP_MEMBER_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_PRICE_TRADE_MONITOR_PARAMETERS PRIMARY KEY (MARKET);
ALTER TABLE "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT" ADD ("IS_SELECT_FINANCE_MEMBER" CHAR(1 BYTE));
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR" (
  "BUSINESS_DATE" TIMESTAMP NOT NULL,
  "TRADE_ID" NUMBER(19, 0) NOT NULL,
  "PURCHASE_DATE" DATE,
  "REPURCHASE_DATE" DATE,
  "BASKET" VARCHAR2(50 BYTE) NOT NULL,
  "BUYER" VARCHAR2(50 BYTE),
  "SELLER" VARCHAR2(50 BYTE),
  "CONTRACT_TERM" VARCHAR2(50 BYTE),
  "CURRENCY" VARCHAR2(50 BYTE) NOT NULL,
  "RATE" NUMBER(126) NOT NULL,
  "MEAN" NUMBER(126),
  "STANDARD_DEVIATION" NUMBER(126),
  "LOWER_BOUND" VARCHAR2(50 BYTE),
  "UPPER_BOUND" VARCHAR2(50 BYTE),
  "ESTIMATION" VARCHAR2(250 BYTE),
  "DESCRIPTION_GUI" VARCHAR2(250 BYTE),
  "COMMENT_GUI" VARCHAR2(250 BYTE),
  "RESULT_ACTION" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "MARKET" VARCHAR2(50 BYTE),
  "AVERAGE" VARCHAR2(50 BYTE),
  "LOWER_BOUND_AVG" VARCHAR2(50 BYTE),
  "UPPER_BOUND_AVG" VARCHAR2(50 BYTE)
);;
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_AT" (
  "BUSINESS_DATE" TIMESTAMP NOT NULL,
  "TRADE_ID" NUMBER(19, 0) NOT NULL,
  "PURCHASE_DATE" DATE,
  "REPURCHASE_DATE" DATE,
  "BASKET" VARCHAR2(50 BYTE) NOT NULL,
  "BUYER" VARCHAR2(50 BYTE),
  "SELLER" VARCHAR2(50 BYTE),
  "CONTRACT_TERM" VARCHAR2(50 BYTE),
  "CURRENCY" VARCHAR2(50 BYTE) NOT NULL,
  "RATE" NUMBER(126) NOT NULL,
  "MEAN" NUMBER(126),
  "STANDARD_DEVIATION" NUMBER(126),
  "LOWER_BOUND" VARCHAR2(50 BYTE),
  "UPPER_BOUND" VARCHAR2(50 BYTE),
  "ESTIMATION" VARCHAR2(250 BYTE),
  "DESCRIPTION_GUI" VARCHAR2(250 BYTE),
  "COMMENT_GUI" VARCHAR2(250 BYTE),
  "RESULT_ACTION" VARCHAR2(250 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "MARKET" VARCHAR2(50 BYTE),
  "AVERAGE" VARCHAR2(50 BYTE),
  "LOWER_BOUND_AVG" VARCHAR2(50 BYTE),
  "UPPER_BOUND_AVG" VARCHAR2(50 BYTE)
);;
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS_AT" (
  "MARKET" VARCHAR2(50 BYTE) NOT NULL,
  "SPAN" NUMBER(19, 0) NOT NULL,
  "OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL,
  "MIN_OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL,
  "NUMBER_OF_STDDEV" NUMBER(19, 0) NOT NULL,
  "FEES_IN_BP" NUMBER(19, 0) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;