ALTER TABLE "GUI_XMDM_LST"."BACKUP_ARRANGEMENT" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_BACKUP_ARRANGEMENT PRIMARY KEY (MEMBER_ROLE);
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_DEF_ASSIGN" DROP COLUMN "ISSUER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_COUNTERPARTY_DEF_ASSIGN PRIMARY KEY (SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_ROLE_ASSIGN" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_COUNTERPARTY_ROLE_ASSIGN PRIMARY KEY (SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_ASN" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CP_EXCL_SET_ASN PRIMARY KEY (SCENARIO_CODE, COUNTERPARTY_EXCL_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CP_EXCL_SET_MSTR PRIMARY KEY (COUNTERPARTY_EXCL_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CP_EXCL_SET_MSTR PRIMARY KEY (COUNTERPARTY_EXCL_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."CST_MP_SCAL_FACTOR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CST_MP_SCAL_FACTOR PRIMARY KEY (CST_SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_CFG" DROP COLUMN "CST_SCENARIO_PURPOSE" ADD ("CST_GOBAL_SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CST_SCEN_GROUP_CFG PRIMARY KEY (CST_GBL_SCENARIO_GROUP_CODE, CST_GOBAL_SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CST_SCEN_GROUP_MSTR PRIMARY KEY (CST_GBL_SCENARIO_GROUP_CODE);
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_PRIORITY" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CURRENCY_PRIORITY PRIMARY KEY (CURRENCY_CODE);
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_CFG" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CURRENCY_SET_CFG PRIMARY KEY (CURRENCY_SET_CODE, CURRENCY_CODE);
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_CURRENCY_SET_MSTR PRIMARY KEY (CURRENCY_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."DQA_ABORTS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LST_DQA_ABORTS PRIMARY KEY (FACT_DATE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_CFG" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_CFG PRIMARY KEY (FLOW_TYPE_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_COMP PRIMARY KEY (SCENARIO_CODE, FLOW_TYPE_COMPONENT_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_COMP_MSTR PRIMARY KEY (FLOW_TYPE_COMPONENT_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_CFG" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_GROUP_CFG PRIMARY KEY (FLOW_TYPE_REP_GROUP_CODE, FLOW_TYPE_GROUP_CODE, FLOW_TYPE_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_MASTER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LOW_TYPE_GROUP_MASTER PRIMARY KEY (FLOW_TYPE_GROUP_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_REP_GROUP_MASTER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_REP_GROUP_MASTER PRIMARY KEY (FLOW_TYPE_REP_GROUP_CODE);
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_SCALE_FACT" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_FLOW_TYPE_SCALE_FACT PRIMARY KEY (FLOW_TYPE_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_CHANNEL_CFG" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_CHANNEL_CFG PRIMARY KEY (MOBILIZATION_CHANNEL_CODE, MOBILIZATION_BASKET_CODE, MOBILIZATION_CURRENCY_CODE, CURRENCY_VIEW_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_CHANNEL_FLOW_TYPE_ASN" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_CHANNEL_FLOW_TYPE_ASN PRIMARY KEY (MOB_CHANNEL_CODE, FLOW_TYPE_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_CHANNEL_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LST_MOB_CHANNEL_MSTR PRIMARY KEY (MOB_CHANNEL_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_CHANNEL_TYPE_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_CHANNEL_TYPE_MSTR PRIMARY KEY (MOB_CHANNEL_TYPE_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_FACTOR_SET_CONF" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_FACTOR_SET_CONF PRIMARY KEY (MOBILIZATION_FACTOR_SET_CODE, FLOW_TYPE_CODE, CURRENCY_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_FACTOR_SET_MSTR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_FACTOR_SET_MSTR PRIMARY KEY (MOBILIZATION_FACTOR_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_JURISDICTIONS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_JURISDICTIONS PRIMARY KEY (CMS_REGION_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_SET_CFG" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_SET_CFG PRIMARY KEY (MOBILIZATION_SET_CODE, MOBILIZATION_COMPONENT_CODE, MOBILIZATION_CALC_LOGIC_CODE, MOBILIZATION_CHANNEL_CODE, MOBILIZATION_FACTOR_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_SET_CFG_CHANNEL" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_SET_CFG_CHANNEL PRIMARY KEY (MOB_SET_CODE, MOB_CHANNEL_CODE, MOB_CURRENCY);
ALTER TABLE "GUI_XMDM_LST"."MOB_SET_CFG_COMPONENTS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_SET_CFG_COMPONENTS PRIMARY KEY (MOB_SET_CODE, MOB_COMPONENT_CODE);
ALTER TABLE "GUI_XMDM_LST"."MOB_SET_MSTR" ADD ("MOBILIZATION_CALC_LOGIC_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL) ADD ("MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MOB_SET_MSTR PRIMARY KEY (MOBILIZATION_SET_CODE);
ALTER TABLE "GUI_XMDM_LST"."OTHER_LST_COMPONENTS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTHER_LST_COMPONENTS PRIMARY KEY (FLOW_TYPE_CODE, CURRENCY_VIEW_CODE, PARAM_VALUE_TYPE_CODE, PARAM_VALUE_UNIT_CODE, CURRENCY_CODE);
ALTER TABLE "GUI_XMDM_LST"."QUALITY_CHECK_DEF" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LST_QA_DEF PRIMARY KEY (CHECK_ID);
ALTER TABLE "GUI_XMDM_LST"."REPORTING_COMP_MSTR" ADD ("REPORTING_ORDER_NO" NUMBER) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_REPORTING_COMP_MSTR PRIMARY KEY (REPORTING_COMPONENT_CODE);
ALTER TABLE "GUI_XMDM_LST"."SCENARIO_GROUP_MASTER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_SCENARIO_GROUP_MASTER PRIMARY KEY (SCENARIO_GROUP_CODE);
ALTER TABLE "GUI_XMDM_LST"."SCENARIO_TYPE_MASTER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_SCENARIO_TYPE_MASTER PRIMARY KEY (SCENARIO_TYPE);
ALTER TABLE "GUI_XMDM_LST"."SET_RULE_ASN" MODIFY ("MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LST_SET_RULE_ASN PRIMARY KEY (SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."SET_RULE_ASN" MODIFY ("MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_LST_SET_RULE_ASN PRIMARY KEY (SCENARIO_CODE);
ALTER TABLE "GUI_XMDM_LST"."BACKUP_ARRANGEMENT_AT" MODIFY ("BACKUP_ARRANGEMENT_IN_DAYS" NUMBER NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_DEF_ASSIGN_AT" DROP COLUMN "ISSUER";
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_CFG_AT" DROP COLUMN "CST_SCENARIO_PURPOSE" ADD ("CST_GOBAL_SCENARIO_CODE" VARCHAR2(256 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."DQA_ABORTS_AT" DROP COLUMN "ITS" MODIFY ("FACT_DATE" DATE NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."MOB_SET_MSTR_AT" ADD ("MOBILIZATION_CALC_LOGIC_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL) ADD ("MOBILIZATION_FACTOR_SET_CODE" VARCHAR2(256 BYTE) DEFAULT 'NA' NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."OTHER_LST_COMPONENTS_AT" MODIFY ("PARAM_VALUE_TYPE_CODE" VARCHAR2(256 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."QUALITY_CHECK_DEF_AT" DROP COLUMN "ITS" MODIFY ("CHECK_ID" NUMBER NOT NULL);
ALTER TABLE "GUI_XMDM_LST"."REPORTING_COMP_MSTR_AT" ADD ("REPORTING_ORDER_NO" NUMBER);
ALTER TABLE "GUI_XMDM_LST"."SET_RULE_ASN_AT" MODIFY ("MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NULL);
ALTER TABLE "GUI_XMDM_LST"."SET_RULE_ASN_AT" MODIFY ("MOBILIZATION_SET_CODE" VARCHAR2(256 BYTE) NULL);
CREATE TABLE "GUI_XMDM_LST"."AGGREGATION_LEVELS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "ENTITY" VARCHAR2(50 BYTE) NOT NULL,
  "AGG_GROUP" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_AGGREGATION_LEVELS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."BASKET_CAPACITIES" (
  "CATEGORY_I" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY_II" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_BASKET" VARCHAR2(50 BYTE) NOT NULL,
  "CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  "CAP_IN_BN_SINGLE_CURR" NUMBER(7, 3) NOT NULL,
  "CAP_IN_BN_AGG" NUMBER(7, 3) NOT NULL,
  "HAIRCUT" NUMBER(3, 0),
  "CROSS_CURR_HAIRCUT" NUMBER(3, 2),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_BASKET_CAPACITIES" PRIMARY KEY ("CATEGORY_I", "CATEGORY_II", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY_FAILURE" VARCHAR2(50 BYTE),
  "CASH_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_COMPANY_CAP" VARCHAR2(50 BYTE) NOT NULL,
  "SEC_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE),
  "SEC_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE),
  "OTC_CURRENCY_PREFUNDING" VARCHAR2(50 BYTE),
  "OWN_FUNDS" VARCHAR2(50 BYTE) NOT NULL,
  "CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "COLLATERALISED_CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "OTC_CURRENCY_SWAPLINES" VARCHAR2(50 BYTE),
  "CCP_PREFINANCING_ACTIVITIES" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99_9" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COMPONENT_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET_CONFIG" (
  "FLOW_TYPE_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_SECURITIES_INDICATOR" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_GROUP" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "ESMA_FLOW_TYPE" VARCHAR2(50 BYTE),
  "ALLOWED_USAGE" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COMPONENT_SET_CONFIG" PRIMARY KEY ("FLOW_TYPE_CODE", "FLOW_TYPE_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_EX_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY__EX_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_EX_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_SET" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CLEARING_MEMBER" VARCHAR2(50 BYTE),
  "CLEARING_INSTITUTE" VARCHAR2(50 BYTE),
  "LIQUIDITY_PROVIDER" VARCHAR2(50 BYTE),
  "NOSTRO_AGENT" VARCHAR2(50 BYTE),
  "SETTLEMENT_BANK" VARCHAR2(50 BYTE),
  "CUSTODIAN_BANK" VARCHAR2(50 BYTE),
  "PAYMENT_SEC_SET_SYSTEMS" VARCHAR2(50 BYTE),
  "ISSUER" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_COUNTERPARTY_SET" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."CST_GLOBAL_SCENARIOS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CST_GLOBAL_SCENARIOS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."CTRPARTY_EXCL_SETS_CONFIG" (
  "CTRPARTY_EXCLUSION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "MEMBERS" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CTRPARTY_EXCL_SETS_CONFIG" PRIMARY KEY ("CTRPARTY_EXCLUSION_SET", "MEMBERS", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."GLOBAL_CST_SCENARIO_CONFIG" (
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_PURPOSE" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_COUNT" NUMBER(4, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_GLOBAL_CST_SCENARIO_CONFIG" PRIMARY KEY ("CST_GLOBAL_SCENARIO_GROUPING", "SCENARIO_PURPOSE", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."LST_MASTER_DATA" (
  "LST_MASTER_DATA_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "CALCULATION_PRIORITY" NUMBER,
  "CALCULATION_FREQUENCY" VARCHAR2(50 BYTE) NOT NULL,
  "ACTIVE_FLAG" CHAR(1 BYTE) NOT NULL,
  "NO_OF_FAILED_COUNTERPARTS" NUMBER(4, 0) NOT NULL,
  "COUNTERPARTY_GROUP" VARCHAR2(50 BYTE),
  "TIME_HORIZON" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_LST_MASTER_DATA" PRIMARY KEY ("LST_MASTER_DATA_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOBILIZATION_SETS" PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS_CONFIG" (
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILISATION_LAG" NUMBER(4, 0) NOT NULL,
  "CALCULATION_LOGIC" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_MOBILIZATION_SETS_CONFIG" PRIMARY KEY ("MOBILIZATION_SET", "COMPONENT", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."REFINANCING_FACTORS" (
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "REFINANCING_FACTOR" NUMBER(3, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_REFINANCING_FACTORS" PRIMARY KEY ("FLOW_TYPE", "REFINANCING_FACTOR", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_CLASS" (
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS_DESC" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SCENARIO_CLASS" PRIMARY KEY ("LST_SCENARIO_CLASS", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "SET_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SETS" PRIMARY KEY ("TIME_FACTOR_SET", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "SET_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SETS" PRIMARY KEY ("TIME_FACTOR_SET", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS_CONFIG" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "FROM_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TO_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR" NUMBER(8, 5),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_TIME_FACTOR_SETS_CONFIG" PRIMARY KEY ("TIME_FACTOR_SET", "FLOW_TYPE", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_LST"."AGGREGATION_LEVELS_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "ENTITY" VARCHAR2(50 BYTE) NOT NULL,
  "AGG_GROUP" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."BASKET_CAPACITIES_AT" (
  "CATEGORY_I" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY_II" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_BASKET" VARCHAR2(50 BYTE) NOT NULL,
  "CURRENCY" VARCHAR2(3 BYTE) NOT NULL,
  "CAP_IN_BN_SINGLE_CURR" NUMBER(7, 3) NOT NULL,
  "CAP_IN_BN_AGG" NUMBER(7, 3) NOT NULL,
  "HAIRCUT" NUMBER(3, 0),
  "CROSS_CURR_HAIRCUT" NUMBER(3, 2),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY_FAILURE" VARCHAR2(50 BYTE),
  "CASH_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_COLLATERAL_COMPANY_CAP" VARCHAR2(50 BYTE) NOT NULL,
  "SEC_COLLATERAL_DEF_FUND" VARCHAR2(50 BYTE),
  "SEC_COLLATERAL_MARGIN_REQ" VARCHAR2(50 BYTE),
  "OTC_CURRENCY_PREFUNDING" VARCHAR2(50 BYTE),
  "OWN_FUNDS" VARCHAR2(50 BYTE) NOT NULL,
  "CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "COLLATERALISED_CREDIT_LINES" VARCHAR2(50 BYTE) NOT NULL,
  "OTC_CURRENCY_SWAPLINES" VARCHAR2(50 BYTE),
  "CCP_PREFINANCING_ACTIVITIES" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99" VARCHAR2(50 BYTE),
  "REPAYMENTS_MEM_CASH_DEP_99_9" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."COMPONENT_SET_CONFIG_AT" (
  "FLOW_TYPE_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "CASH_SECURITIES_INDICATOR" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_GROUP" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE_COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "ESMA_FLOW_TYPE" VARCHAR2(50 BYTE),
  "ALLOWED_USAGE" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_EX_SET_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "COUNTERPARTY__EX_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."COUNTERPARTY_SET_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CLEARING_MEMBER" VARCHAR2(50 BYTE),
  "CLEARING_INSTITUTE" VARCHAR2(50 BYTE),
  "LIQUIDITY_PROVIDER" VARCHAR2(50 BYTE),
  "NOSTRO_AGENT" VARCHAR2(50 BYTE),
  "SETTLEMENT_BANK" VARCHAR2(50 BYTE),
  "CUSTODIAN_BANK" VARCHAR2(50 BYTE),
  "PAYMENT_SEC_SET_SYSTEMS" VARCHAR2(50 BYTE),
  "ISSUER" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."CST_GLOBAL_SCENARIOS_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."CTRPARTY_EXCL_SETS_CONFIG_AT" (
  "CTRPARTY_EXCLUSION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "MEMBERS" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."GLOBAL_CST_SCENARIO_CONFIG_AT" (
  "CST_GLOBAL_SCENARIO_GROUPING" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_PURPOSE" VARCHAR2(50 BYTE) NOT NULL,
  "SCENARIO_COUNT" NUMBER(4, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."LST_MASTER_DATA_AT" (
  "LST_MASTER_DATA_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "CALCULATION_PRIORITY" NUMBER,
  "CALCULATION_FREQUENCY" VARCHAR2(50 BYTE) NOT NULL,
  "ACTIVE_FLAG" CHAR(1 BYTE) NOT NULL,
  "NO_OF_FAILED_COUNTERPARTS" NUMBER(4, 0) NOT NULL,
  "COUNTERPARTY_GROUP" VARCHAR2(50 BYTE),
  "TIME_HORIZON" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS_AT" (
  "LST_SCEN_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS_CONFIG_AT" (
  "MOBILIZATION_SET" VARCHAR2(50 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "COMPONENT" VARCHAR2(50 BYTE) NOT NULL,
  "MOBILISATION_LAG" NUMBER(4, 0) NOT NULL,
  "CALCULATION_LOGIC" VARCHAR2(50 BYTE) NOT NULL,
  "CATEGORY" VARCHAR2(50 BYTE),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."REFINANCING_FACTORS_AT" (
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "REFINANCING_FACTOR" NUMBER(3, 0) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."SCENARIO_CLASS_AT" (
  "LST_SCENARIO_CLASS" VARCHAR2(50 BYTE) NOT NULL,
  "LST_SCENARIO_CLASS_DESC" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS_AT" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "SET_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS_AT" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "SET_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_LST"."TIME_FACTOR_SETS_CONFIG_AT" (
  "TIME_FACTOR_SET" VARCHAR2(50 BYTE) NOT NULL,
  "FLOW_TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "FROM_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TO_SETTLEMENT_DATE_NO" NUMBER(4, 0) NOT NULL,
  "TIME_FACTOR" NUMBER(8, 5),
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;