-- Alter table GUI_XMDM_OTC.F_OTC_IRD_CLIENT_STRUCTURE: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE" DROP CONSTRAINT "PK_F_OTC_IRD_CLIENT_STRUCTURE";

-- Alter table GUI_XMDM_OTC.F_OTC_IRD_CLIENT_STRUCTURE_AT: modify column
ALTER TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE" ADD PRIMARY KEY ("BOOK_FINAL");

-- Alter table GUI_XMDM_OTC.S_OTC_CC210_INPUT_FILTER_AT: add column
ALTER TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE_AT" MODIFY ("BOOK_FINAL" VARCHAR2(50 BYTE) NOT NULL);
