-- Alter table GUI_XMDM_NDF.NDF_REPORT_APPROVAL: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."NDF_REPORT_APPROVAL" DROP CONSTRAINT "PK_NDF_REPORT_APPROVAL";

-- Alter table GUI_XMDM_NDF.PEGGING_INDICATOR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."NDF_REPORT_APPROVAL" ADD PRIMARY KEY ("FACT_DATE");

-- Alter table GUI_XMDM_NDF.POLITICAL_STABILITY_INDEX: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."PEGGING_INDICATOR" DROP CONSTRAINT "PK_PEGGING_INDICATOR";

-- Alter table GUI_XMDM_NDF.PRICE_SOURCE_DISRUPTION_IND: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."PEGGING_INDICATOR" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.SOVEREIGN_HEALTH_INDEX: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."POLITICAL_STABILITY_INDEX" DROP CONSTRAINT "PK_POLITICAL_STABILITY_INDEX";

-- Alter table GUI_XMDM_NDF.STRESS_SCENARIO: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."POLITICAL_STABILITY_INDEX" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.STRESS_SHIFT_MUTIPLIER_NDF: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_NDF"."PRICE_SOURCE_DISRUPTION_IND" DROP CONSTRAINT "PK_PRICE_SOURCE_DISRUPTION_IND";

-- Alter table GUI_XMDM_NDF.NDF_CURRENCY_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."PRICE_SOURCE_DISRUPTION_IND" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.NDF_REPORT_APPROVAL_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."SOVEREIGN_HEALTH_INDEX" DROP CONSTRAINT "PK_SOVEREIGN_HEALTH_INDEX";

-- Alter table GUI_XMDM_NDF.PEGGING_INDICATOR_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."SOVEREIGN_HEALTH_INDEX" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.POLITICAL_STABILITY_INDEX_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."STRESS_SCENARIO" DROP CONSTRAINT "PK_STRESS_SCENARIO";

-- Alter table GUI_XMDM_NDF.PRICE_SOURCE_DISRUPTION_IND_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."STRESS_SCENARIO" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.SOVEREIGN_HEALTH_INDEX_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."STRESS_SHIFT_MUTIPLIER_NDF" DROP CONSTRAINT "PK_STRESS_SHIFT_MUTIPLIER_NDF";

-- Alter table GUI_XMDM_NDF.STRESS_SCENARIO_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."STRESS_SHIFT_MUTIPLIER_NDF" ADD PRIMARY KEY ("CURRENCY_ID");

-- Alter table GUI_XMDM_NDF.STRESS_SHIFT_MUTIPLIER_NDF_AT: modify column
ALTER TABLE "GUI_XMDM_NDF"."NDF_CURRENCY_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
