-- Alter table GUI_XMDM_RLI.COMMITTED_CREDIT_LINES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."COMMITTED_CREDIT_LINES" DROP CONSTRAINT "PK_RLI_COMMITTED_CREDIT_LINES";

-- Alter table GUI_XMDM_RLI.FIX_RLI_VALUE: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."COMMITTED_CREDIT_LINES" ADD PRIMARY KEY ("BUSINESS_PARTNER", "VALID_FROM");

-- Alter table GUI_XMDM_RLI.KLI_4: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."FIX_RLI_VALUE" DROP CONSTRAINT "PK_RLI_FIX_RLI_VALUE";

-- Alter table GUI_XMDM_RLI.LCR_C76: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."FIX_RLI_VALUE" ADD PRIMARY KEY ("FACT_DATE", "RLI_ID", "COMPONENT_NAME");

-- Alter table GUI_XMDM_RLI.LIMITS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."KLI_4" DROP CONSTRAINT "PK_RLI_KLI_4";

-- Alter table GUI_XMDM_RLI.MIN_RESERVE_CALENDAR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."KLI_4" ADD PRIMARY KEY ("OWN_FUNDS", "INTRAGROUP_FUNDING", "OPERATIONAL_LIQUIDITY");

-- Alter table GUI_XMDM_RLI.RECURRING_PAYMENTS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_RLI"."LCR_C76" DROP CONSTRAINT "PK_RLI_LCR_C76";

-- Alter table GUI_XMDM_RLI.FIX_RLI_VALUE_AT: modify column
ALTER TABLE "GUI_XMDM_RLI"."LCR_C76" ADD PRIMARY KEY ("REPDATE", "ID");

-- Alter table GUI_XMDM_RLI.LCR_C76_AT: modify column
ALTER TABLE "GUI_XMDM_RLI"."LIMITS" DROP CONSTRAINT "PK_RLI_LIMITS";

-- Alter table GUI_XMDM_RLI.RECURRING_PAYMENTS_AT: modify column
ALTER TABLE "GUI_XMDM_RLI"."LIMITS" ADD PRIMARY KEY ("LIQUIDITY_INDICATOR", "VALID_FROM");
