-- Alter table GUI_XMDM_EUREX_HFT.S_ESU_VI_INTV: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_VI_INTV" DROP CONSTRAINT "PK_S_ESU_VI_INTV";

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_MEMBER_RELATIONSHIP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_VI_INTV" ADD PRIMARY KEY ("LIMIT_TYPE", "PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM");

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_TRANS_VI_INTV: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_MEMBER_RELATIONSHIP" DROP CONSTRAINT "PK_S_HFT_MEMBER_RELATIONSHIP";

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_VOLATILITY_INDICATOR: modify column, drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_MEMBER_RELATIONSHIP" ADD PRIMARY KEY ("MEMBER_ID", "REPORTING_MEMBER_ID", "VALID_FROM");

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_VOLUME_VI_INTV: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_VI_INTV" DROP CONSTRAINT "PK_S_HFT_TRANS_VI_INTV";

-- Alter table GUI_XMDM_EUREX_HFT.S_ESU_VI_INTV_AT: modify column
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_VI_INTV" ADD PRIMARY KEY ("PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM");

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_TRANS_VI_INTV_AT: modify column
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR" MODIFY ("PRIMARY_FLAG" CHAR(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_VOLATILITY_INDICATOR_AT: modify column
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR" DROP CONSTRAINT "PK_S_HFT_VOLATILITY_INDICATOR";

-- Alter table GUI_XMDM_EUREX_HFT.S_HFT_VOLUME_VI_INTV_AT: modify column
ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR" ADD PRIMARY KEY ("PRODUCT_TYPE", "REFERENCE_PRODUCT", "VALID_FROM");
