-- Create table GUI_XMDM_F7.PRICE_TRADE_MONITOR_PARAMETERS_AT
CREATE TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS_AT" ("MARKET" VARCHAR2(50 BYTE) NOT NULL, "SPAN" NUMBER(19, 0) NOT NULL, "OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL, "MIN_OBSERVATIONS_FOR_STDDEV" NUMBER(19, 0) NOT NULL, "NUMBER_OF_STDDEV" NUMBER(19, 0) NOT NULL, "FEES_IN_BP" NUMBER(19, 0) NOT NULL, "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP, "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Alter table GUI_XMDM_F7.COMMENT_VALUES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_F7"."COMMENT_VALUES" DROP CONSTRAINT "PK_COMMENT_VALUES";

-- Alter table GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_F7"."COMMENT_VALUES" ADD PRIMARY KEY ("COL_GUI_NAME", "DISPLAY_ORDER");

-- Alter table GUI_XMDM_F7.MAP_MEMBER_TO_BILLING_GROUP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES" DROP CONSTRAINT "PK_EUREX_REPO_KEY_FIGURES";

-- Alter table GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES" ADD PRIMARY KEY ("KEY_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_F7.PRICE_TRADE_MONITOR_PARAMETERS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP" DROP CONSTRAINT "PK_MAP_MEMBER_TO_BILLING_GROUP";

-- Set comment on column GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES_AT.KEY_NAME
ALTER TABLE "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP" ADD PRIMARY KEY ("MEMBER_ID", "VALID_FROM");

-- Set comment on column GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES_AT.KEY_VALUE
ALTER TABLE "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT" DROP CONSTRAINT "PK_MAP_PARTICIPANT_TO_PARENT";

-- Set comment on column GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES_AT.VALUE_LAST_YEAR
ALTER TABLE "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT" ADD PRIMARY KEY ("SAP_MEMBER_ID", "VALID_FROM");

-- Set comment on column GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES_AT.VALID_FROM
ALTER TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS" DROP CONSTRAINT "PK_PRICE_TRADE_MONITOR_PARAMETERS";

-- Set comment on column GUI_XMDM_F7.EUREX_REPO_KEY_FIGURES_AT.VALID_TO
ALTER TABLE "GUI_XMDM_F7"."PRICE_TRADE_MONITOR_PARAMETERS" ADD PRIMARY KEY ("MARKET");

-- Set comment on column GUI_XMDM_F7.MAP_MEMBER_TO_BILLING_GROUP_AT.MEMBER_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES_AT"."KEY_NAME" IS 'Name of Key Figure, which displayed in the report "Daily Key Figures"; use upper-case letters';

-- Set comment on column GUI_XMDM_F7.MAP_MEMBER_TO_BILLING_GROUP_AT.BILLING_GROUP
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES_AT"."KEY_VALUE" IS 'Target Value in billion of the Key Figure for the actual year - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"';

-- Set comment on column GUI_XMDM_F7.MAP_MEMBER_TO_BILLING_GROUP_AT.VALID_FROM
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES_AT"."VALUE_LAST_YEAR" IS 'Average value of Key Figure of the last year in billion - use format: "." as decimal separator and 3 decimal places, use "," as thousand separator, e.g.: "1,234.123"';

-- Set comment on column GUI_XMDM_F7.MAP_MEMBER_TO_BILLING_GROUP_AT.VALID_TO
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES_AT"."VALID_FROM" IS 'start date of validity';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.GP_NR
COMMENT ON COLUMN "GUI_XMDM_F7"."EUREX_REPO_KEY_FIGURES_AT"."VALID_TO" IS 'end date of validity';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.ZHS_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP_AT"."MEMBER_ID" IS 'sap member id of a participant';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.F7_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP_AT"."BILLING_GROUP" IS 'billing group, e.g. L1, L2';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.SAP_MEMBER_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP_AT"."VALID_FROM" IS 'start date of validity';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.PARENT_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_MEMBER_TO_BILLING_GROUP_AT"."VALID_TO" IS 'end date of validity';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.XEMAC_CLEARER_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."GP_NR" IS 'member GP number';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.XEMAC_MEMBER_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."ZHS_ID" IS 'id in source system ZHS';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.CCP_CM_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."F7_ID" IS 'member id for participant in F7 system';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.CCP_TM_ID
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."SAP_MEMBER_ID" IS 'SAP member id for participant';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.IS_CORPORATE
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."PARENT_ID" IS 'SAP member id for parent participant';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.VALID_FROM
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."XEMAC_CLEARER_ID" IS 'clearer id in XEMAC';

-- Set comment on column GUI_XMDM_F7.MAP_PARTICIPANT_TO_PARENT_AT.VALID_TO
COMMENT ON COLUMN "GUI_XMDM_F7"."MAP_PARTICIPANT_TO_PARENT_AT"."XEMAC_MEMBER_ID" IS 'member id in XEMAC';
