ALTER TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_REASONS_AT" MODIFY ("LOG_REASON" NUMBER(10, 0) NULL);
ALTER TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_REASONS_AT" MODIFY ("LOG_REASON" NUMBER(10, 0) NULL);
CREATE TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_REASONS" (
  "LOG_REASON" NUMBER(10, 0),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_XETRA_HFT"."S_OTR_REASONS" (
  "LOG_REASON" NUMBER(10, 0),
  "ITS" DATE DEFAULT SYSDATE
);;