CREATE TABLE "GUI_XMDM_SC_LC"."SHORT_LONG_CODE" (
  "MIC" VARCHAR2(4 BYTE) NOT NULL,
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  "SHORTCODE" NUMBER(20, 0) NOT NULL,
  "LONGVALUE" VARCHAR2(35 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "REASON" VARCHAR2(100 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SHORT_LONG_CODE" PRIMARY KEY ("MIC", "MEMBER_ID", "SHORTCODE")
);;
CREATE TABLE "GUI_XMDM_SC_LC"."SHORT_LONG_CODE_AT" (
  "MIC" VARCHAR2(4 BYTE) NOT NULL,
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  "SHORTCODE" NUMBER(20, 0) NOT NULL,
  "LONGVALUE" VARCHAR2(35 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "REASON" VARCHAR2(100 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;