-- Alter table GUI_XMDM_EUREX_RTS24.S_CERTIFIED_DEA_MEMBERS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_EUREX_RTS24"."S_CERTIFIED_DEA_MEMBERS" DROP CONSTRAINT "PK_RTS24_EUREX_CERT_MEMBER";
