-- Alter table GUI_XMDM_MMPM_EEX.S_EX_SW_MM_PRODUCT_SCOPE: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_EX_SW_MM_PRODUCT_SCOPE" MODIFY ("PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_FULFILLMENT_RULES: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_FULFILLMENT_RULES" MODIFY ("PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_PCKG_CAL_SPRD_MTRX: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_PCKG_CAL_SPRD_MTRX" MODIFY ("LEG01_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_EX_SW_MM_PRODUCT_SCOPE_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_PCKG_CAL_SPRD_MTRX" MODIFY ("LEG02_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT NULL);

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_FULFILLMENT_RULES_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_EX_SW_MM_PRODUCT_SCOPE_AT" MODIFY ("PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_PCKG_CAL_SPRD_MTRX_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_FULFILLMENT_RULES_AT" MODIFY ("PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_PRODUCT_SETUP_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_PCKG_CAL_SPRD_MTRX_AT" MODIFY ("LEG01_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y');

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_SIZE_CLASS_DT_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_PCKG_CAL_SPRD_MTRX_AT" MODIFY ("LEG02_PRIMARY_FLAG" VARCHAR2(1 BYTE) DEFAULT NULL);

-- Alter table GUI_XMDM_MMPM_EEX.S_MMPRM_SPREAD_CLASS_DT_AT: modify column
ALTER TABLE "GUI_XMDM_MMPM_EEX"."S_MMPRM_PRODUCT_SETUP_AT" MODIFY ("BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE));
