ALTER TABLE "GUI_XMDM_REV_SHARING"."D_CREDIT_MEMBER_ADDRESSES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_CREDIT_MEMBER_ADDRESSES PRIMARY KEY (MEMBER_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_OBJ_BGC_OTC_MEMB_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_OBJ_BGC_OTC_MEMB_MAP PRIMARY KEY (ETD_MEMBER_ID, OTC_MEMBER_ID, BGC_MEMBER_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_CAPLAB_MEM_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_CAPLAB_MEM_MAP PRIMARY KEY (CAPLAB_MEMB_ID, OTC_MEMBER_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_MEMBER_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_FQPM_MEMBER_MAP PRIMARY KEY (MEMBER_ID, PARTICIPANT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_PLATFORM_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_FQPM_PLATFORM_MAP PRIMARY KEY (MEMBER_ID, PLATFORM_ID, PROTOCOL, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_MULT" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_FQPM_THOLD_MULT PRIMARY KEY (PROTOCOL, FQPM_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_STRM" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_FQPM_THOLD_STRM PRIMARY KEY (PROTOCOL, FQPM_ID, TENOR, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_TIER_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_FQPM_TIER_MAP PRIMARY KEY (MEMBER_ID, STREAMING_TYPE, EUREX_TIER, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_GOLD_PACKAGE_HOLDERS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_GOLD_PACK_HOLDERS PRIMARY KEY (PARTICIPANTS_GROUP_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMBER_ADDRESSES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_MEMBER_ADDRESSES PRIMARY KEY (MEMBER_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMB_ACCOUNT_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_MEMB_ACCOUNT_MAP PRIMARY KEY (MEMBER_ID, ACCOUNT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_OTC_UGR_LEI" MODIFY ("FRA_HOUR" NUMBER(*, 0) NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_OTC_UGR_LEI PRIMARY KEY (LEI_CODE, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VMWM_OTC_MEM_MAP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_D_REV_SHA_VMWM_OTC_MEM_MAP PRIMARY KEY (VMWM_MEMBER_ID, OTC_MEMBER_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."ECAG_PP_CPI" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_ECAG_PP_CPI PRIMARY KEY (CPI_YEAR);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_CB012_DATA" MODIFY ("ROW_INDEX" NUMBER NOT NULL) ADD CONSTRAINT PK_EFS_CB012_DATA PRIMARY KEY (ROW_INDEX);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_ETD_DATA" MODIFY ("ROW_INDEX" NUMBER NOT NULL) ADD CONSTRAINT PK_EFS_ETD_DATA PRIMARY KEY (ROW_INDEX);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_VALIDATION_REPORT" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_EFS_VALIDATION_REPORT PRIMARY KEY (SOURCE, TRADE_DATE, ETD_MEMBER_ID, OTC_MEMBER_ID, MARKETWIRE_ID, VALIDATION_REMARKS);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_EFS_BBG_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_F_REV_SHA_EFS_BBG_DATA PRIMARY KEY (PRODUCT_ID, TRADE_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_WEMATCH_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_F_REV_SHA_WEMATCH_DATA PRIMARY KEY (SERVICE_NAME, TRADE_DATE, CLIENT, TRADE_SIZE, EFFECTIVE_DATE, EXPIRY_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."MEMBER_MAPPING" ADD ("STIR_GROUP_ID" VARCHAR2(50 BYTE) DEFAULT 'EMPTY' NOT NULL) ADD ("CREDIT_GROUP_ID" VARCHAR2(50 BYTE) DEFAULT 'EMPTY' NOT NULL) DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_MEMBER_MAPPING PRIMARY KEY (MEMBER_NAME, OTC_IRD_GROUP_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_AFFILIATED_TRANS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_AFFILIATED_TRANS PRIMARY KEY (VALID_FROM, MEMBER_ID, ENTITY);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_MULTIPLIER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_MULTIPLIER PRIMARY KEY (MULTIPLIER_NAME, PARTICIPANTS_GROUP_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_NRSP_ADJ" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_NRSP_ADJ PRIMARY KEY (REPORTING_MONTH);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_RED_PART_GROUP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_RED_PART_GROUP PRIMARY KEY (MONTH);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_SPECIAL_INCENTIVES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_SPECIAL_INCENTIVES PRIMARY KEY (VALID_FROM, CURRENCY_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_GROWTH_PRODUCT" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_TERM_GROWTH_PRODUCT PRIMARY KEY (MONTH);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_PART_GROUP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_OTC_IRD_TERM_PART_GROUP PRIMARY KEY (PARICIPANTS_GROUP_ID, MONTH);
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_PARTICIPANTS_GROUP PRIMARY KEY (PARTICIPANTS_GROUP_ID, PARTICIPANT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_REPO" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_PARTICIPANTS_GROUPS_REPO PRIMARY KEY (PARTICIPANTS_GROUP_ID, PARTICIPANT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_STIR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_PARTICIPANTS_GROUPS_STIR PRIMARY KEY (PARTICIPANTS_GROUP_ID, PARTICIPANT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."REPO_CLEARING_CORRECTIONS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_REPO_CLEARING_CORRECTIONS PRIMARY KEY (MONTH, PARTICIPANT_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."REPO_MULTIPLIER" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_REPO_MULTIPLIER PRIMARY KEY (MULTIPLIER_NAME, PARTICIPANTS_GROUP_ID, VALID_FROM);
ALTER TABLE "GUI_XMDM_REV_SHARING"."STIR_MEMBERS_MUGR" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_STIR_MUGR_GROUPS PRIMARY KEY (MONTH, PARTICIPANT_ID);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_CONTROL_CTM" ADD ("MANUAL_SCOPE_MONTH" VARCHAR2(6 BYTE)) ADD ("MANUAL_SCOPE_REPORT" VARCHAR2(20 BYTE));
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_BGC_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_S_REV_SHA_EFS_BGC_DATA PRIMARY KEY (MARKETWIRE_ID, TRADE_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_ICAP_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_S_REV_SHA_EFS_ICAP_DATA PRIMARY KEY (MARKETWIRE_ID, TRADE_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_TP_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_S_REV_SHA_EFS_TP_DATA PRIMARY KEY (ORIGINAL_TRADE_MATCH_ID, MARKETWIRE_ID, ETD_MEMBER_ID, OTC_MEMBER_ID, TRADE_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_TP_DATA" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_S_REV_SHA_EFS_TP_DATA PRIMARY KEY (ORIGINAL_TRADE_MATCH_ID, MARKETWIRE_ID, ETD_MEMBER_ID, OTC_MEMBER_ID, TRADE_DATE);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_LOG_CTM" MODIFY ("JOB_NET_TRIGGERED_BY" VARCHAR2(35 BYTE) NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_OBJ_BGC_OTC_MEMB_MAP_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_CAPLAB_MEM_MAP_AT" MODIFY ("CAPLAB_MEMB_ID" VARCHAR2(200 BYTE) NOT NULL) MODIFY ("OTC_MEMBER_ID" VARCHAR2(50 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_STRM_AT" MODIFY ("AVG_TIME_THRESHOLD" NUMBER(19, 2) NOT NULL) MODIFY ("AVG_SIZE_THRESHOLD" NUMBER(19, 2) NOT NULL) MODIFY ("AVG_SPREAD_THRESHOLD" NUMBER(19, 2) NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_OTC_UGR_LEI_AT" MODIFY ("FRA_HOUR" NUMBER(*, 0) NULL) MODIFY ("ACTION" CHAR(1 BYTE) NULL) MODIFY ("STATUS" CHAR(1 BYTE) NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VMWM_OTC_MEM_MAP_AT" MODIFY ("VMWM_MEMBER_ID" VARCHAR2(200 BYTE) NOT NULL) MODIFY ("OTC_MEMBER_ID" VARCHAR2(50 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_CB012_DATA_AT" MODIFY ("ROW_INDEX" NUMBER NOT NULL) MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_ETD_DATA_AT" MODIFY ("ROW_INDEX" NUMBER NOT NULL) MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_VALIDATION_REPORT_AT" MODIFY ("ETD_MEMBER_ID" VARCHAR2(10 CHAR) NOT NULL) MODIFY ("OTC_MEMBER_ID" VARCHAR2(10 CHAR) NOT NULL) MODIFY ("MARKETWIRE_ID" VARCHAR2(20 CHAR) NOT NULL) MODIFY ("VALIDATION_REMARKS" VARCHAR2(50 CHAR) NOT NULL) MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_CAPITALLAB_DATA_AT" ADD ("ROW_INDEX" NUMBER NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_EFS_BBG_DATA_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOLMATCH_DATA_AT" ADD ("ROW_INDEX" NUMBER NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_WEMATCH_DATA_AT" MODIFY ("SERVICE_NAME" VARCHAR2(100 BYTE) NOT NULL) MODIFY ("TRADE_DATE" DATE NOT NULL) MODIFY ("CLIENT" VARCHAR2(200 BYTE) NOT NULL) MODIFY ("TRADE_SIZE" NUMBER(26, 12) NOT NULL) MODIFY ("EFFECTIVE_DATE" DATE NOT NULL) MODIFY ("EXPIRY_DATE" DATE NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."MEMBER_MAPPING_AT" ADD ("STIR_GROUP_ID" VARCHAR2(50 BYTE) DEFAULT 'EMPTY' NOT NULL) ADD ("CREDIT_GROUP_ID" VARCHAR2(50 BYTE) DEFAULT 'EMPTY' NOT NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_AFFILIATED_TRANS_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_RED_PART_GROUP_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_SPECIAL_INCENTIVES_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_GROWTH_PRODUCT_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_PART_GROUP_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_CONTROL_CTM_AT" ADD ("MANUAL_SCOPE_MONTH" VARCHAR2(6 BYTE)) ADD ("MANUAL_SCOPE_REPORT" VARCHAR2(20 BYTE)) MODIFY ("JOB_NET" VARCHAR2(100 BYTE) NULL) MODIFY ("JOB_NET_STATUS" VARCHAR2(50 BYTE) NULL) MODIFY ("JOB_NET_ITS" DATE NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_BGC_DATA_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_ICAP_DATA_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_TP_DATA_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_TP_DATA_AT" MODIFY ("ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL);
ALTER TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_LOG_CTM_AT" MODIFY ("JOB_NET_TRIGGERED_BY" VARCHAR2(35 BYTE) NULL);
CREATE TABLE "GUI_XMDM_REV_SHARING"."CREDIT_AFFILIATED_TRANS" (
  "MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "LEI" VARCHAR2(20 CHAR),
  "UNIQUE_IDENTIFIER" VARCHAR2(50 CHAR) NOT NULL,
  "CLEARING_MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRANSACTION_ACCOUNT" VARCHAR2(32 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_CREDIT_AFFILIATED_TRANS" PRIMARY KEY ("MEMBER_ID", "UNIQUE_IDENTIFIER", "CLEARING_MEMBER_ID", "TRANSACTION_ACCOUNT", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."CREDIT_MEMBERS_MUGR" (
  "MONTH" NUMBER NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "MUGR" NUMBER(26, 12),
  CONSTRAINT "PK_CREDIT_MEMBERS_MUGR" PRIMARY KEY ("MONTH", "PARTICIPANT_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VOICE_MEM_MAP" (
  "VOICE_DEALER" VARCHAR2(200 BYTE) NOT NULL,
  "OTC_MEMBER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_D_REV_SHA_VOICE_MEM_MAP" PRIMARY KEY ("VOICE_DEALER", "OTC_MEMBER_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_STIR_MEMBER_ADDRESSES" (
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  "STREET" VARCHAR2(255 BYTE) NOT NULL,
  "CITY" VARCHAR2(255 BYTE) NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_D_STIR_MEMBER_ADDRESSES" PRIMARY KEY ("MEMBER_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."EFS_RECONCILIATION_REPORT" (
  "ROW_INDEX" NUMBER(*, 0) NOT NULL,
  "SOURCE" VARCHAR2(16 BYTE) NOT NULL,
  "TRADE_DATE" DATE NOT NULL,
  "ETD_MEMBER_ID" VARCHAR2(10 BYTE) NOT NULL,
  "ORIGINAL_TRADE_MATCH_ID" VARCHAR2(19 BYTE) NOT NULL,
  "OTC_MEMBER_ID" VARCHAR2(10 BYTE) NOT NULL,
  "MARKETWIRE_ID" VARCHAR2(256 BYTE) NOT NULL,
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "CATEGORY_ETD" CHAR(25 BYTE),
  "ETD_MEMBID" VARCHAR2(10 BYTE),
  "EUREX_TRANSACTION_ID" VARCHAR2(19 BYTE),
  "CATEGORY_OTC" CHAR(22 BYTE),
  "OTC_MEMBID" VARCHAR2(10 BYTE),
  "EUREX_TRADE_ID" VARCHAR2(20 BYTE),
  "SOURCE_SYSTEM_TRADEID" VARCHAR2(256 BYTE),
  "TRADEDESCRIPTION" VARCHAR2(256 BYTE),
  "LOTS" NUMBER(*, 0),
  "PRICE" NUMBER(*, 0),
  "BUY_SELL" VARCHAR2(1 BYTE),
  "ETD_SIDE_DC" DATE,
  "OTC_SIDE_DC" DATE,
  "DATE_CHECK" VARCHAR2(5 BYTE),
  "FUTURES_PC" VARCHAR2(4 BYTE),
  "PRODUCT_CHECK" VARCHAR2(5 BYTE),
  "ETD_CLR_MEMBID_MC" VARCHAR2(5 BYTE),
  "PG_CLEARING_MEMBID" VARCHAR2(50 BYTE),
  "ETD_EXCH_MEBID_MC" VARCHAR2(5 BYTE),
  "PG_EXCH_MEMBID" VARCHAR2(50 BYTE),
  "ETD_MEMBER_ID_CHECK" VARCHAR2(5 BYTE),
  "OTC_MEMBID_MC" VARCHAR2(5 BYTE),
  "OTC_TRDMEMB_MC" VARCHAR2(5 BYTE),
  "OTC_MEMBER_ID_CHECK" VARCHAR2(5 BYTE),
  "TRANSACTION_ID" VARCHAR2(19 BYTE),
  "TES_TRADE_ID" NUMBER(10, 0),
  "ETD_SD" DATE,
  "ETD_OVERRIDE_SD" DATE,
  "OTC_SD" DATE,
  "START_DATE_CHECK" VARCHAR2(5 BYTE),
  "ETD_ED" DATE,
  "ETD_OVERRIDE_ED" DATE,
  "OTC_ED" DATE,
  "END_DATE_CHECK" VARCHAR2(5 BYTE),
  "ETD_NOTIONAL" NUMBER(*, 0),
  "ETD_OVERRIDE_NOTIONAL" NUMBER(*, 0),
  "OTC_NOTIONAL" NUMBER(17, 2),
  "NOTIONAL_CHECK" VARCHAR2(5 BYTE),
  "SRCSYSTRADEID" VARCHAR2(256 BYTE),
  "SRCSYS_MW_ID_CHECK" VARCHAR2(5 BYTE),
  "GROUPID" VARCHAR2(256 BYTE),
  "GRPID_MW_ID_CHECK" VARCHAR2(5 BYTE),
  "ETD_SIDE_DIRCHECK" VARCHAR2(1 BYTE),
  "OTC_SIDE_DIRCHECK" VARCHAR2(1 BYTE),
  "DIRECTION_CHECK" VARCHAR2(5 BYTE),
  "BBG_EXP_NOTIONAL" NUMBER(*, 0),
  "BBG_U_BOUND" NUMBER(*, 0),
  "BBG_L_BOUND" NUMBER(*, 0),
  "BBG_NOT_CHECK" VARCHAR2(5 BYTE),
  "PP_NOTIONAL" NUMBER(*, 0),
  "TENOR_YRS" NUMBER(*, 0),
  "WEIGHT" NUMBER(*, 0),
  "WEIGHTED_NOTIONAL" NUMBER(*, 0),
  "MEMBER_GROUP_ID" VARCHAR2(50 BYTE),
  "REMARKS" VARCHAR2(50 BYTE),
  "FEEDBACK" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_EFS_RECONCILIATION_REPORT" PRIMARY KEY ("ROW_INDEX", "SOURCE", "TRADE_DATE", "ETD_MEMBER_ID", "ORIGINAL_TRADE_MATCH_ID", "OTC_MEMBER_ID", "MARKETWIRE_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_CAPITALLAB_DATA" (
  "CAPITALAB_RESULT_ID" VARCHAR2(50 BYTE),
  "MARKITWIRE_ID" VARCHAR2(50 BYTE),
  "MW_BOOK" VARCHAR2(100 BYTE),
  "LEGAL_ENTITY_CODE" VARCHAR2(200 BYTE),
  "DEAL_ID" VARCHAR2(50 BYTE),
  "DEAL_ID_2" VARCHAR2(50 BYTE),
  "DEAL_ID_3" VARCHAR2(50 BYTE),
  "CAPITALAB_ID" VARCHAR2(50 BYTE),
  "CPTY_DEAL_ID" VARCHAR2(50 BYTE),
  "CPTY_DEAL_ID2" VARCHAR2(50 BYTE),
  "DESK_ID" VARCHAR2(50 BYTE),
  "PORTFOLIO" VARCHAR2(50 BYTE),
  "PRODUCT" VARCHAR2(50 BYTE),
  "COUNTERPARTY" VARCHAR2(50 BYTE),
  "NOTIONAL" NUMBER(26, 12),
  "NOTIONAL_CCY" VARCHAR2(5 BYTE),
  "UND_TYPE" VARCHAR2(50 BYTE),
  "STRIKE_PCT" VARCHAR2(50 BYTE),
  "TRADE_DATE" DATE,
  "BILAT_IM" VARCHAR2(50 BYTE),
  "UND_START" DATE,
  "UND_END" DATE,
  "SETTLEMENT" VARCHAR2(50 BYTE),
  "FIX_FREQ" VARCHAR2(50 BYTE),
  "FIX_DCB" VARCHAR2(50 BYTE),
  "FLOAT_REFRATE" VARCHAR2(50 BYTE),
  "FLOAT_FREQ" VARCHAR2(50 BYTE),
  "FLOAT_DCB" VARCHAR2(50 BYTE),
  "STUB_RULE" VARCHAR2(50 BYTE),
  "SEF_STATUS" VARCHAR2(50 BYTE),
  "ROW_INDEX" NUMBER NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_F_REV_SHA_CAPITALLAB_DATA" PRIMARY KEY ("ROW_INDEX")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOICE_INPUT_DATA" (
  "PLATFORM" VARCHAR2(30 CHAR),
  "TRADE_ID" VARCHAR2(100 CHAR),
  "TRADE_DATE" DATE,
  "TRADE_TIME" VARCHAR2(30 CHAR),
  "DESCRIPTION" VARCHAR2(100 CHAR),
  "NOTIONAL" NUMBER(26, 12),
  "DEALER" VARCHAR2(255 CHAR),
  "EXECUTION_TYPE" VARCHAR2(50 CHAR),
  "CCY" VARCHAR2(3 CHAR),
  "TYPE" VARCHAR2(50 CHAR),
  "STRATEGY_DESCRIPTION" VARCHAR2(50 CHAR),
  "PRODUCT_TYPE" VARCHAR2(50 CHAR),
  "PACKAGE_ID" VARCHAR2(100 CHAR),
  "STARTDATE" DATE,
  "ENDDATE" DATE,
  "DIRECTION" VARCHAR2(10 CHAR),
  "MARKETWIRE_ID" VARCHAR2(100 CHAR),
  "ROW_INDEX" NUMBER NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_REV_SHA_VOICE_INPUT_DATA" PRIMARY KEY ("ROW_INDEX")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOLMATCH_DATA" (
  "AUCTION_NAME" VARCHAR2(100 BYTE),
  "AUCTION_DATE" VARCHAR2(10 BYTE),
  "AUCTION_START" VARCHAR2(8 BYTE),
  "AUCTION_END" VARCHAR2(8 BYTE),
  "SCREENLABEL" VARCHAR2(100 BYTE),
  "VM_CLIENT" VARCHAR2(200 BYTE),
  "EXECUTIONID" VARCHAR2(50 BYTE),
  "TRADE_SIZE" NUMBER(26, 12),
  "EFFECTIVE" DATE,
  "EXPIRY" DATE,
  "ITS" DATE DEFAULT SYSDATE,
  "ROW_INDEX" NUMBER NOT NULL,
  CONSTRAINT "PK_F_REV_SHA_VOLMATCH_DATA" PRIMARY KEY ("ROW_INDEX")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_UGR_ADJ" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UGR_ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_OTC_IRD_UGR_ADJ" PRIMARY KEY ("REPORTING_MONTH", "PARTICIPANT_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_CREDIT" (
  "PARTICIPANTS_GROUP_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANTS_GROUP_ID" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  CONSTRAINT "PK_PARTICIPANTS_GROUPS_CREDIT" PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "PARTICIPANT_ID", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_AFFILIATED_TRANS" (
  "PARTICIPANT_NAME" VARCHAR2(50 CHAR),
  "MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "LEI" VARCHAR2(20 CHAR),
  "UNIQUE_IDENTIFIER" VARCHAR2(50 CHAR) NOT NULL,
  "CLEARING_MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRANSACTION_ACCOUNT" VARCHAR2(32 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STIR_AFFILIATED_TRANS" PRIMARY KEY ("MEMBER_ID", "UNIQUE_IDENTIFIER", "CLEARING_MEMBER_ID", "TRANSACTION_ACCOUNT", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_MULTIPLIER" (
  "NR" NUMBER(*, 0) NOT NULL,
  "LIT" VARCHAR2(1 BYTE) NOT NULL,
  "MULTIPLIER_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANTS_GROUP_ID" VARCHAR2(50 BYTE) NOT NULL,
  "MULTIPLIER" NUMBER(26, 12) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  CONSTRAINT "PK_STIR_MULTIPLIER" PRIMARY KEY ("MULTIPLIER_NAME", "PARTICIPANTS_GROUP_ID", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_NRSP_ADJ" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_STIR_NRSP_ADJ" PRIMARY KEY ("REPORTING_MONTH")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_UGR_ADJ" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UGR_ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ITS" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_STIR_UGR_ADJ" PRIMARY KEY ("REPORTING_MONTH", "PARTICIPANT_ID")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_ELEC_BGC_DATA" (
  "TRADE_DATE" DATE NOT NULL,
  "TRADE_ID" VARCHAR2(20 CHAR) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 CHAR) NOT NULL,
  "PRODUCT_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRADE_SIZE" NUMBER(*, 0),
  "STRATEGY_TRADE_ID" VARCHAR2(20 CHAR),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_REV_SHA_EFS_ELEC_BGC_DATA" PRIMARY KEY ("PARTICIPANT_ID", "TRADE_ID", "PRODUCT_ID", "TRADE_DATE")
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."CREDIT_AFFILIATED_TRANS_AT" (
  "MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "LEI" VARCHAR2(20 CHAR),
  "UNIQUE_IDENTIFIER" VARCHAR2(50 CHAR) NOT NULL,
  "CLEARING_MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRANSACTION_ACCOUNT" VARCHAR2(32 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."CREDIT_MEMBERS_MUGR_AT" (
  "MONTH" NUMBER NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "MUGR" NUMBER(26, 12),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_CREDIT_MEMBER_ADDRESSES_AT" (
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  "STREET" VARCHAR2(255 BYTE) NOT NULL,
  "CITY" VARCHAR2(255 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VOICE_MEM_MAP_AT" (
  "VOICE_DEALER" VARCHAR2(200 BYTE) NOT NULL,
  "OTC_MEMBER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_STIR_MEMBER_ADDRESSES_AT" (
  "MEMBER_ID" VARCHAR2(5 BYTE) NOT NULL,
  "STREET" VARCHAR2(255 BYTE) NOT NULL,
  "CITY" VARCHAR2(255 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."EFS_RECONCILIATION_REPORT_AT" (
  "ROW_INDEX" NUMBER(*, 0) NOT NULL,
  "SOURCE" VARCHAR2(16 BYTE) NOT NULL,
  "TRADE_DATE" DATE NOT NULL,
  "ETD_MEMBER_ID" VARCHAR2(10 BYTE) NOT NULL,
  "ORIGINAL_TRADE_MATCH_ID" VARCHAR2(19 BYTE) NOT NULL,
  "OTC_MEMBER_ID" VARCHAR2(10 BYTE) NOT NULL,
  "MARKETWIRE_ID" VARCHAR2(256 BYTE) NOT NULL,
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "CATEGORY_ETD" CHAR(25 BYTE),
  "ETD_MEMBID" VARCHAR2(10 BYTE),
  "EUREX_TRANSACTION_ID" VARCHAR2(19 BYTE),
  "CATEGORY_OTC" CHAR(22 BYTE),
  "OTC_MEMBID" VARCHAR2(10 BYTE),
  "EUREX_TRADE_ID" VARCHAR2(20 BYTE),
  "SOURCE_SYSTEM_TRADEID" VARCHAR2(256 BYTE),
  "TRADEDESCRIPTION" VARCHAR2(256 BYTE),
  "LOTS" NUMBER(*, 0),
  "PRICE" NUMBER(*, 0),
  "BUY_SELL" VARCHAR2(1 BYTE),
  "ETD_SIDE_DC" DATE,
  "OTC_SIDE_DC" DATE,
  "DATE_CHECK" VARCHAR2(5 BYTE),
  "FUTURES_PC" VARCHAR2(4 BYTE),
  "PRODUCT_CHECK" VARCHAR2(5 BYTE),
  "ETD_CLR_MEMBID_MC" VARCHAR2(5 BYTE),
  "PG_CLEARING_MEMBID" VARCHAR2(50 BYTE),
  "ETD_EXCH_MEBID_MC" VARCHAR2(5 BYTE),
  "PG_EXCH_MEMBID" VARCHAR2(50 BYTE),
  "ETD_MEMBER_ID_CHECK" VARCHAR2(5 BYTE),
  "OTC_MEMBID_MC" VARCHAR2(5 BYTE),
  "OTC_TRDMEMB_MC" VARCHAR2(5 BYTE),
  "OTC_MEMBER_ID_CHECK" VARCHAR2(5 BYTE),
  "TRANSACTION_ID" VARCHAR2(19 BYTE),
  "TES_TRADE_ID" NUMBER(10, 0),
  "ETD_SD" DATE,
  "ETD_OVERRIDE_SD" DATE,
  "OTC_SD" DATE,
  "START_DATE_CHECK" VARCHAR2(5 BYTE),
  "ETD_ED" DATE,
  "ETD_OVERRIDE_ED" DATE,
  "OTC_ED" DATE,
  "END_DATE_CHECK" VARCHAR2(5 BYTE),
  "ETD_NOTIONAL" NUMBER(*, 0),
  "ETD_OVERRIDE_NOTIONAL" NUMBER(*, 0),
  "OTC_NOTIONAL" NUMBER(17, 2),
  "NOTIONAL_CHECK" VARCHAR2(5 BYTE),
  "SRCSYSTRADEID" VARCHAR2(256 BYTE),
  "SRCSYS_MW_ID_CHECK" VARCHAR2(5 BYTE),
  "GROUPID" VARCHAR2(256 BYTE),
  "GRPID_MW_ID_CHECK" VARCHAR2(5 BYTE),
  "ETD_SIDE_DIRCHECK" VARCHAR2(1 BYTE),
  "OTC_SIDE_DIRCHECK" VARCHAR2(1 BYTE),
  "DIRECTION_CHECK" VARCHAR2(5 BYTE),
  "BBG_EXP_NOTIONAL" NUMBER(*, 0),
  "BBG_U_BOUND" NUMBER(*, 0),
  "BBG_L_BOUND" NUMBER(*, 0),
  "BBG_NOT_CHECK" VARCHAR2(5 BYTE),
  "PP_NOTIONAL" NUMBER(*, 0),
  "TENOR_YRS" NUMBER(*, 0),
  "WEIGHT" NUMBER(*, 0),
  "WEIGHTED_NOTIONAL" NUMBER(*, 0),
  "MEMBER_GROUP_ID" VARCHAR2(50 BYTE),
  "REMARKS" VARCHAR2(50 BYTE),
  "FEEDBACK" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOICE_INPUT_DATA_AT" (
  "PLATFORM" VARCHAR2(30 CHAR),
  "TRADE_ID" VARCHAR2(100 CHAR),
  "TRADE_DATE" DATE,
  "TRADE_TIME" VARCHAR2(30 CHAR),
  "DESCRIPTION" VARCHAR2(100 CHAR),
  "NOTIONAL" NUMBER(26, 12),
  "DEALER" VARCHAR2(255 CHAR),
  "EXECUTION_TYPE" VARCHAR2(50 CHAR),
  "CCY" VARCHAR2(3 CHAR),
  "TYPE" VARCHAR2(50 CHAR),
  "STRATEGY_DESCRIPTION" VARCHAR2(50 CHAR),
  "PRODUCT_TYPE" VARCHAR2(50 CHAR),
  "PACKAGE_ID" VARCHAR2(100 CHAR),
  "STARTDATE" DATE,
  "ENDDATE" DATE,
  "DIRECTION" VARCHAR2(10 CHAR),
  "MARKETWIRE_ID" VARCHAR2(100 CHAR),
  "ROW_INDEX" NUMBER NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_UGR_ADJ_AT" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UGR_ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE NOT NULL
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_CREDIT_AT" (
  "PARTICIPANTS_GROUP_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANTS_GROUP_ID" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_AFFILIATED_TRANS_AT" (
  "PARTICIPANT_NAME" VARCHAR2(50 CHAR),
  "MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "LEI" VARCHAR2(20 CHAR),
  "UNIQUE_IDENTIFIER" VARCHAR2(50 CHAR) NOT NULL,
  "CLEARING_MEMBER_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRANSACTION_ACCOUNT" VARCHAR2(32 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_MULTIPLIER_AT" (
  "NR" NUMBER(*, 0) NOT NULL,
  "LIT" VARCHAR2(1 BYTE) NOT NULL,
  "MULTIPLIER_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PARTICIPANTS_GROUP_ID" VARCHAR2(50 BYTE) NOT NULL,
  "MULTIPLIER" NUMBER(26, 12) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_NRSP_ADJ_AT" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE NOT NULL
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."STIR_UGR_ADJ_AT" (
  "REPORTING_MONTH" NUMBER(6, 0) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UGR_ADJUSTMENT" NUMBER(26, 12) NOT NULL,
  "COMMENT_TXT" VARCHAR2(1024 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE NOT NULL
);;
CREATE TABLE "GUI_XMDM_REV_SHARING"."S_REV_SHA_EFS_ELEC_BGC_DATA_AT" (
  "TRADE_DATE" DATE NOT NULL,
  "TRADE_ID" VARCHAR2(20 CHAR) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 CHAR) NOT NULL,
  "PRODUCT_ID" VARCHAR2(50 CHAR) NOT NULL,
  "TRADE_SIZE" NUMBER(*, 0),
  "STRATEGY_TRADE_ID" VARCHAR2(20 CHAR),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;