-- Alter table GUI_XMDM_ZEPPELIN.NOTEBOOKS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_ZEPPELIN"."NOTEBOOKS" DROP CONSTRAINT "PK_NOTEBOOKS";

-- Alter table GUI_XMDM_ZEPPELIN.NOTE_SCHED_WHITE_LIST: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_ZEPPELIN"."NOTEBOOKS" ADD PRIMARY KEY ("TARGET_PATH");
