-- Create table GUI_XMDM_DMP.S_STG_PAY_TRANSACTION_MANUAL_AT
CREATE TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACTION_MANUAL_AT" ("FACT_DATE" DATE, "DEFAULT_TIMESTAMP" DATE, "DEFAULT_DATE" DATE, "TRANSACTION_DATE" DATE, "VALUE_DATE" DATE, "CASH_SETTLEMENT_RUN" VARCHAR2(4 BYTE), "CLEARER_ID" VARCHAR2(5 BYTE), "ACCOUNT_HOLDER" VARCHAR2(5 BYTE), "ACCOUNT" VARCHAR2(32 BYTE), "POOL_ID" VARCHAR2(15 BYTE), "CASH_CHAIN_ID" VARCHAR2(15 BYTE), "CSH_TRN_GROUP" NUMBER(15, 0), "TRANSACTION_TYPE" VARCHAR2(3 BYTE), "CURRENCY" VARCHAR2(3 BYTE), "CASH_INSTRUCTION" NUMBER(15, 0), "CASH_TRANSACTION" VARCHAR2(15 BYTE), "EXT_CASH_TRANSACTION" VARCHAR2(17 BYTE), "CASH_AMOUNT_INT" NUMBER(19, 2), "AUTOINCREMENT_ID" NUMBER, "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP, "ITS" DATE DEFAULT sysdate, "DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0);

-- Create table GUI_XMDM_DMP.S_STG_PAY_TRANSACTION_OVERVIEW_AT
CREATE TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACTION_OVERVIEW_AT" ("DMP_RUN_ID" NUMBER(*, 0), "FACT_DATE" DATE, "DEFAULT_DATE" DATE, "VALUE_DATE" DATE, "TRANSACTION_DATE" DATE, "ACCOUNT_SPONSOR" VARCHAR2(5 BYTE), "ACCOUNT_HOLDER" VARCHAR2(5 BYTE), "ACCOUNT" VARCHAR2(64 BYTE), "POOL_ID" VARCHAR2(15 BYTE), "PORTING_UNIT" VARCHAR2(64 BYTE), "PORTING_MEMBER" VARCHAR2(5 BYTE), "OP_POOL_TYPE" VARCHAR2(64 BYTE), "CASH_CHAIN_ID" VARCHAR2(32 BYTE), "TRANSACTION_TYPE" VARCHAR2(3 BYTE), "CURRENCY" VARCHAR2(3 BYTE), "CASH_TRANSACTION" VARCHAR2(15 BYTE), "CASH_INSTRUCTION" NUMBER(15, 0), "AMOUNT" NUMBER(18, 2), "CRM_GP_NO" VARCHAR2(10 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP, "ITS" DATE);

-- Create table GUI_XMDM_DMP.S_STG_PAY_TRN_GROUP_OVERRULE_AT
CREATE TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRN_GROUP_OVERRULE_AT" ("FACT_DATE" DATE, "DEFAULT_TIMESTAMP" DATE, "DEFAULT_DATE" DATE, "TRANSACTION_DATE" DATE, "VALUE_DATE" DATE, "CASH_SETTLEMENT_RUN" VARCHAR2(4 BYTE), "OP_RELEVANCE_IND" NUMBER(1, 0), "CRM_PARTNER_ID" NUMBER(15, 0), "CRM_GP_NO" VARCHAR2(10 BYTE), "CLEARER_ID" VARCHAR2(5 BYTE), "ACCOUNT_HOLDER" VARCHAR2(5 BYTE), "ACCOUNT" VARCHAR2(32 BYTE), "POOL_ID" VARCHAR2(15 BYTE), "OP_POOL_TYPE" VARCHAR2(256 CHAR), "OP_CLIENT_TYPE" VARCHAR2(100 BYTE), "LINKEDACCOUNT" VARCHAR2(60 BYTE), "PORTING_UNIT" VARCHAR2(60 BYTE), "CASH_CHAIN_ID" VARCHAR2(15 BYTE), "NBR_OF_PU_PER_CHAIN" NUMBER(15, 0), "CASH_INSTRUCTION" NUMBER(15, 0), "STL_FLG_INSTC" VARCHAR2(1 BYTE), "CSH_TRN_GROUP" NUMBER(2, 0), "CSH_TRN_GROUP_OVERRULE" NUMBER(2, 0), "TRANSACTION_TYPE" VARCHAR2(3 BYTE), "CURRENCY" VARCHAR2(3 BYTE), "CASH_TRANSACTION" VARCHAR2(15 BYTE), "EXT_CASH_TRANSACTION" VARCHAR2(17 BYTE), "CASH_AMOUNT_INT" NUMBER(19, 2), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP, "ITS" DATE DEFAULT sysdate, "PORTING_MEMBER" VARCHAR2(5 CHAR), "DATA_SRC" VARCHAR2(30 BYTE), "DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0 NOT NULL);

-- Alter table GUI_XMDM_DMP.S_STG_CAA_LIQUIDATION_AT: add column
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_LIQUIDATION_AT" ADD ("ITS" DATE DEFAULT SYSDATE);

-- Alter table GUI_XMDM_DMP.S_STG_CAA_PARAMETER_AT: add column, modify column
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_PARAMETER_AT" ADD ("ITS" DATE DEFAULT SYSDATE);

-- Alter table GUI_XMDM_DMP.S_STG_PAY_DEFAULT_DETAILS_AT: add column
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_PARAMETER_AT" MODIFY ("RECORD_ID" NUMBER);

-- Alter table GUI_XMDM_DMP.S_STG_PAY_INSTC_STATUS_AT: drop column, add column, modify column
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_DEFAULT_DETAILS_AT" ADD ("ITS" DATE DEFAULT SYSDATE);
