-- Alter table GUI_XMDM_SCS.D_STA_SCS_SPANISH_TAX: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCS"."D_STA_SCS_SPANISH_TAX" DROP CONSTRAINT "PK_SCS_SPANISH_TAX";

-- Alter table GUI_XMDM_SCS.D_STA_SCS_SPANISH_TAX_AT: modify column
ALTER TABLE "GUI_XMDM_SCS"."D_STA_SCS_SPANISH_TAX" ADD PRIMARY KEY ("FINANCIAL_YEAR", "ISIN", "VALID_TO");
