-- Alter table GUI_XMDM_LST.AGGREGATION_LEVELS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."AGGREGATION_LEVELS" DROP CONSTRAINT "PK_AGGREGATION_LEVELS";

-- Alter table GUI_XMDM_LST.BACKUP_ARRANGEMENT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."AGGREGATION_LEVELS" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.BASKET_CAPACITIES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."BACKUP_ARRANGEMENT" DROP CONSTRAINT "PK_BACKUP_ARRANGEMENT";

-- Alter table GUI_XMDM_LST.COMPONENT_SET: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."BACKUP_ARRANGEMENT" ADD PRIMARY KEY ("MEMBER_ROLE");

-- Alter table GUI_XMDM_LST.COMPONENT_SET_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."BASKET_CAPACITIES" DROP CONSTRAINT "PK_BASKET_CAPACITIES";

-- Alter table GUI_XMDM_LST.COUNTERPARTY_DEF_ASSIGN: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."BASKET_CAPACITIES" ADD PRIMARY KEY ("CATEGORY_I", "CATEGORY_II", "VALID_FROM");

-- Alter table GUI_XMDM_LST.COUNTERPARTY_EX_SET: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COMPONENT_SET" DROP CONSTRAINT "PK_COMPONENT_SET";

-- Alter table GUI_XMDM_LST.COUNTERPARTY_ROLE_ASSIGN: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COMPONENT_SET" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.COUNTERPARTY_SET: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COMPONENT_SET_CONFIG" DROP CONSTRAINT "PK_COMPONENT_SET_CONFIG";

-- Alter table GUI_XMDM_LST.CP_EXCL_SET_ASN: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COMPONENT_SET_CONFIG" ADD PRIMARY KEY ("FLOW_TYPE_CODE", "FLOW_TYPE_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.CP_EXCL_SET_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_DEF_ASSIGN" DROP CONSTRAINT "PK_COUNTERPARTY_DEF_ASSIGN";

-- Alter table GUI_XMDM_LST.CST_GLOBAL_SCENARIOS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_DEF_ASSIGN" ADD PRIMARY KEY ("SCENARIO_CODE");

-- Alter table GUI_XMDM_LST.CST_MP_SCAL_FACTOR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_EX_SET" DROP CONSTRAINT "PK_COUNTERPARTY_EX_SET";

-- Alter table GUI_XMDM_LST.CST_SCEN_GROUP_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_EX_SET" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.CST_SCEN_GROUP_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_ROLE_ASSIGN" DROP CONSTRAINT "PK_COUNTERPARTY_ROLE_ASSIGN";

-- Alter table GUI_XMDM_LST.CTRPARTY_EXCL_SETS_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_ROLE_ASSIGN" ADD PRIMARY KEY ("SCENARIO_CODE");

-- Alter table GUI_XMDM_LST.CURRENCY_PRIORITY: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_SET" DROP CONSTRAINT "PK_COUNTERPARTY_SET";

-- Alter table GUI_XMDM_LST.CURRENCY_SET_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."COUNTERPARTY_SET" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.CURRENCY_SET_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_ASN" DROP CONSTRAINT "PK_CP_EXCL_SET_ASN";

-- Alter table GUI_XMDM_LST.DQA_ABORTS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_ASN" ADD PRIMARY KEY ("SCENARIO_CODE", "COUNTERPARTY_EXCL_SET_CODE");

-- Alter table GUI_XMDM_LST.FLOW_TYPE_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_MSTR" DROP CONSTRAINT "PK_CP_EXCL_SET_MSTR";

-- Alter table GUI_XMDM_LST.FLOW_TYPE_COMP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CP_EXCL_SET_MSTR" ADD PRIMARY KEY ("COUNTERPARTY_EXCL_SET_CODE");

-- Alter table GUI_XMDM_LST.FLOW_TYPE_COMP_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_GLOBAL_SCENARIOS" DROP CONSTRAINT "PK_CST_GLOBAL_SCENARIOS";

-- Alter table GUI_XMDM_LST.FLOW_TYPE_GROUP_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_GLOBAL_SCENARIOS" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.FLOW_TYPE_GROUP_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_MP_SCAL_FACTOR" DROP CONSTRAINT "PK_CST_MP_SCAL_FACTOR";

-- Alter table GUI_XMDM_LST.FLOW_TYPE_REP_GROUP_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_MP_SCAL_FACTOR" ADD PRIMARY KEY ("CST_SCENARIO_CODE");

-- Alter table GUI_XMDM_LST.FLOW_TYPE_SCALE_FACT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_CFG" DROP CONSTRAINT "PK_CST_SCEN_GROUP_CFG";

-- Alter table GUI_XMDM_LST.GLOBAL_CST_SCENARIO_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_CFG" ADD PRIMARY KEY ("CST_GBL_SCENARIO_GROUP_CODE", "CST_GOBAL_SCENARIO_CODE");

-- Alter table GUI_XMDM_LST.LST_MASTER_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_MSTR" DROP CONSTRAINT "PK_CST_SCEN_GROUP_MSTR";

-- Alter table GUI_XMDM_LST.MOBILIZATION_SETS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CST_SCEN_GROUP_MSTR" ADD PRIMARY KEY ("CST_GBL_SCENARIO_GROUP_CODE");

-- Alter table GUI_XMDM_LST.MOBILIZATION_SETS_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CTRPARTY_EXCL_SETS_CONFIG" DROP CONSTRAINT "PK_CTRPARTY_EXCL_SETS_CONFIG";

-- Alter table GUI_XMDM_LST.MOB_CHANNEL_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CTRPARTY_EXCL_SETS_CONFIG" ADD PRIMARY KEY ("CTRPARTY_EXCLUSION_SET", "MEMBERS", "VALID_FROM");

-- Alter table GUI_XMDM_LST.MOB_CHANNEL_FLOW_TYPE_ASN: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_PRIORITY" DROP CONSTRAINT "PK_CURRENCY_PRIORITY";

-- Alter table GUI_XMDM_LST.MOB_CHANNEL_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_PRIORITY" ADD PRIMARY KEY ("CURRENCY_CODE");

-- Alter table GUI_XMDM_LST.MOB_CHANNEL_TYPE_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_CFG" DROP CONSTRAINT "PK_CURRENCY_SET_CFG";

-- Alter table GUI_XMDM_LST.MOB_FACTOR_SET_CONF: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_CFG" ADD PRIMARY KEY ("CURRENCY_SET_CODE", "CURRENCY_CODE");

-- Alter table GUI_XMDM_LST.MOB_FACTOR_SET_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_MSTR" DROP CONSTRAINT "PK_CURRENCY_SET_MSTR";

-- Alter table GUI_XMDM_LST.MOB_JURISDICTIONS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."CURRENCY_SET_MSTR" ADD PRIMARY KEY ("CURRENCY_SET_CODE");

-- Alter table GUI_XMDM_LST.MOB_SET_CFG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."DQA_ABORTS" DROP CONSTRAINT "PK_LST_DQA_ABORTS";

-- Alter table GUI_XMDM_LST.MOB_SET_CFG_CHANNEL: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."DQA_ABORTS" ADD PRIMARY KEY ("FACT_DATE");

-- Alter table GUI_XMDM_LST.MOB_SET_CFG_COMPONENTS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_CFG" DROP CONSTRAINT "PK_FLOW_TYPE_CFG";

-- Alter table GUI_XMDM_LST.MOB_SET_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_CFG" ADD PRIMARY KEY ("FLOW_TYPE_CODE");

-- Alter table GUI_XMDM_LST.OTHER_LST_COMPONENTS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP" DROP CONSTRAINT "PK_FLOW_TYPE_COMP";

-- Alter table GUI_XMDM_LST.QUALITY_CHECK_DEF: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP" ADD PRIMARY KEY ("SCENARIO_CODE", "FLOW_TYPE_COMPONENT_CODE");

-- Alter table GUI_XMDM_LST.REFINANCING_FACTORS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP_MSTR" DROP CONSTRAINT "PK_FLOW_TYPE_COMP_MSTR";

-- Alter table GUI_XMDM_LST.REPORTING_COMP_MSTR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_COMP_MSTR" ADD PRIMARY KEY ("FLOW_TYPE_COMPONENT_CODE");

-- Alter table GUI_XMDM_LST.SCENARIO_CLASS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_CFG" DROP CONSTRAINT "PK_FLOW_TYPE_GROUP_CFG";

-- Alter table GUI_XMDM_LST.SCENARIO_CLASS_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_CFG" ADD PRIMARY KEY ("FLOW_TYPE_REP_GROUP_CODE", "FLOW_TYPE_GROUP_CODE", "FLOW_TYPE_CODE");

-- Alter table GUI_XMDM_LST.SCENARIO_GROUP_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_MASTER" DROP CONSTRAINT "PK_LOW_TYPE_GROUP_MASTER";

-- Alter table GUI_XMDM_LST.SCENARIO_TYPE_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_GROUP_MASTER" ADD PRIMARY KEY ("FLOW_TYPE_GROUP_CODE");

-- Alter table GUI_XMDM_LST.SET_RULE_ASN: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_REP_GROUP_MASTER" DROP CONSTRAINT "PK_FLOW_TYPE_REP_GROUP_MASTER";

-- Alter table GUI_XMDM_LST.TIME_FACTOR_SETS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_REP_GROUP_MASTER" ADD PRIMARY KEY ("FLOW_TYPE_REP_GROUP_CODE");

-- Alter table GUI_XMDM_LST.TIME_FACTOR_SETS_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_SCALE_FACT" DROP CONSTRAINT "PK_FLOW_TYPE_SCALE_FACT";

-- Alter table GUI_XMDM_LST.TIME_FACTOR_SET_CONFIG: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."FLOW_TYPE_SCALE_FACT" ADD PRIMARY KEY ("FLOW_TYPE_CODE");

-- Alter table GUI_XMDM_LST.TIME_FACTOR_SET_MASTER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_LST"."GLOBAL_CST_SCENARIO_CONFIG" DROP CONSTRAINT "PK_GLOBAL_CST_SCENARIO_CONFIG";

-- Alter table GUI_XMDM_LST.BACKUP_ARRANGEMENT_AT: modify column
ALTER TABLE "GUI_XMDM_LST"."GLOBAL_CST_SCENARIO_CONFIG" ADD PRIMARY KEY ("CST_GLOBAL_SCENARIO_GROUPING", "SCENARIO_PURPOSE", "VALID_FROM");

-- Alter table GUI_XMDM_LST.DQA_ABORTS_AT: drop column, modify column
ALTER TABLE "GUI_XMDM_LST"."LST_MASTER_DATA" DROP CONSTRAINT "PK_LST_MASTER_DATA";

-- Alter table GUI_XMDM_LST.LST_MASTER_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_LST"."LST_MASTER_DATA" ADD PRIMARY KEY ("LST_MASTER_DATA_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.OTHER_LST_COMPONENTS_AT: modify column
ALTER TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS" DROP CONSTRAINT "PK_MOBILIZATION_SETS";

-- Alter table GUI_XMDM_LST.QUALITY_CHECK_DEF_AT: drop column, modify column
ALTER TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS" ADD PRIMARY KEY ("LST_SCEN_ID", "LST_SCENARIO_NAME", "VALID_FROM");

-- Alter table GUI_XMDM_LST.SET_RULE_ASN_AT: modify column
ALTER TABLE "GUI_XMDM_LST"."MOBILIZATION_SETS_CONFIG" DROP CONSTRAINT "PK_MOBILIZATION_SETS_CONFIG";
