-- Alter table GUI_XMDM_PMRLP.PMRLP_PARAMETER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMRLP"."PMRLP_PARAMETER" DROP CONSTRAINT "PK_PMRLP_PARAMETER";

-- Alter table GUI_XMDM_PMRLP.PMRLP_PARAMETER_AT: modify column
ALTER TABLE "GUI_XMDM_PMRLP"."PMRLP_PARAMETER" ADD PRIMARY KEY ("ISIN");
