-- Create table GUI_XMDM_MATLAB.S_MATLAB_OTC_IRS_CUR_WHITELIST_AT
CREATE TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_CUR_WHITELIST_AT" ("CURVE" VARCHAR2(25 CHAR) NOT NULL, "ACTIVE" CHAR(1 CHAR) DEFAULT 'N', "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Alter table GUI_XMDM_MATLAB.S_MATLAB_OTC_IRS_MINOR_CUR_AT: add column
ALTER TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_MINOR_CUR_AT" ADD ("ITS" DATE);

-- Alter table GUI_XMDM_MATLAB.S_MATLAB_OTC_IRS_RISK_AT: add column
ALTER TABLE "GUI_XMDM_MATLAB"."S_MATLAB_OTC_IRS_RISK_AT" ADD ("ITS" DATE);
