ALTER TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_F_OTC_IRD_CLIENT_STRUCTURE PRIMARY KEY (BOOK_FINAL);
ALTER TABLE "GUI_XMDM_OTC"."F_OTC_IRD_CLIENT_STRUCTURE_AT" MODIFY ("BOOK_FINAL" VARCHAR2(50 BYTE) NOT NULL);
CREATE TABLE "GUI_XMDM_OTC"."S_OTC_CC210_INPUT_FILTER" (
  "FILTER_CODE" VARCHAR2(30 BYTE),
  "FILTER_VALUE" NUMBER,
  "ENABLED" NUMBER(1, 0),
  "ITS" TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_OTC"."S_OTC_CC210_INPUT_FILTER_AT" (
  "FILTER_CODE" VARCHAR2(30 BYTE),
  "FILTER_VALUE" NUMBER,
  "ENABLED" NUMBER(1, 0),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP
);;