ALTER TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_MEMBER_RELATIONSHIP" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_S_HFT_MEMBER_RELATIONSHIP PRIMARY KEY (MEMBER_ID, REPORTING_MEMBER_ID, VALID_FROM);
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "VOLUME_FACTOR" NUMBER,
  "SMC_FACTOR" NUMBER,
  "NON_MM_FLOOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  "LIMIT_TYPE" VARCHAR2(100 BYTE),
  "VOLUME_FACTOR_PASSIVE" NUMBER,
  "VOLUME_FACTOR_AGGRESSIVE" NUMBER
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_FEE" (
  "LIMIT_TYPE" VARCHAR2(100 CHAR) NOT NULL,
  "SYSTEMATIC_THRESHLD" NUMBER,
  "TXN_LT_50_PCT_EUR" NUMBER,
  "TXN_GT_50_LT_100_PCT_EUR" NUMBER,
  "TXN_GT_100_PCT_EUR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_INTV_SQ" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_BASE" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE,
  "LIMIT_TYPE" VARCHAR2(100 CHAR) DEFAULT 'A'
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_VI_INTV" (
  "LIMIT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_ESU_VI_INTV" PRIMARY KEY ("LIMIT_TYPE", "PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "MINIMUM_DENOMINATOR" NUMBER,
  "BASE_LIMIT" NUMBER,
  "SMC_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_PROD" (
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  "THRESHOLD" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_SQ_INTV" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_VI_INTV" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_TRANS_VI_INTV" PRIMARY KEY ("PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "REFERENCE_PRODUCT" VARCHAR2(10 CHAR) NOT NULL,
  "ROLLOVER_WINDOW" NUMBER,
  "AVERAGING_WINDOW" NUMBER,
  "PRIMARY_FLAG" CHAR(1 BYTE) DEFAULT 'Y',
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_VOLATILITY_INDICATOR" PRIMARY KEY ("PRODUCT_TYPE", "REFERENCE_PRODUCT", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "MINIMUM_DENOMINATOR" NUMBER,
  "BASE_LIMIT" NUMBER,
  "SMC_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_PROD" (
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  "THRESHOLD" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_SQ_INTV" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_VI_INTV" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_S_HFT_VOLUME_VI_INTV" PRIMARY KEY ("PRODUCT_TYPE", "INTERVAL_NO", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "VOLUME_FACTOR" NUMBER,
  "SMC_FACTOR" NUMBER,
  "NON_MM_FLOOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE,
  "LIMIT_TYPE" VARCHAR2(100 BYTE),
  "VOLUME_FACTOR_PASSIVE" NUMBER,
  "VOLUME_FACTOR_AGGRESSIVE" NUMBER
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_FEE_AT" (
  "LIMIT_TYPE" VARCHAR2(100 CHAR) NOT NULL,
  "SYSTEMATIC_THRESHLD" NUMBER,
  "TXN_LT_50_PCT_EUR" NUMBER,
  "TXN_GT_50_LT_100_PCT_EUR" NUMBER,
  "TXN_GT_100_PCT_EUR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_INTV_SQ_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_BASE" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE,
  "LIMIT_TYPE" VARCHAR2(100 CHAR) DEFAULT 'A'
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_ESU_VI_INTV_AT" (
  "LIMIT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "MINIMUM_DENOMINATOR" NUMBER,
  "BASE_LIMIT" NUMBER,
  "SMC_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_PROD_AT" (
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  "THRESHOLD" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_SQ_INTV_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_TRANS_VI_INTV_AT" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLATILITY_INDICATOR_AT" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "REFERENCE_PRODUCT" VARCHAR2(10 CHAR) NOT NULL,
  "ROLLOVER_WINDOW" NUMBER,
  "AVERAGING_WINDOW" NUMBER,
  "PRIMARY_FLAG" CHAR(1 BYTE) DEFAULT 'Y',
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "GRACE_FACTOR" NUMBER,
  "MINIMUM_DENOMINATOR" NUMBER,
  "BASE_LIMIT" NUMBER,
  "SMC_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_PROD_AT" (
  "PRODUCT_ID" VARCHAR2(100 CHAR) NOT NULL,
  "THRESHOLD" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_SQ_INTV_AT" (
  "PRODUCT_GROUP" VARCHAR2(100 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER,
  "SPREAD_QUALITY" NUMBER,
  "MM_FACTOR" NUMBER,
  "BUSINESS_VALID_FROM" DATE DEFAULT TRUNC(SYSDATE),
  "BUSINESS_VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_EUREX_HFT"."S_HFT_VOLUME_VI_INTV_AT" (
  "PRODUCT_TYPE" VARCHAR2(10 CHAR) NOT NULL,
  "INTERVAL_NO" NUMBER(*, 0) NOT NULL,
  "VI" NUMBER(16, 8),
  "VI_FACTOR" NUMBER(16, 8),
  "VALID_FROM" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  "VALID_TO" DATE DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;