ALTER TABLE "GUI_XMDM_XETRA_RTS24"."S_SCHEDULING_PARAMS" ADD ("INSTRUMENT_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A') MODIFY ("PRODUCT_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL) MODIFY ("MEMBER_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL);
ALTER TABLE "GUI_XMDM_XETRA_RTS24"."S_SCHEDULING_PARAMS_AT" ADD ("INSTRUMENT_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A') MODIFY ("PRODUCT_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL) MODIFY ("MEMBER_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL);
CREATE TABLE "GUI_XMDM_XETRA_RTS24"."S_CERTIFIED_DEA_MEMBERS" (
  "MEMBER" VARCHAR2(5 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_RTS24_EUREX_CERT_MEMBER" PRIMARY KEY ("MEMBER", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_XETRA_RTS24"."S_CERTIFIED_DEA_MEMBERS_AT" (
  "MEMBER" VARCHAR2(5 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;