ALTER TABLE "GUI_XMDM_RLI"."COMMITTED_CREDIT_LINES" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_COMMITTED_CREDIT_LINES PRIMARY KEY (BUSINESS_PARTNER, VALID_FROM);
ALTER TABLE "GUI_XMDM_RLI"."KLI_4" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_KLI_4 PRIMARY KEY (OWN_FUNDS, INTRAGROUP_FUNDING, OPERATIONAL_LIQUIDITY);
ALTER TABLE "GUI_XMDM_RLI"."LCR_C76" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_LCR_C76 PRIMARY KEY (REPDATE, ID);
ALTER TABLE "GUI_XMDM_RLI"."LIMITS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_LIMITS PRIMARY KEY (LIQUIDITY_INDICATOR, VALID_FROM);
ALTER TABLE "GUI_XMDM_RLI"."MIN_RESERVE_CALENDAR" DROP COLUMN "VALUE_VALID_FROM" DROP COLUMN "VALUE_VALID_UNTIL" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_MIN_RESERVE_CALENDAR PRIMARY KEY (REPORT_MONTH, VALID_FROM);
ALTER TABLE "GUI_XMDM_RLI"."RECURRING_PAYMENTS" DROP CONSTRAINT "PRIMARY" ADD CONSTRAINT PK_RLI_RECURRING_PAYMENTS PRIMARY KEY (LOCATION, ACCOUNT, FACILITY, CURRENCY, VALID_FROM);
ALTER TABLE "GUI_XMDM_RLI"."LCR_C76_AT" MODIFY ("REPDATE" DATE NOT NULL) MODIFY ("ID" VARCHAR2(50 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_RLI"."MIN_RESERVE_CALENDAR_AT" DROP COLUMN "VALUE_VALID_FROM" DROP COLUMN "VALUE_VALID_UNTIL";
ALTER TABLE "GUI_XMDM_RLI"."MIN_RESERVE_CALENDAR_HT" DROP COLUMN "VALUE_VALID_FROM" DROP COLUMN "VALUE_VALID_UNTIL";
ALTER TABLE "GUI_XMDM_RLI"."RECURRING_PAYMENTS_AT" MODIFY ("LOCATION" VARCHAR2(50 BYTE) NOT NULL) MODIFY ("ACCOUNT" VARCHAR2(50 BYTE) NOT NULL) MODIFY ("FACILITY" VARCHAR2(50 BYTE) NOT NULL);
ALTER TABLE "GUI_XMDM_RLI"."RECURRING_PAYMENTS_HT" MODIFY ("LOCATION" VARCHAR2(50 BYTE) NOT NULL) MODIFY ("ACCOUNT" VARCHAR2(50 BYTE) NOT NULL) MODIFY ("FACILITY" VARCHAR2(50 BYTE) NOT NULL);
CREATE TABLE "GUI_XMDM_RLI"."FIX_RLI_VALUE" (
  "FACT_DATE" DATE NOT NULL,
  "RLI_ID" VARCHAR2(50 BYTE) NOT NULL,
  "COMPONENT_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "COMPONENT_VALUE" NUMBER,
  "ACTION_TYPE" CHAR(1 BYTE),
  "ENTRY_INSERT_DATE" DATE,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_RLI_FIX_RLI_VALUE" PRIMARY KEY ("FACT_DATE", "RLI_ID", "COMPONENT_NAME")
);;
CREATE TABLE "GUI_XMDM_RLI"."FIX_RLI_VALUE_AT" (
  "FACT_DATE" DATE NOT NULL,
  "RLI_ID" VARCHAR2(50 BYTE) NOT NULL,
  "COMPONENT_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "COMPONENT_VALUE" NUMBER,
  "ACTION_TYPE" CHAR(1 BYTE),
  "ENTRY_INSERT_DATE" DATE,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;