-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_C7FXS_ETD: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_C7FXS_ETD" DROP CONSTRAINT "PK_ACCOUNT_MAPPING_C7FXS_ETD";

-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_SCS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_C7FXS_ETD" ADD PRIMARY KEY ("CURRENCY", "SOURCE_SYSTEM");

-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_SWIFT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SCS" DROP CONSTRAINT "PK_ACCOUNT_MAPPING_SCS";

-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_C7FXS_ETD_AT: modify column
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SCS" ADD PRIMARY KEY ("SETTLEMENT_ACCOUNT_NUMBER", "SETTLEMENT_ACCOUNT_LOCATION", "CURRENCY", "SOURCE_SYSTEM");

-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_SCS_AT: modify column
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SWIFT" DROP CONSTRAINT "PK_ACCOUNT_MAPPING_SWIFT";

-- Alter table GUI_XMDM_TBCR.ACCOUNT_MAPPING_SWIFT_AT: modify column
ALTER TABLE "GUI_XMDM_TBCR"."ACCOUNT_MAPPING_SWIFT" ADD PRIMARY KEY ("SENDER", "EXTERNAL_ACCOUNT_NUMBER", "SOURCE_SYSTEM");
