-- Alter table GUI_XMDM_DTCC.ALPHA_SWAP_TERMINATIONS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_DTCC"."ALPHA_SWAP_TERMINATIONS" DROP CONSTRAINT "PK_ALPHA_SWAP_TERMINATIONS";

-- Alter table GUI_XMDM_DTCC.ALPHA_SWAP_TERMINATIONS_AT: add column, modify column
ALTER TABLE "GUI_XMDM_DTCC"."ALPHA_SWAP_TERMINATIONS" ADD PRIMARY KEY ("SOURCE_SYS_TRADE_ID", "USI_PREFIX", "VALID_FROM");
