ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEFINITIONS" MODIFY ("VIOLATIONS" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEF_PRICE_LIST_ASSIGNM" MODIFY ("JOIN_ID" NUMBER(*, 0) NULL) MODIFY ("M_PLUS_P" NUMBER(*, 0) NULL) MODIFY ("BLENDED" NUMBER(*, 0) NULL) MODIFY ("OVERALL_THRESHOLD" NUMBER(*, 0) NULL) MODIFY ("NO_MEMBER_CIRCLE" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_LIST_SCN_ASSIGNM" MODIFY ("PRIORITY" NUMBER(*, 0) NULL) MODIFY ("EXCLUDE_IPS" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_REBATES" MODIFY ("THRESHOLD" NUMBER(*, 0) NULL) MODIFY ("REBATE" NUMBER(*, 0) NULL) MODIFY ("PACKAGE_REBATE" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEFINITIONS_AT" MODIFY ("VIOLATIONS" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_DEF_PRICE_LIST_ASSIGNM_AT" MODIFY ("JOIN_ID" NUMBER(*, 0) NULL) MODIFY ("M_PLUS_P" NUMBER(*, 0) NULL) MODIFY ("BLENDED" NUMBER(*, 0) NULL) MODIFY ("OVERALL_THRESHOLD" NUMBER(*, 0) NULL) MODIFY ("NO_MEMBER_CIRCLE" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_LIST_SCN_ASSIGNM_AT" MODIFY ("PRIORITY" NUMBER(*, 0) NULL) MODIFY ("EXCLUDE_IPS" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_REBATES_V"."VR_REBATES_AT" MODIFY ("THRESHOLD" NUMBER(*, 0) NULL) MODIFY ("REBATE" NUMBER(*, 0) NULL) MODIFY ("PACKAGE_REBATE" NUMBER(*, 0) NULL);