-- Alter table GUI_XMDM_ESMIRA.STAT_PRODUCTS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_ESMIRA"."STAT_PRODUCTS" DROP CONSTRAINT "PK_STAT_PRODUCTS";

-- Alter table GUI_XMDM_ESMIRA.STAT_PRODUCTS_AT: modify column
ALTER TABLE "GUI_XMDM_ESMIRA"."STAT_PRODUCTS" ADD PRIMARY KEY ("PRODUCT");
