ALTER TABLE "GUI_XMDM_EPS_PRICE_LST"."KNOWN_PRICETYPES" MODIFY ("IS_PRIMARY" NUMBER(*, 0) NULL);
ALTER TABLE "GUI_XMDM_EPS_PRICE_LST"."KNOWN_PRICETYPES_AT" MODIFY ("IS_PRIMARY" NUMBER(*, 0) NULL);
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST" (
  "ACLIST" VARCHAR2(30 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST_MEMBERS" (
  "ACLIST" VARCHAR2(30 BYTE),
  "MEMBER_ID" VARCHAR2(50 BYTE),
  "PRODUCT_ID" VARCHAR2(50 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "CURRENCY" VARCHAR2(5 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST_SCENARIO_ASSIGNM" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "ACLIST" VARCHAR2(30 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_PRICELIST_ASSIGNM" (
  "PLIST" VARCHAR2(100 BYTE),
  "PGRID" VARCHAR2(150 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "PRIORITY" NUMBER(*, 0),
  "ACCOUNTTYPE" VARCHAR2(50 BYTE),
  "DELAY" VARCHAR2(50 BYTE),
  "EXECTYPE" VARCHAR2(50 BYTE),
  "DISCLOSED" VARCHAR2(50 BYTE),
  "SUBTYPE_NAME" VARCHAR2(50 BYTE),
  "EXPIRY" VARCHAR2(50 BYTE),
  "PRICE_CHANGED" VARCHAR2(50 BYTE),
  "CHARGE_LEPOS" NUMBER(*, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_PRICE_ASSIGNM" (
  "PGRID" VARCHAR2(150 BYTE),
  "PRICING_GROUP" VARCHAR2(150 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "PRICE" NUMBER,
  "CURRENCY" VARCHAR2(5 BYTE),
  "ALTERNATIVE_CURRENCY" VARCHAR2(5 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "UNIT_OF_COUNT" VARCHAR2(50 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_TEMPLATE_ASSIGNM" (
  "PGRID" VARCHAR2(150 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "TEMPLATE" VARCHAR2(150 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."INHERITANCE_EXCEPTION" (
  "SCENARIO_NAME" VARCHAR2(500 BYTE),
  "SERVICE" VARCHAR2(50 BYTE),
  "INH_NAME" VARCHAR2(500 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."PRICELIST" (
  "PLIST" VARCHAR2(100 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."PRICELIST_SCENARIO_ASSIGNM" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "SERVICE" VARCHAR2(50 BYTE),
  "ROUTE" VARCHAR2(50 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "PRIORITY" NUMBER(*, 0),
  "PLIST" VARCHAR2(100 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "IS_ENLIGHT_INCENT" NUMBER(*, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."SCENARIOS" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "CASE_NAME" VARCHAR2(100 BYTE),
  "SCENARIO_NAME_PARENT" VARCHAR2(100 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "INCLUDE_PROJECTION" NUMBER(*, 0),
  "MULTILATERAL_TRADE" NUMBER(*, 0),
  "CHARGE_FREE_VOLUME" NUMBER(*, 0),
  "EBI_NO_TSR" NUMBER(*, 0),
  "EBI_NO_MMR" NUMBER(*, 0),
  "EBI_NO_VR" NUMBER(*, 0),
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."TEMPLATES" (
  "TEMPLATE" VARCHAR2(150 BYTE),
  "PRICING_GROUP" VARCHAR2(150 BYTE),
  "CURRENCY" VARCHAR2(5 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "FIBU" VARCHAR2(20 BYTE),
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST_AT" (
  "ACLIST" VARCHAR2(30 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST_MEMBERS_AT" (
  "ACLIST" VARCHAR2(30 BYTE),
  "MEMBER_ID" VARCHAR2(50 BYTE),
  "PRODUCT_ID" VARCHAR2(50 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "CURRENCY" VARCHAR2(5 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."ACLIST_SCENARIO_ASSIGNM_AT" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "ACLIST" VARCHAR2(30 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_PRICELIST_ASSIGNM_AT" (
  "PLIST" VARCHAR2(100 BYTE),
  "PGRID" VARCHAR2(150 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "PRIORITY" NUMBER(*, 0),
  "ACCOUNTTYPE" VARCHAR2(50 BYTE),
  "DELAY" VARCHAR2(50 BYTE),
  "EXECTYPE" VARCHAR2(50 BYTE),
  "DISCLOSED" VARCHAR2(50 BYTE),
  "SUBTYPE_NAME" VARCHAR2(50 BYTE),
  "EXPIRY" VARCHAR2(50 BYTE),
  "PRICE_CHANGED" VARCHAR2(50 BYTE),
  "CHARGE_LEPOS" NUMBER(*, 0),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_PRICE_ASSIGNM_AT" (
  "PGRID" VARCHAR2(150 BYTE),
  "PRICING_GROUP" VARCHAR2(150 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "PRICE" NUMBER,
  "CURRENCY" VARCHAR2(5 BYTE),
  "ALTERNATIVE_CURRENCY" VARCHAR2(5 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "UNIT_OF_COUNT" VARCHAR2(50 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."GRID_TEMPLATE_ASSIGNM_AT" (
  "PGRID" VARCHAR2(150 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "TEMPLATE" VARCHAR2(150 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."INHERITANCE_EXCEPTION_AT" (
  "SCENARIO_NAME" VARCHAR2(500 BYTE),
  "SERVICE" VARCHAR2(50 BYTE),
  "INH_NAME" VARCHAR2(500 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."PRICELIST_AT" (
  "PLIST" VARCHAR2(100 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."PRICELIST_SCENARIO_ASSIGNM_AT" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "SERVICE" VARCHAR2(50 BYTE),
  "ROUTE" VARCHAR2(50 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "PRIORITY" NUMBER(*, 0),
  "PLIST" VARCHAR2(100 BYTE),
  "REMARKS" VARCHAR2(250 BYTE),
  "IS_ENLIGHT_INCENT" NUMBER(*, 0),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."SCENARIOS_AT" (
  "SCENARIO_NAME" VARCHAR2(100 BYTE),
  "CASE_NAME" VARCHAR2(100 BYTE),
  "SCENARIO_NAME_PARENT" VARCHAR2(100 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "INCLUDE_PROJECTION" NUMBER(*, 0),
  "MULTILATERAL_TRADE" NUMBER(*, 0),
  "CHARGE_FREE_VOLUME" NUMBER(*, 0),
  "EBI_NO_TSR" NUMBER(*, 0),
  "EBI_NO_MMR" NUMBER(*, 0),
  "EBI_NO_VR" NUMBER(*, 0),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_EPS_PRICE_LST"."TEMPLATES_AT" (
  "TEMPLATE" VARCHAR2(150 BYTE),
  "PRICING_GROUP" VARCHAR2(150 BYTE),
  "CURRENCY" VARCHAR2(5 BYTE),
  "NODE" VARCHAR2(150 BYTE),
  "FIBU" VARCHAR2(20 BYTE),
  "PRODUCT_ID" VARCHAR2(20 BYTE),
  "PRODUCT_NAME" VARCHAR2(150 BYTE),
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;