CREATE TABLE "GUI_XMDM_STX_TESTS"."S_TEST_MMPM" (
  "MODULE_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "DATA_SOURCE" VARCHAR2(20 CHAR) NOT NULL,
  "BUSINESS_DATE" DATE NOT NULL,
  "TEST_GROUP" VARCHAR2(30 CHAR) NOT NULL,
  "TEST_NAME" VARCHAR2(100 CHAR) NOT NULL,
  "ACTIVE" CHAR(1 BYTE) DEFAULT 'Y',
  "INPUT" VARCHAR2(4000 BYTE),
  "EXPECTED" VARCHAR2(4000 BYTE),
  "PARAMETERS" VARCHAR2(4000 BYTE),
  "DESCRIPTION" VARCHAR2(255 CHAR),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_STX_TESTS"."S_TEST_MMPM_AT" (
  "MODULE_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "DATA_SOURCE" VARCHAR2(20 CHAR) NOT NULL,
  "BUSINESS_DATE" DATE NOT NULL,
  "TEST_GROUP" VARCHAR2(30 CHAR) NOT NULL,
  "TEST_NAME" VARCHAR2(100 CHAR) NOT NULL,
  "ACTIVE" CHAR(1 BYTE) DEFAULT 'Y',
  "INPUT" VARCHAR2(4000 BYTE),
  "EXPECTED" VARCHAR2(4000 BYTE),
  "PARAMETERS" VARCHAR2(4000 BYTE),
  "DESCRIPTION" VARCHAR2(255 CHAR),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;