CREATE TABLE "GUI_XMDM_EUREX_RTS24"."S_CERTIFIED_DEA_MEMBERS" (
  "MEMBER" VARCHAR2(5 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ITS" DATE DEFAULT SYSDATE,
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) DEFAULT 't7_eurex',
  CONSTRAINT "PK_RTS24_EUREX_CERT_MEMBER" PRIMARY KEY ("MEMBER", "VALID_FROM")
);;
CREATE TABLE "GUI_XMDM_EUREX_RTS24"."S_SCHEDULING_PARAMS" (
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "PRODUCT_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL,
  "MEMBER_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL,
  "RESULT_STATUS" VARCHAR2(50 CHAR),
  "ITS" DATE DEFAULT SYSDATE,
  "INSTRUMENT_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A'
);;
CREATE TABLE "GUI_XMDM_EUREX_RTS24"."S_CERTIFIED_DEA_MEMBERS_AT" (
  "MEMBER" VARCHAR2(5 CHAR) NOT NULL,
  "VALID_FROM" DATE NOT NULL,
  "VALID_TO" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE,
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) DEFAULT 't7_eurex'
);;
CREATE TABLE "GUI_XMDM_EUREX_RTS24"."S_SCHEDULING_PARAMS_AT" (
  "EXCHANGE_CODE" VARCHAR2(15 CHAR) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "PRODUCT_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL,
  "MEMBER_BUS_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A' NOT NULL,
  "RESULT_STATUS" VARCHAR2(50 CHAR),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE,
  "INSTRUMENT_ID" VARCHAR2(20 CHAR) DEFAULT 'N/A'
);;