CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_FINAL_MISSING" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XETR_FINAL_MISSING" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_INCORRECT_LONGCODE" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XETR_INCORRECT_LONGCODE" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_FINAL_MISSING" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XEUR_FINAL_MISSING" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_INCORRECT_LONGCODE" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XEUR_INCORRECT_LONGCODE" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XFRA_FINAL_MISSING" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XFRA_FINAL_MISSING" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XFRA_INCORRECT_LONGCODE" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_F_SCLC_DI_TOOL_XFRA_INCORRECT_LONGCODE" PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM")
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_FINAL_MISSING_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_INCORRECT_LONGCODE_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_FINAL_MISSING_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_INCORRECT_LONGCODE_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XFRA_FINAL_MISSING_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_SCLC_DI_TOOL"."XFRA_INCORRECT_LONGCODE_AT" (
  "MIC" VARCHAR2(20 BYTE) NOT NULL,
  "PARTICIPANT_ID" VARCHAR2(20 BYTE) NOT NULL,
  "SHORT_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "REPORTING_DATE_FROM" DATE NOT NULL,
  "REPORTING_DATE_TO" DATE NOT NULL,
  "ENTRY_DATE" DATE NOT NULL,
  "REASON" VARCHAR2(1000 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;