ALTER TABLE "GUI_XMDM_F7_HFT"."S_OTR_LIMITS_VOLUME" ADD ("AVERAGE_VOLUME" NUMBER(18, 5) NOT NULL);
ALTER TABLE "GUI_XMDM_F7_HFT"."S_OTR_LIMITS_VOLUME_AT" ADD ("AVERAGE_VOLUME" NUMBER(18, 5) NOT NULL);