CREATE TABLE "GUI_XMDM_XETRA_HYPMI"."S_HYPMI_AGG_SLICE" (
  "SLICE_ID" NUMBER(4, 0) NOT NULL,
  "AGGREGATION_LEVEL" VARCHAR2(30 CHAR),
  "SLICE_BEGIN" NUMBER(9, 0) NOT NULL,
  "SLICE_END" NUMBER(9, 0) NOT NULL,
  "SLICE_NAME" VARCHAR2(30 CHAR),
  "SLICE_WEIGHT" NUMBER(6, 3),
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_XETRA_HYPMI"."S_HYPMI_OBOOK_CALC_SCOPE" (
  "CALC_BEGIN" VARCHAR2(6 CHAR) NOT NULL,
  "CALC_END" VARCHAR2(6 CHAR) NOT NULL,
  "CALC_INCR" NUMBER(9, 4) NOT NULL,
  "CALC_INCR_UNIT" VARCHAR2(15 BYTE) NOT NULL,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_XETRA_HYPMI"."S_HYPMI_AGG_SLICE_AT" (
  "SLICE_ID" NUMBER(4, 0) NOT NULL,
  "AGGREGATION_LEVEL" VARCHAR2(30 CHAR),
  "SLICE_BEGIN" NUMBER(9, 0) NOT NULL,
  "SLICE_END" NUMBER(9, 0) NOT NULL,
  "SLICE_NAME" VARCHAR2(30 CHAR),
  "SLICE_WEIGHT" NUMBER(6, 3),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;
CREATE TABLE "GUI_XMDM_XETRA_HYPMI"."S_HYPMI_OBOOK_CALC_SCOPE_AT" (
  "CALC_BEGIN" VARCHAR2(6 CHAR) NOT NULL,
  "CALC_END" VARCHAR2(6 CHAR) NOT NULL,
  "CALC_INCR" NUMBER(9, 4) NOT NULL,
  "CALC_INCR_UNIT" VARCHAR2(15 BYTE) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT SYSDATE
);;