-- Create table GUI_XMDM_REV_SHARING.D_REV_SHA_GOLD_PACKAGE_HOLDERS_AT
CREATE TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_GOLD_PACKAGE_HOLDERS_AT" ("PARTICIPANTS_GROUP_ID" VARCHAR2(50 BYTE) NOT NULL, "VALID_FROM" DATE NOT NULL, "VALID_TO" DATE NOT NULL, "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP, "ITS" DATE DEFAULT SYSDATE);

-- Alter table GUI_XMDM_REV_SHARING.CREDIT_AFFILIATED_TRANS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."CREDIT_AFFILIATED_TRANS" DROP CONSTRAINT "PK_CREDIT_AFFILIATED_TRANS";

-- Alter table GUI_XMDM_REV_SHARING.CREDIT_MEMBERS_MUGR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."CREDIT_AFFILIATED_TRANS" ADD PRIMARY KEY ("MEMBER_ID", "UNIQUE_IDENTIFIER", "CLEARING_MEMBER_ID", "TRANSACTION_ACCOUNT", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.D_CREDIT_MEMBER_ADDRESSES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."CREDIT_MEMBERS_MUGR" DROP CONSTRAINT "PK_CREDIT_MEMBERS_MUGR";

-- Alter table GUI_XMDM_REV_SHARING.D_OBJ_BGC_OTC_MEMB_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."CREDIT_MEMBERS_MUGR" ADD PRIMARY KEY ("MONTH", "PARTICIPANT_ID");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_CAPLAB_MEM_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_CREDIT_MEMBER_ADDRESSES" DROP CONSTRAINT "PK_D_CREDIT_MEMBER_ADDRESSES";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_MEMBER_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_CREDIT_MEMBER_ADDRESSES" ADD PRIMARY KEY ("MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_PLATFORM_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_OBJ_BGC_OTC_MEMB_MAP" DROP CONSTRAINT "PK_D_OBJ_BGC_OTC_MEMB_MAP";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_THOLD_MULT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_OBJ_BGC_OTC_MEMB_MAP" ADD PRIMARY KEY ("ETD_MEMBER_ID", "OTC_MEMBER_ID", "BGC_MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_THOLD_STRM: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_CAPLAB_MEM_MAP" DROP CONSTRAINT "PK_D_REV_SHA_CAPLAB_MEM_MAP";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_TIER_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_CAPLAB_MEM_MAP" ADD PRIMARY KEY ("CAPLAB_MEMB_ID", "OTC_MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_GOLD_PACKAGE_HOLDERS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_MEMBER_MAP" DROP CONSTRAINT "PK_D_REV_SHA_FQPM_MEMBER_MAP";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_MEMBER_ADDRESSES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_MEMBER_MAP" ADD PRIMARY KEY ("MEMBER_ID", "PARTICIPANT_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_MEMB_ACCOUNT_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_PLATFORM_MAP" DROP CONSTRAINT "PK_D_REV_SHA_FQPM_PLATFORM_MAP";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_OTC_UGR_LEI: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_PLATFORM_MAP" ADD PRIMARY KEY ("MEMBER_ID", "PLATFORM_ID", "PROTOCOL", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_VMWM_OTC_MEM_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_MULT" DROP CONSTRAINT "PK_D_REV_SHA_FQPM_THOLD_MULT";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_VOICE_MEM_MAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_MULT" ADD PRIMARY KEY ("PROTOCOL", "FQPM_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.D_STIR_MEMBER_ADDRESSES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_STRM" DROP CONSTRAINT "PK_D_REV_SHA_FQPM_THOLD_STRM";

-- Alter table GUI_XMDM_REV_SHARING.ECAG_PP_CPI: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_THOLD_STRM" ADD PRIMARY KEY ("PROTOCOL", "FQPM_ID", "TENOR", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.EFS_CB012_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_TIER_MAP" DROP CONSTRAINT "PK_D_REV_SHA_FQPM_TIER_MAP";

-- Alter table GUI_XMDM_REV_SHARING.EFS_ETD_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_FQPM_TIER_MAP" ADD PRIMARY KEY ("MEMBER_ID", "STREAMING_TYPE", "EUREX_TIER", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.EFS_RECONCILIATION_REPORT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_GOLD_PACKAGE_HOLDERS" DROP CONSTRAINT "PK_D_REV_SHA_GOLD_PACK_HOLDERS";

-- Alter table GUI_XMDM_REV_SHARING.EFS_VALIDATION_REPORT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_GOLD_PACKAGE_HOLDERS" ADD PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_CAPITALLAB_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMBER_ADDRESSES" DROP CONSTRAINT "PK_D_REV_SHA_MEMBER_ADDRESSES";

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_EFS_BBG_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMBER_ADDRESSES" ADD PRIMARY KEY ("MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_VOICE_INPUT_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMB_ACCOUNT_MAP" DROP CONSTRAINT "PK_D_REV_SHA_MEMB_ACCOUNT_MAP";

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_VOLMATCH_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_MEMB_ACCOUNT_MAP" ADD PRIMARY KEY ("MEMBER_ID", "ACCOUNT_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_WEMATCH_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_OTC_UGR_LEI" DROP CONSTRAINT "PK_D_REV_SHA_OTC_UGR_LEI";

-- Alter table GUI_XMDM_REV_SHARING.MEMBER_MAPPING: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_OTC_UGR_LEI" ADD PRIMARY KEY ("LEI_CODE", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_AFFILIATED_TRANS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VMWM_OTC_MEM_MAP" DROP CONSTRAINT "PK_D_REV_SHA_VMWM_OTC_MEM_MAP";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_MULTIPLIER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VMWM_OTC_MEM_MAP" ADD PRIMARY KEY ("VMWM_MEMBER_ID", "OTC_MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_NRSP_ADJ: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VOICE_MEM_MAP" DROP CONSTRAINT "PK_D_REV_SHA_VOICE_MEM_MAP";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_RED_PART_GROUP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_REV_SHA_VOICE_MEM_MAP" ADD PRIMARY KEY ("VOICE_DEALER", "OTC_MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_SPECIAL_INCENTIVES: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_STIR_MEMBER_ADDRESSES" DROP CONSTRAINT "PK_D_STIR_MEMBER_ADDRESSES";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_TERM_GROWTH_PRODUCT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."D_STIR_MEMBER_ADDRESSES" ADD PRIMARY KEY ("MEMBER_ID");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_TERM_PART_GROUP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."ECAG_PP_CPI" DROP CONSTRAINT "PK_ECAG_PP_CPI";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_UGR_ADJ: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."ECAG_PP_CPI" ADD PRIMARY KEY ("CPI_YEAR");

-- Alter table GUI_XMDM_REV_SHARING.PARTICIPANTS_GROUPS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_CB012_DATA" DROP CONSTRAINT "PK_EFS_CB012_DATA";

-- Alter table GUI_XMDM_REV_SHARING.PARTICIPANTS_GROUPS_CREDIT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_CB012_DATA" ADD PRIMARY KEY ("ROW_INDEX");

-- Alter table GUI_XMDM_REV_SHARING.PARTICIPANTS_GROUPS_REPO: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_ETD_DATA" DROP CONSTRAINT "PK_EFS_ETD_DATA";

-- Alter table GUI_XMDM_REV_SHARING.PARTICIPANTS_GROUPS_STIR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_ETD_DATA" ADD PRIMARY KEY ("ROW_INDEX");

-- Alter table GUI_XMDM_REV_SHARING.REPO_CLEARING_CORRECTIONS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_RECONCILIATION_REPORT" DROP CONSTRAINT "PK_EFS_RECONCILIATION_REPORT";

-- Alter table GUI_XMDM_REV_SHARING.REPO_MULTIPLIER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_RECONCILIATION_REPORT" ADD PRIMARY KEY ("ROW_INDEX", "SOURCE", "TRADE_DATE", "ETD_MEMBER_ID", "ORIGINAL_TRADE_MATCH_ID", "OTC_MEMBER_ID", "MARKETWIRE_ID");

-- Alter table GUI_XMDM_REV_SHARING.STIR_AFFILIATED_TRANS: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_VALIDATION_REPORT" DROP CONSTRAINT "PK_EFS_VALIDATION_REPORT";

-- Alter table GUI_XMDM_REV_SHARING.STIR_MEMBERS_MUGR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."EFS_VALIDATION_REPORT" ADD PRIMARY KEY ("SOURCE", "TRADE_DATE", "ETD_MEMBER_ID", "OTC_MEMBER_ID", "MARKETWIRE_ID", "VALIDATION_REMARKS");

-- Alter table GUI_XMDM_REV_SHARING.STIR_MULTIPLIER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_CAPITALLAB_DATA" DROP CONSTRAINT "PK_F_REV_SHA_CAPITALLAB_DATA";

-- Alter table GUI_XMDM_REV_SHARING.STIR_NRSP_ADJ: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_CAPITALLAB_DATA" ADD PRIMARY KEY ("ROW_INDEX");

-- Alter table GUI_XMDM_REV_SHARING.STIR_UGR_ADJ: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_EFS_BBG_DATA" DROP CONSTRAINT "PK_F_REV_SHA_EFS_BBG_DATA";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_BGC_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_EFS_BBG_DATA" ADD PRIMARY KEY ("PRODUCT_ID", "TRADE_DATE");

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_ELEC_BGC_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOICE_INPUT_DATA" DROP CONSTRAINT "PK_F_REV_SHA_VOICE_INPUT_DATA";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_ICAP_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOICE_INPUT_DATA" ADD PRIMARY KEY ("ROW_INDEX");

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_TP_DATA: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOLMATCH_DATA" DROP CONSTRAINT "PK_F_REV_SHA_VOLMATCH_DATA";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_UGR_CB182_CORR: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_VOLMATCH_DATA" ADD PRIMARY KEY ("ROW_INDEX");

-- Alter table GUI_XMDM_REV_SHARING.D_OBJ_BGC_OTC_MEMB_MAP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_WEMATCH_DATA" DROP CONSTRAINT "PK_F_REV_SHA_WEMATCH_DATA";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_CAPLAB_MEM_MAP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."F_REV_SHA_WEMATCH_DATA" ADD PRIMARY KEY ("SERVICE_NAME", "TRADE_DATE", "CLIENT", "TRADE_SIZE", "EFFECTIVE_DATE", "EXPIRY_DATE");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_FQPM_THOLD_STRM_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."MEMBER_MAPPING" DROP CONSTRAINT "PK_MEMBER_MAPPING";

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_OTC_UGR_LEI_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."MEMBER_MAPPING" ADD PRIMARY KEY ("MEMBER_NAME", "OTC_IRD_GROUP_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.D_REV_SHA_VMWM_OTC_MEM_MAP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_AFFILIATED_TRANS" DROP CONSTRAINT "PK_OTC_IRD_AFFILIATED_TRANS";

-- Alter table GUI_XMDM_REV_SHARING.EFS_CB012_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_AFFILIATED_TRANS" ADD PRIMARY KEY ("VALID_FROM", "MEMBER_ID", "ENTITY");

-- Alter table GUI_XMDM_REV_SHARING.EFS_ETD_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_MULTIPLIER" DROP CONSTRAINT "PK_OTC_IRD_MULTIPLIER";

-- Alter table GUI_XMDM_REV_SHARING.EFS_VALIDATION_REPORT_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_MULTIPLIER" ADD PRIMARY KEY ("MULTIPLIER_NAME", "PARTICIPANTS_GROUP_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_CAPITALLAB_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_NRSP_ADJ" DROP CONSTRAINT "PK_OTC_IRD_NRSP_ADJ";

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_EFS_BBG_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_NRSP_ADJ" ADD PRIMARY KEY ("REPORTING_MONTH");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_VOICE_INPUT_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_RED_PART_GROUP" DROP CONSTRAINT "PK_OTC_IRD_RED_PART_GROUP";

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_VOLMATCH_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_RED_PART_GROUP" ADD PRIMARY KEY ("MONTH");

-- Alter table GUI_XMDM_REV_SHARING.F_REV_SHA_WEMATCH_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_SPECIAL_INCENTIVES" DROP CONSTRAINT "PK_OTC_IRD_SPECIAL_INCENTIVES";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_AFFILIATED_TRANS_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_SPECIAL_INCENTIVES" ADD PRIMARY KEY ("VALID_FROM", "CURRENCY_ID");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_RED_PART_GROUP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_GROWTH_PRODUCT" DROP CONSTRAINT "PK_OTC_IRD_TERM_GROWTH_PRODUCT";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_SPECIAL_INCENTIVES_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_GROWTH_PRODUCT" ADD PRIMARY KEY ("MONTH");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_TERM_GROWTH_PRODUCT_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_PART_GROUP" DROP CONSTRAINT "PK_OTC_IRD_TERM_PART_GROUP";

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_TERM_PART_GROUP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_TERM_PART_GROUP" ADD PRIMARY KEY ("PARICIPANTS_GROUP_ID", "MONTH");

-- Alter table GUI_XMDM_REV_SHARING.OTC_IRD_UGR_ADJ_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_UGR_ADJ" DROP CONSTRAINT "PK_OTC_IRD_UGR_ADJ";

-- Alter table GUI_XMDM_REV_SHARING.STIR_MULTIPLIER_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."OTC_IRD_UGR_ADJ" ADD PRIMARY KEY ("REPORTING_MONTH", "PARTICIPANT_ID");

-- Alter table GUI_XMDM_REV_SHARING.STIR_NRSP_ADJ_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS" DROP CONSTRAINT "PK_PARTICIPANTS_GROUP";

-- Alter table GUI_XMDM_REV_SHARING.STIR_UGR_ADJ_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS" ADD PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "PARTICIPANT_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_CONTROL_CTM_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_CREDIT" DROP CONSTRAINT "PK_PARTICIPANTS_GROUPS_CREDIT";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_BGC_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_CREDIT" ADD PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "PARTICIPANT_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_ELEC_BGC_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_REPO" DROP CONSTRAINT "PK_PARTICIPANTS_GROUPS_REPO";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_ICAP_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_REPO" ADD PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "PARTICIPANT_ID", "VALID_FROM");

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_EFS_TP_DATA_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_STIR" DROP CONSTRAINT "PK_PARTICIPANTS_GROUPS_STIR";

-- Alter table GUI_XMDM_REV_SHARING.S_REV_SHA_UGR_CB182_CORR_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHARING"."PARTICIPANTS_GROUPS_STIR" ADD PRIMARY KEY ("PARTICIPANTS_GROUP_ID", "PARTICIPANT_ID", "VALID_FROM");
