-- Alter table GUI_XMDM_PMBFZ.TX_ARIVA_MAPPING: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_ARIVA_MAPPING" DROP CONSTRAINT "PK_TX_ARIVA_MAPPING";

-- Alter table GUI_XMDM_PMBFZ.TX_STM_PARAMETER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_ARIVA_MAPPING" ADD PRIMARY KEY ("A_ARIVA_SUB_CLASS_ID");

-- Alter table GUI_XMDM_PMBFZ.TX_STM_PAR_EXE_PERF: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_STM_PARAMETER" DROP CONSTRAINT "PK_TX_STM_PARAMETER";

-- Alter table GUI_XMDM_PMBFZ.TX_STM_SEGMENT_GROUP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_STM_PARAMETER" ADD PRIMARY KEY ("A_PROD_GROUP");

-- Alter table GUI_XMDM_PMBFZ.TX_ARIVA_MAPPING_AT: modify column
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_STM_PAR_EXE_PERF" DROP CONSTRAINT "TX_STM_PAR_EXE_PERF";

-- Alter table GUI_XMDM_PMBFZ.TX_STM_PAR_EXE_PERF_AT: modify column
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_STM_PAR_EXE_PERF" ADD PRIMARY KEY ("A_PM_TYPE", "A_PM_TYPE_LEVEL");

-- Alter table GUI_XMDM_PMBFZ.TX_STM_SEGMENT_GROUP_AT: modify column
ALTER TABLE "GUI_XMDM_PMBFZ"."TX_STM_SEGMENT_GROUP" DROP CONSTRAINT "PK_TX_STM_SEGMENT_GROUP";
