-- Alter table GUI_XMDM_REV_SHAR_OPTIM.OPTIM_NEW_TRADES_SWAP: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHAR_OPTIM"."OPTIM_NEW_TRADES_SWAP" DROP CONSTRAINT "PK_OPTIM_NEW_TRADES_SWAP";

-- Alter table GUI_XMDM_REV_SHAR_OPTIM.OPTIM_STRTGY_INPUT_CRNT: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_REV_SHAR_OPTIM"."OPTIM_NEW_TRADES_SWAP" ADD PRIMARY KEY ("CAPITALAB_ID");

-- Alter table GUI_XMDM_REV_SHAR_OPTIM.OPTIM_NEW_TRADES_SWAP_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHAR_OPTIM"."OPTIM_STRTGY_INPUT_CRNT" DROP CONSTRAINT "PK_OPTIM_STRTGY_INPUT_CRNT";

-- Alter table GUI_XMDM_REV_SHAR_OPTIM.OPTIM_STRTGY_INPUT_CRNT_AT: modify column
ALTER TABLE "GUI_XMDM_REV_SHAR_OPTIM"."OPTIM_STRTGY_INPUT_CRNT" ADD PRIMARY KEY ("BOOKS", "LEGAL_ENTITY");
