CREATE TABLE "GUI_XMDM_NDF"."NDF_CURRENCY" (
  "CURRENCY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."NDF_REPORT_APPROVAL" (
  "OUT_OF_BOUNDS_VARIATIONS" VARCHAR2(4000 CHAR) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_NDF_REPORT_APPROVAL" PRIMARY KEY ("FACT_DATE")
);;
CREATE TABLE "GUI_XMDM_NDF"."PEGGING_INDICATOR" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PEGGING_VALUE" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PEGGING_INDICATOR" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."POLITICAL_STABILITY_INDEX" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PSI_VALUE" NUMBER NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_POLITICAL_STABILITY_INDEX" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."PRICE_SOURCE_DISRUPTION_IND" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PSD_VALUE" CHAR(1 BYTE),
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_PRICE_SOURCE_DISRUPTION_IND" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."SOVEREIGN_HEALTH_INDEX" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "SHI_VALUE" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_SOVEREIGN_HEALTH_INDEX" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SCENARIO" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "STRESS_VALUE_UP" NUMBER NOT NULL,
  "STRESS_VALUE_DOWN" NUMBER NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STRESS_SCENARIO" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SHIFT_MUTIPLIER_NDF" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "STRESS_SHIFT_MULTIPLIER" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_STRESS_SHIFT_MUTIPLIER_NDF" PRIMARY KEY ("CURRENCY_ID")
);;
CREATE TABLE "GUI_XMDM_NDF"."NDF_CURRENCY_AT" (
  "CURRENCY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."NDF_REPORT_APPROVAL_AT" (
  "OUT_OF_BOUNDS_VARIATIONS" VARCHAR2(4000 CHAR) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."PEGGING_INDICATOR_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PEGGING_VALUE" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."POLITICAL_STABILITY_INDEX_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PSI_VALUE" NUMBER NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."PRICE_SOURCE_DISRUPTION_IND_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "PSD_VALUE" CHAR(1 BYTE),
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."SOVEREIGN_HEALTH_INDEX_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "SHI_VALUE" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SCENARIO_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "STRESS_VALUE_UP" NUMBER NOT NULL,
  "STRESS_VALUE_DOWN" NUMBER NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;
CREATE TABLE "GUI_XMDM_NDF"."STRESS_SHIFT_MUTIPLIER_NDF_AT" (
  "COUNTRY_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CURRENCY_ID" VARCHAR2(3 CHAR) NOT NULL,
  "STRESS_SHIFT_MULTIPLIER" NUMBER(5, 4) NOT NULL,
  "FACT_DATE" DATE NOT NULL,
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;