-- Alter table GUI_XMDM_SCLC_DI_TOOL.XETR_FINAL_MISSING: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_FINAL_MISSING" DROP CONSTRAINT "PK_F_SCLC_DI_TOOL_XETR_FINAL_MISSING";

-- Alter table GUI_XMDM_SCLC_DI_TOOL.XETR_INCORRECT_LONGCODE: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_FINAL_MISSING" ADD PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM");

-- Alter table GUI_XMDM_SCLC_DI_TOOL.XEUR_FINAL_MISSING: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_INCORRECT_LONGCODE" DROP CONSTRAINT "PK_F_SCLC_DI_TOOL_XETR_INCORRECT_LONGCODE";

-- Alter table GUI_XMDM_SCLC_DI_TOOL.XEUR_INCORRECT_LONGCODE: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XETR_INCORRECT_LONGCODE" ADD PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM");

-- Alter table GUI_XMDM_SCLC_DI_TOOL.XFRA_FINAL_MISSING: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_FINAL_MISSING" DROP CONSTRAINT "PK_F_SCLC_DI_TOOL_XEUR_FINAL_MISSING";

-- Alter table GUI_XMDM_SCLC_DI_TOOL.XFRA_INCORRECT_LONGCODE: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_SCLC_DI_TOOL"."XEUR_FINAL_MISSING" ADD PRIMARY KEY ("MIC", "PARTICIPANT_ID", "SHORT_CODE", "REPORTING_DATE_FROM");
