-- Alter table GUI_XMDM_PMETF.PMETF_PARAMETER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMETF"."PMETF_PARAMETER" DROP CONSTRAINT "PK_PMETF_PARAMETER";

-- Alter table GUI_XMDM_PMETF.PMETF_REPORT_OWNER: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_PMETF"."PMETF_PARAMETER" ADD PRIMARY KEY ("PARAMETER_SET_ID", "ISIN", "PRICE_CURRENCY", "ISSUER");

-- Alter table GUI_XMDM_PMETF.PMETF_PARAMETER_AT: modify column
ALTER TABLE "GUI_XMDM_PMETF"."PMETF_REPORT_OWNER" DROP CONSTRAINT "PK_PMETF_REPORT_OWNER";

-- Alter table GUI_XMDM_PMETF.PMETF_REPORT_OWNER_AT: modify column
ALTER TABLE "GUI_XMDM_PMETF"."PMETF_REPORT_OWNER" ADD PRIMARY KEY ("MEMBER_ID", "ISSUER");
