-- Create table GUI_XMDM.XMDM_CONF_APP_04122025_AT
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_04122025_AT" ("APP_NAME" VARCHAR2(20 BYTE), "APP_GUI_NAME" VARCHAR2(150 BYTE), "APP_DESC" VARCHAR2(250 BYTE), "APP_HELP_LINK" VARCHAR2(1000 BYTE), "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE), "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE), "VALIDATION_ACTION" VARCHAR2(4000 BYTE), "ON_LOAD_ACTION" VARCHAR2(1000 BYTE), "SETTINGS" VARCHAR2(4000 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Create table GUI_XMDM.XMDM_CONF_APP_05122025_AT
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_05122025_AT" ("APP_NAME" VARCHAR2(20 BYTE), "APP_GUI_NAME" VARCHAR2(150 BYTE), "APP_DESC" VARCHAR2(250 BYTE), "APP_HELP_LINK" VARCHAR2(1000 BYTE), "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE), "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE), "VALIDATION_ACTION" VARCHAR2(4000 BYTE), "ON_LOAD_ACTION" VARCHAR2(1000 BYTE), "SETTINGS" VARCHAR2(4000 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Create table GUI_XMDM.XMDM_CONF_APP_06122025_AT
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_06122025_AT" ("APP_NAME" VARCHAR2(20 BYTE), "APP_GUI_NAME" VARCHAR2(150 BYTE), "APP_DESC" VARCHAR2(250 BYTE), "APP_HELP_LINK" VARCHAR2(1000 BYTE), "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE), "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE), "VALIDATION_ACTION" VARCHAR2(4000 BYTE), "ON_LOAD_ACTION" VARCHAR2(1000 BYTE), "SETTINGS" VARCHAR2(4000 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Create table GUI_XMDM.XMDM_CONF_APP_07122025_AT
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_07122025_AT" ("APP_NAME" VARCHAR2(20 BYTE), "APP_GUI_NAME" VARCHAR2(150 BYTE), "APP_DESC" VARCHAR2(250 BYTE), "APP_HELP_LINK" VARCHAR2(1000 BYTE), "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE), "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE), "VALIDATION_ACTION" VARCHAR2(4000 BYTE), "ON_LOAD_ACTION" VARCHAR2(1000 BYTE), "SETTINGS" VARCHAR2(4000 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Create table GUI_XMDM.XMDM_CONF_APP_08122025_AT
CREATE TABLE "GUI_XMDM"."XMDM_CONF_APP_08122025_AT" ("APP_NAME" VARCHAR2(20 BYTE), "APP_GUI_NAME" VARCHAR2(150 BYTE), "APP_DESC" VARCHAR2(250 BYTE), "APP_HELP_LINK" VARCHAR2(1000 BYTE), "PRE_RELEASE_ACTION" VARCHAR2(4000 BYTE), "POST_RELEASE_ACTION" VARCHAR2(4000 BYTE), "VALIDATION_ACTION" VARCHAR2(4000 BYTE), "ON_LOAD_ACTION" VARCHAR2(1000 BYTE), "SETTINGS" VARCHAR2(4000 BYTE), "ACTION" CHAR(1 BYTE), "MODIFIED_BY" VARCHAR2(15 BYTE), "MODIFIED_AT" TIMESTAMP, "ACCEPTED_BY" VARCHAR2(15 BYTE), "ACCEPTED_AT" TIMESTAMP, "STATUS" CHAR(1 BYTE), "STATUS_AT" TIMESTAMP);

-- Alter table GUI_XMDM.XMDM_CONF_USER_PERM: drop constraint
ALTER TABLE "GUI_XMDM"."XMDM_CONF_USER_PERM" DROP CONSTRAINT "UNIUQ_USER_APP";

-- Alter table GUI_XMDM.XMDM_CONF_USER_SETTING: drop constraint
ALTER TABLE "GUI_XMDM"."XMDM_CONF_USER_SETTING" DROP CONSTRAINT "UNIQ_TABLE_SET";
