-- Alter table GUI_XMDM_MAX_MUSTER.D_FIXED_VALUES_MAXM_XMDM: drop constraint, add constraint
ALTER TABLE "GUI_XMDM_MAX_MUSTER"."D_FIXED_VALUES_MAXM_XMDM" DROP CONSTRAINT "PK_D_FIXED_VALUES_MAXM_XMDM";

-- Alter table GUI_XMDM_MAX_MUSTER.D_FIXED_VALUES_MAXM_XMDM_AT: modify column
ALTER TABLE "GUI_XMDM_MAX_MUSTER"."D_FIXED_VALUES_MAXM_XMDM" ADD PRIMARY KEY ("CLIENT_LONG_VALUE");
