ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_LIQUIDATION" DROP COLUMN "RECORD_ID" ADD ("DMP_RUN_ID" NUMBER) ADD ("SETTLEMENT_AMNT" NUMBER(15, 3));
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_PARAMETER" ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT NULL);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_DEFAULT_DETAILS" ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_INSTC_STATUS" ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0 NOT NULL) ADD ("CLEARER_ID" VARCHAR2(5 BYTE)) ADD ("SOURCE" VARCHAR2(10 CHAR));
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACTION_MANUAL" ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACTION_OVERVIEW" ADD ("FACT_DATE" DATE) ADD ("DEFAULT_DATE" DATE) ADD ("VALUE_DATE" DATE) ADD ("TRANSACTION_DATE" DATE) ADD ("ACCOUNT_SPONSOR" VARCHAR2(5 BYTE)) ADD ("ACCOUNT_HOLDER" VARCHAR2(5 BYTE)) ADD ("ACCOUNT" VARCHAR2(64 BYTE)) ADD ("POOL_ID" VARCHAR2(15 BYTE)) ADD ("PORTING_UNIT" VARCHAR2(64 BYTE)) ADD ("PORTING_MEMBER" VARCHAR2(5 BYTE)) ADD ("OP_POOL_TYPE" VARCHAR2(64 BYTE)) ADD ("CASH_CHAIN_ID" VARCHAR2(32 BYTE)) ADD ("TRANSACTION_TYPE" VARCHAR2(3 BYTE)) ADD ("CURRENCY" VARCHAR2(3 BYTE)) ADD ("CASH_TRANSACTION" VARCHAR2(15 BYTE)) ADD ("CASH_INSTRUCTION" NUMBER(15, 0)) ADD ("AMOUNT" NUMBER(18, 2)) ADD ("CRM_GP_NO" VARCHAR2(10 BYTE)) ADD ("ITS" DATE);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_LIQUIDATION_AT" DROP COLUMN "RECORD_ID" ADD ("DMP_RUN_ID" NUMBER) ADD ("ITS" DATE DEFAULT SYSDATE) ADD ("SETTLEMENT_AMNT" NUMBER(15, 3));
ALTER TABLE "GUI_XMDM_DMP"."S_STG_CAA_PARAMETER_AT" ADD ("ITS" DATE DEFAULT SYSDATE) ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT NULL);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_DEFAULT_DETAILS_AT" ADD ("ITS" DATE DEFAULT SYSDATE) ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_INSTC_STATUS_AT" ADD ("ITS" DATE DEFAULT SYSDATE) ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0 NOT NULL) ADD ("CLEARER_ID" VARCHAR2(5 BYTE)) ADD ("SOURCE" VARCHAR2(10 CHAR));
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACT_MANUAL_AT" ADD ("ITS" DATE DEFAULT sysdate) ADD ("DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0);
ALTER TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRANSACT_OVERVIEW_AT" ADD ("FACT_DATE" DATE) ADD ("DEFAULT_DATE" DATE) ADD ("VALUE_DATE" DATE) ADD ("TRANSACTION_DATE" DATE) ADD ("ACCOUNT_SPONSOR" VARCHAR2(5 BYTE)) ADD ("ACCOUNT_HOLDER" VARCHAR2(5 BYTE)) ADD ("ACCOUNT" VARCHAR2(64 BYTE)) ADD ("POOL_ID" VARCHAR2(15 BYTE)) ADD ("PORTING_UNIT" VARCHAR2(64 BYTE)) ADD ("PORTING_MEMBER" VARCHAR2(5 BYTE)) ADD ("OP_POOL_TYPE" VARCHAR2(64 BYTE)) ADD ("CASH_CHAIN_ID" VARCHAR2(32 BYTE)) ADD ("TRANSACTION_TYPE" VARCHAR2(3 BYTE)) ADD ("CURRENCY" VARCHAR2(3 BYTE)) ADD ("CASH_TRANSACTION" VARCHAR2(15 BYTE)) ADD ("CASH_INSTRUCTION" NUMBER(15, 0)) ADD ("AMOUNT" NUMBER(18, 2)) ADD ("CRM_GP_NO" VARCHAR2(10 BYTE)) ADD ("ITS" DATE);
CREATE TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRN_GROUP_OVERRULE" (
  "FACT_DATE" DATE,
  "DEFAULT_TIMESTAMP" DATE,
  "DEFAULT_DATE" DATE,
  "TRANSACTION_DATE" DATE,
  "VALUE_DATE" DATE,
  "CASH_SETTLEMENT_RUN" VARCHAR2(4 BYTE),
  "OP_RELEVANCE_IND" NUMBER(1, 0),
  "CRM_PARTNER_ID" NUMBER(15, 0),
  "CRM_GP_NO" VARCHAR2(10 BYTE),
  "CLEARER_ID" VARCHAR2(5 BYTE),
  "ACCOUNT_HOLDER" VARCHAR2(5 BYTE),
  "ACCOUNT" VARCHAR2(32 BYTE),
  "POOL_ID" VARCHAR2(15 BYTE),
  "OP_POOL_TYPE" VARCHAR2(256 CHAR),
  "OP_CLIENT_TYPE" VARCHAR2(100 BYTE),
  "LINKEDACCOUNT" VARCHAR2(60 BYTE),
  "PORTING_UNIT" VARCHAR2(60 BYTE),
  "CASH_CHAIN_ID" VARCHAR2(15 BYTE),
  "NBR_OF_PU_PER_CHAIN" NUMBER(15, 0),
  "CASH_INSTRUCTION" NUMBER(15, 0),
  "STL_FLG_INSTC" VARCHAR2(1 BYTE),
  "CSH_TRN_GROUP" NUMBER(2, 0),
  "CSH_TRN_GROUP_OVERRULE" NUMBER(2, 0),
  "TRANSACTION_TYPE" VARCHAR2(3 BYTE),
  "CURRENCY" VARCHAR2(3 BYTE),
  "CASH_TRANSACTION" VARCHAR2(15 BYTE),
  "EXT_CASH_TRANSACTION" VARCHAR2(17 BYTE),
  "CASH_AMOUNT_INT" NUMBER(19, 2),
  "ITS" DATE DEFAULT sysdate,
  "PORTING_MEMBER" VARCHAR2(5 CHAR),
  "DATA_SRC" VARCHAR2(30 BYTE),
  "DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0 NOT NULL
);;
CREATE TABLE "GUI_XMDM_DMP"."S_STG_PAY_TRN_GRP_OVERRULE_AT" (
  "FACT_DATE" DATE,
  "DEFAULT_TIMESTAMP" DATE,
  "DEFAULT_DATE" DATE,
  "TRANSACTION_DATE" DATE,
  "VALUE_DATE" DATE,
  "CASH_SETTLEMENT_RUN" VARCHAR2(4 BYTE),
  "OP_RELEVANCE_IND" NUMBER(1, 0),
  "CRM_PARTNER_ID" NUMBER(15, 0),
  "CRM_GP_NO" VARCHAR2(10 BYTE),
  "CLEARER_ID" VARCHAR2(5 BYTE),
  "ACCOUNT_HOLDER" VARCHAR2(5 BYTE),
  "ACCOUNT" VARCHAR2(32 BYTE),
  "POOL_ID" VARCHAR2(15 BYTE),
  "OP_POOL_TYPE" VARCHAR2(256 CHAR),
  "OP_CLIENT_TYPE" VARCHAR2(100 BYTE),
  "LINKEDACCOUNT" VARCHAR2(60 BYTE),
  "PORTING_UNIT" VARCHAR2(60 BYTE),
  "CASH_CHAIN_ID" VARCHAR2(15 BYTE),
  "NBR_OF_PU_PER_CHAIN" NUMBER(15, 0),
  "CASH_INSTRUCTION" NUMBER(15, 0),
  "STL_FLG_INSTC" VARCHAR2(1 BYTE),
  "CSH_TRN_GROUP" NUMBER(2, 0),
  "CSH_TRN_GROUP_OVERRULE" NUMBER(2, 0),
  "TRANSACTION_TYPE" VARCHAR2(3 BYTE),
  "CURRENCY" VARCHAR2(3 BYTE),
  "CASH_TRANSACTION" VARCHAR2(15 BYTE),
  "EXT_CASH_TRANSACTION" VARCHAR2(17 BYTE),
  "CASH_AMOUNT_INT" NUMBER(19, 2),
  "ACTION" CHAR(1 BYTE),
  "MODIFIED_BY" VARCHAR2(15 BYTE),
  "MODIFIED_AT" TIMESTAMP,
  "ACCEPTED_BY" VARCHAR2(15 BYTE),
  "ACCEPTED_AT" TIMESTAMP,
  "STATUS" CHAR(1 BYTE),
  "STATUS_AT" TIMESTAMP,
  "ITS" DATE DEFAULT sysdate,
  "PORTING_MEMBER" VARCHAR2(5 CHAR),
  "DATA_SRC" VARCHAR2(30 BYTE),
  "DMP_RUN_ID" NUMBER(15, 0) DEFAULT 0 NOT NULL
);;